### ISSUE TITLE
Add new reader audio

### ISSUE THREAD

**Issue by sulaiman-radwan** [quran/quran_android#1081]
Hi, 

I have a great local reader audio and I'd like to add it to this app.
Any idea how to start?

Thanks

**Comment by ahmedre** [comment]
1. send me the url so i can upload it to quran.com servers.
2. modify [readers.xml](https://github.com/quran/quran_android/blob/master/app/src/main/res/values/readers.xml) to add the qari
3. update the qaris name in the readers.xml for different languages (example: [Arabic](https://github.com/quran/quran_android/blob/master/app/src/main/res/values-ar/readers.xml)).

jazakAllah khairan.

**Comment by ahmedre** [comment]
closing for now - please feel free to reopen
