### ISSUE TITLE
Gradle sync failed 

### ISSUE THREAD

**Issue by selmanon** [quran/quran_android#1082]
Salam wr lah,

I got this issue while trying to import the project as described on the readme. any idea about this issue ?
**Hint :** The command line `./gradlew assembleMadaniDebug` run successfully.

>Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

Thanks.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
strange - so at the command line, it builds fine, but importing it into Android Studio 3.4 beta 3 gives you that error message?
walsalam 3alaikum.

**Comment by ozbek** [comment]
CL build (`./gradlew assembleMadaniDebug`) succeed regardless if you are using Android Studio 3.4 or earlier version. For GUI, please make sure you are on 3.4.

Also, by default Android Studio picks up `madaniBeta` variant. Switch to `madaniDebug` from Build Variants tab.

**Comment by optionight** [comment]
Salam.  
CL ./gradlew assembleMadaniDebug gives: 
The following options were not recognized by any processor: '[dagger.gradle.incremental, kapt.kotlin.generated, dagger.formatGeneratedSource]'
and
error: package javax.annotation.processing does not exist
How can I fix that?  Thanks in advance.

**Comment by ahmedre** [comment]
do you have java 8 installed and is your `JAVA_HOME` set properly?

**Comment by optionight** [comment]
With Java 8 it works.  Thanks!

**Comment by ahmedre** [comment]
closing, please re-open if you're still having trouble.
