### ISSUE TITLE
display dates and times on bookmarks

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1085]
we keep the dates for when bookmarks were saved, let's expose them somewhere (this could be toggle-able).

**Comment by aluckin3** [comment]
This can be done on press or hold, when you press to add new row where is "Time added: date" or on hold to show time of adding, as when you hold "menu_jump_last_page" you get information?

**Comment by ahmedre** [comment]
this has actually been done. in the main screen under bookmarks / tags, pressing the three line menu and choosing “show date” shows the date.
