### ISSUE TITLE
Bosnian Translation Issues (Muhamed Mehanovic)

### ISSUE THREAD

**Issue by aluckin3** [quran/quran_android#1124]
Chapter 78, ayah 40 should go: 'Mi vas, zaista, na patnju blisku upozoravamo, na Dan u kojem će čovjek djela ruku svojih vidjeti, a nevjernik uzviknuti: "Kamo sreće da sam prašina bio!"'

Ayah 39-40 should go according arabic text is:
39. A zašto nisi, kad si u vrt ušao, rekao: 'Mašallah! Snaga je samo u Allaha!' Ako vidiš da je u mene manje blaga i manje roda nego u tebe, 
40. pa Gospodar moj može mi bolji vrt od tvoga dati, a na tvoj nepogodu s neba poslati, pa da ostane samo klizava ledina bez ičega

But according on translation of professor Muhamed current translation is correct, i think according to ibn Kathir view on this?!

**Comment by ahmedre** [comment]
@aluckin3 got this email today - should i consider replacing this version with the translation for the sheikh present on https://quranenc.com?

> Es selamu alejkum.

> Pronasao sam u jednom ajetu grešku za prijevod Muhameda Mehanovica.

> 98 ajet sure Tewba 

> (وَمِنَ ٱلۡأَعۡرَابِ مَن یَتَّخِذُ مَا یُنفِقُ مَغۡرَمࣰا وَیَتَرَبَّصُ بِكُمُ ٱلدَّوَاۤىِٕرَۚ عَلَیۡهِمۡ دَاۤىِٕرَةُ ٱلسَّوۡءِۗ وَٱللَّهُ سَمِیعٌ عَلِیمࣱ)
> [Surat At-Tawbah 98]

> (Muhamed Mehanović)
> Ima beduina koji ono što daju smatraju nametom i jedva čekaju da vas nesreće stignu – neka njih pogodi nesreća, a Allah je Onaj Koji sve zna i mudar je.

>Na kraju ajeta ne (vAllahu semiun alim) znači "a Allah je Onaj koji sve čuje i sve zna"

**Comment by aluckin3** [comment]
Yeah that is error in translation, i will contact professor Muhamad, JazakAllah khairan you and brother who reported this.

**Comment by aluckin3** [comment]
Change this: "Kad bi se kakvom knjigom brda pokrenula, ili zemlja iskomadala, ili mrtvi dozvali, Kur’an bi to bio! Štaviše, Allahu pripada sve! A zar nemaju nade i ne znaju oni koji ne vjeruju da bi Allah, kad bi samo htio, sve ljude uputio. A nevjernike će nesreća neprestano pogađati ili će u blizini mjesta njihova doći zbog onoga što rade – sve dok se Allahovo obećanje ne ostvari. Allah, zaista, ne krši obećanje.", with: correct translation: "Kad bi se kakvom knjigom brda pokrenula, ili zemlja iskomadala, ili mrtvi dozvali, Kur’an bi to bio! Štaviše, Allahu pripada sve! A zar nemaju nade i ne znaju oni koji vjeruju da bi Allah, kad bi samo htio, sve ljude uputio. A nevjernike će nesreća neprestano pogađati ili će u blizini mjesta njihova doći zbog onoga što rade – sve dok se Allahovo obećanje ne ostvari. Allah, zaista, ne krši obećanje." 

Surah Er-Raʿd, 31. ayah

**Comment by ahmedre** [comment]
salam 3alaikum,
@aluckin3 how are you? hope you are well in sha' Allah.

i got some more reports:

> you can see 27th ayah of surah Hadid, on translation, there's missing part from here

i see the one in quranenc.com has more text than the one in our app.


also:

> Esselamu alejkum,
> There is a mistake in the Bosnian (Mehanovic) translation in surah Sad, verse 48 where it says:
> وَٱذۡكُرۡ إِسۡمَٰعِيلَ وَٱلۡيَسَعَ وَذَا ٱلۡكِفۡلِۖ وَكُلّٞ مِّنَ ٱلۡأَخۡيَارِ
>
> (Muhamed Mehanović)
> I sjeti se Ismaila i El-Jese'a i Il’jasa i Zulkifla, svi su oni bili dobri.
>
> -Sura Ṣād, 48. ajet
>
>El-Jese'a (Il'jasa) is mentioned twice.

**Comment by ahmedre** [comment]
i think i didn't update the rest of these yet, is that right? may you double check and if so i'll go ahead and fix and push an update this weekend in sha' Allah? jazakAllah khairan.

**Comment by aluckin3** [comment]
> salam 3alaikum,
> @aluckin3 how are you? hope you are well in sha' Allah.
> 
> i got some more reports:
> 
> > you can see 27th ayah of surah Hadid, on translation, there's missing part from here
> 
> i see the one in quranenc.com has more text than the one in our app.

Yeah, that part is missing.
> also:
> 
> > Esselamu alejkum,
> > There is a mistake in the Bosnian (Mehanovic) translation in surah Sad, verse 48 where it says:
> > وَٱذۡكُرۡ إِسۡمَٰعِيلَ وَٱلۡيَسَعَ وَذَا ٱلۡكِفۡلِۖ وَكُلّٞ مِّنَ ٱلۡأَخۡيَارِ
> > (Muhamed Mehanović)
> > I sjeti se Ismaila i El-Jese'a i Il’jasa i Zulkifla, svi su oni bili dobri.
> > -Sura Ṣād, 48. ajet
> > El-Jese'a (Il'jasa) is mentioned twice.

Yeah, that name is duplicated, will ask shaykh Muhammad what name to use.

**Comment by aluckin3** [comment]
> i think i didn't update the rest of these yet, is that right? may you double check and if so i'll go ahead and fix and push an update this weekend in sha' Allah? jazakAllah khairan.

Yeah, posts before need fixes too.

**Comment by ahmedre** [comment]
ok will wait until the sheikh replies and then will do all the updates in one go in sha' Allah - jazakAllah khairan!

**Comment by ahmedre** [comment]
one more:

> In the Bosnian translation of Muhamed Mehanović surah Alu-Imran 154 is incomplete translated.

**Comment by aluckin3** [comment]
> ok will wait until the sheikh replies and then will do all the updates in one go in sha' Allah - jazakAllah khairan!

For surah Sad, use `El-Jese'a` instead of Il'jasa

Alu-Imran 154 should be:

Zatim vam je, poslije nevolje, spokojstvo spustio, san koji je neke od vas obuzeo, dok su se drugi brinuli samo o sebi, misleći o Allahu ono što nije istina, mislima paganskim. Govorili su: "Imamo li mi išta u svemu ovom?" Reci: “Odredba u cijelosti pripada samo Allahu!” Oni u sebi kriju ono što tebi ne pokazuju. I govorili su: "Da smo išta u svemu ovome imali, ne bismo ovdje izginuli!" Reci: "I da ste u kućama svojim bili, opet bi oni kojima je propisano da poginu izišli na mjesta pogibije svoje, da Allah iskuša šta je u grudima vašim i da ispita šta je u srcima vašim! A Allah dobro zna šta je u grudima."

**Comment by ahmedre** [comment]
pushed updated database 3/26/2020. jazakAllah khairan @aluckin3
