### ISSUE TITLE
dagger error when build release app

### ISSUE THREAD

**Issue by struggledevl** [quran/quran_android#1125]
When i try to build release app dagger error in message android studio

**Comment by ahmedre** [comment]
what error are you getting?

**Comment by struggledevl** [comment]
i got this message:
Error:(224, 88) error: [RefersToDaggerCodegen] Don't refer to Dagger's internal or generated code
(see https://errorprone.info/bugpattern/RefersToDaggerCodegen)

![daggerERror](https://user-images.githubusercontent.com/44139585/55643436-51123180-57fd-11e9-9950-d254e9eb2441.png)

i use android studio 3.0.1
and i try build quran_android-2.0.1-p1

**Comment by ahmedre** [comment]
did you accidentally upgrade `errorprone`?

**Comment by struggledevl** [comment]
Idk sir, what should i do for fix coding it

**Comment by ahmedre** [comment]
i am asking if you accidentally upgraded errorprone in app/build.gradle or its plugin - these errors only show up if you try to do this.

**Comment by ahmedre** [comment]
closing, please re-open if you still have an issue
