### ISSUE TITLE
How to report apps that take app and add ads ?

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#1140]
I searched and find this app use app source code and add ads 
https://play.google.com/store/apps/details?id=com.ezapp.quranreaderandroid.debug

what should I do?

**Comment by ozbek** [comment]
Please visit https://support.google.com/legal/contact/lr_legalother?product=googleplay and send a complaint. More people do that, higher chances the Google will react.

**Comment by MahmoudMabrok** [comment]
ask for a law? what should I do? Is there any template?

**Comment by ozbek** [comment]
I tried the link above and Google sent me an another more appropriate one. Please use this link instead: https://support.google.com/googleplay/android-developer/contact/takedown

![Selection_001](https://user-images.githubusercontent.com/452620/56005747-f56c0a80-5d0c-11e9-84a8-9ab92b791bb7.png)

**Comment by MahmoudMabrok** [comment]
I will do it, thanks.

**Comment by ahmedre** [comment]
jazakAllah khairan!

**Comment by MahmoudMabrok** [comment]
this needed data to report 

Please explain briefly why you flagged the app? 
answer: 
This is a complete rip-off https://github.com/quran/quran_androidincluding images and data. The original project's data is licensed under CC BY-NC-ND which prohibits profiting from it (by way ads, in-app purchases, etc). 

link:
https://play.google.com/store/apps/details?id=com.ezapp.quranreaderandroid.debug
