### ISSUE TITLE
Navbar stays white when reading in night mode

### ISSUE THREAD

**Issue by MahmoodMahmood** [quran/quran_android#1142]
Bug confirmed in both oneplus 6 and samsung note 8.

Before:
![56970964_848470415488824_8782265241854541824_n](https://user-images.githubusercontent.com/14712160/56098093-dab4b400-5f0d-11e9-98a5-4405b9323112.jpg)

After:
![57133760_453967955347303_5333886062034944000_n](https://user-images.githubusercontent.com/14712160/56098208-2caa0980-5f0f-11e9-9e90-d53c99d1e3cf.jpg)

**Comment by ahmedre** [comment]
should be fixed now, jazakAllah khairan for your patch.
