### ISSUE TITLE
Check notch support

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1147]
I got a complaint that Quran for Android doesn't work well when the device has a notch. My phone doesn't have a notch so I can't verify this (though I should probably re-test on the emulator again to see if anything stands out).

**Comment by MahmoudMabrok** [comment]
My  Phone has a notch and app work smoothly

**Comment by MahmoodMahmood** [comment]
Ditto

**Comment by ahmedre** [comment]
ok awesome, closing this for now then. jazakumAllah khairan.
