### ISSUE TITLE
Add more gapless data

### ISSUE THREAD

**Issue by ZaherAirout** [quran/quran_android#1175]
Please Add Mishary Alafsay to gapless menu
Thanks in advance

**Comment by Bakr-Ali** [comment]
Yes please add gapless audio file of Sh. Alafasy. I was just listening to Surat 78 (An-Naba') and the gaps are really noticable especially on Ayat 31-34.

Question: I've listened to those same verses on my iPad in an app called "Golden Quran | المصحف الذهبي" and the gaps were a lot less noticable. So my question is: why this much difference is present between those two apps? Is there a way to reduce the gaps between the Ayat without gapless file?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
the latest version we just pushed this week (still rolling out) has sheikh Mishari in gapless. you should get it by the end of the week in sha' Allah, but you can also download it from the releases page if you're in a rush.
walsalam 3alaikum.
