### ISSUE TITLE
Correction in letters .. sura al baqra .. verse 21 

### ISSUE THREAD

**Issue by sultanlearning** [quran/quran_android#1176]
![Screenshot_20190506-043849_Quran](https://user-images.githubusercontent.com/50307610/57202941-4396c580-6fbc-11e9-9506-1de04ca700bf.jpg)
![20190506_043939](https://user-images.githubusercontent.com/50307610/57202947-55786880-6fbc-11e9-89ef-4a422d3dd0f8.jpg)

Please check the difference and correct. . please make sure to get this corrected asap . Its "firaa shawwassamaa " and if you have any clarification on it. I want to really know. Whether it is read differently.  Please put a light on it jazaak

**Comment by moussa-b** [comment]
Assalam ahlikoum,

I don't think it is a mistake, see attached how it is written in dar al maarifa tajweed mushaf, it is written exactly the same way. You can find all the pages [here](http://www.easyquran.com/quran-jpg/). For you what is the mistake? The alif (ا) missing after the letter ra (ر) and the chedda on the waw (وّ) ?

![page_4](https://user-images.githubusercontent.com/26151311/57213336-c3d22080-6fe6-11e9-851d-8906d75e9e63.jpg)

**Comment by sultanlearning** [comment]
the chedda on the waw (وّ)
Because I have a Quran which has the waw with tazdeet ( chedda) on it and the Quran app or the the link you have sent in that also its without .. therefore I wanted to know whether there different ways of writing Quran and reading Quran or it was an error . Please clarify

**Comment by ahmedre** [comment]
this isn't a mistake - Quran for Android replicates the madani mushaf and in the madani mushaf, it's written that way (as Moussa pointed out above). if you want the style similar to what you attached as a screenshot, check out the naskh app which uses the same naskh font - https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh
