### ISSUE TITLE
Script to convert exported bookmarks to csv

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1177]
This was requested via email - but if we can provide a script (or a small website?) so that people can easily upload Quran for Android json files and have them output as csv instead would be useful.

**Comment by murtraja** [comment]
@ahmedre , We could spin up a server that does this conversion, but I wanted to know, shouldn't this be done by the App itself? So, if I wanted to get CSV, I have to first export the bookmarks, then upload them and download the CSV. Instead, wouldn't it be more convenient if the App could export it in CSV itself in addition to JSON format?

**Comment by ahmedre** [comment]
that's true - the only reason i didn't think to put it in the app directly is because i've only seen one person request this so far (and the default format is json which is easy to parse and i think should be shared with the iOS app (though not sure if it is or not)).

**Comment by murtraja** [comment]
In that case, I can run a server on Heroku which does this. Do you have a language preference for the same?

I am asking this because in the future we might end up merging it with Quran.com backend.

Also, can you share the CSV format in which the output is expected (or should I plainly spit out CSV from JSON)?

**Comment by ahmedre** [comment]
i don't think it has to be a service - i just want to point people to "use this to convert from json to csv format" if someone asks - so a simple script in any language would do the trick

**Comment by murtraja** [comment]
@ahmedre, I checked on my iPhone5, I couldn't find any export bookmarks option. However the bookmarks tab correctly shows three kinds of bookmark - Page bookmarks, Ayah bookmarks and Recent pages. (there is no concept of tag)

**Comment by ahmedre** [comment]
oh i didn't realize there aren't tags on the iOS app yet. i guess the hope is that the files would be shareable between both apps once the iOS app supports this.

**Comment by MahmoudMabrok** [comment]
> i don't think it has to be a service - i just want to point people to "use this to convert from json to csv format" if someone asks - so a simple script in any language would do the trick

is it still open?

**Comment by weekmo** [comment]
Is it still open?

**Comment by ozbek** [comment]
Salam.

Yes, please. Issues with `PRs Welcome` tag are open to anyone wishing to contribute.

**Comment by jibraniqbal666** [comment]
Salam @ahmedre bhai, I worked with you in Careem and i would love to contribute in this.
What if we add directly export CSV in the app?

**Comment by ahmedre** [comment]
wa3laikum alsalam @jibraniqbal666 bhai,
nice to hear from you - sure, as long as the PR isn't in Flutter 😂 
there is an export feature already that exports json so maybe we can just have one option to export csv and one to export json when you tap the export button?
walsalam 3alaikum

**Comment by jibraniqbal666** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/30576574/163681305-5813a3b1-4286-453b-8b7b-5ffc96bede83.png">
Came up with this i will pull up PR, it's just export not import. :)

**Comment by ahmedre** [comment]
jazakumAllah khairan Jibran - merged via #1946
