### ISSUE TITLE
support reordering of translations

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1179]
say you have 3 translations - what if you want a particular one first and then another and then a third? we should allow re-ordering of translations.

**Comment by papasmile** [comment]
Assalaam alaykum, @ahmedre .  Similarly, what about a simple 'favorite translation' option, then have a small divider between favorites and others?

Relating to your suggestion, where would newly added translations get put in that list?  At the bottom, perhaps?  Any ideas on where to do re-ordering?  Perhaps a 'settings' header menu with a 'reorder translations' options that puts that screen into a reorder mode (with a 'done' button)?

**Comment by ahmedre** [comment]
not sure how we are ordering these right now - but let's say this is low priority for now. i think if we want to do it we can just enable that ordering from the translation manager screen itself.

**Comment by papasmile** [comment]
salam, @ahmedre  It looks like we initially display in order of database IDs:

https://github.com/quran/quran_android/blob/15c922185815cf5c634c11d8443fdfbee4256601/app/src/main/java/com/quran/labs/androidquran/database/TranslationsDBAdapter.java#L73

https://github.com/quran/quran_android/blob/654b3368269f2ec622f1fb764eabef41b5c473d9/app/src/main/java/com/quran/labs/androidquran/ui/PagerActivity.java#L1348

Also, display order changes whenever a translation is checked/selected:

https://github.com/quran/quran_android/blob/18bd051be861a348e304cbe33021b21f35c2e92a/app/src/main/java/com/quran/labs/androidquran/ui/util/TranslationsSpinnerAdapter.java#L65

Anyway, If I'm understanding you right your idea is to have some kind of ordering interface in settings then honor setting in ayah display (and action bar).

Also, you're saying 'low priority'... is there another mainly-code task that would be better to pick up?
