### ISSUE TITLE
How to use Images of quran in my App?

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#1182]
I am developing a simple open source app for Quran 
I need Quran Images to be added to my App. 
how can retrieve it from your resources??

**Comment by ahmedre** [comment]
sorry for the very late reply - you can get the images from your phone and bundle them with your apk.

closing this issue for now please feel free to reopen.

**Comment by MahmoudMabrok** [comment]
i have developed app, and open sourced it, thanks for your efforts,
https://github.com/MahmoudMabrok/QuranyApp
