### ISSUE TITLE
Justified mode: يخش become يخس

### ISSUE THREAD

**Issue by selmanon** [quran/quran_android#1184]
![Screenshot_20190514-223745_Warsh Quran](https://user-images.githubusercontent.com/2206036/57730586-12438700-7699-11e9-9870-ef67a27e956a.jpg)

**Comment by ahmedre** [comment]
what app is this? this tracker is for Quran for Android, that doesn't look like Quran for Android?

**Comment by selmanon** [comment]
Sorry it's warsh quran. I beleived that's quran for Android.

**Comment by ahmedre** [comment]
also not Quran for Android Warsh - which is here https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.warsh
