### ISSUE TITLE
Incoming call restarts audio

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1193]
Got this one via email, we'll need to check though - claims that if you get a phone call while playing audio, when the call is done, the audio restarts instead of continuing where it left off (or the app restarts having forgotten where it was).

**Comment by AliAzaz** [comment]
It's working properly. I tested on some devices. Can you please ask that person, on which device this issue is happening.

**Comment by ahmedre** [comment]
jazakAllah khair for trying this brother, will close for now then since i haven't heard anything back.
