### ISSUE TITLE
Question about a reciter link

### ISSUE THREAD

**Issue by vipafattal** [quran/quran_android#1195]
Peace upon you all,
I need Ayman Suwaid recitation verse by verse and I've noticed you've included Ayman Suwaid recitation verse by verse, but I couldn't find the link to his recitation although I've noticed his name in readers.xml.

So please could direct me to the link of Ayman Suwaid recitation verse by verse.

God bless you for your hard working

**Comment by vipafattal** [comment]
Peace upon you all,
I need  Ayman Suwaid recitation verse by verse and I've noticed you've included Ayman Suwaid recitation verse by verse, but I couldn't find the link to his recitation although I've noticed his name in _readers.xml_.

So please could direct me to the link of Ayman Suwaid recitation verse by verse.

God bless you for your hard working

**Comment by ahmedre** [comment]
wa3laikum alsalam,
the open source project only contains a handful of the audio resources to discourage people from republishing the app as is with naming changes (and possibly ads), especially since there are server costs associated with hosting the mp3s and pages and what not.

you can find the files on everyayayh.com though.
walsalam 3alaikum.

**Comment by vipafattal** [comment]
Thank you for sharing with me this link,
but all the links that direct to Ayman Sowaid 64kbps in http://everyayah.com/data are redirecting to the status page for instance:
http://www.everyayah.com/data/Ayman_Sowaid_64kbps/000_versebyverse.zip

**Comment by ahmedre** [comment]
the verse by verse links work
ex: http://www.everyayah.com/data/Ayman_Sowaid_64kbps/001001.mp3

but i don't think there's an all verses for the sheikh.

**Comment by vipafattal** [comment]
Ok I understand, thanks a lot for your help.
