### ISSUE TITLE
Need Help to configure this project

### ISSUE THREAD

**Issue by AbdulRahman8871** [quran/quran_android#1205]
Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully!

**Comment by ozbek** [comment]
Please use debug build.

**Comment by AbdulRahman8871** [comment]
how can i use debug build?? @ozbek

**Comment by ozbek** [comment]
Please see issues #603, #662, #693, #695, and/or #1183.

**Comment by AbdulRahman8871** [comment]
thanks @ozbek it is configured now
