### ISSUE TITLE
Typos in surat al-Kahf trabslation mode (Qur'an an Sahih International translation)d

### ISSUE THREAD

**Issue by mbarbar** [quran/quran_android#1207]
السلام عليكم

I'v come across two typos in the translation mode for surat al-Kahf.

1. In the text of the Qur'an:
![Screenshot_20190916-203538](https://user-images.githubusercontent.com/12083002/64951783-0a535800-d8c2-11e9-8364-af8375697971.png)
There is an extra صد (sorry I don't know how to make the symbol) after كذلك.

2. In the Sahih International translation, the name al-Khidr seems to always (or often, I have not checked all instances) have a space before the r.
![Screenshot_20190916-204223](https://user-images.githubusercontent.com/12083002/64951994-82218280-d8c2-11e9-9f1d-512a93ff3143.png)

**Comment by ahmedre** [comment]
وعليكم السلام

1. that's the way it is in the Arabic text so leaving it.
2. fixed on 3/26/2020 replacing Khidh r with Khidhr in ayahs 71, 72, 74, 75, 77, 78 of Sura Kahf

جزاك الله خيراً
