### ISSUE TITLE
Please teach me how to modify the app. [temporary post]

### ISSUE THREAD

**Issue by abillahbd** [quran/quran_android#1209]
Several months ago, [I had requested a feature](https://github.com/quran/quran_android/issues/1185) of page no. relative to sura and zuz. But I don't see any response from the contributors. I have knowledge of web programming (php, js, etc). So I want to modify my version of the app as I need the feature very badly. I need to revise the 15 juz that I memorized, otherwise I will forget. But I have zero knowledge of android programming. Please somebody at least give me some hints as to how to do it.

I know this post can't be in "issues". So I will delete the post once I have some hints from you brothers.

Thanks all.

**Comment by ahmedre** [comment]
salam 3alaikum,
for the popup, you can do it [here](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/ui/helpers/QuranDisplayHelper.java).

for the actual corners of the image, probably [here](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/presenter/quran/ayahtracker/AyahImageTrackerItem.java) or one of the sibling classes in the `onSetPageBounds` method.

walsalam 3alaikum.

**Comment by abillahbd** [comment]
> salam 3alaikum,
> for the popup, you can do it [here](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/ui/helpers/QuranDisplayHelper.java).
> 
> for the actual corners of the image, probably [here](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/presenter/quran/ayahtracker/AyahImageTrackerItem.java) or one of the sibling classes in the `onSetPageBounds` method.
> 
> walsalam 3alaikum.

Thanks. These seemed difficult for me. Fortunately, I could hard-write the page numbers on the image files using PHP GD library. It's fine now. Let me know if you need these image files. Take a look (at the number on top of the page): 
![Screenshot_20190922-192630](https://user-images.githubusercontent.com/18022475/65388579-167e6000-dd6f-11e9-8f8d-a262f0fe5624.png)

**Comment by ahmedre** [comment]
closing for now. please reopen if needed.
