### ISSUE TITLE
Landscape pages not showing

### ISSUE THREAD

**Issue by AbdullahiAbdulkabir** [quran/quran_android#1226]
As salamu Alaykum, each time I rotates my screen to landscape the pages on my app doesnt show, any help?

Jazakumullahu Khayran.

**Comment by ozbek** [comment]
Wa alaikum assalam.

What model is your phone? What's the Android version? 

Are you using the latest version of our app? https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

**Comment by ahmedre** [comment]
wa3laikum alsalam,
please also check:
1. is your phone's "lock orientation" setting enabled? if so, it'll not allow the app to go landscape.
2. did you accidentally enable the setting for locking portrait mode in Quran's settings?

**Comment by AbdullahiAbdulkabir** [comment]
Fixed, it is now when I split my screen to two that it happens
