### ISSUE TITLE
Notice about Saood Ashuraym recitation 

### ISSUE THREAD

**Issue by Mohanad2020** [quran/quran_android#1239]
When I select Saood Ashuraym recitation in Surat Al-Baqara Ayah 219 at the end it is Yatafakarron but  I noticed that recitation is Yatathakarron 

"يسالونك عن الخمر والميسر ..... لعلكم تتفكرون"

**Comment by ahmedre** [comment]
he pretty clearly says "tatafakaroon" - are you sure you got the right sheikh? closing for now.
