### ISSUE TITLE
quran lines database  for each page

### ISSUE THREAD

**Issue by mohamed-ibrahim-soft** [quran/quran_android#1242]
I want to display quran as font
I will make linearlayout for each page with vertical orientation 
and add inside it many horizontal linear layouts whose count = number of lines in the page 

Each horizontal linear layout has custom views whose count= number of rows related to this line in the following database  that i ask about

Is there a database for quran that contains each line content in each page, i.e for example :
Page 10 has 15 lines from verse 62 to 69, I want 3 rows for line 3
row shows :
ربهم ولا خوف عليهم ولا هم يحزنون
In tashkeel for sure
that has column line 3 and verse 62 

And row shows the verse number 62 itself has column line = 3
And row shows
وإذ أخذنا
that has column line 3 and verse 63

**Comment by ahmedre** [comment]
see the quran/quran.com-images - it's the repo of the script that generates the images from such a database.

**Comment by ahmedre** [comment]
closing for now, please re-open if you are still having issues.
