### ISSUE TITLE
Re-add partial page clean up text

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1252]
There used to be partial page clean up code to clean up cases where people downloaded the pages when we had bugs (resulting in a potentially partial page). Still getting reports about partial pages so really should add this code back.

**Comment by ahmedre** [comment]
Also trying to consider bundling the pages with the app. This would make it easier to “fix” partial pages by overriding them and also would “fix” some of the network issues and download errors people constantly complain about. It can also help with scoped storage.

One point is what pages would make sense to bundle - new or old madani? Right now leaning more towards old madani to help migrate people with issues and partial pages now, and in a future update, make new madani the default and potentially show the page type switcher on first launch.

**Comment by ozbek** [comment]
> consider bundling the pages with the app

Why wasn't that done in the beginning? What has changed since?

**Comment by ahmedre** [comment]
it wasn't done early on since we had several different densities that we offered devices and tried to give each device the "closest" density for their screen. ever since, we've moved to a world in which most people with old madani are getting the same size of images for a while now, and all people on new madani are getting images of the same width.

**Comment by ahmedre** [comment]
also, combining this with the complaints about partial pages makes this more interesting of an idea.

for history of the partial page issues, see #991 with the fix for partial page downloads (which i am hoping is effective and there's no other edge case for this), and #1018 (which used to delete on startup, but removed it after a few months thinking most people likely migrated).

**Comment by ahmedre** [comment]
the discussion of bundling images is still one i am thinking about, but probably not for this next release that i aim to push out in the upcoming days in sha' Allah.

**Comment by benomaire** [comment]
A recent comment on play store (11 Sep 2020)

> تطبيق ممتاز جدا جدا بس فيه الصفحه الثالثه في سوره مريم نصفها مفقود

Do you know what exactly the problem is now? I mean, is it just incomplete download?
Can we require hashes.txt (md5) next to images and compare them at every app start?
or may be compare image sizes with known values (should be faster)?
