### ISSUE TITLE
expanded ayahs are cached across translation changes

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1256]
when the translations change, we should reset the expanded ayah flags

**Comment by papasmile** [comment]
Asslaam alaykum, @ahmedre, are you saying when switching under 'Translations' we ought to reset 'Ayat before translation' back to 'checked'?

![Screenshot_20200416-095125_Quran](https://user-images.githubusercontent.com/3638363/79465174-fe02bb00-7fc8-11ea-8cc6-fd7c55283b36.jpg)

Also, just curious, was that functionality a customer request?  What about just prompting whether they want to reset 'Ayat before translation' or not when they change translation?

**Comment by papasmile** [comment]
Or I think maybe you mean when changing multi-select while viewing actual ayah... but then same question, by 'expanded ayah flags' do you mean that app-wide setting?

**Comment by ahmedre** [comment]
nope - download two translations with long items (ex ibn katheer and sa'di) - choose one of them and show the translation of a sura/ayah - translation items are truncated beyond 500 characters, so find a few of these and expand them. now enable the other tafseer and disable this one, you'll find all the corresponding ones that were expanded with tafseer 1 are now expanded with tafseer 2.

**Comment by papasmile** [comment]
ah ok gotcha.  Tried it out and also found that seem to only happen when there is exactly one translation showing.  That is, when two or three translations are used simultaneously then each translation keeps it expansion state (or perhaps it is based on relative position).

**Comment by papasmile** [comment]
Salam, looking at code, seems like translation changes use normal presenter refresh[1], meaning they are not distinguishable from other refreshes like page load, navigation, background/foregrounding app, etc.  So planning to go ahead with ** translations text always 'collapsing' whenever any refresh or translation change happens **.  We'd need some pretty healthy changes to re-work translation change events to maintain state of expansion so probably better not to worry about it unless we get popular demand for something like that.

[1] https://github.com/quran/quran_android/blob/e1e0ab71f015ee23d90563de62e738a68366b4f6/app/src/main/java/com/quran/labs/androidquran/ui/PagerActivity.java#L1084-L1089
