### ISSUE TITLE
Adding more docs

### ISSUE THREAD

**Issue by ismail-s** [quran/quran_android#1278]
@ahmedre (as you seem to be the main contributor),

Salaams.

I'm thinking of trying to contribute to this project. I'm not sure how much time I'll have (and how committed I'll be), and thought I'd start small and try and add some Javadocs to the code whilst trying to understand it. Then maybe try to see if I can tidy up any of the code, or convert more of it to Kotlin, or work on a small feature. If that sounds sort-of reasonable to you (thought I might as well message you before getting started).

Wassallam,
Ismail

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khair, this sounds great! please feel free!
please try to stick to smaller PRs (i.e. one file at a time, etc so it's easy to review).
jazakAllah khairan!
