### ISSUE TITLE
What is the difference betwee verses and verses_content in sqlit3 database?

### ISSUE THREAD

**Issue by alishir** [quran/quran_android#1284]
Hi all,

I tried to find the schema description of the database, but I didn't find any documentation about database schema. Would you please describe the database schemas?

Regards,
Ali

**Comment by ahmedre** [comment]
`verses` is a [virtual table](https://sqlite.org/vtab.html) - when you make a virtual table, it generates these other tables automatically (verses_content, etc). we only read from `verses`.
