### ISSUE TITLE
[Turkish] Diyanet Isleri translation is outdated

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#1289]
Salam.

The one we have is same as in the [tanzil](http://tanzil.net/trans/tr.diyanet) and, apparently, tanzil has an old version.

See, for comparison, Al-Imran 199:

[tanzil](http://tanzil.net/#trans/tr.diyanet/3:199) | (official) [Diyanet İşleri](https://kuran.diyanet.gov.tr/mushaf/kuran-meal-2/al-i-imran-suresi-3/ayet-199/diyanet-isleri-baskanligi-meali-1)
------------- | -------------
Kitap ehlinden Allah'a huşu duyarak inanıp, Allah'ın ayetlerini az bir değere değişmeyenler vardır. İşte onların ecirleri Rablerinin katındadır. Şüphesiz Allah'ın hesabı çabuktur. | Kitap ehlinden öyleleri var ki, Allah'a, size indirilene ve kendilerine indirilene, Allah'a derinden saygı duyarak inanırlar. Allah'ın âyetlerini az bir değere satmazlar. Onlar var ya, işte onların, Rableri katında mükafatları vardır. Şüphesiz Allah hesabı çabuk görendir.

**Comment by ahmedre** [comment]
JazakAllah khairan - do you know how we can get an updated version?

**Comment by ozbek** [comment]
I could take on that... We had a table somewhere which surah/ayah refers to which page?

**Comment by ahmedre** [comment]
this array tells you what ayah starts on each page - https://github.com/quran/quran_android/blob/357b4933062ceffd436115448b762e5a2e6f49f5/common/data/src/main/java/com/quran/data/pageinfo/common/MadaniDataSource.kt#L51

**Comment by ozbek** [comment]
Would JSON format work for you? Also, there are many cases where multiple ayahs are merged in translation text.

Al-Fatihah:

```json
{"1.1": "Bismillahirrahmânirrahîm"},
{"1.2-4": "Hamd, Âlemlerin Rabbi, Rahmân, Rahîm, hesap ve ceza gününün (ahiret gününün) maliki Allah'a mahsustur."},
{"1.5": "(Allahım!) Yalnız sana ibadet ederiz ve yalnız senden yardım dileriz."},
{"1.6-7": "Bizi doğru yola, kendilerine nimet verdiklerinin yoluna ilet; gazaba uğrayanlarınkine ve sapıklarınkine değil."}
```

Aal-E-Imran:
```json
{"3.1": "Elif Lâm Mîm."},
{"3.2": "Allah, kendisinden başka hiçbir ilah bulunmayandır. Diridir, kayyumdur."},
{"3.3-4": "O, sana Kitab'ı hak ve kendisinden öncekileri doğrulayıcı olarak indirdi. O, daha önce Tevrat'ı ve İncil'i insanlar için birer hidayet olarak indirmişti.Furkan'ı da indirdi. Şüphesiz, Allah'ın âyetlerini inkar edenler için şiddetli bir azap vardır. Allah mutlak güç sahibidir, intikam sahibidir."}
```

Is that good enough?

**Comment by ahmedre** [comment]
sure, that would work - perhaps easier even is csv using a non comma delimiter - maybe `|` - but no problem either way.

i have some way to deal with those duplicates (i have to double check) but i do it for the Arabic tafaseer now too so can do the same for this to say "see ayah 3" when you look at 3:4 for example.

jazakAllah khairan for doing this!

**Comment by ozbek** [comment]
First version: [diyanet.json.zip](https://github.com/quran/quran_android/files/4354022/diyanet.json.zip)

**Comment by ahmedre** [comment]
jazakAllah khairan - will try this out and update you.

**Comment by ahmedre** [comment]
i wrote a script to parse this format (just need to make it into Quran for Android format now). i am think something needs tweaking though - at the bottom for example, there is:

```
{
    "112.1": "De ki: \"O, Allah'tır, bir tektir.\""
  },
  {
    "112.2": "\"Allah Samed'dir. (Her şey O'na muhtaçtır, o, hiçbir şeye muhtaç değildir.)\""
  },
  {
    "112.3": "Ondan çocuk olmamıştır (Kimsenin babası değildir). Kendisi de doğmamıştır (kimsenin çocuğu değildir).\""
  },
  {
    "112.4": "\"Hiçbir şey O'na denk ve benzer değildir.\""
  },
  {
    "112.1-5": "De ki: \"Yarattığı şeylerin kötülüğünden, karanlığı çöktüğü zaman gecenin kötülüğünden, düğümlere üfleyenlerin kötülüğünden, haset ettiği zaman hasetçinin kötülüğünden, sabah aydınlığının Rabbine sığınırım.\""
  },
  {
    "112.1-6": "De ki: \"Cinlerden ve insanlardan; insanların kalplerine vesvese veren sinsi vesvesecinin kötülüğünden, insanların Rabbine, insanların Melik'ine, insanların İlah'ına sığınırım.\""
  }
```

and there is no 113 and 114.

**Comment by ozbek** [comment]
Updated [above](https://github.com/quran/quran_android/issues/1289#issuecomment-601112470).

**Comment by ahmedre** [comment]
can you give this a shot? had to change 18:46 (copied it directly from the website) because the data was saying "null" only for it - also a handful of rows were split across 2 pages so had to join those with the script but all is good - if you want to see the linking properly you'll have to trick the app into thinking the minimum version is 5 - line 109 of `BaseTranslationPresenter`, otherwise you'll see numbers.

[quran.tr.diyanet.db.zip](https://github.com/quran/quran_android/files/4399650/quran.tr.diyanet.db.zip)

**Comment by ozbek** [comment]
Looks good to me :+1: 

> had to change 18:46 (copied it directly from the website) because the data was saying "null"

I don't know how that could happen :\ Probably a network issue or the text wasn't available when I was crawling... I don't know )

**Comment by ozbek** [comment]
Ping @ahmedre! What's happening with this one? :)

**Comment by ahmedre** [comment]
deployed - jazakAllah khairan for this @ozbek !
