### ISSUE TITLE
Fabric is shutting down on Ma‌y 4, 2020

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#1292]
Time to migrate! 
Perhaps to Firebase Crashlytics (since Google bought Fabric).

**Comment by WaseemAlkurdi** [comment]
Or to neither one ... both are non-free :-(
There are free alternatives, which should permit the inclusion of this app in F-Droid.

**Comment by ahmedre** [comment]
FirebaseCrashlytics is open source - so as long as I don't use the analytics sdk and just use crashlytics, we should be ok in terms of F-Droid.
