### ISSUE TITLE
Api is not working

### ISSUE THREAD

**Issue by rustamsmax** [quran/quran_android#1304]
http://android.quran.com/data/zips/images_1260.zip

<img width="640" alt="Screen Shot 2020-04-03 at 04 42 19" src="https://user-images.githubusercontent.com/36570577/78309837-93339780-7565-11ea-9cc8-7639b2358585.png">

**Comment by ahmedre** [comment]
working fine here across all the various servers in the load balancer - can you send me the ip of android.quran.com? does the actual main page load (i.e. if you just go to android.quran.com, what happens?)

**Comment by ahmedre** [comment]
closing for now, please reopen with more info if you can.
