### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by murtraja** [quran/quran_android#1305]
Hello,

I tried to open the project using Android Studio 3.5.3
```
FAILURE: Build failed with an exception.

* What went wrong:
This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 40s
This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.
```

Then I  tried to open using Android Studio 4.1 Canary 1
`The project is using an incompatible version of the Android Gradle plugin.  To continue opening the project, the IDE will update the plugin to version 4.1.0-alpha01.  You can learn more about this version of the plugin from the release notes. `
```
The project is using an incompatible version (4.0.0-beta03) of the Android Gradle plugin.
Upgrade to the latest version
```

If I upgrade, then I get this error
```
A problem occurred configuring project ':app'.
> groovy.lang.MissingPropertyException: No such property: scope for class: com.android.build.gradle.internal.variant.ApplicationVariantData
```

If I build from command line via `./gradlew assembleMadaniDebug` it works fine. But I do want to use Android Studio. Please suggest a solution.

Note: The build variants section was empty so couldn't select Madani Debug from there in both the Android Studio versions

**Comment by ahmedre** [comment]
wa3laikum alsalam,
please try on Android Studio 4.0 Beta 2 (https://androidstudio.googleblog.com/2020/03/android-studio-40-beta-2-available.html) - i haven't tried 4.1 yet.
walsalam 3alaikum.

**Comment by ozbek** [comment]
If you want to stick with the stable version, change build tools version to 3.6.2 (the latest version as of this writing):

```
diff --git a/build.gradle b/build.gradle
index 62025d39..900c9b10 100644
--- a/build.gradle
+++ b/build.gradle
@@ -41,7 +41,7 @@ buildscript {
   }
 
   dependencies {
-    classpath 'com.android.tools.build:gradle:4.0.0-beta03'
+    classpath 'com.android.tools.build:gradle:3.6.2'
     classpath "io.fabric.tools:gradle:1.31.2"
     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
     classpath "net.ltgt.gradle:gradle-errorprone-plugin:1.1.1"
```

**Comment by murtraja** [comment]
Thank you very much @ahmedre and @ozbek 
Since I am on a slow connection, I simply changed the gradle version to 3.5.3 and it worked on the stable release.

**Comment by ahmedre** [comment]
btw 4.1 doesn't work right now because of this bug:
https://issuetracker.google.com/issues/150397894
