### ISSUE TITLE
Headers font size of sura name, juzaa and page number are small

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1322]
Headers font size of sura name, juzaa and page number are small, as shown in the picture attached.
![Screenshot_20200419-053445_Quran](https://user-images.githubusercontent.com/60948528/79679674-db0e1c00-81ff-11ea-870e-8a938eaf0081.jpg)

**Comment by murtraja** [comment]
https://github.com/quran/quran_android/blob/e1e0ab71f015ee23d90563de62e738a68366b4f6/app/src/main/res/values/dimens.xml#L31

**Comment by murtraja** [comment]
A temporary solution would be to simply increase the system font size in accessibility settings. Kill the app and restart.

**Comment by ozbek** [comment]
Right, actually `10sp` is kind of small. For readability 11+ is recommended.

**Comment by nacer80** [comment]
Baraka Allaho fikom my brothers.
I tried to increase font of system but all other fonts are increased but the fonts of sura name and page number changed little bit.
So we will wait till changing in the script

**Comment by nacer80** [comment]
The fonts size of the page headers are depended of screen resolution, when the the resolution increased the fonts headeres decreased.
So I chooed FHD+ not WQHD+ as before.
![SmartSelect_20200419-133322_Settings](https://user-images.githubusercontent.com/60948528/79688030-36adc900-8243-11ea-96e5-d228915a94eb.jpg)

**Comment by nacer80** [comment]
![Screenshot_20200419-135514_Quran](https://user-images.githubusercontent.com/60948528/79688319-78d80a00-8245-11ea-8188-9d077e7ed85e.jpg)

**Comment by nacer80** [comment]
I tested the application in different mobiles with different screens resolution, I found the same issue of small headers font.

**Comment by ahmedre** [comment]
will fix this in sha' Allah.

**Comment by nacer80** [comment]
In sha'Allah my Brother
Jazek Allaho khearen

**Comment by nacer80** [comment]
Salam 3alikom 
Please try to resize up the headers font (sura name) and page number I think also if we make it **Bold** is better.

**Comment by benomaire** [comment]
I think the dual page mode is fine. But the others (full landscape, and portrait) have the problem. The images below are from Nexus API 22.

<details><summary>Screenshots</summary>

![img1](https://user-images.githubusercontent.com/69304392/99152390-83129780-26b2-11eb-9d69-9c409dd66959.png)
![img2](https://user-images.githubusercontent.com/69304392/99152392-860d8800-26b2-11eb-8fff-25f5871d1fdc.png)
![img3](https://user-images.githubusercontent.com/69304392/99152394-886fe200-26b2-11eb-9ce7-4a2be29805b3.png)
![img4](https://user-images.githubusercontent.com/69304392/99152397-8ad23c00-26b2-11eb-8325-cf12ae952455.png)


</details>

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله 
Yes my brother I agree with you. I have a same.
Screen shot from note 10+
![Screenshot_20201114-195341_Quran](https://user-images.githubusercontent.com/60948528/99152626-f4067f00-26b3-11eb-9fd3-7396af23f73e.jpg)
