### ISSUE TITLE
Project in my computer problems

### ISSUE THREAD

**Issue by Hiwaselah** [quran/quran_android#1323]
![https://drive.google.com/file/d/1Cc-NfHt7_gnSvqEWQeelVC2dWrUG9GyK/view?usp=drivesdk]()
Project in my computer problems

**Comment by ozbek** [comment]
The photo you have linked is not accessible.

If you are having errors building the app locally, please see issues #603, #662, #693, #695, and/or #1183.

**Comment by Hiwaselah** [comment]
![20200419_085634](https://user-images.githubusercontent.com/20328840/79689400-4803cf00-825d-11ea-9b73-9432e7e84580.jpg)

**Comment by ahmedre** [comment]
please set your build type to madani debug.

**Comment by Hiwaselah** [comment]
Building problems👇
Crashlytics found an invalid API key : null.
Check the Crashlytics plugin to make sure that the application has been successfully!
Contact support@fabric.io for assistance.

**Comment by ahmedre** [comment]
yes, that's because you didn't set your build type to madani debug.
please set your build type to madani debug.

**Comment by Hiwaselah** [comment]
Thank you
Madani debug for apk no problem

**Comment by ahmedre** [comment]
closing since it's resolved

**Comment by Hiwaselah** [comment]
وين مكان sinse
