### ISSUE TITLE
Feature Request: Support verse by verse mode without translations

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1327]
We have the full screen translation view - some people want to read Quran there without translations. This would just allow that there are no translations with a check next to them.

**Comment by ahmedre** [comment]
btw this is doable today by removing all tafaseer (deleting them from the translation manager). but it's a bit of work just to read ayah by ayah alone 😂

**Comment by murtraja** [comment]
Is it possible to choose the translations like in quran.com ?
Instead of having a check for "No translations" we can go one step further and add checkboxes for corresponding downloaded translations. That way, user can uncheck all checkboxes to get the effect of reading Quran ayah by ayah.

**Comment by ahmedre** [comment]
we already have that - just need to not force "at least one checkbox must be checked" thing - if you are in the full screen translation mode and tap the header you'll see checkboxes by each one.
