### ISSUE TITLE
Add new reciter: Mishary Afasy khatma California 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1334]
I have a timing file of data base of recitation of Shaikh Mishary Afasy khatma California with Tayba way.
ختمة كالفورنيا بقصر المد النفصل عن طريق الطيبة 
It's a beautiful recitation I hope that you help me to add this recitation to application.

https://download.quranicaudio.com/quran/mishaari_california/

**Comment by ahmedre** [comment]
wa3laikum alsalam,
would love to have this. please let me know how i can help.
walsalam 3alaikum.

**Comment by nacer80** [comment]
Salam 3alikom 
Baraka Allaho fik my brother.
I will send you the timing file by email is ready.

**Comment by nacer80** [comment]
Salam 3alikom 
My brothers
I sent you the timing file by email (mishari_alafasy_Cal.db), please chek it and advise me.
I hope Inshallah that we add it in the next update 
Jasakom Allaho keiren

**Comment by ahmedre** [comment]
jazakAllah khairan @nacer80

**Comment by nacer80** [comment]
@ahmedre 
السلام عليكم ورحمة الله وبركاته 
I sent to you timing database update by email

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً
