### ISSUE TITLE
Change speed for audio player

### ISSUE THREAD

**Issue by sbou88** [quran/quran_android#1338]
Salam a3laykoum, 

It can be useful to reduce or increase speed of audio. 

Saha ftourkoum, 
Saïd

**Comment by ozbek** [comment]
Wa 3alaikum salam,

Possible duplicate of #408.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan - closing as duplicate.
walsalam 3alaikum.
