### ISSUE TITLE
Add words meaning, I3rab and Tadabour of Quran 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1351]
We hope that we add words meaning, I3rab and Tadabour of Quran to tafseer and translation.
معاني الكلمات 
اعراب القرآن العظيم 
تدبر القرآن العظيم

**Comment by nacer80** [comment]
@ahmedre 
Salam 3alikom 
I have files i3rab and words meaning of quran on realm database, I hope that we add it to application.

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullah,
jazakAllah khairan - may you send an example and can take a look at it? is there some resource online that has this that i can see what it is first? or the book it comes from?
jazakAllah khairan.
walsalam 3alaikum

**Comment by nacer80** [comment]
Salam 3alikom

1- E3rab.realm  Da3ess & Gassem

اعراب القرآن المؤلف: دعاس وقاسم

https://drive.google.com/file/d/1-XsNIaKdLnAeFdxb1QLUUyeIxK9sr84j/view?usp=drivesdk

2-Ar_ma3any.realm Hessenin Mohammed Mekhlof
معاني كلمات القرآن المؤلف: حسنين محمد مخلوف

https://drive.google.com/file/d/1-MkrdsMBHGWGV5BFp2n5LYPzrGi_Z6sF/view?usp=drivesdk

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
There is another Book of words meaning but I can't found the database.
**El-Siraj** fi ma3ani el-quran Sheikh el-khodhiry.
السراج في معاني القرآن للشيخ محمد عبد العزيز الخضيري

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I'm working for database files DB (words meanings, I3rab and taddabor), when I finish Inshallah I will send it with sources
وجزاك الله خيرا 
![Screenshot_20200602-210153](https://user-images.githubusercontent.com/60948528/83575468-73016400-a527-11ea-81b6-7737af82bb41.jpg)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
 Elhamdo lilah, I already finished words  meanings and I3rab of Quran database files db.

I sent it by email.

السراج في معاني غريب القرآن للشيخ الدكتور محمد عبد العزيز الخضيري 
إعراب القرآن الكريم للدعاس 
 أحمد عبيد الدعاس- أحمد محمد حميدان - إسماعيل محمود القاسم

**Comment by nacer80** [comment]
Salam 3alikom 
@ahmedre 

I need your opinion about tow files, if there is any issue let me know.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakumAllah khairan - haven't looked yet but will take a look this week and let you know in sha' Allah.
walsalam 3alaikum.

**Comment by nacer80** [comment]
Inshaa Allah

**Comment by nacer80** [comment]
الحمد لله 

We add to tafseer three books
1- words meanings Skeikh Khodhair.
2- I3rab of quran (syntax of quran) Sheikh Da3ass Kassem and Homiden.
3-Asbab Nozul of quran (reasons of revelation of quran) Sheikh Wahidy
١- معاني الكلمات من كتاب السراج في بيان غريب القرآن 
للشيخ الدكتور محمد عبد العزيز الخضيري

٢-إعراب القرآن الكريم للدعاس قاسم 
أحمد عبيد الدعاس- أحمد محمد حميدان - إسماعيل 
محمود القاسم 

٣-أسباب النزول للواحدي
الواحدي النيسابوري تحقيق الشيخ الحميدان
