### ISSUE TITLE
كيف أسجل الوقت بصوت واحد في داتابيس؟

### ISSUE THREAD

**Issue by Hiwaselah** [quran/quran_android#1354]
چۆن کات لە دەنگێکدا تۆمار بکەم لە داتابەیس؟
How do I record time in one voice in a database?
كيف أسجل الوقت بصوت واحد في قاعدة البيانات؟

**Comment by Hiwaselah** [comment]
![Screenshot_20200514-062103_SQLite Editor](https://user-images.githubusercontent.com/20328840/81891020-0b06d000-95b0-11ea-802f-a3ace8bd50e4.jpg)

**Comment by ahmedre** [comment]
wa3laikum alsalam,
if you have a csv (excel sheet like that), we can easily write a script to translate it into Quran database format.
walsalam 3alaikum.

**Comment by Hiwaselah** [comment]
و عليكم السلام اخي الحبيب جزاكم الله خيرا
بلا زحمة بالنظر إلى تلك الصورة وعلمني
![Screenshot_20200514-134132_Sheets](https://user-images.githubusercontent.com/20328840/81925658-79b44f80-95e9-11ea-8db6-10f466be9327.jpg)

**Comment by Hiwaselah** [comment]
انا أكراد من كردستان عيراق
ان شاء الله انا اريد إضافة قراء كردية من برنامج

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً - من القارئ؟
لابد أن تكون التوقيت بدقة "milliseconds"
والسلام عليكم

**Comment by Hiwaselah** [comment]
قارئ رعد كردي
بيشوا قادر
قارئ سعد الغامدي( الترجمة كردية)

**Comment by Hiwaselah** [comment]
اخي الحبيب
مثل
55 = 55000

**Comment by ahmedre** [comment]
نعم، صحيح، ولكن لو فعلت هذا ربما لا تكن الدقة كافية إلا لو القارئ يقف وقت كثير بين الأيات

**Comment by ahmedre** [comment]
المشكلة تكون واضحة أكثر لو شغلت أية مقررة (يبدأ الشيخ نفس الأية بعد قضائها)

**Comment by Hiwaselah** [comment]
جزاك الله خيرا و عليكم السلام و رحمة الله و بركاته

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
أخي
استطيع مساعدتك 
لاضافة مقرئ يجب أن تنشئ ملف يحتوي وقت توقف 
 المقرئ على رؤوس الآيات ، وانا شخصيا استعمل برنامج audacity 
حيث تستمع للمقرئ ثم تأخذ وقت وقوفه على رأس الأية بعض القراء قد لايقف على رأس الاية لكن يجب عليك 
 توقيف الصوت وتأخذ وقت وصوله الى رأس الآية  
(اعني  الوقت المناسب بين آيتين)
وفي حالة حصولك على وقت جميع السور تستطيع 
مراسلتي لانشاء قاعدة البيانات
.ويشرفني ان اساعد في ذلك
ذكر ان اصعب مرحلة في المشروع هي استخراج الوقت بعناية

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً أخي ناصر
عندي سكريبت استخدمه ليسهل ذلك - ربما استطيع فتحه لو يساعد - ولكن يبحث عن السكتات ويعطي طريقة سريعة لتحديد الأيات بدون سماع الصورة كلها بأنه يقفز بين السكتات التي في أغلب الوقت تكون في أوائل الأية

**Comment by nacer80** [comment]
بارك الله فيك و جزاك الله خيرا أخي 
سيساعدنا كثيرا السكريبت لان استخراج التوقيت يدويا يأخذ الكثير من الوقت والجهد 
لو تفضلت اخي وأرسلت لي السكريبت

**Comment by ahmedre** [comment]
ارسلته لك على بريدك الالكتروني
إن شاء الله اجعله على 
github 
في المستقبل

**Comment by nacer80** [comment]
بارك الله فيك وجزاك الله خيرا

**Comment by ahmedre** [comment]
وباراك الله فيك وجزاكم الله خيراً

**Comment by nacer80** [comment]
Salam 3alikom 
Please I need your help about the script

**Comment by nacer80** [comment]
Salam 3alikom 
@MJayyusi
Brother witch program you worked with to get timing database file.

**Comment by MJayyusi** [comment]
@nacer80 
In my case I found the ayah by ayah files, the files didn't match exactly to the gapless audio, so I wrote a script to calculate the length of the aya files and add them, then manipulated them as needed using Excel. 

If you want to use audacity, it will take you a lot of effort. 
Unfortunately I don't know any shortcuts other than what brother ahmed mentioned here.

**Comment by nacer80** [comment]
Baraka Allaho fik my brother
