### ISSUE TITLE
How do I record audio times in a database?

### ISSUE THREAD

**Issue by Hiwaselah** [quran/quran_android#1356]
چۆن کاتەکانی دەنگێک لە داتابەیسدا تۆمار بکەم؟
كيف يمكنني تسجيل وقت الصوت لصورة في قاعدة بيانات؟
How do I record audio times in a database?

**Comment by ahmedre** [comment]
if you have csv format (Excel / Google Sheets / Numbers) - we can export this to csv (comma separated values) which are then easy to write a small script to convert them to the database.

**Comment by nacer80** [comment]
SALAM 3ALIKOM 
@ahmedre 
Please I need you help about script

**Comment by ahmedre** [comment]
closing for now since al7amdulillah i know brother Nacer you figured this out - closing, but please reopen if not.
jazakumAllah khairan
