### ISSUE TITLE
Add gabless reciter: Maher Al Muaiqly

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1359]
Salam 3alikom 
Alhamdo lilah, we got database timing file of Shaikh Maher Al Muaiqly (Maher_Al_Muaiqly.db). Brother Abdullah Hussein helped me to obtain database timing file and URLs (with his permission), jazaho Allaho kheiren.

http://abdullahhussein.com/mushaf_files/sound_sura/maher_sura/001.mp3

**Comment by ahmedre** [comment]
wa3laikum alsalam,
masha'Allah amazing! are these files different than the ones we have on quranicaudio.com? please do send the database :)
jazakAllah khairan.
walsalam 3alaikum

**Comment by nacer80** [comment]
Salam 3alikom

Find attached file timing database

**Comment by nacer80** [comment]
Wa3likom aslam

I found some difference in duration time, so I prefer to use http://abdullahhussein.com/mushaf_files/sound_sura/maher_sura/0xx.mp3

**Comment by ahmedre** [comment]
GitHub issues dropped the attachment? may you email it instead?
jazakumAllah khairan.

this recitation looks like it comes originally from tvquran - in sha' Allah we can use it though one day i hope to move to a newer one (like the one on haramain.info.

**Comment by nacer80** [comment]
Salam 3alikom 
Yes Brother it comes originally from tvquran server as brother Abdullah Hussein informed me.
I think there's no big difference between them.
You can upload it now and in the future we will update it Inshallah.

**Comment by ahmedre** [comment]
sounds good - just waiting on the database file from you since i still haven't received it :(
jazakumAllah khairan.

**Comment by ahmedre** [comment]
jazakumAllah khairan - here's an apk for testing:
http://cafesalam.net/uploads/quran_with_sheikh_maher.apk

it doesn't have the translations yet (only English right now). will add them in sha' Allah.

can you also compare with the [known errors](https://github.com/quran/quran_android/issues/204#issuecomment-277400657) in the gapped version to make sure that these files don't have them?

also, i only tested Fatiha for now but i think we might need to re-encode these files if they seem always to be slightly off.

**Comment by nacer80** [comment]
Barak allaho fik, wa jazek Allaho khieren 

Inshallah I will test it, and I report to you if there's any error.

Wassalam 3alikom

**Comment by ahmedre** [comment]
jazakumAllah khairan, really appreciate it may Allah reward you greatly!
while testing it, see if the timings seem slightly off (i.e. cuts off the start of the ayah, especially if you hit back to start at an ayah) - if so i can re-encode the files.

**Comment by nacer80** [comment]
Salam 3alikom 

I checked known errors
1- I found missing of "waw" when we start the Ayah El Bakara 135, due to the timing only, I can fix the issue by changing the timing of Ayah.
2- I found no sound in Ayah Al Inssan 13 from middle to end of Ayah, I searched in the other sites for sura file like mp3quran, Quranicaudio but I found it a same.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan - 

1 - can you make sure the timing actually needs to change? sometimes the timing is correct but the encoding is the problem so if the timing is fine in the audio file, let me know and i can re-encode the files.

2- can we get the one from here instead: https://archive.org/details/HaramainMaahir

**Comment by nacer80** [comment]
Salam 3alikom 

https://archive.org/details/HaramainMaahir
Is new version, the sound quality looks very good but tilawa very slow, it needs new timing file,

**Comment by nacer80** [comment]
Salam 3alikom 

I fixed the issue of missing "WAW" in Sura Al-Bakara Ayah 135.

**Comment by ahmedre** [comment]
will close this since it’s done - jazakAllah khairan @nacer80

**Comment by ahmedre** [comment]
salam 3alaikum,
the brothers on Ayah actually made timing files for this and are willing to share - thinking to switch to this new one because of the higher sound quality (but, as you mentioned, it is much slower - ~2 hrs 15 min for sura Baqarah vs 1 hr 45 min). what do you think? any strong opinion? should we keep the new one only or both?

cc @nacer80 @benomaire 
jazakumAllah khairan.
walsalam 3alaikum.

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
I guess we can have both. We may call it studio version or something, like we have broadcast for Sheikh Husary.
Although the newer version should be better tajweed, etc since they record in KFGQPC studio and have a plenty of time to prepare and review.

Reasons:
1. Speed (you know some people already want the option to speed any recitation 1.5x or so).
2. some people may think for a while this is not Al Muaiqly

see the following comments from [KFGQPC app on play store](https://play.google.com/store/apps/details?id=com.kfgqpc.mmn&hl=ar&showAllReviews=true)

- 2020.06.27

>  ممتاز ولكن في تلاوة الشيخ ماهر المعيقلي بين كل آية و آية فيه لحظة صمت طويلة اتمنى تقصر هذه الفترة

I guess this is because they use non-gapless files.

- 2020.05.28

> حملت القاريء المعيقلي فقط شغلت سورة الملك البسملة بسم الله الرحمن الرحيم بصوت المعيقلي سورة الملك بصوت قاريء أخر غير المعيقلي امل التأكد من صوت القاريء صوت المعيقلي معروف ولا يغيب عن الأذهان يمكن انا مخطيء يمكن ان اكون على صواب....

- 2020.06.01

>  كتب الله أجركم تطبيق رائع ومفيد وفيه بشرى لمحبي تلاوات الشيخ ماهر المعيقلي القراءة الموجودة في التطبيق مجودة برواية حفص

This one likes the new version more!

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I suggest to keep both.
The recitation that exists now is the one reciting the Sheikh in the Haramin and which people are accustomed to hearing.  
The second recitation is very pure and with good ahkam tajweed.
So we can change the name of first one to: 
 maher Al Muaiqly(Haramin,gabless)
 (ماهر الميعقلي(الحرمين،متصل

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً
that sounds good to me.
والسلام عليكم

**Comment by nacer80** [comment]
> salam 3alaikum,
> the brothers on Ayah actually made timing files for this and are willing to share - thinking to switch to this new one because of the higher sound quality (but, as you mentioned, it is much slower - ~2 hrs 15 min for sura Baqarah vs 1 hr 45 min). what do you think? any strong opinion? should we keep the new one only or both?
> 
> the files are here: https://qurancomplex.gov.sa/sounds-muaiqly-hafs/
> 
> cc @nacer80 @benomaire
> jazakumAllah khairan.
> walsalam 3alaikum.

السلام عليكم ورحمة الله وبركاته 
@ahmedre 
About telawa of sheikh Maher Al Muaiqly recorded in KFGQPC
I suggest to use the mp3 files from https://archive.org/details/HaramainMaahir
I found the quality of sound is better then  KFGQPC files.
So if you have already the timing database file please share it with me to check it or I will start making it.
وجزاكم الله خيرا
