### ISSUE TITLE
No scrollbars in QuranActivity

### ISSUE THREAD

**Issue by ismail-s** [quran/quran_android#1370]
There aren't any scrollbars in `QuranActivity`. This isn't so much of an issue with the Sura/Juz lists, but with the bookmarks, if there are a lot of bookmarks, then this can be hard to navigate (perhaps this issue should instead be more focussed on making navigation of large numbers of bookmarks easier in general, I'm not sure).

**Comment by ahmedre** [comment]
you mean like a fast scroll type thing? agree we definitely should do this - even for the sura/juz views as well.

**Comment by ismail-s** [comment]
I've been taking a look into this and searching for/trying out different options:
- [This blog post](https://androidkt.com/recyclerview-fast-scrolling/) describes how to use the plain `RecyclerView` to do fast scrolling. I've tried this out (with colours instead of full-on drawables mentioned in the blogpost), and this works, but is tricky to grab the scrollbar (on my phone, I have to grab the top part of the scrollbar, it's a bit awkward to do), though this might be because of the way I wrote the test code. And the scrollbar gets very small when the list is very long, [this is a 3 years old Android bug](https://issuetracker.google.com/issues/64729576).
- Alternatively, we could use a third-party dependency. There's a few options (all Apache-licensed, all give you that fancy thumb/popup while scrolling):
  - https://github.com/zhanghai/AndroidFastScroll - made by a Google employee but not an official Google thing. Looks fine, but only supports from SDK version 21
  - https://github.com/quiph/RecyclerView-FastScroller - looks nice, but min SDK version is 16
  - https://github.com/timusus/RecyclerView-FastScroll - looks popular-ish, sort-of maintained, min SDK version is 14 (ie same as us). I've given this a try, it works fine. This is the one I think we could go with, but it involves adding a third-party dependency, if that's ok with you.

**Comment by benomaire** [comment]
I would love to see something like [this](https://github.com/reddit/IndicatorFastScroll) if that is possible.

I think the ideas in the images below is good (from [this app](https://apps.apple.com/us/app/bayan-quran-%D8%A8%D9%8A%D8%A7%D9%86-%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86/id525719136) before their major update)

<details><summary>Screenshots</summary>

![juz](https://user-images.githubusercontent.com/69304392/94639701-7b0abe00-02e5-11eb-9673-0f79bc595810.png)
![surah](https://user-images.githubusercontent.com/69304392/94639704-7cd48180-02e5-11eb-8ad4-0747e7c79a2f.png)


</details>

**Comment by amynbe** [comment]
Regarding the fast scroller concept, I suspect that most people just need to jump between surat Al Baqarah and Juz' Amma.

That is at least my case and having to scroll physically during several seconds to do that is painful, from a user experience point of view.

So if we had to opt for a minimal solution, I'd be happy with even just two buttons, one to scroll to the top and one to scroll to the bottom of the list.

**Comment by ahmedre** [comment]
done for now - when we switch to minSdk 21 we can adopt the reddit library and show the sura number also in sha' Allah.

**Comment by ahmedre** [comment]
jazakumAllah khairan @ismail-s
