### ISSUE TITLE
Issue with page headers on Curve edge phones

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1373]
السلام عليكم ورحمة الله وبركاته 
 On curve edge phones the name of Surah and hizeb partially appear due to the curve of screen phone like Samsung, so I propose to move the headers a little bit from the edge of page and resize up it and make with **bold** font.**
جزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
may you send a screenshot? we should fix this if so in sha' Allah.
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
![Screenshot_20200602-014140_Quran](https://user-images.githubusercontent.com/60948528/83467645-7555b680-a472-11ea-8857-dfd6bbf3b792.jpg)

**Comment by ahmedre** [comment]
jazakumAllah khairan will fix

**Comment by nacer80** [comment]
ان شاء الله 
بارك الله فيكم وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Still headers fonts and page number need to resize  up and **Bold** 
وجزاك الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله 
Still Surah name and page number on the header are small size, it needs to resize and I suggest to change the **font  to bold with black color**.
وجزاكم الله خيرا
