### ISSUE TITLE
Page numbers are not shown on translation pages

### ISSUE THREAD

**Issue by Ahmed9914** [quran/quran_android#1377]
السلام عليكم

Page numbers are not shown on translation pages, however they are shown on quran pages.

و جزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
I hope that we use interface for translation and tafseer as quranapp.com , it's very useful and amazing.
It contains Surah name, tafseer or translation name, page and index for choosing surah.
Please see the attached pictures
![Screenshot_20200616-143858_Samsung Internet](https://user-images.githubusercontent.com/60948528/84784743-937af500-afe2-11ea-8ab8-4bf591cb4c77.jpg)
![Screenshot_20200616-143942_Samsung Internet](https://user-images.githubusercontent.com/60948528/84784813-a4c40180-afe2-11ea-8135-e21122c29b8b.jpg)
http://quranapp.com/89
وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@Somaiagabr 
Please we need your help about the issue.
I think the interface tafsser of http://quranapp.com/89
It's useful then the current ones.
