### ISSUE TITLE
Add new gapless reciter :sheikh Juhaynee

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1379]
السلام عليكم ورحمة الله وبركاته 
Too many people ask about sheikh Juhaynee.
Now I have timing database file db but we have an issue in our server https://download.quranicaudio.com/quran/abdullaah_3awwaad_al-juhaynee/
 for this sheikh  so I suppose to use other server till repair it.
http://abdullahhussein.com/mushaf_files/sound_sura/abdullah_juhayne_sura/

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً - i love sheikh Juhany, will be great to get him. though i wish for a newer recitation if possible :)

what is the issue you're having with our server?
it seems to be loading fine for me?
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
There is an issue with the quality of sounds, when I open  the file I hear only bessmla good but after I hear only noise.
I downloaded surah Afatiha but the still fhe same issue.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I sent the timing database file of Shaikh Juhaynee by email

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
oh you mean the quality - ok - so i should download the ones from the other url you sent? that link seems to be broken.
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
وجزاكم مثله
وبارك الله فيكم
