### ISSUE TITLE
Misplaced translation for ayah 91:5

### ISSUE THREAD

**Issue by rhsarker** [quran/quran_android#1381]
Ayah 91:5 has wrong translation in Bangla by ABU BAKAR ZAKARIA.  91:5 and 91:6 are showing the same translations in this case.

**Comment by ahmedre** [comment]
jazakAllah khairan - reported this to the quranenc.com team and will wait for them to advise.

**Comment by rhsarker** [comment]
Another misplaced translation in Bangla by ABU BAKAR ZAKARIA.  56:64 and 56:65 are showing the same translations in this case.  Thank you for your attention.  JajhakAllahu khairan.

**Comment by ahmedre** [comment]
already reported this second one to them when someone reported. still waiting on their update in sha' Allah.

**Comment by ahmedre** [comment]
fixed now. jazakumAllah khairan.

**Comment by rhsarker** [comment]
Thank you for your quick attention to this matter.
Rakibul Sarker

**Comment by rhsarker** [comment]
Assalamualaikum.

Dear brother,

In surah kahf (#18), ayah 32, Bangla translation is not showing property.
Please check it and fix it as soon as possible.  Thank you for your
attention.

Rakibul Sarker
