### ISSUE TITLE
Add new gapless reciters: sheikh Qari Yassin & I.Doussery

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1391]
السلام عليكم ورحمة الله وبركاته 

For warsh version, I hope that we add the famous shouiokh of reweyet warsh: sheikh Qari Yassin Eljzairy and sheikh Ibrahim Doussery.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
we already have sheikh Ibrahim Dossary.
open to getting more shuyookh in sha' Allah.
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I think Sheikh Doussery recitation not gapless.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I created the timing database files of both shouiokh for new warsh Mushaf (the number of Ayats in Warsh not same as Hafs).
I will send by email.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
I sent by email the timing database for:
- Yassin Eljzairy ياسين الجزائري
yassin_eljzairy.db

https://server11.mp3quran.net/qari/001.mp3
- Ibrahim Doussery  إبراهيم الدوسري
ibrahim_doussery.db

https://server10.mp3quran.net/ibrahim_dosri_hafs/Rewayat-Warsh-A-n-Nafi/001.mp3

Both reciters for Warsh Mushaf (6214 Ayah).
I  hope that you add it to  Warsh app
Wa jazek Allaho khieren

**Comment by Hiyaro** [comment]
What do you think of this one ?

Also al hussary is a great reciter. If you tell me what you need I can work on his recitation in warsh.

**Comment by nacer80** [comment]
I listened to some surahs of recitation of sheikh Abdelkarim Aldeghoush, he has a good Ahkem tajweed, but still Sheikh Al hussary the best in Ahkem.

So I propose to start with Sheikh Al hussary first then we can work with Sheikh Al deghoushi.

وجزاك الله خيرا

**Comment by Hiyaro** [comment]
Yes + Al hussary is widly used by Hufadh.
It is the one my teacher advised me to listen to, to learn Qira'at warsh at home.

Tell me what to do. If there's a tuto I can help out.

**Comment by ahmedre** [comment]
here's a version with these shuyookh, jazakumAllah khairan for making these databases -
http://cafesalam.net/uploads/warsh_tajweed_updated.apk
