### ISSUE TITLE
Inconsistent Audio Playback on Tablets

### ISSUE THREAD

**Issue by Korogba** [quran/quran_android#1393]
When playing audio on tablets the audio playback jumps between ayahs.

### To reproduce:
- Go to Surah Al-Fatihah on a tablet
- Activate dual and quran mode  
- Start audio playback
- Wait for recitation of Fatihah to finish
### Expected result
- After recitation of Fatihah, recitation of Surah Al-Baqarah is started
### Actual result
- After recitation of Al-Fatihah, recitation jumps to ayah 6 of Baqarah - **Q[2, 6]**
- After recitating some ayahs, it jumps back to the beginning of Baqarah and so on.

**Comment by ahmedre** [comment]
salam 3alaikum,
i just tried this and it seems to work for me - does it still happen for you? if so, may you tell me:

1. the sheikh
2. your setting for streaming - is it on or off?
3. your setting for "download amount"?

jazakumAllah khairan.
walsalam 3alaikum

**Comment by Korogba** [comment]
Walaikum salaam. 

I am unable to reproduce this. I will close this issue then.

Wa Antum fa Jazaakum Allaahu Khayran.
