### ISSUE TITLE
Add new gapless reciters: sheikh Fares Abbad

### ISSUE THREAD

**Issue by programmingsmartly** [quran/quran_android#1395]

**Comment by ahmedre** [comment]
cc @nacer80 if you're up for it :) we get this request a lot.

**Comment by programmingsmartly** [comment]
إن شاء الله I'm up for it

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I'm working for it

**Comment by programmingsmartly** [comment]
و عليكم السلام ورحمة الله و بركاته 
Great! sounds promising

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Alhamdo lilah,
Finely, I created database timing file of sheikh Fares Abbad. فارس عباد
fares_abbad.db

https://download.quranicaudio.com/quran/fares/001.mp3

Or (same durations)

https://download.quran.islamway.net/quran3/321/001.mp3

But we have to re-encoding the mp3 to work with application without changing the duration of each file.
وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
masha'Allah amazing! جزاك الله خيراً!
lots of people have been asking for the sheikh.

i'll just re-encode the quranicaudio files in sha' Allah.
looking forward to the database via email since it didn't attach here.
barak Allah feekum and جزاك الله خيراً
walsalam 3alaikum.

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
I sent the file via email.
FYI I used the link below to create the timing database file:
https://download.quran.islamway.net/quran3/104/001.mp3
The files have the same duration  but note the same quality, so I hope we keep the same duration of each mp3 file after re-encoding or we will have to modify the database timing file.
وجزاك الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Baraka Allaho fik @ahmedre 
The  files re-encoded, except the surah Zomar 39 (039.mp3).
We need to fix this issue.
About database timing file is ready Alhamdo lilah , I will resend it via email.
وجزاك الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
yes al7amdulillah they are reencoded here - https://download.quranicaudio.com/quran/fares/reencode/
sura Zumar is here - https://download.quranicaudio.com/quran/fares/mistakes/ - i copied it there when someone reported an error in it many years ago, but can't remember what - maybe if we can find the error we can just patch the file in sha' Allah and use it.
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
About surah Zumar sura  https://download.quranicaudio.com/quran/fares/mistakes/039.mp3
 I checked it many times, I didn't find any error.
والله اعلم

**Comment by programmingsmartly** [comment]
السلام عليكم ورحمة الله و بركاته
الحمد لله رب العالمين
Error found at minute 11:54 it skips from "إن في ذلك " Aya 42 to "قل يا عبادي" Aya 53

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
بارك الله فيك 
I used other link to creat database file

https://download.quran.islamway.net/quran3/104/039.mp3
and when I  cheked؛  I listened to the same file.

You re right barak Allaho fik, there is an error in this version 
https://download.quranicaudio.com/quran/fares/mistakes/039.mp3

@programmingsmartly 
Check the file in above link, if it's ok, we will request to Ahmed to change the mistake file with the correct one.
وجزاكم الله خيرا

**Comment by programmingsmartly** [comment]
السلام عليكم ورحمة الله و بركاته
 بارك الله فيكم جميعاً

https://download.quran.islamway.net/quran3/321/039.mp3

Checked and highly recommended, since it's quality way higher than the other one.

 و جزاكم الله خيراً كثيراً

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 

Could you please put it in re encode folder

وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
done - sorry i had forgotten - also i did reencode it.
والسلام عليكم

**Comment by ahmedre** [comment]
http://cafesalam.net/uploads/quran_with_fares.apk
