### ISSUE TITLE
11

### ISSUE THREAD

**Issue by heshamgadalla** [quran/quran_android#1400]

**Comment by heshamgadalla** [comment]
![Screenshot_20200710-142455](https://user-images.githubusercontent.com/68110263/87150270-67d5ec80-c2ba-11ea-9904-9daafaaa2b55.png)

**Comment by ahmedre** [comment]
we took the pages we are using here from the King Fahd Quran Complex in Saudi Arabia, which publishes a lot of the masahif in the world. this is the way the signs were in the older madani mushaf as printed by the King Fahd Quran complex.they changed it in the newer versions, which you can access by going to settings, page types, and choosing the new madani page type.

in general there is ikhtilaf about the stopping symbols and so you'll see differences in stops between different masahif.
