### ISSUE TITLE
Add new gapless reciter: Sheikh Khalifa Taniji

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1406]
السلام عليكم ورحمة الله وبركاته 
We hope that we add Sheikh Khalifa taniji, he has a good recitation and  very good Ahkam tajweed.
I found a good quality of mp3's files:

http://s1.zekr.online/quran/47/(*)/00(*).mp3
http://s1.zekr.online/quran/47/1/001.mp3
to
http://s1.zekr.online/quran/47/114/114.mp3
وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Insh'Allah I will use the files from mp3quran to create the timing database file:
https://server12.mp3quran.net/tnjy/001.mp3
to
https://server12.mp3quran.net/tnjy/114.mp3

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Alhamdo'lilah, I created database timing file of sheikh Taniji: 
Khalifa_taniji.db ( خليفة الطنيجي )
Tilawa mp3 files links:
from
https://server12.mp3quran.net/tnjy/001.mp3
to
https://server12.mp3quran.net/tnjy/009.mp3

Surah Yunus file from
https://download.quran.islamway.net/quran3/677/010.mp3

from
https://server12.mp3quran.net/tnjy/011.mp3
to
https://server12.mp3quran.net/tnjy/114.mp3

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
I sent you the database timing file via email

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً
http://cafesalam.net/uploads/sheikhs_khalifa_and_matrood.apk
والسلام عليكم
