### ISSUE TITLE
Improvements to audio settings

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1407]
From an email (and I agree with these making sense):

> 1. When I play a Surat then I go into settings to chose to play from what Surat to what Surat and I click play only above verses, the audio of the Surat will restart. It really shouldn't have to restart and should just apply the settings and keep playing. It makes it harder for the kids to focus because it repeats when I apply the settings.

> 2. There should be an option to remember the last selected setting being "play only above verses". I'm always having to manually select it.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I got this comment from Google play store.

**8/25/20  

Assalamualaikum. In this new version, I cant select the number of ayahs to be played. Once we select the 'play' button, it will play the entire surah. The previous version let us select the number of ayahs to be played.**

**Comment by arman2123** [comment]
Is this issue solved? Any further improvement needed on this area?

**Comment by sempsmahad** [comment]
@arman2123 not yet solved @ahmedre had told me to make some changes to my solution

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
this functionality never went away - start playing - at the bottom of the screen in the audio bar is a settings icon. tap it and you can select the number of verses being played, how many to repeat, and so on.
والسلام عليكم

**Comment by sempsmahad** [comment]
وعليكم السلام ورحمة الله وبركاته
@ahmedre i think i will have something by monday next week إِنْ شَاءَ ٱللَّٰ

**Comment by arman2123** [comment]
I am new to this project, although I use quran.com regularly. I'll try to get the working in the local dev environment. I'll get back to the github Issues later to pick up tasks when I can handle them. 

Do you guys have any channel where you communicate? Slack, teams etc. Just in case if I need to discuss something.

**Comment by reinaldoriant** [comment]
@ahmedre 
السلام عليكم ورحمة الله وبركاته
I tried this repro, but I didn't find yet the problem in the first opinion. But the second opinion is maybe I can help using data store, can I?.

**Comment by shahawi** [comment]
السلام عليكم و رحمة الله و بركاته

I was wondering what is the state of this issue, And how can I help instead of starting over.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
I believe this was fixed and merged long ago.
please open a new issue if there are still problems with it.
would be glad to have your contribution on any improvements to the code though, please feel free to open a ticket with some info about what you want to do / improve before building it.
جزاكم الله خيراً
والسلام عليكم
