### ISSUE TITLE
Add new gapless reciter:sheikh Abdullah Matroud

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1409]
Many people are asking for Sheikh Abdullah Matroud عبدالله المطرود 
So we hope that we add him to App.
Tilwa link:

https://download.quranicaudio.com/quran/abdullah_matroud/reencode/

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
I sent you the database timing file via email

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً
http://cafesalam.net/uploads/sheikhs_khalifa_and_matrood.apk
والسلام عليكم
