### ISSUE TITLE
Skipping several words in Surat Ya-Seen 

### ISSUE THREAD

**Issue by programmingsmartly** [quran/quran_android#1412]
السلام عليكم و رحمة الله و بركاته
Skipping after the first word of Aya 83 in Surat Ya-Seen, to Aya 1 in Surat As-saaffat. While Fares Abbad reciting.

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
I fixed the issue.
I will send the database timing file update.
وجزاك الله خيرا
