### ISSUE TITLE
Starting at the middle of Aya, instead of the beginning.

### ISSUE THREAD

**Issue by programmingsmartly** [quran/quran_android#1413]
السلام عليكم و رحمة الله و بركاته

Starting at لم تقولون ما لا تفعلون in Aya 2 Surat As-saf, instead of the beginning يأيها اللذين ءامنوا

Although coming from Aya 1 same Surah, reads the whole Aya from the beginning to the end, but with a little delay in transferring the green highlight from Aya 1 to Aya 2.

"While Fares Abbad reciting"

وجزاكم الله خيراً

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
Brother @nacer80, may you take a look?
جزاك الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
Barak allaho fik my brother for your help.
I fixed the issue.
Please try to close the issue #1412, and keep #1413 open till we fix all issues if we have .
وجزاكم الله خيرا 
[fares_abbad.zip](https://github.com/quran/quran_android/files/5051674/fares_abbad.zip)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@programmingsmartly، 
I think no more issues, if it's ok please close the issue.
Jazek allaho kheiren for your help.

**Comment by programmingsmartly** [comment]
السلام عليكم ورحمة الله وبركاته و جزاكم الله خيراً
