### ISSUE TITLE
ayah snippets in warsh should use warsh data

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1414]
"wa sari3u" is 7afs - in warsh it should just be "sari3u"

![Screenshot_20200810-224538_Quran - Warsh](https://user-images.githubusercontent.com/47771/89834236-7b070100-db73-11ea-8e3c-fae03656ae5e.jpg)

**Comment by ahmedre** [comment]
(this fix should also apply to other non-hafs rewayat)

**Comment by ahmedre** [comment]
@nacer80 did we already fix this one or only for search?

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته
@ahmedre 
We  already fixed it in last update 2.0.2 
![867srBUvZIcDlUjsQPWHBhkQTWv.jpg](https://user-images.githubusercontent.com/60948528/160851462-4f01b4e5-b4d9-4359-867a-c21eea64465e.jpg)

**Comment by ahmedre** [comment]
جزاكم الله خيرا
