### ISSUE TITLE
Add new gapless reciter: Sheikh Salah Bukhatir

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1415]
السلام عليكم ورحمة الله وبركاته 

lots of people have been asking for the sheikh Salah Bukhatir.
But first we need to fix the issue in sura Al-Bakara 
Ayah 74 start time @21:08

https://download.quranicaudio.com/quran/salaah_bukhaatir/mistakes/002.mp3
Alhamdo lilah I found good one in Skeikh web site

http://www.salahbukhatir.com/storage/app/media/Sounds/Quran/02.mp3
So please @Ahmedre try to change the old one with the new one.
وجزاك الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً - replaced the file.
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Baraka Allaho fik my brother 
Now all files in
https://download.quranicaudio.com/quran/salaah_bukhaatir/xxx.mp3
Find attached file of timing database of sheikh Salah Bukhatir  صلاح بوخاطر 
[salah_bukhatir.zip](https://github.com/quran/quran_android/files/5078277/salah_bukhatir.zip)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
Please add Sheikh Salah Bukhatir to app reciters list 
وجزاك الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاك الله خيراً akhi
really sorry for the delay, and may Allah reward you greatly!
http://cafesalam.net/uploads/sheikh_bukhatir.apk
والسلام عليكم

**Comment by nacer80** [comment]
وفيك بارك الله أخي 
وجزاك الله خيرا
