### ISSUE TITLE
Ayat Markers overlap with text in two-page mode

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1419]
See the attached image. The circle touches the Quran text and sometimes overlaps with it.
![bug1](https://user-images.githubusercontent.com/69304392/90427230-ee0bfc80-e0ca-11ea-8401-ec53068cb0ab.png)

**Comment by ahmedre** [comment]
fixed, jazakumAllah khairan. there was a mistake with the calculation that caused the ayah marker width to be too large.

![Screenshot_1602333606](https://user-images.githubusercontent.com/47771/95655379-efc8ce00-0b17-11eb-8af1-4d3a98e1571d.png)
