### ISSUE TITLE
Database Error: Sheikh Muhammad Jibreel Surah 9

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1420]
From Google play:

> التطبيق ممتاز جزاكم الله خيرا بس في سورة التوبه بدل ما يقرا الايه اللي ضغط عليها يقرأ االي بعدها وينقل القراءه للصفحه الاخري ولاكن الصفحه لا تقلب وسوره يونس الصوت بايظ خالص للشيخ محمد جبريل

Database not synchronized. Not sure what is the issue in Surah 10.

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
I know that you are good at working with audio files, but I think there are several quality issues. For example, I did not notice the noise that starts at minute 21 before, sorry for that.

Anyways can you check the following links, I guess the link of Surah 10 is the one you already used.
1. [Surah 9](https://dl2.islamweb.net/Audio3/quran/mjebreel/s9.mp3)
2. [Surah 10](https://dl2.islamweb.net/Audio3/quran/mjebreel/s10.mp3)

BTW I use hotmail

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Jazek allaho kheiren my brother
Now we can use both files.
I created also the database timing file and I changed the version from 2 to 3.
@ahmedre please change the old damaged files:

https://download.quranicaudio.com/quran/muhammad_jibreel/complete/009.mp3
https://download.quranicaudio.com/quran/muhammad_jibreel/complete/010.mp3
By:
https://dl2.islamweb.net/Audio3/quran/mjebreel/s9.mp3
https://dl2.islamweb.net/Audio3/quran/mjebreel/s10.mp3
[mjibreel.zip](https://github.com/quran/quran_android/files/5115193/mjibreel.zip)
About you question, I use my mobile phone  media player like Samsung player, Google player, Mx player....

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً - acknowledging receiving this - haven't uploaded yet, but will in sha' Allah.
one quick question - these files aren't great in terms of quality - if there are just ayat that are cut, can we just fix them instead (example ayah 73, can we just take that ayah from this mp3, glue it into our mp3 and keep the overall higher quality version?) - how about suras 9 and 10?
جزاكم الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
About the files 9 and 10, my brother @benomaire and me checked other servers but we found the same file as our server(the same issue), so we chose the these files from islamweb, we know the bit rate is 64 kps but the quality is good.
About the file 8 :
We already have the file modified :
https://download.quranicaudio.com/quran/muhammad_jibreel/complete/008.mp3
but when I compared with :
https://dl2.islamweb.net/Audio3/quran/mjebreel/s8.mp3
I found the last one is better even the bit rate is 64 kps.
N.B:
The issue cut of Ayat 73 in: 
https://download.quranicaudio.com/quran/muhammad_jibreel/complete/reencoded/008.mp3

وجزاكم الله خيرا

**Comment by benomaire** [comment]
I think our quality perception is subjective. For example, the original google play comment stated that surah 10 has bad quality, and I was not sure what is the problem because it looked good for me.
Personally, I still feel that quranicaudio files are better in quality than islamweb. The difference in quality in the middle of the files exist in both websites, and I think it is because the recordings were not done in the same day. May be the noise in quranicaudio is more clear because it is more loud.

Let's focus on surah 8 for now. I applied Low Pass Filter and noise reduction on [this file](https://download.quranicaudio.com/quran/muhammad_jibreel/complete/008.mp3) and the result [is here](https://archive.org/download/008filtered/008filtered.mp3). It should have low noise now (also compare the spectrograms).

<details>
<summary>
Spectrograms
</summary>

#### Original
![008quranicAudio](https://user-images.githubusercontent.com/69304392/91666142-2c5dde80-eb03-11ea-8d55-9da4f65a6083.png)

#### Filtered
![008quranicAudio-filtered](https://user-images.githubusercontent.com/69304392/91666175-6202c780-eb03-11ea-9c15-c4e14441ceff.png)

</details>

**Comment by ahmedre** [comment]
السلام عليكم ورحمة الله وبركاته
جزاكم الله خيراً 
i was trying these again and -

1. sura Anfal - i fixed on 2/17 (including the database) but accidentally forgot to copy the file into reencoded folder - i think we should keep this one and maybe replace the ayah itself with the correct one from the recitation you gave (and perhaps the mp3 with the one @benomaire ran filtering on).

2. sura Tawbah - this is very strange - on the phone, using the quranicaudio mp3 - the first 57 verses are great quality (in quranicaudio mp3) and then quality is terrible - on the web, quality is good throughout.

3. sura Yunus - on my phone, using the quranicaudio mp3, the quality is really bad, but on the web, quality is much much better.

will hold off on this until i can investigate further - both the files in /complete/ and the files in /complete/reencoded are actually great if you listen to them on the web.

جزاكم الله خيراً 
والسلام عليكم

**Comment by ahmedre** [comment]
tried sura Tawba ayahs 58 and beyond and sura Yunus on another Android phone (and on an emulator) and they sound good just like the website on both of these.

both sound really bad on the Huawei phone i was testing on though - and i am guessing that explains a lot - i also tried playing them in the browser directly from the website and the quality is equally bad, so it's not due to a bug in the app - somehow Huawei phones don't like the specific encoding of ayahs 58 and beyond of sura Tawba and a bit of sura Yunus in this case :(

**Comment by benomaire** [comment]
@ahmedre Try reencoding the quranicaudio mp3 files of surah 9 and 10 again and repeat your tests.
`sox 009.mp3 009reencoded.mp3`

**Comment by ahmedre** [comment]
for Surah Yunus (the one I was testing with) - just tried using `sox` - didn't help. also tried a lot of other things, all of which didn't help -

* made it mono
* reduced bitrate
* increased bitrate
* converted to wave and played that
* ran a high frequency filter in Audacity
* ran a low frequency filter in Audacity
* matching frequency and bitrate to the Islamweb file

and irrespective, none of these actually help at all - there's a day and night difference between the Islamweb files and the Quranicaudio files on the Huawei device - though on my computer and on my other Android phone and the emulator, the Quranicaudio files are much much better.

might just go with these Islamweb files  ¯\_(ツ)_/¯

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 

I think this is the best way.

Also the quality of sound is good even the bit rate 64kb/s (I mean islamweb files)


Great job Mash'Allah brothers  @benomaire   
@ahmedre 
جزاكم الله خيرا

**Comment by benomaire** [comment]
@ahmedre Thanks for the extensive tests. I guess I know what is the problem now. I finally was able to reproduce the bad quality on the pc. 

If I am not mistaken, the problem is in the sampling rate, and this will explain what @nacer80 was referring to as well. I suggest using [this software](https://soundconverter.org/) with the following settings:
### Type of result?
Format: MP3 (.mp3)
Bitrate mode: Variable (VBR) - Best quality
Quality: Normal

**Tick** Resample 48kHz

@ahmedre please try that, and hopefully we will all agree on this result.

**Comment by ahmedre** [comment]
i am not using Linux so i can't actually try this specific software - but i did try:

```
ffmpeg -i 010.mp3 -q:a 3 -ar 48000 010_vbr.m3p
```

it didn't help :( also tried with `-q:a 0`.

**Comment by ahmedre** [comment]
السلام عليكم ورحمة الله وبركاته
copied brother Nacer's files. closing this now.
جزاكم الله خيراً
والسلام عليكم

**Comment by benomaire** [comment]
@ahmedre can you share some details about that Huawei phone?

**Comment by ahmedre** [comment]
Huawei Nova 7i running Android 10.

tried:
```
ffmpeg -i 010.mp3 -b:a 32k -ar 24000 -ac 2 010_24k.mp3
```

but same result :(

**Comment by benomaire** [comment]
@ahmedre if you have time please test these

[010-1.zip](https://github.com/quran/quran_android/files/5252567/010-1.zip)

[010-2.zip](https://github.com/quran/quran_android/files/5252566/010-2.zip)

**Comment by ahmedre** [comment]
@benomaire jazakAllah khair - both of those actually play fine on the Huawei phone

**Comment by benomaire** [comment]
This is really strange. 
You [previously reported](https://github.com/quran/quran_android/issues/1420#issuecomment-692960195) that converting the file to mono does not work. I am not sure how you did it, but here is one way to convert to mono by "mixing" the two channels:
```
sox 010.mp3 010soxRemix.mp3 remix -
```
and the result I get is that the file is damaged on any media player. Not sure if that Huawei phone is ignoring the stereo and mixing both channels to mono! If you use a headphone, does it make a difference than loudspeaker?! I really have no explanation now.


The files I uploaded are just a mix to mono and resample using one of the following:
```
sox 010.mp3 010soxRemix1.mp3 remix 1
sox 010soxRemix1.mp3 -r 24000 010soxRemix124.mp3
```
or
```
sox 010.mp3 010soxRemix.mp3 remix 2
sox 010soxRemix.mp3 -r 24000 010soxRemix24.mp3
```

Probably then, the resample step is not necessarry, but it reduces the file size without affecting the quality. It is now mono after all, but I think still better than islamweb files.

May be you like to duplicate one mono track to make it stereo again and post it.

**Comment by benomaire** [comment]
@ahmedre @nacer80 Please check these:

- [Surah 9](https://archive.org/download/008filtered/009.mp3)
- [Surah 10](https://archive.org/download/008filtered/010.mp3)

44.1kHz, 128kbps, stereo

<details><summary>How</summary>

Manually selected the half file that is damaged and applied the "invert" filter on the second track.
</details>

**Comment by nacer80** [comment]
جزاك الله خيرا
It works very well for me

**Comment by ahmedre** [comment]
I think we fixed this some time back so closing.

**Comment by benomaire** [comment]
I recently found this link which posts wav files for sheikh Jibreel. I combined the wav files to generate new files for Surah 9 and Surah 10. These new files are untouched (no effects applied, except some occasional fade to merge recordings smoothly. Also no dithering introduced). The encoding was done using: `lame --cbr -q 0 010.wav 010.mp3`

You can find the new files here: 
- [Surah 9](https://archive.org/download/jibreel_2/009.mp3)
- [Surah 10](https://archive.org/download/jibreel_2/010.mp3)

In my opinion, the new files posted here are better than [the older temporary solution of islamweb](https://github.com/quran/quran_android/issues/1420#issuecomment-678842380), better than the original files on quranicaudio (that get damaged when mixed to mono), and also better than [my previous fix](https://github.com/quran/quran_android/issues/1420#issuecomment-697113373) that was never used upstream.

@nacer80 please double check the timing for these new files.
وجزاكم الله خيرا

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
Jazak'Allho kheiren my brother.
Insh'Allah I will check and fix timing database

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 

Please find attached file.
[009.mp3](https://drive.google.com/file/d/1Jvou1m7nLNLnQOzqRtZns2VI2Yo0eQ39/view?usp=drivesdk) 
[010.mp3](https://drive.google.com/file/d/1KIQhbmXQ8BglYidwPTYVTo5FO80_85K9/view?usp=drivesdk)
I Created timing database for both mp3 files:
[mjibreel_database](https://drive.google.com/file/d/1KJhGYMeghYSooltvzAzFLHls3wSR36Yq/view?usp=drivesdk) 

Please use those mp3 files.
وجزاك الله خيرا

**Comment by ahmedre** [comment]
updated these now - jazakumAllah khairan
