### ISSUE TITLE
Issue with timing database file : Sheikh Alafasy

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1423]
السلام عليكم ورحمة الله وبركاته 
Issue with telawa of Sheikh Mishari Alafasy in surah Ghafer 40 last tow Ayats.

I fixed the issue and I changed the version from 3 to 4 .
@ahmedre please find attached update database file.
[mishari_alafasy.zip](https://github.com/quran/quran_android/files/5114255/mishari_alafasy.zip)

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre please update timing database file for sheikh Alafasy.
وجزاك الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
database timing file not updated yet.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
in sha' Allah this week - sorry about this - want to combine the other sheikh Afasy corrections (and sheikh Jibreel corrections) and do one update for them in sha' Allah. barak Allah feekum.

also, if you have some time @nacer80, may you see if you can help with some of the other issues in #204?
جزاك الله خيراً
والسلام عليكم

**Comment by ahmedre** [comment]
السلام عليكم ورحمة الله وبركاته
done. closing this now.
جزاك الله خيراً
والسلام عليكم
