### ISSUE TITLE
Missing Sample Images from Page Type Selection

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1432]
It looks like there should be an image showing a sample of the Mushaf print when You go to `Settings -> Page Type (experimental)`, but all I see is like the image below. 

<details><summary>Screenshot</summary>

![PageType](https://user-images.githubusercontent.com/69304392/92609213-fec12400-f2be-11ea-8f29-b3776c9dfc09.png)

</details>

**Comment by ahmedre** [comment]
جزاكم الله خيراً

added a spinner:
![Screenshot_1599951690](https://user-images.githubusercontent.com/47771/93006522-402b2b00-f56e-11ea-8cf3-ad89e8f2a8f7.png)
