### ISSUE TITLE
Use upper right arrow for "go to" in widget

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1467]
The widget is great! thanks to all who made it possible.
جزاكم الله خيرا

just a small note, I feel it will be more intuitive to use an arrow like the one in the picture below, because the current arrow looks like "back".
![widget](https://user-images.githubusercontent.com/69304392/96377194-93575580-118c-11eb-9d39-65af3d017510.png)

@ismail-s @ahmedre @ozbek  What do you think?

**Comment by ismail-s** [comment]
@benomaire I agree. I wasn't happy with the icon I chose but couldn't think of a better one at the time.
