### ISSUE TITLE
Mistake in Tafsir Jalalayn

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1468]
الانشقاق ٢٥
84:25

From google play (2020-10-03):

> جميل وهو من أفضل البرامج و التطبيقات عندي وما اجد جهاز أندرويد عند صديق الا وانصحه بهذا التطبيق ... غير اني وجدت اليوم خطأ في تفسير سورة الانشقاق تفسير الجلالين الآيه ٢٥ خطأ في الآيه مم قوله تعالى لهم أجر غيرت الى له أجر برجاء مراجعه وجزاكم الله خيرا ورفع قدركم وذكركم في الدنيا والآخرة...

The mistake is also in [furqan.co](https://tafsir.app/jalalayn/84/25). 
It is correct in [al-maktaba.org](https://al-maktaba.org/book/12876/6703) and [this print](https://almeshkat.net/book/12805). The error is in the ayah text, so these sources are not needed anyway.

**Comment by benomaire** [comment]
Added مْ
in both data and verses tables. Also incremented `text_version`. 
[quran.ar.jalalayn2.db.zip](https://github.com/quran/quran_android/files/5403566/quran.ar.jalalayn2.db.zip)

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته

جزاكم الله خيراً

i finally put together an excel spreadsheet of Arabic typos that i collected over the past time from people via emails - i unfortunately didn't get to fix any of them yet, but would love some help doing so. was hoping in sha' Allah you and @nacer80 could help me out.

**Comment by ahmedre** [comment]
@benomaire may you send me an email with your email address so i can invite you to this spreadsheet?
جزاكم الله خيراً

**Comment by benomaire** [comment]
done

> @benomaire may you send me an email with your email address so i can invite you to this spreadsheet?
> جزاكم الله خيراً

**Comment by ahmedre** [comment]
closing this since we're tracking this on a spreadsheet with these errors
