### ISSUE TITLE
Quraan page are lagging behind recitation as of today. 

### ISSUE THREAD

**Issue by asadmalik** [quran/quran_android#1493]
Salam to all,

When I started the Quraan android app today I noticed that pages are not syncing with the audio. Before it worked perfectly, i.e. currently recited  ayaat will scroll to top so it was possible to follow translations with Qari/audio. 

So my request is, can someone please point me to path where I can revert the App back to working version.

Please help.

May Allah's bounties with you all, in this life and after.

Wassalm,
Asad.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakumAllah khair - already fixed in #1485 and updated release is rolling out now. you should get it in the next few days in sha' Allah.
walsalam 3alaikum.

**Comment by asadmalik** [comment]
Thanks!
Jazak Allah.
