### ISSUE TITLE
Images for new Madani pages 

### ISSUE THREAD

**Issue by M-Fararjeh** [quran/quran_android#1498]
السلام عليكم ورحمة الله وبركاته 

I'm developing App for Quran But I need the images for the new Madani pages, Please can you tell me what is the URL for the new Madani pages with a database for all screen sizes?

Thanks

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
I am not sure what are your requirements. But [here is the source of the images](https://qurancomplex.gov.sa/kfgqpc-quran-hafs/) used in the app.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
closing for now, please reopen if this is still an issue.
جزاكم الله خيراً
والسلام عليكم

**Comment by M-Fararjeh** [comment]
وعليكم السلام 
شكرا لردك، انا الان بطور برنامج خاص لتفسير القران الكريم ومحتاج صور مصحف القران الكريم المدني الجديد، أريد الصور مع قاعدة اليبانات الخاصة لتحديد الاحداثيات لغرض التظليل
ان امكن تزويدي برابط لأقوم بتحميل الصور مع قاعدة البيانات واتوقع وجدود اكثر من صيغة للصور. 
حاولت العثور عليهم عن طريق الكود الخاص بكم ولم استطيع ايجاده وشكرا لكم

**Comment by benomaire** [comment]
You just download the files using the app and you have everything on your phone (the images and the highlighting database)!
If you want the newest 1441 pages, go to settings -> Page Type (experimental) -> Madani Mushaf (1441).
If you want to generate different sizes, you may find [ayah_detection](https://github.com/quran/ayah-detection) useful.

If you have doubts, please go over the issues where we discussed generating Mushaf pages. See #1244 and the likes.

BTW, we have many Tafasir in this app, may be if what you plan to do is not very different then you can contribute here instead!
جزاكم الله خيرا
