### ISSUE TITLE
Sheikh Abu Bakr Ash-Shatri - Surah Al-Hashr timings off

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1502]
Nov 25:
> جزاكم الله خيراً فيه تعديل بسيط : في سورة الحشر الآية رقم 4 يبدو أن البرمجة بقراءة الشيخ شيخ أبو بكر الشاطري اعتبرت ان الآية الرابعة تنتهي عند قوله تعالى (وَمَن یُشَاۤقِّ ٱللَّهَ فَإِنَّ) فيقف القارئ على "فإن" وما تبقى من الآية يقرؤها القارئ كأنها جزء من الآية الخامسة مع أنها جزء من الآية الرابعة

cc @nacer80

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
The issue fixed
Please find attached data base timing file 
وجزاكم الله خيرا

**Comment by ahmedre** [comment]
جزاكم الله خيراً
fixed now. updates happen in a background process that runs once a week.
