### ISSUE TITLE
Bug: Popup does not show

### ISSUE THREAD

**Issue by OsmanAltun** [quran/quran_android#1503]
### Expected behavior
![Screenshot_20201210-164809](https://user-images.githubusercontent.com/17157809/101810036-992c4000-3b18-11eb-944a-662a659a5c5a.jpg)

### The problem
![Screenshot_20201210-164824](https://user-images.githubusercontent.com/17157809/101810177-c24cd080-3b18-11eb-90b9-c8e981723101.jpg)

**Comment by ozbek** [comment]
Salam.

I also noticed this, though that does not always happen.

**Comment by OsmanAltun** [comment]
Salam,
I think it is fixed in version 3.0.4 so I am closing the issue.
