### ISSUE TITLE
salam. I cannot download quran audio content using wifi. Whenerver i want to download i receive this error "network error, trying to resume". I need someone to help me ASAP. Thanks in advance

### ISSUE THREAD

**Issue by ali003-sketch** [quran/quran_android#1504]

**Comment by benomaire** [comment]
This is strange. Basic questions first

1. Are you sure you can browse the internet using wifi normally (i mean other apps)?
2. Can you listen to Quran online, without downloading (using this app)?

**Comment by ali003-sketch** [comment]
yes, i can

**Comment by benomaire** [comment]
@ali003-sketch 
1. Do you have free storage space?
2. Are you using the latest update of the app?
3. Go to Settings -> Audio Manager. Can you download from there?
4. Close the app completely (swipe it out of the list of open apps). Then can you provide a video where you try downloading from Quran page and Audio Manager?

**Comment by ali003-sketch** [comment]
Ok, I will check. Thanks

**Comment by ahmedre** [comment]
can you see if https://android.quran.com and https://download.quranicaudio.com load on your phone's browser?

**Comment by ali003-sketch** [comment]
Yes, I can see it.

**Comment by ahmedre** [comment]
@ali003-sketch please check this and let us know

> @ali003-sketch
> 
> 1. Do you have free storage space?
> 2. Are you using the latest update of the app?
> 3. Go to Settings -> Audio Manager. Can you download from there?
> 4. Close the app completely (swipe it out of the list of open apps). Then can you provide a video where you try downloading from Quran page and Audio Manager?

**Comment by ahmedre** [comment]
closing for now
