### ISSUE TITLE
خطأ إملائي

### ISSUE THREAD

**Issue by amanyy00** [quran/quran_android#1510]
سورة ص تفسير السعدي آية رقم ٤٩
يوجد خطأ إملائي في كلمة رزقنا 
جزاكم الله خير وكتب اجركم

**Comment by ahmedre** [comment]
جزاكم الله خيراً
سنغير نسخة تفسير السعدي بنسخة أفضل قريباً إن شاء الله وتصلح هذا الخطأ - جزاكم الله خيراً

**Comment by ahmedre** [comment]
this is fixed now al7amdulillah - please go to settings, translations, and get the Saadi update - جزاكم الله خيراً
