### ISSUE TITLE
Hizb popup not showing when quickly turning pages

### ISSUE THREAD

**Issue by amynbe** [quran/quran_android#1516]
السلام عليكم

[`QuranDisplayHelper#displayMarkerPopup`](https://github.com/quran/quran_android/blob/b28fa79ea5cf04ab46aa3e8620a980b0fc828438/app/src/main/java/com/quran/labs/androidquran/ui/helpers/QuranDisplayHelper.java#L59) has this check:

    if (System.currentTimeMillis() - lastPopupTime < 3000) {
          return ...

causing the behaviour stated in the title.

I often turn pages quickly as a way to navigate, looking for a quarter of hizb near to my reading position.
While doing so, I like to rely on the popup rather than the hizb marker in the page as it is easy to miss.

Can I ask why you added this guard @ahmedre and would it be fine to shorten the delay, to e.g 300ms?

**Comment by benomaire** [comment]
I think 3 seconds is the duration of viewing the popup.
For now may be you can look at the top of the screen if you have `show page info` activated. You will see `Hizb 58` for example.

**Comment by amynbe** [comment]
`show page info` shows only the Hizb, not rub3.
I tried changing the delay to 300 and it seems to work fine. The new popup replaces the old one.

**Comment by benomaire** [comment]
> `show page info` shows only the Hizb, not rub3.

This is confusing. There are 8 rub3 in each Juz', and taking Juz' 2 as an example you should see

1. `Juz' 2 , Hizb 3 ` on page 22
2. `Juz' 2 , ¼ Hizb 3 ` on page 24
3. `Juz' 2 , ½ Hizb 3 ` on page 27
4. `Juz' 2 , ¾ Hizb 3 ` on page 29
5. `Juz' 2 , Hizb 4 ` on page 32
6. `Juz' 2 , ¼ Hizb 4 ` on page 34
7. `Juz' 2 , ½ Hizb 4 ` on page 37
8. `Juz' 2 , ¾ Hizb 4 ` on page 39

and you see only `Juz' 2` in the rest of the pages. So you know the rub3 by the long text.

**Comment by amynbe** [comment]
Sorry, you are right, I was confusing info bar with the overlay that appears upon click.
I still believe it's worth fixing this minor usability glitch but I'll try using the info bar for now.
جزاكم الله خيرا

**Comment by benomaire** [comment]
> I still believe it's worth fixing this minor usability glitch but I'll try using the info bar for now.

I don't have a strong opinion for either side yet (regarding the popup time), I just wanted to mention an available alternative.
