### ISSUE TITLE
Issue with a stop sign

### ISSUE THREAD

**Issue by moelkateb** [quran/quran_android#1518]
As'Salamu Aleikum brothers,

Jazackum Allah Kheir for the app.

There is a mistake on my version, Aya 68 of Surat yaseen. The mistake is only on my android, not on iOS.

See screenshot. 

It should be one of the stop signs after the word khalq.

Sent from my Huawei phone
![Screenshot_20201230_064111](https://user-images.githubusercontent.com/76776919/103349732-a3809080-4a6b-11eb-97bc-bce9b2cc6267.jpg)

**Comment by benomaire** [comment]
> It should be one of the stop signs after the word khalq.

Sorry I did not get what is the mistake?

Also, please provide a screenshot form your iOS.

**Comment by ahmedre** [comment]
stop signs are a point of ikhtilaf and they change from edition to edition of the mushafs. here, you are comparing different versions of the mushaf. the iOS app uses the very old madani mushaf (before 1429 hijri). the picture from Android is from you using the 1441 edition. here's a picture from my mushaf matching what you are seeing in Quran for Android:

![page](https://user-images.githubusercontent.com/47771/103353767-25e86f00-4ac3-11eb-9305-6e67d2f702db.jpg)

similarly, if you find an old print madani mushaf, you'll find it matching the iOS app (or the Android app if you swap the page type for the "classic madani" page type.

**Comment by moelkateb** [comment]
I didn't know there was difference of opinion around this matter, nor that there is differences in mushafs, and clearly I didn't know there are different versions of android compared to iOS.One would have assumed uniformity/consistency within the app across different platforms, but you are telling me that is not the case, so based on all the above it's not an issue. Jazack Allah KheirSent from my Huawei phone-------- Original message --------From: Ahmed El-Helw <notifications@github.com>Date: Wed, 30 Dec 2020, 08:33To: quran/quran_android <quran_android@noreply.github.com>Cc: moelkateb <thereacous@gmail.com>, Author <author@noreply.github.com>Subject: Re: [quran/quran_android] Issue with a stop sign (#1518)
stop signs are a point of ikhtilaf and they change from edition to edition of the mushafs. here, you are comparing different versions of the mushaf. the iOS app uses the very old madani mushaf (before 1429 hijri). the picture from Android is from you using the 1441 edition. here's a picture from my mushaf matching what you are seeing in Quran for Android:

similarly, if you find an old print madani mushaf, you'll find it matching the iOS app (or the Android app if you swap the page type for the "classic madani" page type.

**Comment by ahmedre** [comment]
i updated my message after to clarify a mistake i made in my original reply - the default page type in Android (if you don't change it) matches the one in iOS, which matches the picture you posted above and my picture as well.

the newer version of the madani pages replaces this stop marker with a different one - you can get that one if you want from settings -> page type (choose the latest 1441 pages).

closing for now but please feel free to reopen if you have any other questions.
جزاكم الله خيراً
