### ISSUE TITLE
Add page number to search results 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1525]
السلام عليكم ورحمة الله وبركاته 

Some times  when we search for word in Quran we need also the page number not only Ayah number and Surah name.
وجزاكم الله خيرا

**Comment by MahmoudMabrok** [comment]
can i work on that @ahmedre ?

**Comment by ahmedre** [comment]
sure, please go ahead - جزاكم الله خيراً

**Comment by MahmoudMabrok** [comment]
@ahmedre 
can i add json file directly of ayahs,suraha,page number, sura num 
so when search we can got all data needed

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 

Brother @MahmoudMabrok  please try to fix this issue.

وجزاكم الله خيرا

**Comment by MahmoudMabrok** [comment]
وعليكم السلام ورحمة الله وبركاته 
 
 I will try ISA my brother
