### ISSUE TITLE
Post on fdroid

### ISSUE THREAD

**Issue by Thewisem** [quran/quran_android#1526]
This is an FOSS quran app and I would love it if you could post this on Fdroid. The FOSS platform. It will help in reaching more people and many people will consided your app more

**Comment by ozbek** [comment]
Salam!

This looks like a duplicate of #434 and/or #755.

**Comment by Thewisem** [comment]
Huh So people DID ask this ok

**Comment by Thewisem** [comment]
Well then please do it

**Comment by Thewisem** [comment]
Huh! Ok then please do it. It would help us in updating the app
Waalaykummusalam

**Comment by ahmedre** [comment]
closing in favor of #755
