### ISSUE TITLE
use Room database instead of SQLiteDatabase

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#1532]
https://developer.android.com/training/data-storage/room

**Comment by amynbe** [comment]
Is it really worth it, given the maturity of the application? The page says:

> 
> Room provides the following benefits:
> 
> Compile-time verification of SQL queries.
> Convenience annotations that minimize repetitive and error-prone boilerplate code.
> Streamlined database migration paths.

Which are mainly development time convenience points, probably more useful at early development stages.

**Comment by ahmedre** [comment]
wouldn't mind switching to Room or Sqldelight in the future, but it's a bit of work today.

- getting Room to match the data model we have will probably need a migration (for bookmarks/tags at least). not sure about translations, but if it needs it for translations, this will be even more cumbersome.
- i recall Sqldelight being picky about types - so having a column with type `VARCHAR` might not identify and you'd have to rename the type to `TEXT` even though they're equivalent

**Comment by MahmoudMabrok** [comment]
ur right, but I think we need it so the code is more readable and clean, and it supports to be a  reactive data source.

**Comment by MahmoudMabrok** [comment]
> * getting Room to match the data model we have will probably need a migration (for bookmarks/tags at least). not sure about translations, but if it needs it for translations, this will be even more cumbersome.

i think we will not need migration, will need to build db schema(entities,dao)

**Comment by ahmedre** [comment]
closing since we're already using SqlDelight in some places - no point in using Room and SqlDelight both.
