### ISSUE TITLE
A community channel instead of G+ as it is out of service in these days 

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#1535]
We need  social/communication platform instead of G+

**Comment by ahmedre** [comment]
removed the G+ link - it wasn't for social communications but was for the play beta when we had one.
you can join the quran.com slack though, we have an Android channel there.
جزاكم الله خيراً

**Comment by MahmoudMabrok** [comment]
what link of slack?

**Comment by ahmedre** [comment]
https://quranslack.herokuapp.com
