### ISSUE TITLE
Tafseer problem

### ISSUE THREAD

**Issue by MohammadHizam1416** [quran/quran_android#1537]
Asslamualiakum,

First, I would like to thank you for the huge effort you made in serving the greatest book, which is the Quran.

The **issue** as follows: 
usually for each verse (ayah), there is a Tafseer text after it. But in some cases (like in Muyassar Tafseer) some verses come with Tafseer for it and several verses after it.

I suggest separating each verse with its Tafseer.

You can see these pictures to know what I mean 
![image](https://user-images.githubusercontent.com/46600102/104441786-33aef180-55a5-11eb-8b93-ab0019489135.png)

![image](https://user-images.githubusercontent.com/46600102/104441924-65c05380-55a5-11eb-8b49-051f77ef1394.png)

_______________________________
I have another suggestion ...

Why you don't make an app for Sunnah books?
You can use your Quran app as a template. :)

**Comment by benomaire** [comment]
وعليكم السلام ورحمة الله وبركاته
You have posted the same image twice, but I think I got what you mean.

For Tafseer Muyassar, I believe the behaviour of the app matches [the original print from KFGQPC](https://qurancomplex.gov.sa/kfgqpc-books-tafseer-muyassar/). See a sample image below for the ayah you mentioned. 

![page583](https://user-images.githubusercontent.com/69304392/104813379-e5eeef00-5819-11eb-8fb6-85bde4122917.png)


You might also try to long touch on an ayah and view tafsir there. In this way you automatically get the tafsir text if it was shared among several ayat.

For Sunnah books, have you seen some existing projects? like:
1. [sunnah.com](https://sunnah.com/)
2. [sunnah.one](https://sunnah.one/)
3. [dorar.net/hadith](https://dorar.net/hadith)

جزاكم الله خيرا

**Comment by ahmedre** [comment]
closing this since nothing to change here since we match the books as they are. also, splitting these is very difficult if even possible since the tafaseer themselves group the set of ayahs under one.

for sunnah app, really would love to, but it's difficult enough to even keep this app updated, so it's difficult to take any extra projects.

jazakumAllah khairan.
