### ISSUE TITLE
Comparison between Madani Mushaf 1429 and 1441

### ISSUE THREAD

**Issue by edesigns-LK** [quran/quran_android#1538]
I noticed few differences between Madani Mushaf 1429 and 1441. 

![1441](https://user-images.githubusercontent.com/52587663/106343184-28a8d080-62ca-11eb-961e-d44836ec7dc4.png)

**Comment by ahmedre** [comment]
the madani mushaf is handwritten - so there are subtle differences like this throughout, none of which change the words/meanings/etc. there are also differences in pause marks and stop signs and what not. none of these are mistakes, and these types of subtle changes are expected to exist.

**Comment by ahmedre** [comment]
closing, please reopen if necessary.
