### ISSUE TITLE
Feature request: Porting Quran app to Windows

### ISSUE THREAD

**Issue by ahmed3110c** [quran/quran_android#1548]
How about porting quran app to Windows either to WUP platform or as an x86/x64 native application?

**Comment by ahmedre** [comment]
a brother had a native Windows version some time back - https://github.com/stankovski/quran-phone - but hasn't been updated for a while and I tried to reach him and could not.

**Comment by ahmed3110c** [comment]
Can you try to make an updated Windows version of this app?
It will be great thing to make since there is no proper Quran application on Windows since about 2003 there was a program called QuranHafs with 5 recetations plus tafseer and tahfeez features.

**Comment by ahmedre** [comment]
personally, i can't, but if anyone wants to, they can feel free in sha' Allah.

**Comment by benomaire** [comment]
@ahmed3110c did you try the following app:
https://mushaf-services.qurancomplex.gov.sa/
