### ISSUE TITLE
Arabic Translations Support

### ISSUE THREAD

**Issue by vipafattal** [quran/quran_android#1550]
Thanks for your efforts for that blessed project, we're working on expanding Arabic translation in Mushaf for Android ([Github](https://github.com/vipafattal/Mushaf), [play](https://play.google.com/store/apps/details?id=com.brilliancesoft.mushaf)).

Since Musahf for Android is based on [alquran.cloud](https://alquran.cloud/api) API, we're working on adding them there first so they would be available in the mobile app.

So is it possible to provide us with the Arabic translation you're using in your app?

**Comment by ahmedre** [comment]
we're using the ones from tafsir.app - please contact them for permission first and please note that there are a lot of typos that are there - some of the brothers here have been fixing.

general recommendation is to try to get all translations from a place like quranenc.com so typos can be fixed regularly.
