### ISSUE TITLE
Add a hint for Sajdah pages

### ISSUE THREAD

**Issue by amirian** [quran/quran_android#1552]
Add a hint entering pages having Sajdah Ayah.
Sajdah Wajibah pages: 416, 480, 528, 597
Sajdah Mandubah pages: 176, 251, 272, 293, 309, 334, 341, 365, 379, 454, 589

**Comment by HashirGJ8842** [comment]
Salaam, can i proceed with this issue @ahmedre ?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i don't think we need to do anything here - there are already ayah markers by each sajdah.
walsalam 3alaikum.
