### ISSUE TITLE
Add Persian translation and interpretation

### ISSUE THREAD

**Issue by Ahmadreza128** [quran/quran_android#1557]
Assalamu aleykum brothers!
May Allah reward you for your excellent work.
I am interested in adding to your program 4 interpretation to the holy Quran in Farsi language. This is .db file .
https://drive.google.com/file/d/1JsBL4SDX0plltQsIKa0Opbll5pRKy53T/view?usp=sharing
Inshallah, if there is a life left, some other interpretations will be prepared.
Translation is all sunni.
Thank you very much

**Comment by ahmedre** [comment]
wa3laikum alsalam,
sorry for the late reply - the Google Drive link is protected, mind making it open so the team can check?
jazakumAllah khairan,
walsalam 3alaikum.

**Comment by Ahmadreza128** [comment]
Persian (1)
<https://drive.google.com/file/d/138slQLRkzsLa5v39cFWAT9TLGa0VDzn1/view?usp=drive_web>
Assalaamu’alaikum wa rahmatullah wabarakatuhu
I apologize very much for my late reply
I am very happy to be able to make a very small contribution to this work
May God protect you and reward you for your goodness
Thank you very much my dear brother Ahmed El-Helw
jazakumAllah khairan,
walsalam 3alaikum.

**Comment by Ahmadreza128** [comment]
These are Excel files of tafseers, each with the name of interpretation and author in Persian and English
تفسیر نور - دکتر مصطفی خرمدل – noor tafseer - Dr. Mostafa Khorramdel
تفسیر سعدی (تيسير الکريم الرحمن في تفسير کلام المنان) – شیخ عبدالرحمن بن ناصر السعدی – sa3di tafseer  - Sheikh Abdul Rahman bin Nasser Al-Saadi
تفسیر انوار القران - عبدالرؤوف مخلص - Tafseer Anwar Al-Quran - Abdul Rauf Mukhlis
تفسير ميسر - شیخ عائض القرنی –- misar tafseer  Sheikh A'iz Al-Qarni
[تفسير ميسر - شیخ عائض القرنی –- misar tafseer  Sheikh A'iz Al-Qarni.xlsx](https://github.com/quran/quran_android/files/6217021/-.-.misar.tafseer.Sheikh.A.iz.Al-Qarni.xlsx)
[تفسیر سعدی (تيسير الکريم الرحمن في تفسير کلام المنان) – شیخ عبدالرحمن بن ناصر السعدی – sa3di tafseer  - Sheikh Abdul Rahman bin Nasser Al-Saadi.xlsx](https://github.com/quran/quran_android/files/6217022/sa3di.tafseer.-.Sheikh.Abdul.Rahman.bin.Nasser.Al-Saadi.xlsx)
[تفسیر نور - دکتر مصطفی خرمدل – noor tafseer - Dr. Mostafa Khorramdel.xlsx](https://github.com/quran/quran_android/files/6217023/-.noor.tafseer.-.Dr.Mostafa.Khorramdel.xlsx)
[تفسیر انوار القران - عبدالرؤوف مخلص - Tafseer Anwar Al-Quran - Abdul Rauf Mukhlis.xlsx](https://github.com/quran/quran_android/files/6217024/-.-.Tafseer.Anwar.Al-Quran.-.Abdul.Rauf.Mukhlis.xlsx)

**Comment by Ahmadreza128** [comment]
Assalaamu’alaikum wa rahmatullah wabarakatuhu
Tafsir al-Jalalayn after deleting the app and reinstalling it can not be seen and can not be downloaded.
The previous interpretation file of your service will be sent
[quran.ar.jalalayn.zip](https://github.com/quran/quran_android/files/6309774/quran.ar.jalalayn.zip)
jazakumAllah khairan,
walsalam 3alaikum.

**Comment by benomaire** [comment]
can you share pdf copies of these translations (also kurdish)?

**Comment by Ahmadreza128** [comment]
wa3laikum alsalam,
please try this link
https://s19.picofile.com/file/8435408576/tafser.rar.html
jazakumAllah khairan,
walsalam 3alaikum.

‪On Tue, Jun 1, 2021 at 2:19 PM ‫رضا تیره ای‬‎ ***@***.***> wrote:‬

**Comment by Ahmadreza128** [comment]
wa3laikum alsalam,
please try this link
https://s19.picofile.com/file/8435408576/tafser.rar.html
jazakumAllah khairan,
walsalam 3alaikum.

**Comment by rezad1393** [comment]
I don't see any Persian tafsir in the app to download.
Am I missing something?

**Comment by ahmedre** [comment]
it's there as "Farsi Translation"

**Comment by rezad1393** [comment]
> it's there as "Farsi Translation"

sorry.
if I was not clear I meant tafseer not translation.
this is only one persian translation in app.
I though maybe the referenced tafseers at the top may have been added to the app.

**Comment by ahmedre** [comment]
No Persian tafaseer at the moment unfortunately

**Comment by ahmedre** [comment]
we can take the available quranenc.com Persian tafaseer for the app (today, Saadi, and I guess Mokhtasar is still a WIP there). We'll wait on the others to be available on quranenc.com.

**Comment by rezad1393** [comment]
> we can take the available quranenc.com Persian tafaseer for the app (today, Saadi, and I guess Mokhtasar is still a WIP there). We'll wait on the others to be available on quranenc.com.

thanks for the answer.
I like open source app.
I already have an app that has persian tafseer https://play.google.com/store/apps/details?id=com.quran.zekr (if that is the correct word) but it is closed source (as much as a  free app on play store can be) but as I said I want to replace it with a FOSS app.  also that app downloads the texts (And voices) from a websites that seems to be half dead like this links (http://zekr.info/uploads/text_books/fa_mokhtasar/fa_mokhtasar.zip) so I cant even dare delete it.

can I share the zip files from that app here if I can extract them? I don't think they are copy righted.


wish there was a repository of religious text for muslims (both Shia and Sunni sources).
they are not usually copy righted.
I remember in my windows days I saw an Iranian app that had those texts from a software burned on cd. but I lost it.

**Comment by hamidsafdari** [comment]
@ahmedre, is there a reason for only relying on quranenc.com? This is a big restriction because quranenc only includes Sunni translations.
![image](https://github.com/quran/quran_android/assets/5158006/147a1406-37cc-4d02-b95a-e94925774c02)

The readme says you have also taken translations from the Tanzil project. Tanzil's website includes many Persian translations.
![image](https://github.com/quran/quran_android/assets/5158006/bcea058c-9d8c-4951-b8d0-be196b9853e1)

Are you ignoring them because those translations were done by Shia's?

**Comment by rezad1393** [comment]
> Are you ignoring them because those translations were done by Shia's?

I don't think it is right to just accuse him of something first.

let him speak first.

but I am of course in favor of adding these sources as I am not Sunni.

maybe even adding a comparison between sources can be added to this app which would make it very interesting.
or at least adding the ability to show more than one translation or tafsir for user to see them together.

**Comment by ahmedre** [comment]
The team is accountable in front of Allah ﷻ for the content we share and make available, and, as Sunni Muslims, we aim to only share Sunni translations and avoid non-Sunni translations.

**Comment by rezad1393** [comment]
> The team is accountable in front of Allah ﷻ for the content we share and make available, and, as Sunni Muslims, we aim to only share Sunni translations and avoid non-Sunni translations.

oh.
ok.

**Comment by benomaire** [comment]
If I make an app, I have the full right to choose to include whatever I want.
I can also reject any request without reasons.
If you don't like it, I think you should not post statements like 'but it seems I am not a muslim.'
I also believe that if you spent a decent amount of time reading and understanding the Quran, you will not write such statements.
Ultimately, you can think whatever you want about yourself, you don't need to tell us. 

Wish you and all the readers a fruitful journey with the Quran this Ramadan.

**Comment by fakhriamir** [comment]
سلام نرم افزار قرآن مجید رو می تونید از سایت quranapp.ir دانلود کنید که همه این ترجمه ها و ... فارسی رو داره

**Comment by rezad1393** [comment]
> سلام نرم افزار قرآن مجید رو می تونید از سایت quranapp.ir دانلود کنید که همه این ترجمه ها و ... فارسی رو داره

site doesnt exist.
