### ISSUE TITLE
Aya marker using custom icon!

### ISSUE THREAD

**Issue by AhmedAsser** [quran/quran_android#1558]
Salamo alykom,
How to change aya marker with a custom icon ?, is there a version of Madinah Mushaf pages available without aya marker like the image below, Including SQL data that represent aya mark location on every line? 

Does "ayah-detection repo" remove aya marker from images and create marker SQL locations?
Thanks.
![page569](https://user-images.githubusercontent.com/5795325/110467005-26af0a00-80df-11eb-8b44-cd755df737cf.png)

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
yes, the ayah-detection repo has scripts to remove the marker and then you can replace with code at run time.
والسلام عليكم
