### ISSUE TITLE
Opening Tafseer via action bar doesn't take to the requested Aya.

### ISSUE THREAD

**Issue by BasemAlMoudares** [quran/quran_android#1559]
السلام عليكم و رحمة الله وبركاته

Opening Tafseer via the action bar doesn't take to the requested Aya, instead takes to the first Aya in the page.

However opening it via the floating box, does take to the exact Aya, but it only allow to expand the view to half the screen instead of to the upper edge.

I know that theye should be a separate issues, so I'll open a second issue for the viewing tafseer via the floating box.

وجزاكم الله خيراً

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
this is actually intended behavior. when you long press an ayah it's a contextual action to go to that ayah's tafsir. when you tap and press in the top bar, you're switching modes from reading mode to tafsir mode so this is as intended.

in the future though in sha' Allah plan on trying to unify these views and making the experience better.
جزاكم الله خيراً
والسلام عليكم
