### ISSUE TITLE
 Inconsistent Italian translation

### ISSUE THREAD

**Issue by diaahere89** [quran/quran_android#1563]
Alsalamu Alaikum,

If you open Quran.com on your phone and want to listen to any Aya/Verse, you will find the Italian translation of the word (play ex...an audio) as (giocare) which means to play a game. A better translation would be (Ascoltare) which means (to listen).

Would it be possible to update the word giocare to ascoltare??

Thank you!
Diaa

**Comment by benomaire** [comment]
You are also welcome to add Italian strings for [quran_android](https://play.google.com/store/apps/details?id=com.quran.labs.androidquran).
You can use android studio (preferred) or edit the [English xml file](https://github.com/quran/quran_android/blob/master/app/src/main/res/values/strings.xml) directly.
Your contributions are appreciated!
جزاكم الله خيرا

**Comment by ahmedre** [comment]
closing in favor of https://github.com/quran/quran.com-frontend-v2/issues/360

**Comment by diaahere89** [comment]
Please let me know when the translation is deployed, thank you!

Il giorno sab 20 mar 2021 alle ore 22:54 Ahmed El-Helw <
***@***.***> ha scritto:
