### ISSUE TITLE
Add back infinite repeat setting

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1582]
people are complaining that the infinite setting is removed.
cc @benomaire if you want to pick this one up

**Comment by benomaire** [comment]
Does it have to be *infinite* ?
some options:
1. increase the maximum to 99 or more.
2. go back to the drop down list and fill it with 25 options + infinite.
3. add a 2 check boxes in the current UI for infinite repetition (showing the text "infinity").
4. add an option to control the maximum (somewhere in settings).
5. add a special symbol (∞) at the end of the current list for number 26 which is mapped to infinity. I believe this will require initializing a string array again :)
6. add a checkbox with the string ∞ (linked PR).
