### ISSUE TITLE
Surah names (Surah translated names) Franch language mode

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1584]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
Many brothers commented about Surah names list in franch language mode.
The list must be in arabic with english letters same as  English mode.
Surah names (Surah translated names):
Surah Al-Fatihah (The Opener).
 
Franch language:
Sourate Al-Fatihah (L'ouverture) 
Sourate Al-Baqarah (La vache) 

وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Please fix the issue also for warsh, Qaloon and naskh.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
done now
جزاكم الله خيراً
