### ISSUE TITLE
Quran pages stretch to fill device display

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1589]
السلام عليكم ورحمة الله وبركاته 
I have one suggestion to make Quran pages stretch to fill device display as Ayah app.
Screen shot from quran_android app:
![Screenshot_20210413-174531_Quran](https://user-images.githubusercontent.com/60948528/114591847-35f71980-9c82-11eb-937e-8054703c7e05.jpg)
Screen shot from Ayah app:
![Screenshot_20210413-174506_Ayah](https://user-images.githubusercontent.com/60948528/114591885-40b1ae80-9c82-11eb-802b-9657bb3814ca.jpg)

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
definitely want to do this in sha' Allah.
جزاكم الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Please I need your help to fix this issue 
وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
still working on it, just a bit too much on my plate at the moment.
والسلام عليكم

**Comment by nacer80** [comment]
> 
> السلام عليكم ورحمة الله وبركاته 
> I have one suggestion to make Quran pages stretch to fill device display as Ayah app.
> Screen shot from quran_android app:
> ![Screenshot_20210413-174531_Quran](https://user-images.githubusercontent.com/60948528/114591847-35f71980-9c82-11eb-937e-8054703c7e05.jpg)
> Screen shot from Ayah app:
> ![Screenshot_20210413-174506_Ayah](https://user-images.githubusercontent.com/60948528/114591885-40b1ae80-9c82-11eb-802b-9657bb3814ca.jpg)
> 

 
Also if there is an ability to make the font of the Qur'an darker (rougher)

**Comment by ahmedre** [comment]
work is in progress al7amdulillah -

![Screenshot_20210926_001349](https://user-images.githubusercontent.com/47771/134785420-d894fc41-875f-4726-bdc5-a0b5c3b6858e.png)

**Comment by nacer80** [comment]
Mash'Allah great job, it looks good

**Comment by ahmedre** [comment]
السلام عليكم ورحمة الله وبركاته
[here](http://cafesalam.net/uploads//fullpage-debug.apk) is a debug apk for the app (can be installed side by side with the real version) that has the larger images. please try it and let me know in sha' Allah.

settings -> page type.
cc @nacer80 @benomaire 
جزاكم الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله 
Mash'Allah, it looks very good, I tested it in Samsung note 10+.
Also surah names are good now,
 I hope we make a same for last version1441.
جزاك الله خيرا![Screenshot_20211030-135826.jpg](https://user-images.githubusercontent.com/60948528/139535471-4b0f360e-8792-4cbe-874d-fa96b5c61038.jpg)

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
glad to hear it - for the sura names, I haven't applied your new database yet.
جزاكم الله خيراً
والسلام عليكم

**Comment by benomaire** [comment]
Overall, very nice work. But I have three notes:
1. After downloading the images and preparing the 9000+ files, the app showed a black screen, and the system showed the "Quran Madani not responding" dialog. Few seconds later, the first page of the Quran loaded normally. Not sure why this slowness.
2. using landscape mode (without dual pages), the page number is floating on the screen (I mean the position of the page number depends on the physical screen rather than the Quran page). Not sure if that is intentional.
3. #1767 (happened to be on master as well, so wrote a separate issue).

جزاكم الله خيرا

**Comment by ahmedre** [comment]
@benomaire JazakumAllah khairan - one question about point 1 - when exactly did the ANR happen? if you can repro it, can you send me the traces.txt? I checked the code and see that all of this runs on a background thread. was it when you clicked a sura to open it (after the download was done and you saw the list), or was it just the first time after the download and preparing files happened, or?

for point 2 - initially was intentional but will fix it in sha' Allah.
for point 4 - may you send a screenshot and tell me what device this is on?

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
I tested the app on Samsung devices(A,S and Note) till now it's ok, 
About the point 1, we have to download all the pages. If one page missed the stopped even we restart the app we can't open the other pages.
Also I found one issue while shearing tafseer, when we have one tafseer, we can't copy or share.
السلام عليكم ورحمة الله

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً

@nacer80  -
You're right - yeah there's no dynamic downloading of the line by line images today, and not really planning to do it - so instead if the download fails now or is canceled or ignored, I reset the page type to the new madani page type instead.

Fixed the sharing bug you mentioned also.

@benomaire fixed the footer, but didn't do anything yet for cut off header. I checked the code and all the screen is used, so perhaps there's too much padding - if you can tell me the type of device and send a screenshot would help. also, please let me know about the ANR.

I'll update with an updated APK after fixing some more of these issues in sha' Allah.

جزاكم الله خيراً
والسلام عليكم

**Comment by ahmedre** [comment]
with respect to zakhrafa, I talked to a designer and he made some samples - would love to get some votes on these. I think once we have one I can ask for similar ayah designs to the sura designs.

today: http://cafesalam.net/uploads//zakhrafa_today.png
style 1: http://cafesalam.net/uploads/zakhrafa_1.png
style 2: http://cafesalam.net/uploads/zakhrafa_2.png
style 3: http://cafesalam.net/uploads/zakhrafa_3.png
style 4: http://cafesalam.net/uploads/zakhrafa_4.png
style 5: http://cafesalam.net/uploads/zakhrafa_5.png
style 6: http://cafesalam.net/uploads//zakhrafa_6.png

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله 

About Tafseer sharing format please check the issue #1769
About Zakhrafah I choose number 4, what you think about Ayah spinner if we change it with Zakhrafah also.
وجزاك الله خيرا

**Comment by Haroun-98** [comment]
السلام عليكم ورحمة الله

Good job brothers.
About Zakhrafa n 4 and 5 are the same, it looks good.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
There is an issue while choosing repetition times, 
Ex: if we choose repetition 3 times and at this moment if the reciter read the next Ayah، the counter go back automatically to 1.

**Comment by Haroun-98** [comment]
السلام عليكم 
Please add page number to search results

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
closing this now since the repeats one was fixed and page number was added to search results.
جزاكم الله خيراً
والسلام عليكم
