### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by Thewisem** [quran/quran_android#1595]
I think this is a very necessary feature which isn't available in the qur'an app. It would be helpful for people who can't read small letter during landscape orientation. I would like it to be there in dual and  single page mode.(especially dual page as the letters are smaller and sometimes we need to zoom in to see some signs). Insha Allah. Assalamu alaykum

**Comment by mufidu** [comment]
agreed. and it will be good if it zooms like ebook (using flowing text).

**Comment by mohammadn0man** [comment]
Yeah, I also agree with that. I am not sure that maybe I can do that but it is worth a try.

**Comment by ahmedre** [comment]
not planning on doing this tbh - currently working on a new page view where the lines are larger to take up the whole screen and in sha' Allah that'll remove the need for zoom.

**Comment by mohammadn0man** [comment]
If possible let me help. I need some instructions on how to do it.

**Comment by nacer80** [comment]
> not planning on doing this tbh - currently working on a new page view where the lines are larger to take up the whole screen and in sha' Allah that'll remove the need for zoom.

Also if there is an ability to make the font of the Qur'an darker (rougher)
Please see the issue  #1589

**Comment by ahmedre** [comment]
going to close because not planning to do this - the next update will have images that are larger to fit the screen. I don't think adding zoom is the right ux decision here.

JazakumAllah khairan.
