### ISSUE TITLE
Update Malaysian app strings

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#1597]
Malaysian app strings are outdated. One that someone just complained about is the search results -
"Found in Surah Al-An'am, Ayah 96" isn't translated.

**Comment by ahmedre** [comment]
@asyazwan would you mind taking a look at this? jazakumAllah khairan

**Comment by asyazwan** [comment]
Got it.

**Comment by ahmedre** [comment]
may Allah reward you greatly - jazakumAllah khairan!

**Comment by asyazwan** [comment]
I cannot replicate the issue. Just in case I tried Indonesian as well but no problem either. I'll need a screenshot.

**Comment by ahmedre** [comment]
closing for now then - jazakumAllah khairan
