### ISSUE TITLE
Issue with search in warsh app 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1599]
السلام عليكم ورحمة الله وبركاته 
This database update will fix Insh'Allah the issue of search and sharing 
[warsh_database_update.zip](https://github.com/quran/quran_android/files/6412300/warsh_database_update.zip)

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
already replaced with this, so closing.
جزاكم الله خيراً
والسلام عليكم
