### ISSUE TITLE
Show reciter name in notification player bar

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1606]

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 

Now the option is working perfectly but the Surah in arabic apears without Tashkil "سُورَةُ"  

e.g: سُورَةُ الهُمَزَةِ instead of سورة الهمزة
![Screenshot_20220530-101127_One UI Home.jpg](https://user-images.githubusercontent.com/60948528/170960698-f15fbfdc-f28b-4368-a665-c5b2da316c13.jpg)
وجزاكم وجزاكم خيرا

**Comment by ahmedre** [comment]
جزاكم الله خيراً 
done in #1989
