### ISSUE TITLE
Issue with readers there are just three readers.

### ISSUE THREAD

**Issue by 9iaashalaby** [quran/quran_android#1611]
There are just three readers in quran_android/pages/madani/src/main/res/values/readers.xml file.

**Comment by ahmedre** [comment]
this is intentional - lots of people take the app's code and republish with ads (while using the servers, etc we are paying for, leaving our email address so people get very upset at "why does this app have ads" - when we don't have ads) and so on.

as a way to discourage this, we don't put the full set of reciters in the open source version.

**Comment by 9iaashalaby** [comment]
What if I want to get all readers??

**Comment by ahmedre** [comment]
you can download our app from the releases tab or from the app store

**Comment by 9iaashalaby** [comment]
> you can download our app from the releases tab or from the app store

the same just three readers I want this xml file please.

**Comment by 9iaashalaby** [comment]
How can I get it please help.

**Comment by 9iaashalaby** [comment]
OK thank you I have got a solution.

**Comment by ahmedre** [comment]
please do not use this if you are planning on making your app either:
a. paid, or
b. with advertisements

and in these cases you are responsible for your own hosting, audio, and data. if we find an app that does this, we will report it to Google.

**Comment by 9iaashalaby** [comment]
> please do not use this if you are planning on making your app either:
> a. paid, or
> b. with advertisements
> 
> and in these cases you are responsible for your own hosting, audio, and data. if we find an app that does this, we will report it to Google.

My app does not have advertisements and its completely free but I have some features I want to make theme.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
@ahmedre 
I found this app[https://play.google.com/store/apps/details?id=se.anwar.quran]() used our application with ADS 
Please I need your help to stop this application.
وجزاكم الله خيرا

**Comment by 9iaashalaby** [comment]
> السلام عليكم ورحمة الله وبركاته
> @ahmedre
> I found this application in Google play:
> https://play.google.com/store/apps/details?id=se.anwar.quran
> used our application with ADS
> Please I need your help to stop this application.
> وجزاكم الله خيرا

Ok we have to stop it please.
