### ISSUE TITLE
Madani font

### ISSUE THREAD

**Issue by Muaviyaaa** [quran/quran_android#1613]
Brother I make videos of Quran recitations with English subtitles. I just want to know that can I get this Madani font to use in my videos?

**Comment by benomaire** [comment]
I don't know which Madani font you mean, but I can suggest two options:
### Option A: Newest Madani font (1441)
1. download vector pages from here: https://dm.qurancomplex.gov.sa/Download/1441-AI-hafs.zip 
2. crop per line or per ayah, and add to your videos
### Option B: Old Madani font (~1406)
use the following website: https://qurancliphelper.com/

I would recommend using the newest font (1441):
1. you can get high quality images
2. the newest font is arguably a little easier to read

**Comment by benomaire** [comment]
You may also use images for 1441 font from this link: https://qurancomplex.gov.sa/kfgqpc-quran-hafs/

Examples of high quality images:
standard39: https://epub.qurancomplex.gov.sa/issues/hafs/standard39/files/pages/svg/607.jpg
wasat39: https://epub.qurancomplex.gov.sa/issues/hafs/wasat39/files/pages/svg/607.jpg
jawamee39: https://epub.qurancomplex.gov.sa/issues/hafs/jawamee39/files/pages/svg/607.jpg

This way you can get colorful ayah markers and borders if you want, but the quality is less than ai files.

**Comment by ahmedre** [comment]
Merging #1782 into this
