### ISSUE TITLE
Release for iOS

### ISSUE THREAD

**Issue by mzokirov** [quran/quran_android#1615]
Hi brothers and sisters,

Is it possible to release a version of this app for iOS? It would be really helpful.

Thank you!

**Comment by ahmedre** [comment]
wa3laikum alsalam,
yes, we have one - you can download it here - https://apps.apple.com/us/app/quran-by-quran-com-%D9%82%D8%B1%D8%A2%D9%86/id1118663303.
walsalam 3alaikum.

**Comment by mzokirov** [comment]
Thank you so much brother!
