### ISSUE TITLE
Recite Translations

### ISSUE THREAD

**Issue by jehanzebqayyum** [quran/quran_android#1618]
Salaam,

It would be really nice if the app supports reciation of translations as well. Ideally after quran arabic recitation of a line, recitation of translation should follow it. I see this a nice feature which lead people to youtube to search for recitations with audio translations as well.

Thanks

**Comment by ahmedre** [comment]
wa3laikum alsalam,
we already have this for a few recitations, so closing.
walsalam 3alaikum.

**Comment by jehanzebqayyum** [comment]
can we recite urdu translation while listening to quran in arabic?

**Comment by ahmedre** [comment]
unfortunately not today - only English and Arabic, but we'll add Urdu ones in the future when we get timings for them in sha' Allah.
