### ISSUE TITLE
New Qaloon Version from KFGQPC - 1442

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1619]
The new version is available on [the website of KFGQPC](https://qurancomplex.gov.sa/kfgqpc-quran-qiraat-qaloun/).
features:
1. 604 pages
2. 6214 ayah, like [this print of Libya](https://archive.org/details/MushafQalo4696466996469679onLibya)

The current Qaloon app uses [this print of Tunisia](https://archive.org/details/qaloon_tQQQQQQQQQQQQunes), which was probably the best option for quran\_android until recently, since it has 604 pages but 6236 ayat.

I think we should switch to the new version from KFGQPC, since
1. now we can handle 6214 ayat like the new update for the Warsh app
2. preparing audio timings will be made once based on 6214 ayat

Is there a strong reason nowadays for staying with the current print of Tunisia, other than western arabic numerals?

**Comment by ahmedre** [comment]
جزاكم الله خيراً
we did this, so closing this now.
