### ISSUE TITLE
[Request] Remove `QuranActionBarActivity` due to the bug is not exist anymore

### ISSUE THREAD

**Issue by wiryadev** [quran/quran_android#1663]
I realized this [class](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/ui/QuranActionBarActivity.java) is not necessary anymore due to minSdk is far above Jelly Bean.  The `sBuggyMenuVersion` is always false, hence the two overriden method is always depends on its super class definition and the additional code is not useful anymore.

With that said, i think it is better to remove it and make the activity that extends it use `AppCompatActivity` directly. I have done it in my fork that can be accessed [**here**](https://github.com/wiryadev/quran_android/tree/qaba-removal). If it is accepted, i will create a PR.

Thanks

**Comment by ahmedre** [comment]
looks reasonable - please open the PR - jazakumAllah khairan

**Comment by wiryadev** [comment]
Closed with [this PR](https://github.com/quran/quran_android/pull/1664).
