### ISSUE TITLE
RxJava 3

### ISSUE THREAD

**Issue by wiryadev** [quran/quran_android#1675]
Lately im tinkering with possibility of this repo using RxJava 3. And it looks like it is possible. All the test is passed (at least locally).
![image](https://user-images.githubusercontent.com/26060382/129223734-ddded550-e304-4781-9983-4f56756dc606.png)
![image](https://user-images.githubusercontent.com/26060382/129223874-9643f6f8-630d-468d-8527-66ba8c7949ec.png)

The only breaking(?) change i found probably is the removal of `awaitTerminalEvent` for testing. So i create util for this.

Im not opening PR since i dont know if this is necessary. So i will just give the link to access it in case anyone want to try it. The branch can be accessed [here](https://github.com/wiryadev/quran_android/tree/rx3-playground).

**Comment by ahmedre** [comment]
jazakumAllah khairan - sure, let's do it - i want to replace Rx with coroutines but might as well go with Rx3 over Rx2 for now in sha' Allah

**Comment by wiryadev** [comment]
> jazakumAllah khairan - sure, let's do it - i want to replace Rx with coroutines but might as well go with Rx3 over Rx2 for now in sha' Allah

thanks, PR opened [here](https://github.com/quran/quran_android/pull/1684)

**Comment by ahmedre** [comment]
closing since this is already done - JazakumAllah khairan.
