### ISSUE TITLE
Accurate Arabic Transcription

### ISSUE THREAD

**Issue by mustafa0x** [quran/quran_android#1697]
I just prepared these, so thought I'd share them here in case they're of interest.

https://gist.github.com/mustafa0x/836dc26cb8dc7295cdd870d1c8fd1b4c

Eg. Aal-E-Imran ➔ Āli-ʿImrān, Al-Ma'idah ➔ Al-Māʾidah, Al-Adiyat ➔ Al-ʿĀdiyāt

**Comment by ahmedre** [comment]
JazakumAllah khairan! definitely should do this.

**Comment by Abdou-31** [comment]
السلام عليكم.
I think the system that @mustafa0x suggested has some characters that are not commonly used and recognized among non-Arabs, namely `ʾ` for hamza and `ʿ` for ع. [This Wikipedia article](https://en.wikipedia.org/wiki/Romanization_of_Arabic#Comparison_table) has a table that shows different Arabic romanization systems, we should use a more common one.
بارك الله فيكم.

**Comment by mustafa0x** [comment]
Reusing a single quote, apostrophe, or back-tick instead of a character dedicated for a specific purpose is not good. Also, the visual end result is similar, so shouldn't make much difference.

Would certainly be good to have a quick info box explaining the characters, used, because even long-vowel marks are foreign to many.

**Comment by Abdou-31** [comment]
> Reusing a single quote, apostrophe, or back-tick instead of a character dedicated for a specific purpose is not good. Also, the visual end result is similar, so shouldn't make much difference.
> 
> Would certainly be good to have a quick info box explaining the characters, used, because even long-vowel marks are foreign to many.

There are many Arabic romanization systems as described in the Wikipedia article I've linked to. Which one your list is based on?

**Comment by mustafa0x** [comment]
Funny thing, I just realized Āli-ʿImrān should be Ālu-ʿImrān, especially to be consistent with Al-Muʾminūn, Al-Munāfiqūn, and Al-Kāfirūn (they end with ūn/ون, and not īn/ين, so they are مرفوع). Haven't seen anyone write it that way though.

> There are many Arabic romanization systems as described in the Wikipedia article I've linked to. Which one your list is based on?

I'm not sure, maybe Brill. You can easily compare I think.
