### ISSUE TITLE
Add Ruku/Juz landmarks

### ISSUE THREAD

**Issue by fauzan-muhammadi** [quran/quran_android#170]
Already the app supports hizb landmarks.
However in the kufi mushaf which is very popular in india/pak etc we follow ruku & juz landmarks
Each juz is subdivided into four parts (rubu,nisf, salasa arba3, juz)
Smly each Surah has rukus which are divided more or less contextually.
There should be some options to togglg between kufi system of landmarks and madani system of landmarks.
Thanks, may allah reward you.

**Comment by ahmedre** [comment]
this is added in quran android naskh, so closing.
