### ISSUE TITLE
Add Kufi Mushaf

### ISSUE THREAD

**Issue by fauzan-muhammadi** [quran/quran_android#171]
The madani mushaf is the best mushaf avalible.
However in india Pak and many other countries kufi mushaf is more prevalent.
There should be an option to download it.
This will increase the benifit of this app & the reward for you too.

**Comment by ahmedre** [comment]
done, thanks to brother Asim M - https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh
