### ISSUE TITLE
Incorrect Indonesian translation in Aali Imraan: 14

### ISSUE THREAD

**Issue by mufidu** [quran/quran_android#1722]
I found an incorrect translation into Bahasa Indonesia in Aali Imraan: 14.

I highlighted the sentence. I think it's incorrect because there is a shalawat even though there is no mention of Prophet Muhammad ﷺ.

Thanks. May Allah reward your efforts.

![image](https://user-images.githubusercontent.com/70360519/135571665-e73507e8-13a5-42ac-ae63-6710470e56ae.png)

**Comment by tifa2UP** [comment]
Thank you mufidu for reporting the bug. Can you log it here: https://feedback.quran.com/b/translation-errors/

I created a dedicated board for translation bugs.

**Comment by ahmedre** [comment]
i just checked and seems like you have an older version of the translation. please go to settings, translations and update the Indonesian translation. this is, as you mentioned, a mistake that was fixed some time back - the correct translation, from quranenc.com today, says:

> Dijadikan terasa indah dalam pandangan manusia cinta terhadap apa yang diinginkan, berupa wanita-wanita, anak-anak, harta benda yang bertumpuk dalam bentuk emas dan perak, kuda pilihan, hewan ternak*(114) dan sawah ladang. Itulah kesenangan hidup di dunia, dan di sisi Allah-lah tempat kembali yang baik.

**Comment by ahmedre** [comment]
this is also correct on quran.com - closing.

**Comment by mufidu** [comment]
Oh, I'm very sorry for that.

**Comment by ahmedre** [comment]
no problem brother really appreciate you reporting this (jazakumAllah khairan!), please report any other issues you see in the future so we can report them and get them fixed in sha' Allah!

**Comment by mufidu** [comment]
Wa iyyaak. Thanks for your kindness and efforts.
