### ISSUE TITLE
Bookmarks related bug

### ISSUE THREAD

**Issue by benomaire** [quran/quran_android#1740]
1. Bookmark Ayah 1:6 (or any ayah, I guess)
2. Go to the Bookmarks list
3. Select the bookmarked Ayah
4. Double touch to remove the selection
5. Now swipe to the next page, and the app crashes.

**Comment by ahmedre** [comment]
jazakumAllah khairan for filing - does this happen on the latest code (in master) or in the production version?

**Comment by benomaire** [comment]
only on master.
It does happen with old bookmarks as well.
