### ISSUE TITLE
Suggestion: tafseer sharing text format 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1769]
السلام عليكم ورحمة الله وبركاته 

I have one suggestion about sharing tafseer text format:

{Ayah or Ayats}
[Surah name:Ayah number]

Tafseer name:
Tafseer text

Ex:
From the app:

ذَٰلِكَ ٱلۡكِتَٰبُ لَا رَيۡبَۛ فِيهِۛ هُدٗى لِّلۡمُتَّقِينَ

(المختصر)
ذلك القرآن العظيم لا شك فيه، لا من جهة تنزيله، ولا من حيث لفظه ومعناه، فهو كلام الله، يهدي المتقين إلى الطريق الموصل إليه.

-سورة البقرة، آية ٢

Suggestion(new format):

{ذَ ٰ⁠لِكَ ٱلۡكِتَـٰبُ لَا رَیۡبَۛ فِیهِۛ هُدࣰى لِّلۡمُتَّقِین}
[سورة البقرة: 2]

:المختصر
ذلك القرآن العظيم لا شك فيه، لا من جهة تنزيله، ولا من حيث لفظه ومعناه، فهو كلام الله، يهدي المتقين إلى الطريق الموصل إليه.

وجزاكم الله خيرا

**Comment by Haroun-98** [comment]
وعليكم السلام  

Yes, this new format it looks good and useful.
