### ISSUE TITLE
Auto Scroll

### ISSUE THREAD

**Issue by chiccoss** [quran/quran_android#1795]
Assalamu aleykum brothers!
May Allah reward you for your work.
I am interested in adding to the app an auto scroll between screens with a delay. 

Jazakumullahu khairan

**Comment by ahmedre** [comment]
wa3laikum alsalam,
this is tricky because it's hard to know what delay to use since every person will be different - don't think we'll be doing this for now.
JazakumAllah khairan,
walsalam 3alaikum.
