### ISSUE TITLE
Issue in audio file: recitation of Sheikh Alafasy 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1812]
السلام عليكم ورحمة الله وبركاته 
I found this issue in play store
![Screenshot_20211207-233003_Google Play Store](https://user-images.githubusercontent.com/60948528/145116075-324786f1-7f32-49d0-bfcd-a17eb02235a8.jpg)

Cut of sound in Surah Ali-Imran @time:01:02:00
I fixed the issue, 
@ahmedre please replace the old file with this [003.mp3](https://drive.google.com/file/d/1Nz_07pDJDoUxSZ4Q0KEWqlh4FQ-z-jwB/view?usp=drivesdk) 
وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
done.
والسلام عليكم
