### ISSUE TITLE
Share multiple Ayats from two pages 

### ISSUE THREAD

**Issue by nacer80** [quran/quran_android#1829]
السلام عليكم ورحمة الله وبركاته 
 Now we can share multiple Ayats from the same page only, but we can't share multiple Ayats from two pages.
e.g: if we have 1st Ayah in the end of page n 2 and  2nd Ayah in  the beginning of page 3 we can't  select both Ayats in the same time to share.
وجزاكم الله خيرا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Still we have the issue of sharing Ayats from multiple pages 
Screenshot from play store:
![Screenshot_20220119-182515_Google Play Store.jpg](https://user-images.githubusercontent.com/60948528/150182881-369f45d5-ae35-44c5-b6fa-91e91eaee40c.jpg)

وجزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
How are you? I actually tried it and it works if you long press a verse on first page and long press a verse on second page, it selects the full range and lets you share - does it not work for you?

Also, will have to revert the ayah markers change -  got this feedback email:


جزاكم الله خيراً
والسلام عليكم

**Comment by nacer80** [comment]
Alhamdo'lilah Akhi.

If I select the Ayat in 1st page then  I go to 2nd page  and select the 1st Ayah, and when I try to share i found only the second Ayah ( the ayah in 1st page deselected)

I tried many times but the I got the same results
وجزاك الله خيرا
