### ISSUE TITLE
customize 

### ISSUE THREAD

**Issue by ar100ir** [quran/quran_android#1847]
hi I have publisher and want use this app in my Quran papers. can I use this with your data and in resources say your name and all data about you?
thanks. 🙏 🙏
God bless you.

**Comment by benomaire** [comment]
If you want to print, I believe the [ai files here](https://dm.qurancomplex.gov.sa/Download/1441-AI-hafs.zip)  will be more suitable. You can read [the license of those vector images here](https://dm.qurancomplex.gov.sa/en/copyright-2/).
جزاكم الله خيرا
