### ISSUE TITLE
Gray background for night reading mode إضافة الخلفية الرمادية لوضع القراءة الليلية

### ISSUE THREAD

**Issue by AlbahrawyTiger** [quran/quran_android#1886]
![1644602556375](https://user-images.githubusercontent.com/61330601/153648426-0b169ceb-6fc2-43d0-a65e-4d2d6351dfaa.png)

jazakum allahu khairan 
Please add the ability to customize the night reading mode and make the background of the Arabic reading in gray, as in this modified image, the gray color is more comfortable for the eye than the dark black.
جزاكم الله خيرا. رجاء إضافة إمكانية تخصيص وضع القراءة الليلية وجعل خلفية القراءة العربية باللون الرمادي كما بهذه الصورة المعدلة فاللون الرمادي مريح للعين افضل من الاسود المعتم.

**Comment by MahmoudMabrok** [comment]
I think we can add this to setting screen to change/set background color SO we will have options (default-current used-, custom color from user). @ahmedre

**Comment by AlbahrawyTiger** [comment]
I hope to see it soon in the settings of Quran for android, jazakum allah khairan @MahmoudMabrok @ahmedre
