### ISSUE TITLE
Arabic Issues in Translation

### ISSUE THREAD

**Issue by afarra** [quran/quran_android#191]
from market comments:
>shadab - August 18, 2012 - Samsung Galaxy Note with version 2.1.0
>In translation arabic fonts break
>While changing to translation, Quranic ayat's Arabic fonts break and are abrupt. Howerver without translation it is perfect. I use galaxy note (ICS 4.0.3) while my brother uses HTC (Ginger bread) in which there is no problem. Later on I downloaded many Arabic fonts and started using them. It fixed the issue partially with the Arabic words being smooth but then the starting two words of each sentence used to be missing/hidden. Please help me and send your solution to fix it at mohamedshadab.shaikh@yahoo.co.in JazakALLAHU khairan, Mohamed Shadab

**Comment by ahmedre** [comment]
closing as we no longer include a custom font.
