### ISSUE TITLE
Adding tajweed images

### ISSUE THREAD

**Issue by RealYusufIsmail** [quran/quran_android#1924]
As discussed on Discord I will be adding tajweed images. Please can you assignee me to this issue. @naveed-ahmad also can you let me know were to add it.

**Comment by HiIAmMoot** [comment]
Where is this discord? I was looking into adding tajweed images myself..

**Comment by nacer80** [comment]
Don't forget to add tajweed index too, as Warsh version.

**Comment by ahmedre** [comment]
closing since we already added tajweed images.
