### ISSUE TITLE
️ 

### ISSUE THREAD

**Issue by Hamza1244** [quran/quran_android#1935]

**Comment by nacer80** [comment]
وعليكم السلام السلام الله وبركاته 
بارك الله اخي 
مافهمته من رسالتك انك قمت بإنشاء ملف تزامن التلاوة timing database file 
تستطيع نشر رابط التلاوة مع ملف المزامنة باستعمال قوقل درايف مثلا 
ولقد ذكرت في القائمة القارئ رعد الكردي، و الكثير من الاخوة يطلبون اضافة هذا القارئ.
وجزاك الله خيرا 
والسلام عليكم ورحمة الله وبركاته

**Comment by Hamza1244** [comment]
أخي ، نعم ، لقد صنعت 7 قراء للقرآن الكريم. أرسل كل شيء إليك. يمكنك أن
تعلمني كيفية إرساله إليك أو إعطائك رقمك.

**Comment by nacer80** [comment]
Please check this video from YouTube my it will help you

https://youtu.be/gdrxAoqfvbA
When you upload the files and create a linke, you can share it here.
Please try to send the link of Ra'ad Elkurdi files first and I will Insh'Allah check it.
وجزاك الله خيرا أخي

**Comment by Hamza1244** [comment]
@nacer80 
يا أخي، أرجوك أن تعطيني "رقيم" أو "فيسبوك"، وهناك بعض الأشياء التي يجب أن أتحدث إليك لأشرحها لك

**Comment by nacer80** [comment]
Please check this video from YouTube my it will help you

https://youtu.be/gdrxAoqfvbA
When you upload the files and create a linke, you can share it here.
Please try to send the link of Ra'ad Elkurdi files first and I will Insh'Allah check it.
وجزاك الله خيرا أخي

**Comment by Hamza1244** [comment]
@nacer80
يا أخي، أرجوك أن تعطيني "رقيم" أو "فيسبوك"، وهناك بعض الأشياء التي يجب أن أتحدث إليك لأشرحها لك

**Comment by Hamza1244** [comment]
@ahmedre 
Brother, I need it very much, the problem is that I will test the long reds in my program, what should be the reason, and i will send khalid Jalil's voice to you now, it's good to test

**Comment by Hamza1244** [comment]
@ahmedre ,@nacer80
Brother, please send you a telegram because i can't give you a google drive, my circumcision can't be done, but it's good for the telegram if you don't want to put it

**Comment by Hamza1244** [comment]
@ahmedre 
Please help me

**Comment by Hamza1244** [comment]
@ahmedre @nacer80 
️ السَّلَاْمُ عَلَیْکُم 
Dear brother, this is Khalid Jalil's voice file.

https://terabox.com/s/158VjSA9ZQNR9z_zs2j5qCQ

And that's the database. 

https://terabox.com/s/1CVoWiqpSfMWZI9IgBU4p7A

Try this and tell me if there is any problem, but the long surahs may have problems if this is without problems, I will send you other votes like Raad al-Kurdi, peshawa al-kurdi many more Kurds
 Jazakum al-Allah khirah

**Comment by Hamza1244** [comment]
@nacer80  
اخی

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
1- I didn't have an account in terabox so I can't download your files, please try with Google drive.
2- Please try to make all files complete.
3- Check the Ahkem of Tajweed, because some reciters make issues, like Surah Ibrahim telawa(Taraweeh) Sheikh Aljalil.
4- Check the mp3 Quality ( 128kps and 44.1 khz).

وجزاكم الله خيرا

**Comment by Hamza1244** [comment]
@nacer80 
️ السَّلَاْمُ عَلَیْکُم 
1- Brother Google Drive is not useful. Please close it there.
2_How do I fully file what do you mean?
3 the quality of the votes is okay brother
 جَزَاكُمُ اللّٰهُ خَيْرََا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
if you can't use Google Drive (https://drive.google.com) to upload the files, you have other options:
- dropbox (Dropbox.com)
- give the URL for another website that has the files we can download (ex mp3quran.net, islamway.com, ...)

the timings you can put in a text file here.

**Comment by ahmedre** [comment]
also, brother what language do you speak, I'll see if I can find someone to help bridge the language boundaries in sha' Allah if you tell me.

**Comment by Hamza1244** [comment]
@ahmedre 
Brother kurdish

**Comment by Hamza1244** [comment]
@ahmedre @nacer80 
Brother, here you are. 
https://www.dropbox.com/s/chr76qlp5kaugem/%D8%AE%D8%A7%D9%84%DB%8C%D8%AF%20%D8%AC%D9%84%DB%8C%D9%84.zip?dl=0

It contains both the time file and the votes please tell me what it was I would like to add soon to your program these days so that we are not deprived of the good of this month people will listen to this voice
 جَزَاكُمُ اللّٰهُ خَيْرََا

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
Please close the second issue.
I checked your files:
1- I can't open the database.
2- the mp3 files quality are not good, it contains a lot of noisy.
وجزاك الله خيرا

**Comment by Hamza1244** [comment]
@ahmedre @nacer80 
️ وَعَلَيْكُمَ السَّلَاْم 
Brother, please let me know how to create databases with a computer on the second problem. 
1. It's okay to open the database, brother. Try well. 
2- The votes are not a problem, brother Khalid Jalil himself is the voice, it is not a problem, be sure
 جَزَاكُمُ اللّٰهُ خَيْرََا

**Comment by Hamza1244** [comment]
@ahmedre @nacer80 
️ السَّلَاْمُ عَلَیْکُم 
Brother, there's a program like a ayah splitter for the computer to do his work. Please tell me if i need it too much

**Comment by ahmedre** [comment]
@nacer80 is this one better? https://www.mp3quran.net/ar/jleel?
@Hamza1244 let me ask if we can do it automatically so you don't have to manually do it.

btw, the sheikh most people are asking for is sheikh Ra'd al Kurdi so maybe we can start with him?

**Comment by Hamza1244** [comment]
All right, brother, please tell me whatever it was if it was done with a computer, it would be much better for me because the mobile phone is bad for my eyes, my eyes are bad, please help me to have a program like that for the computer and it's Khalid Jalil to take the voices I've put in because I've worked on it a lot 
If it is without problems, if I send Raad al-Kurdish, but one question that The Kurdish Raad completes his four suras will be like this without those 4 suras

**Comment by Hamza1244** [comment]
@nacer80 
Brother What Khalid Jalil sent that voice because I put the best reading methods and reviewed all the texts

**Comment by Hamza1244** [comment]
@nacer80 @ahmedre 
️ السَّلَاْمُ عَلَیْکُم 
Dear brother, sorry, this is a database link. See if you're going to add it soon.
 
https://www.dropbox.com/s/5l52vbp5fr3nz3f/kalidjalil.db?dl=0
 جَزَاكُمُ اللّٰهُ خَيْرََا

**Comment by Hamza1244** [comment]
@ahmedre @nacer80 
️ السَّلَاْمُ عَلَیْکُم 
 Brother, you asked what could be done automatically without your hand. You didn't have an answer, brother. You'll get it. If there's a program like Ayah Splitter to the computer, tell me to use it. I'm very necessary.Please help me
 جَزَاكُمُ اللّٰهُ خَيْرََا

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
You will find all what you ask here
 https://tanzil.net/docs/adding_new_recitations?s[]=recitation

وجزاك الله خيرا
