### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by agentpros** [quran/quran_android#1942]
Error when i try to view the app on Android Studio 

> Task :app:kaptMadaniDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptMadaniDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

Thanks you

**Comment by ahmedre** [comment]
what's the full stack trace, and what version of Android Studio are you using?

**Comment by agentpros** [comment]
version Android Studio 4.1.3

full stack trace : Execution failed for task ':app:kaptMadaniDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by ahmedre** [comment]
please update to Android Studio Bumblebee | 2021.1.1 or higher - 4.1.3 is a very old version now.
otherwise you can try compiling on the command line - `./gradlew assembleMadaniDebug`

**Comment by agentpros** [comment]
جزاكم الله خيراً

**Comment by jibraniqbal666** [comment]
I would be great if we could close issues that are stale or resolved as there is a lot of noise :) @ahmedre

**Comment by ahmedre** [comment]
closing, please re-open if there is an issue still.
