### ISSUE TITLE
Tafseer mixes and displays ayat in a confusing way

### ISSUE THREAD

**Issue by mohamedcode2000** [quran/quran_android#2022]
السلام عليكم

في تفسير التحرير والتنوير في سورة التكوير في الآية الأولى (التفسير هنا يجمع بين عدة آيات فعليك التقدم فيه لكي تصل إلى الموضع الموضح بالصورة).

في الصورة المرفقة تم الخلط بين الآيات

![screenshot1](https://user-images.githubusercontent.com/109630658/179859150-2400d258-ccb8-438e-88aa-60d942b35186.jpg)

نفس الموضع في التفسير ولكن في الوضع الأفقي يبدو أفضل ولكن به بعض المشاكل (تكملة الآية في السطر الثاني في أقصى اليسار)

![screenshot2](https://user-images.githubusercontent.com/109630658/179859401-0fafdf70-57d0-43d1-b698-49afa413a767.jpg)

قمت بتجربة هذا على هاتف آخر بأبعاد شاشة مختلفة قليلًا وظهرت نفس المشكلة مع اختلافات طفيفة في موضع الخلط بين الآيات.

هذه المشكلة قد تظهر في تفسيرات أخرى ومواضع أخرى.

This seems related to how wrapping across multiple lines is done. Also notice that some lines are aligned to the left, but not sure if this is related to the issue.

جزاكم الله خيرًا.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
this was fixed some time back by @benomaire so closing it now.
جزاكم الله خيراً
والسلام عليكم
