### ISSUE TITLE
Split font size preference for Arabic and translation

### ISSUE THREAD

**Issue by shakib2018** [quran/quran_android#2042]
assalamu alaikum. currently i can only increase the font size of the translation text but not the arabic quran text separately. can you add an option to do that?

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
For the translation screen specifically, the font size affects both the Arabic text and the translation together. For the pages, a font size setting is unfortunately not possible today due to the pages being a set of images.
Walsalam 3alaikum

**Comment by shakib2018** [comment]
![Screenshot_2022-08-05-02-20-22-78](https://user-images.githubusercontent.com/86146710/182945307-f4eb59ae-fdd1-410c-8955-7d81a254b020.jpg)
Yes it affects both. But I want to decrease the translation size, but can't do that because that also decreases Arabic text, and makes Arabic smaller. So decreasing the translation & increasing the Quran text, that's not possible? That's I wanted to say.

**Comment by ahmedre** [comment]
jazakumAllah khairan @jayfan0 for fixing this!
