### ISSUE TITLE
Feature: Playback speed

### ISSUE THREAD

**Issue by shakib2018** [quran/quran_android#2043]
playing speed 1.25x, 1.5x etc.

**Comment by DoozyDoz** [comment]
Why play quran in speed? Just pick shuraym or sudais

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
You listen to Sheikh Yasser Salama (Hadr) his recitation is fast.
And Sheikh Maher AlMuaiqly (KFGQPC) his recitation is slow.

**Comment by shakib2018** [comment]
sorry, didn't notice that discussions happened before #1529
