### ISSUE TITLE
[Suggestions] Adding complete (the whole mushaf) option in Download Amount menu

### ISSUE THREAD

**Issue by ashrafdeeb** [quran/quran_android#206]
Adding complete (the whole mushaf) option in Download Amount menu

will be very nice to be able to download the complete mushaf audio at a time instead of juz' by juz'

and it would be much more nicer to provide links to download it on PC and then transfer to its android location

and I mean the real files used in the app ready to put in there android location not the everyayah.com files which still needs renaming (6000+ files renaming !!!!)

جزاكم الله خيراً .. اللهم اجعلها في موازين حسناتكم 
آميـــن

**Comment by ahmedre** [comment]
download manager exists for a while now that lets this be done pretty much, so closing.
