### ISSUE TITLE
Inquiry: How to make page fill the screen? 

### ISSUE THREAD

**Issue by AbdullahM0hamed** [quran/quran_android#2088]
So I recently bought a new phone (Pixel 6), which has a longer screen than my previous phone (the ayah info db I'm getting is 1260, vs my previous 1024), and when I download the pages in the Qur'an app, they appear like so:

![Screenshot_20221004-164344](https://user-images.githubusercontent.com/25087116/193836505-e821d98a-a9ee-4d52-a376-3c47e72979a0.png)

Is there any way to make it so that the pages take up the screen and there isn't so much whitespace? I am unable to find relevant settings to help me

**Comment by ahmedre** [comment]
Please go to settings, page type, and choose the type that is best suited to larger screens.
