### ISSUE TITLE
Broken audio for Imam Yasser Ad-Dussary

### ISSUE THREAD

**Issue by WholesomeDoktor** [quran/quran_android#2224]
Assalam. I have downloaded the whole quran audio files for Imam Yasser Ad-Dussary and was listening to Surah Nur and at ayah 35 the audio started breaking it didn't recover. 
I don't remember facing the same issue on iOS app.

**Comment by ahmedre** [comment]
wa3laikum alsalam
just tested this and it seems fine for me - can you try going to settings -> audio manager, and deleting the file and re-downloading it?
jazakumAllah khairan.
walsalam 3alaikum

**Comment by WholesomeDoktor** [comment]
Yes, now it works. Sorry, I should've tried this. 

Wa iyyakum 

Thankf for the support.
