### ISSUE TITLE
Where to get quran images and the ayah coordinates

### ISSUE THREAD

**Issue by FouadMagdy01** [quran/quran_android#2234]
I want to know ehre can i get the images url and also the ayah coordinates or the words coordinates
I am trying to build a mobile application and highlights ayah when user presses it

**Comment by ahmedre** [comment]
please see https://github.com/quran/quran.com-images

**Comment by FouadMagdy01** [comment]
> please see https://github.com/quran/quran.com-images

I want an api i am not familiar with python
