### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Hamza1244** [quran/quran_android#2239]
@ahmedre 
I need a tool that cuts the sounds automatically. Please give me or tag someone who has it

**Comment by ahmedre** [comment]
If you just mean the cutting piece after you give the files, I guess you can write a script using ffmpeg - see [here](https://askubuntu.com/questions/1264779/how-to-split-an-mp3-file-by-detecting-silent-parts) for example.

If you mean a general all in one solution where you feed in an mp3 and get timings, if one becomes available for public use will be happy to point you to it - closing for now.

**Comment by Hamza1244** [comment]
@ahmedre I mean, the second one will be available to the public. I need it very much. Please give it to me

**Comment by ahmedre** [comment]
I think I already answered this for you in a few other issues on the tracker, so let me ask you a different question - which sets do you want cut?

**Comment by Hamza1244** [comment]
@ahmedre  
Yes, you told me to use Aya Splatter, but it doesn't automatically cut the votes. I want to cut it automatically. You said there is a tool that cuts it automatically. I want to cut the Kurdish Quran readers.  When will you release a new version of Ayman Swedish?
