### ISSUE TITLE
Outdated Clear Quran translation?

### ISSUE THREAD

**Issue by GitMuslim** [quran/quran_android#2262]
**Translation of 3:96 on [PC](https://quran.com/3?startingVerse=96)**
![image](https://user-images.githubusercontent.com/42213155/233773015-42706955-ad8f-4240-9482-087af2f5c50c.png)

**Translation of 3:96 on ["The Clear Quran" app](https://play.google.com/store/apps/details?id=com.theclearquranapp&hl=en&gl=US):**
![image](https://user-images.githubusercontent.com/42213155/233772939-bd57dc62-0080-4e9c-aca8-96d98a33b81e.png)

**Translation of 3:96 on [Quran Android](https://play.google.com/store/apps/details?id=com.quran.labs.androidquran&hl=en&gl=US):**
![image](https://user-images.githubusercontent.com/42213155/233773215-02574cb5-c972-4da3-a1ab-7a5acbdae063.png)

**Comment by ahmedre** [comment]
just uploaded the latest version which has this fix.

**Comment by GitMuslim** [comment]
JazakAllahu Khayran
