### ISSUE TITLE
What is the API used in this great application

### ISSUE THREAD

**Issue by boodyy24** [quran/quran_android#2266]
Hello, i am very pleased with the application, thank you so much for it.
I just want to know what is the API used to create the app ? (the audio for every ayah, tafsir...etc)

**Comment by madamoniem** [comment]
As far as I know, Quran.com and their mobile app use their own API they've generously collected and compiled into an API. Here is the documentation you can use in your own projects: https://quran.api-docs.io/v4/getting-started/introduction and here is some more info on their development: https://quran.com/en/developers
