### ISSUE TITLE
The path of the surah mp3

### ISSUE THREAD

**Issue by ahmedaboudb** [quran/quran_android#2268]
Where can I find the path of the loaded Surah

**Comment by ahmedre** [comment]
data is on internal storage by default, which isn't accessible. you can go to settings, advanced settings, and change to the external sdcard if the option is there for you.

**Comment by ahmedaboudb** [comment]
> data is on internal storage by default, which isn't accessible. you can go to settings, advanced settings, and change to the external sdcard if the option is there for you.

Thank you
