### ISSUE TITLE
Translate UI to Vietnamese

### ISSUE THREAD

**Issue by techyescountry** [quran/quran_android#2284]
Assalamualaykum brothers, I want to help translate the app interface to Vietnamese but not sure how. Pls guide me through insha'Allah. Thank you.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
yes, you'd want to translate the various strings.xml files in:

app/src/main/res/values/strings.xml (this is the biggest one - all the rest are significantly smaller).
common/audio/src/main/res/values/strings.xml
common/toolbar/src/main/res/values/strings.xml
common/ui/core/src/main/res/values/strings.xml
feature/downloadmanager/src/main/res/values/strings.xml
feature/qarilist/src/main/res/values/strings.xml
pages/madani/src/main/res/values/strings.xml

for reciters, there's also:
common/audio/src/main/res/values/readers.xml

for sura name translations, there's:
app/src/main/res/values/sura_names.xml

jazakumAllah khairan

**Comment by techyescountry** [comment]
ok thank you brother, jazakallah khairan.

**Comment by techyescountry** [comment]
Pull request sent. Thank you brothers. Jazakallah khair.

**Comment by ahmedre** [comment]
jazakumAllah khair for fixing this - closing this issue since this is now merged.
