### ISSUE TITLE
اقتراح اضافة مسرع الصوت

### ISSUE THREAD

**Issue by ageeb1982** [quran/quran_android#2315]
السلام عليكم ورحمة الله وبركاته
جزاكم الله خيرا على هذا العمل  الضخم نسأل الله ان يتقبله منكم 

اقتراح بخصوص زيادة سرعة الصوتيات مثل يوتيوب
١+
١.٥+
١.٧٥+
٢.٠+

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
وفيك بارك الله أخي الكريم.
بالنسبة لخاصية تسريع الصوت، وفرنا في التطبيق قراءة الحدر* للشيخ ياسر سلامة، ليكون تسريع الصوت طبيعيا وليس آليا، احتراما وتقديسا لكلام الله.
وان شاء الله مستقبلا سنحاول إضافة قراء آخرين.
أما بالنسبة للقراءة المتأنية-التحقيق- يتوفر في التطبيق العديد من القراء كالشيخ الحصري، الشيخ أيمن سويد والشيخ المعيقلي تسجيل مجمع الملك فهد....
* الحدر هي احدى الطرق -المراتب- لقراءة القرآن بطريقة سريعة مع مراعاة أحكام الترتيل ومخارج الحروف.
والسلام عليكم ورحمة الله وبركاته

**Comment by ageeb1982** [comment]
وعليكم السلام وحمة الله وبركاته 
وجزاك الله خيراً 
المقصد من اقتراحي بارك الله فيك تسريع قراءة بعض القراء لمراجعة الحفظ 
مثل قراءة الشيخ محمد أيوب رحمه الله تعالى في مثل هذا المقطع 
[https://www.youtube.com/watch?v=HoThYLPjjjc]( https://www.youtube.com/watch?v=HoThYLPjjjc)
فلو حفظ الإنسان ثم اراد ان يراجع عن طريق صوته يجد فيه بطئ شديد وبالتالي نستخدم موقع اليوتيوب لتسريع القراءة 

فيما اعلم ليس في الامر عدم احترام او عدم تقديس و تعظيم لكلام الله ولو في المسألة تفصيل شرعي او قول لأهل العلم في منع مثل هذه المسائل افدنا بها بارك الله فيك

**Comment by ahmedre** [comment]
جزاكم الله خيراً
closing as a duplicate of #1529 where more discussion is happening.
