### ISSUE TITLE
Advertisement message after audio recitation

### ISSUE THREAD

**Issue by amynbe** [quran/quran_android#2358]
السلام عليكم
surat at tahrim at the end with Khalifa Taniji has some extra advertisement message after the recitation

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً

underlying mp3:
https://mirrors.quranicaudio.com/mp3quran/khalifah_taniji/066.mp3

will fix this in sha' Allah.

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
The extra advertisement started at 5:46.
So we can change the value of 999 to 345000

وجزاكم الله خيرا

**Comment by ahmedre** [comment]
fixed, جزاكم الله خيراً
