### ISSUE TITLE
French translation mistakes

### ISSUE THREAD

**Issue by amynbe** [quran/quran_android#2359]
42:3 traduction francaise repetee
41:44 ils sont frappés aveuglement
57:13 : de votre lumières

**Comment by ahmedre** [comment]
salam 3alaikum,
jazakumAllah khairan - may you report these here:

https://quranenc.com/en/browse/french_hameedullah/41/44
https://quranenc.com/en/browse/french_hameedullah/42/3
https://quranenc.com/en/browse/french_hameedullah/57/13

when they update it there in sha' Allah we can re-import for the mobile apps.

jazakumAllah khairan.
