### ISSUE TITLE
Footnotes Missing in English Translation by Dr. Mustafa Khattab, the Clear Quran

### ISSUE THREAD

**Issue by nizam19** [quran/quran_android#2360]
_Assalamualaikum warahmatullahi wabarakatuhu_  😇

I have noticed in the Quran Android app there are no footnotes present in English Translation by Dr. Mustafa Khattab, the Clear Quran, but there are footnotes present on [Quran.com](https://quran.com/2)(website), is this intentional?

Also noticed the Quran Android app supports footnotes, for instance in Translation by Saheeh International, but why not for  Translation by Dr. Mustafa Khattab, the Clear Quran 🤔 

Screenshots below 😉
1. Android Chapter 2 - English Translation by Dr. Mustafa Khattab, the Clear Quran (Footnotes **absent**)
2. [Website](https://quran.com/2) Chapter 2 - English Translation by Dr. Mustafa Khattab, the Clear Quran (Footnotes **present**)
3. Android Chapter 2 - English Translation by Sahih International (Footnotes **present**)

<p float="left">
        <img src="https://github.com/quran/quran_android/assets/42406724/3ffffb41-ac28-41e7-ba16-26a0232da6e4" width="270" height="600">
        <img src="https://github.com/quran/quran_android/assets/42406724/b2b04ae9-766f-4f45-b834-2c0f0533f2b0" width="270" height="600">
        <img src="https://github.com/quran/quran_android/assets/42406724/c664e85b-af51-4765-8072-c0449249daee" width="270" height="600">
</p>

_Jazāk Allāhu Khayran_ ❤️

**Comment by ahmedre** [comment]
wa3laikum alsalam was ra7matullahi wa barakatuh,
jazakumAllah khairan, will import the one with footnotes in sha' Allah (both for Dr. Mustafa Khattab and for AbdulHaleem in sha' Allah.

**Comment by nizam19** [comment]
In sha' Allah
JazakAllah for looking into this issue :)

**Comment by ahmedre** [comment]
just uploaded the version with footnotes.

**Comment by nizam19** [comment]
JazakAllah Ahmed, could verify I can see the footnotes now :)

The coloring to open the footnotes doesn't look visible enough in white mode on a small screen

<img src="https://github.com/quran/quran_android/assets/42406724/825801ab-683b-4ecf-8494-af10361d80a9" width="350" height="400">

What do you think? (looks fine in dark mode though)

**Comment by ahmedre** [comment]
waiyyakum - good point, fixed in #2423

**Comment by nizam19** [comment]
Awesome! Jazakallah khair for quick fix!!
