### ISSUE TITLE
Convert the surah view and highlight ayah to use it in flutter application

### ISSUE THREAD

**Issue by SAFI174** [quran/quran_android#2367]
i work on flutter app (Full Islamic App) and i want to use the ayahinfo_1260.db and pic of every page how can i use it.
i mean how i convert the algorithm that used in this app to an flutter application

**Comment by ibrahmad18** [comment]
That good Idea , also i need this for my Flutter app , and the android quran ayah_info is a good thing to use i think .

**Comment by SAFI174** [comment]
yeah but its so difficult to understand and i really need it.
i did the same thing using QCF Font in richtext and textspan but i had to adjust dimension of every page to show it like madina quran 15 line

**Comment by azizndao** [comment]
I already do it in flutter with the madani v1 from quran.com. It give more controls but I have to load for each single page. I intend to use madani 1441 images of quran_android can anyone say how get it ?

**Comment by maminsedghi** [comment]
Hello, can you give me the source of Madani Quran with database?

**Comment by maminsedghi** [comment]
In flutter

**Comment by ahmedre** [comment]
Sorry brother - the code is written in kotlin and Java, not in flutter.

**Comment by maminsedghi** [comment]
![Screenshot_۲۰۲۴۰۱۱۹-۱۶۱۷۲۷_ ](https://github.com/quran/quran_android/assets/99609077/60c20794-df3d-4acf-a67b-f1a2c34d6103)
This application written with flutter 
But the software source is not for sale

**Comment by ahmedre** [comment]
The image you shared is not from our application.

**Comment by aminsedghi2** [comment]
Yes I know
I mean, don't you know someone who can write?

**Comment by ahmedre** [comment]
You can ask for help on other forums but this issue tracker is just for issues with the Android mobile apps. I apologize for the inconvenience.

**Comment by ahmedre** [comment]
@SAFI174 masha'Allah, may Allah reward you for this great work - may you send me an email - my GitHub handle at gmail to discuss some collaboration?
