### ISSUE TITLE
Request for warsh ayah positions database

### ISSUE THREAD

**Issue by aymendn** [quran/quran_android#2370]
السلام عليكم

Thank you for this amazing project. May God bless you.
I was working on a Quran app (warsh), and I was looking for the ayah position database to highlight an ayah whenever the user taps on it (to show tafsir, translations...).

I spent a good time looking for it, but coudn't find unfortunately. I saw that this project uses this database, but I coudn't find the actual file.

So, anyone help by sending the url for it?

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
you can install the app on your phone, download the files, and copy them from your sdcard (change the location of the app files from settings -> advanced settings).
جزاكم الله خيراً
والسلام عليكم
