### ISSUE TITLE
Audio is cut off early at the end of surah if been playing for a while

### ISSUE THREAD

**Issue by amynbe** [quran/quran_android#2392]
For example, start playback with Reciter Khalifa Taniji from page 45.
Let it play until the end of surat al baqarah.
The final verse will be interrupted a few seconds before the end and move on to the next surah.

There seems to be some increasing de-synchronisation between the audio and text over time. The longer it's been reciting, the bigger the cut off amount.

**Comment by ahmedre** [comment]
cc @nacer80 @benomaire - may one of you check this please? جزاكم الله خيراً

**Comment by nacer80** [comment]
ان شاءالله

**Comment by benomaire** [comment]
Seems to be specific to Sheikh Khalifa Taniji

**Comment by nacer80** [comment]
السلام عليكم ورحمة الله وبركاته 
It seems like codec issue.
Please @ahmedre can you make recoding to Cheikh Taniji mp3's files.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
just checked this on iOS where they don't need reencoding, and it's wrong there also. I then checked the audio file for sura Baqarah and the time for the ayah 45 is 13 minutes and 58.5 seconds, which is at "أفلا تعقلون", instead of "واستعينوا"

**Comment by benomaire** [comment]
Connecting the dots from previous posts, the audio is damaged (dropped frames) and should be replaced (for all Suras)
Possible alternatives in order of my preference:
1. Contact the reciter to acquire original recording files. (I believe he is the current head of holyquran.shj.ae) 
2. https://alteneiji.net/albums/ (19kbps) (Duration: 02:03:03.98)
3. http://www.el-moslem.com/telawa.php?id=100 (32kbps) (Duration: 02:02:38.07)
4. https://en.islamway.net/collection/308/al-mushaf-al-murattal (normal quality 32kbps seems to match the previous option) (Duration: 02:02:38.15)
5. https://en.islamway.net/collection/308/al-mushaf-al-murattal (high quality 128kbps) (Duration: 02:01:53.27)
6. Re-encode the current edition that we have (e.g. `lame --cbr -b 56 -t -q 0 002.mp3`) and redo the timing (Duration: 02:00:51.77)

Note that all 3,4,5,6 seem to originally contain dropped frames that are skipped during encoding. By looking at their durations, 3 and 4 have a little number of dropped frames, and 5 has more dropped frames, and 6 has even more dropped frames

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
JazakumAllah khairan 
I agreed with 5 and 6.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
I saw that Ayah has this reciter and tried the end of sura Baqarah there that one looks okay to me. If you all think this one is okay, can use their timings and mp3 here, since the brothers share their data with me.

جزاكم الله خيراً
والسلام عليكم

**Comment by benomaire** [comment]
The version of Ayah 
- is definitely better than our current version in terms of dropped frames (Duration: 02:02:40.97)
- arguably has slightly lower audio fidelity than our current version (I think both are lower than option 5 above)

So it is the quickest fix, and should be fine for long term as well.

والله أعلم

**Comment by mdetamo82** [comment]
Assalamualaikum Warahmatullahi Wabarakatuh @nacer80  can you create timing for this audio file [shatri with amharic audio language] 
 (https://quran.nebatyiwu.com/shatri_with_amharic_audio_translation.zip) jazakallah

**Comment by ahmedre** [comment]
replaced sura Baqarah and the timing file.

**Comment by benomaire** [comment]
> replaced sura Baqarah and the timing file.

That is not enough. You should replace ALL files. 
It did not take me long to hear dropped frames in Surat Aali-3imran, and for the synchronization to be off. Listen for example to Ayat 17, 20, 28, 44, 45, 55.

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 

I prefer to use: https://en.islamway.net/collection/308/al-mushaf-al-murattal
The quality of mp3's files is batter than Ayah files.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
ok - would you be able to prepare a database of timing files?
جزاكم الله خيراً
والسلام عليكم

**Comment by ahmedre** [comment]
replaced all these files al7amdulillah. closing.
