### ISSUE TITLE
Qaloon Audio uses Kufi counting instead of Madani

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#2405]
Today, Qaloon audio is still using kufi counting (6236 ayat) instead of madani counting (6214 ayat). This is generally troublesome for gapless audio, especially in suras like Sajdah where the first 10 ayat are "off by one" (the rest of the sura ayah 11 and on are correct). These types of issues happen throughout.

It's even more problematic though with the gapped audio for sheikh Hudhayfi, which uses kufi counting also (ex [32:1](https://mirrors.quranicaudio.com/everyayah/qaloon_hudhayfi_96kbps/032001.mp3), which in Madani counting would also include 32:2).

I checked Warsh, which also uses madani counting. All the gapless databases there use Madani counting, however, the one gapped qari there (who has a gapless version now so it's not that big of a problem) has the same problem.

@nacer80 @benomaire - any suggestions on fixing this? Qaloon has 2 gapless qaris and 1 gapped qari. One thought was to write a script using the rules we know to fix the database for the gapless qaris (and the files for the gapped ones), while marking some files as needing manual fixes (ex when we have to split an ayah because 32:10 in Kufi counting corresponds to both 32:9 and 32:10 in Madani counting).

Another option is to just update the app itself to do this mapping before playback, but I am not too sure about that idea at the moment because it won't give us the opportunity to fix some of those issues in the future. Perhaps one long term advantage of this second approach though is that if we have a way to play Kufi counting on either a Kufi counting or Madani counting mushaf, it brings us one step closer to being able to have one single unified app for everything.

**Comment by nacer80** [comment]
وعليكم السلام ورحمة الله وبركاته 
I prefer the second option, we can fix the issues after.
وجزاك الله خيرا

**Comment by ahmedre** [comment]
this is now fixed by manually redoing the timings - جزاكم الله خيراً @benomaire for doing this.
