### ISSUE TITLE
Can you add more tafaseer to the application

### ISSUE THREAD

**Issue by mohamedghonemi** [quran/quran_android#241]
The application is very nice, but it will be more useful if it contains more tafaseer
I suggest the following tafaseer :
- Al-galalin (الجلالين)
- Al-Qortoby (القرطبي)
- Al-Tabary (الطبري)
- Fath AlQadeer  (فتح القدير للشوكاني)
- Baghawi (البغوي)

**Comment by ahmedre** [comment]
note that sheikh Isa Garcia is now the default (only?) Spanish translation in the app.

**Comment by ATouhou** [comment]
@ahmedre "al-mizan" is shiaa tafseer. You should not add unreliable things like that.

**Comment by ahmedre** [comment]
jazakAllah khairan for pointing this out - i'll add it to that ticket too to make sure we don't accidentally add this. we try very hard to keep all our tafaseer sunni only.

**Comment by ahmedre** [comment]
closing for now since most of the said Arabic translations are added (same with Sheikh Garcia).
