### ISSUE TITLE
Alslamo alaikom my brother

### ISSUE THREAD

**Issue by Iam-Muslim** [quran/quran_android#2422]
Alslamo alaikom my brother <3
This is a good work may Allah bless you <3

I need to get the quran text you use 
maybe you have it in json or xml or excel or doc formats 
i want it for various uses as i have some text but needs some fixes

**Comment by benomaire** [comment]
This might be useful for you:
https://download.qurancomplex.gov.sa/resources_dev/UthmanicHafs_v2-0.zip

**Comment by ahmedre** [comment]
closing this one for now
