### ISSUE TITLE
Mistake in "Surah Muzzamil"

### ISSUE THREAD

**Issue by lionage** [quran/quran_android#2433]
Plz chech the highlighted text, there should be "shad" on wao. correct one is small Pic and mistake from ur app on big page. Sorry for my English.
![Screenshot_20231018-220511_Quran](https://github.com/quran/quran_android/assets/47098256/cfcf8992-bc1f-4c93-878b-082662e9b960)
![Screenshot_20231018-222220_Chrome](https://github.com/quran/quran_android/assets/47098256/1042b24c-6d32-4aeb-b73c-08510f7f4f93)

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
There are two popular scripts for the Hafs Quran - the Madani script and the Naskh script - both are correct and both are found in Masjid al-Haram and Masjid al-Nabawi and both say the same thing (and both copies are actually published by the King Fahd Quran printing Complex in Saudi Arabia), but they draw the diacritics and tashkeel differently. From the picture you shared, you are used to reading the Quran Naskh script. Please download our Naskh app here - https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh.
jazakumAllah khairan.
walsalam 3alaikum.

**Comment by lionage** [comment]
Thank you 4 the brief guidelines. May Allah bless you and your team alot. And who contribute in this Holy project.
Keep up the good work

**Comment by ahmedre** [comment]
ameen, jazakumAllah khairan
