### ISSUE TITLE
There is No PageType (experimental)

### ISSUE THREAD

**Issue by muqtadir321** [quran/quran_android#2447]
No PageType (experimental) is showing in git version.

**Comment by ahmedre** [comment]
yes, today only the madani type is there. considering to migrate some of the others tot he open source version in the future in sha' Allah.

**Comment by bateni** [comment]
Is the latest github version using the old madani mushaf or the new version from 1441? I just compiled it and it seems to be using the old images. Am I doing something wrong?

**Comment by ahmedre** [comment]
by default it uses the old images. you'd need to add a new `PageProvider` that provides the 1441 pages but otherwise all the remaining code should be there for it to work.

**Comment by bateni** [comment]
thanks. so this means the images plus some sort of geometry for each ayah. right?

**Comment by ahmedre** [comment]
yes that's right
