### ISSUE TITLE
AI tool for generating qari database files

### ISSUE THREAD

**Issue by g3ida** [quran/quran_android#2532]
السلام عليكم

I am a software developer and I would like to contribute by the development of an automatic tool to generate database files for gap-less reciters using AI and voice recognition. I would greatly appreciate hearing your thoughts on this project.

Also upon reviewing past discussions, I noticed the existence of some foundational tools for Madani/Kufi ayah counting like
https://drive.google.com/file/d/1cCDm3AlW2CaWb2I435E78oEHvTGQ_E6n/view
and 
https://drive.google.com/file/d/1oBFFSiYG_8vHTMAsPmq0vipdHO9dEUVa/view
While this tool simplifies the task, there remains a good amount of manual work in the process.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً
the green tech brothers have a tool that we ask them to run for us when we want to get the timings, and it uses AI to mark the timings of every ayah (and the words within the ayah even).

جزاكم الله خيراً

**Comment by g3ida** [comment]
I am happy to hear that. thanks for letting me know :)
