### ISSUE TITLE
flutter app

### ISSUE THREAD

**Issue by maminsedghi** [quran/quran_android#2536]
کسی میتونه سورس فلاتر این اپلیکیشن رو در اختیار بنده بزاره؟
اجرکم عند الله
هل يمكن لأحد أن يزودني بالملف المصدر لهذا التطبيق؟ اجرکم عند الله

Can someone provide me with the source file of this application? My reward is with Allah

**Comment by ahmedre** [comment]
the application is not written in Flutter - it's written in native Java and Kotlin, and this repository contains its source code.

**Comment by maminsedghi** [comment]
کسی میتواند بنویسد؟
