### ISSUE TITLE
💡 Which version of the Quran are you using? 

### ISSUE THREAD

**Issue by Pantyhose-X** [quran/quran_android#2587]
Early Quranic manuscripts https://en.wikipedia.org/wiki/Early_Quranic_manuscripts

> https://en.wikipedia.org/wiki/Islam
> [Quran](https://en.wikipedia.org/wiki/Quran)[Sunnah](https://en.wikipedia.org/wiki/Sunnah)
([Hadith](https://en.wikipedia.org/wiki/Hadith), [Sirah](https://en.wikipedia.org/wiki/Prophetic_biography))
[Tafsir (exegesis)](https://en.wikipedia.org/wiki/Tafsir)[Aqidah (creed)](https://en.wikipedia.org/wiki/Aqidah)
[Qisas al-Anbiya ("Stories of the Prophets")](https://en.wikipedia.org/wiki/Qisas_al-Anbiya)
[Mathnawi](https://en.wikipedia.org/wiki/Mathnawi) (Poems)
[Fiqh (jurisprudence)](https://en.wikipedia.org/wiki/Fiqh)[Sharia (law)](https://en.wikipedia.org/wiki/Sharia)

**Comment by ahmedre** [comment]
we're using the King Fahd Quran Printing Complex images for most of the images we have in most of our apps (main Quran for Android app - all except Shemerly and Tajweed (Dar al Marefa), Naskh app, Qaloon app). Warsh is using Dar al Marefa tajweed images also.

**Comment by Pantyhose-X** [comment]
> Quran Printing Complex images
> Warsh is using Dar al Marefa tajweed images
I couldn't find it on the Internet. That's the version of scripture they printed. 
He could be a fake.

## I'm looking for the text here
https://en.wikipedia.org/wiki/Early_Quranic_manuscripts
https://qurantalkblog.com/2023/09/04/oldest-quran-manuscripts/

**Comment by ahmedre** [comment]
We don't have the early manuscript versions in the app, nor would you likely find them anywhere other than museums.

If you do find them, you'll find them to say the exact same thing as what we have today.
