### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by masreplay** [quran/quran_android#2592]
السلام عليكم ورحمة الله
I read that the project code 
If I want to make an application using a “Flutter” for all devices, my question is as follows: Should I use the API or should the data be located offline?

and where I can find Quran font in the project
جزاكم الله خيرا

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
it depends on what you want to do - mobile apps typically have an offline mode for when data isn't available though. you can use quran.com's API for some data. this app is written in Kotlin, perhaps you can take a look at [this app](https://github.com/SAFI174/tawakkul) which is open source and written in Flutter.

for the pages, our app uses images, not fonts.
جزاكم الله خيراً
والسلام عليكم
