### ISSUE TITLE
تحميل الصوت كاملا

### ISSUE THREAD

**Issue by jam99al** [quran/quran_android#2675]
السلام عليكم ورحمة الله 
هل من طريقة لتحميل صوت اي قارئ مرة واحدة لكامل القرآن.  التحميل عندي للسورة الواحدة او الصفحة المحددة.
ربنا يتقبل منكم

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
يمكنكم ذلك من الإعدادات ثم إدارة الصوتيات.
جزاكم الله خيراً
والسلام عليكم
