### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by amirian** [quran/quran_android#2686]
After the last commit (merging 2681 pull request), apk generation is stopped with the following error:
`Circular dependency between the following tasks:
:app:generateMadaniReleaseRFile
\--- :app:parseMadaniReleaseLocalResources
     \--- :app:packageMadaniReleaseResources
          \--- :app:injectCrashlyticsMappingFileIdMadaniRelease
               +--- :app:kaptMadaniReleaseKotlin
               |    \--- :app:kaptGenerateStubsMadaniReleaseKotlin
               |         +--- :app:generateMadaniReleaseRFile (*)
               |         \--- :app:kspMadaniReleaseKotlin
               |              \--- :app:generateMadaniReleaseRFile (*)
               \--- :app:kspMadaniReleaseKotlin (*)
`
even `./gradlew clean` and `./gradlew --rerun-tasks` won't help. Making project is perfect, the error rises in apk generation.

**Comment by ahmedre** [comment]
it's building fine both here and in CI/CD - i didn't try a release build, but did a debug build and it was fine - `./gradlew assembleMadaniDebug` - can you try that and see if it's working? are you sure you have no other changes in your branch?

**Comment by amirian** [comment]
assembleMadaniDebug works fine, assembleMadaniRelease does not. I have made changes with no difference in dependencies. Moreover, my changes made no issues till your last commit.

**Comment by amirian** [comment]
I already tried your main branch, it also generates the error.

**Comment by ahmedre** [comment]
Ok I can repro now - two workarounds while I find a fix - either set `crashlytics` in gradle/libs.versions.toml back to 2.9.9, or compile using `-PdisableFirebase`

**Comment by amirian** [comment]
That's it, [the firebase bug](https://github.com/firebase/firebase-android-sdk/issues/5925). They are having that fixed.

**Comment by amirian** [comment]
That's it, [the firebase bug](https://github.com/firebase/firebase-android-sdk/issues/5925). They are having that fixed.

**Comment by amirian** [comment]
Crashlytics bug is fixed within v3.0.1, I'n not permitted to create a branch and update the dependency.

**Comment by ahmedre** [comment]
I am waiting for 3.0.2 because there's a problem with 3.0.1 also

**Comment by amirian** [comment]
They mentioned the issue is related to a package for Google services not the crashlytics. I have tested 3.0.1 and confirm it is resolved in the release. Anyway, you can wait for a new version but it will not be about this bug.

**Comment by amirian** [comment]
3.0.2 has come for a while, why sticking on 2.9.9?

**Comment by ahmedre** [comment]
merging in #2781
