### ISSUE TITLE
support direct download links

### ISSUE THREAD

**Issue by hmaher** [quran/quran_android#269]
- the aim of this is to stop emails inquiring about direct links to download from pcs then copy to sdcard
- we need to discus this @ahmedre

**Comment by ahmedre** [comment]
we now have an audio manager that lets you download all the suras from within the app, so closing this for now.

**Comment by aelmahmoudy** [comment]
I think the point of this issue is enabling users to use pre-downloaded audio files (for example copy them from another user). But I don't see that the audio manager enables this.
