### ISSUE TITLE
Audio control bar not centered

### ISSUE THREAD

**Issue by rachidBensaid** [quran/quran_android#2708]
Salam aleykoum wa rahmatoullah

### Description:
The media control bar at the bottom of the screen, which includes the play, pause, and stop buttons, is not centered. This affects the user experience by making the controls harder to use and aesthetically unbalanced.

### Steps to Reproduce:

- Open the Quran reading application.
- Navigate to any Surah and start the audio playback.
- Observe the media control bar at the bottom of the screen.

### Expected Behavior:
The media control bar should be centered horizontally to ensure a balanced and user-friendly interface.

### Actual Behavior:
The media control bar is off-centered

### Screenshot:

![Screenshot_2024-05-15-22-58-10-106_com quran labs androidquran](https://github.com/quran/quran_android/assets/25226974/1da3de3a-a5fc-40ad-a68f-accb96756bbe)

### Environment:
App Version: 3.4.4
Device: Redmi Note 12
Android version: Android 12
OS: MIUI

Jazakum Allahu Khairan for addressing this issue.

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
JazakumAllah khairan - it's intentionally not centered (because it needs to be scalable for tablets and landscape), but also, the latest version of this code completely rewrote and changed the audio bar so please feel free to try it out

**Comment by rachidBensaid** [comment]
> Wa3laikum alsalam, JazakumAllah khairan - it's intentionally not centered (because it needs to be scalable for tablets and landscape), but also, the latest version of this code completely rewrote and changed the audio bar so please feel free to try it out

ok barakallahou fik for your quick answer, it's fine if it's intentionally not centered, may Allah reward you and everyone working on the app greatly, it's the only app i'm using to read the qur'an on my phone, because it's the best in my opinion
