### ISSUE TITLE
Authentic Swahili Translation

### ISSUE THREAD

**Issue by ALWISHARIFF** [quran/quran_android#2731]
Assalamu alaykum warahmatullahy wabarakatuh,
I have successfully added a Swahili translation on quranenc.com
Below is the link.
[QURAN SWAHILI TRANSLATION](https://quranenc.com/en/browse/swahili_abubakr)

What makes this translation better is its correct translation in names and attributes of Allah aaza wajal
BarakaAllah feekum

**Comment by ahmedre** [comment]
salam 3alaikum,
received, can't do anything until either they make it available for download (it's not yet), or until Quran.com starts indexing it.

**Comment by ALWISHARIFF** [comment]
JazkaAllah Kheiran for your reply akhi
Allahu akbar Allahu akbar La illaha illa llah Allahu akbar Allahu akbar Walillahi Lhamd
What does indexing by quran.com mean?Can i contribute to index ins Allah If you can share more details
BarakAllah Feek @ahmedre 
JazakaAllah kheiran
Assalamu alaykum warahmatullahy wabarakatuh

**Comment by ahmedre** [comment]
nothing needed from your side akhi - i'll check with the Quran.com team this weekend in sha' Allah and see if they can index it.

**Comment by ALWISHARIFF** [comment]
JazakaAllah kheiran ins Allah

**Comment by ALWISHARIFF** [comment]
السلام عليكم ورحمة الله وبركاته 
Eid Mubarak 
تقبل الله منا ومنكم صالح الأعمال

**Comment by ALWISHARIFF** [comment]
> nothing needed from your side akhi - i'll check with the Quran.com team this weekend in sha' Allah and see if they can index it.

Assalamu alaykum warahmatullahy wabarakatuh

**Comment by ALWISHARIFF** [comment]
Assalamu alaykum warahmatullahy wabarakatuh brother @ahmedre any update on the translation addition you promised to work on it any update

**Comment by ALWISHARIFF** [comment]
Assalamu alaykum warahmatullahy wabarakatuh @ahmedre

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh.
haven't forgotten about this akhi but just have not gotten to it yet.
will update when done in sha' Allah.
walsalam 3alaikum

**Comment by ALWISHARIFF** [comment]
I thank you very much for your sincere efforts in daawah @ahmedre
Barakallah feek

**Comment by ahmedre** [comment]
this is now done, closing.
you can get the update from translations, pull to refresh, and find it in the list.

**Comment by ALWISHARIFF** [comment]
Barakallah feek @ahmedre
I thank you very much for your support may Allah aaza wajal accept from you and protect the ummah worldwide

**Comment by ahmedre** [comment]
wa feek akhi, ameen 👐

**Comment by ALWISHARIFF** [comment]
Assalamu alaykum warahamatullahy wabarakatuh @ahmedre 
I hope you are doing well there is an update on QuranEnc for the swahili translation
Kindly please update with the latest translation i remember last time you scraped the translation
BarakaAllah feek
