### ISSUE TITLE
Surah 15, Ayah 73 Highlight is off

### ISSUE THREAD

**Issue by MrNewbie72** [quran/quran_android#2755]
If you long press the ayah 73 from surah 15 you'll notice the highlighting is off.

The fix to this is not in the application but in the ayahinfo db's getting the next word max_x and placing it in min_x would fix it.

Running this in each ayahinfo_**x**.db sqlite file, should fix it
```sql
update glyphs set min_x = (select max_x from glyphs where page_number = 266 and ayah_number = 74 and position = 1) where page_number = 266 and ayah_number = 73 and position = 4;
```

Jzakom Allah Khair

**Comment by ahmedre** [comment]
JazakumAllah khairan fixed this for the next release. Alternatively you can erase the image database manually and it will download the new one

**Comment by MrNewbie72** [comment]
Here is another one for Surah 37, Ayah 171.

```
update glyphs set min_x = (select max_x from glyphs where page_number = 452 and ayah_number = 172 and position = 1) where page_number = 452 and ayah_number = 171 and position = 6;
```

**Comment by ahmedre** [comment]
JazakumAllah khairan this one is also fixed in the next version and/or uninstall and reinstall the app to get the updated database today

**Comment by MrNewbie72** [comment]
Here is another one for Surah 8, Ayah 39.

update glyphs set min_x = (select max_x from glyphs where page_number = 181 and ayah_number = 38 and position = 1) where page_number = 181 and ayah_number = 39 and position = 17;

**Comment by ahmedre** [comment]
jazakumAllah khairan - fixed this one also. fixed in the next version and/or uninstall and reinstall the app to get the updated database today
