### ISSUE TITLE
make surah name searchable

### ISSUE THREAD

**Issue by mohalfarizi** [quran/quran_android#2864]
assalamualaikum sir, can you make the surah names searchable? because sometimes i found a really good recitation online and it only tell the surah name and finding it by scrolling one by one is a little tiring

**Comment by MalikSaabSays** [comment]
Salam.

If you go to the 'Go To Page' option, you can just type in surah name, and it will appear in that. You can put in the number of the surah too.

![Screenshot_2024_1007_061011](https://github.com/user-attachments/assets/28a6f186-c396-4fb4-bd17-fba8971fdcd4)

**Comment by MahmoudMabrok** [comment]
Is this fine bow, @mohalfarizi

**Comment by ahmedre** [comment]
I still have a todo to do this in the actual search though, since, today, search doesn't search sura names or numbers

**Comment by mohalfarizi** [comment]
yes thank you, this is actually what i've been searching, though it would be great if i can also do it in the global search for example by typing "30:12" it will bring me to surah 30 ayat 12.

btw i will mark this as closed
