### ISSUE TITLE
Harokat pada surat almursalat

### ISSUE THREAD

**Issue by Valey169** [quran/quran_android#2909]
{ ٱنطَلِقُوۤا۟ إِلَىٰ مَا كُنتُم بِهِۦ تُكَذِّبُونَ }
[Surat Al-Mursalat: 29]
Pada awal ayat tersebut berharokat pathah, kenapa tidak berharokat kasroh

**Comment by ahmedre** [comment]
This is an alif wasla, and is pronounced as a kasra as you mentioned. This is how it is rendered in the madani mushaf as printed by the King Fahd Glorious Quran Printing Complex.
