### ISSUE TITLE
Feature: hide system navigation bars once open dialog of choosing ayas range

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#2936]
After we choose ayahs range we have to wait time until we able to click on apply button. 

![Screenshot_2024-11-06-00-16-35-184_com quran labs androidquran](https://github.com/user-attachments/assets/b0784f0a-1ce7-4ab8-a6e9-8fe138757350)

**Comment by ahmedre** [comment]
This is already fixed by #2559, just haven't released since then.

**Comment by MahmoudMabrok** [comment]
I think adding margin would fix it.

**Comment by MahmoudMabrok** [comment]
could we have a workflow that generate a build every week, and upload it to GitHub or the beta tester channel at google play?

**Comment by ahmedre** [comment]
There is a margin already - could you check if it's scrollable?

Yeah we have a Google Play alpha channel that we are not using right now but might be a good time to start up again

**Comment by MahmoudMabrok** [comment]
sorry for being late, yes view is scrollable.

**Comment by ahmedre** [comment]
جزاكم الله خيراً
