### ISSUE TITLE
تفسير السعدي

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#299]
الصفحات ١٦٥،١٦٧ من سورة الأعراف في تفسير السعدي لا توجد لها تفسير!!

**Comment by g360230** [comment]
السلام عليكم ،

قمنا بتحيين قاعدة البيانات الخاصة بتفسير السعدي.

القاعدة المحينة موجودة في الرابط التالي :
https://www.dropbox.com/s/iivi4jv5b08vdlm/quran.ar.sa3dy.db?dl=0

في هذا التحيين حاولنا معالجة الأخطاء المذكورة في هذا الجدول :

__________________________________________________
|........................السورة.............|..الأيات............|..النتيجة..|
__________________________________________________
|.........البقرة..............|..269...............|..تم تحيين التفسير..|
|..............الأعراف...........|..121 --> 130..|..لا يوجد تفسير..|
|..............الأعراف...........|..138 --> 143..|..لا يوجد تفسير..|
|..........ابراهيم.............|..9..................|..تم تحيين التفسير..|
|..الكهف..............|..22...............|..التفسير الموجود صحيح..|
|..........الحج.................|..52................|..تم تحيين التفسير..|
|..........الزغرف............|..26 --> 81......|..تم تحيين التفسير..|
|..........الذاريات............|..37 --> 51......|..تم تحيين التفسير..|
__________________________________________________

 باراك الله فيكم

**Comment by Somaiagabr** [comment]
وجدت في تفسير ابن سعدي في سورة إبراهيم تفسير الآيات 7،8،9 بعدها مباشرة تفسير آيات من أول سورة الحجر صححهوها وفقكم الله .

**Comment by Somaiagabr** [comment]
الاحزاب اية رقم 51 حيث ان الآية تقول "عليما حليما" اما في تفسير السعدي لهذه الآية  مكتوبة "عليما حكيما".

**Comment by Somaiagabr** [comment]
البقرة صفحة 33 حيث ان التفسير ليس له علاقة باﻵيات المراد تفسيرها

**Comment by Somaiagabr** [comment]
36:30 Tafsir al-Saadi its a mistake in the arabic,

in your programm 

قال الله متوجعاً للعباد "يا حسرة علي العباد ما يأتيهم من رسول إلا كانوا به يستهزؤون"

but "Mutawaji3an" its meaning : Allah say with pain...  and we know that allah dont have any pain.


right its: 

[قال الله مترحماً للعباد : (يا حسرة على العباد...)

**Comment by Somaiagabr** [comment]
Al sa'di with ayah numbers 7 and 8 of surah Ibrahim. Apparently the tafseer of ayahs 7 and 8 of surah Al hijr have appeared in their place.

**Comment by Somaiagabr** [comment]
ayah no. 64 of surah al Nahl is missing the tafsir.

**Comment by Somaiagabr** [comment]
I found a mistake in as-Sa'diyy's tafseer. For soorah  79 aayah 2 it says

أو أن النزع يكون لأرواح المؤمنين، والنشط لأرواح الكفار

But in the printed version of the book it says

أو أن النشط يكون لأرواح المؤمنين، والنزع لأرواح الكفار

**Comment by ahmedre** [comment]
check:
> تفسير سورة البقرة ؛ تفسير السعدي ؛ الآية 232

**Comment by ahmedre** [comment]
يوجد خلل في تفسير السعدي لسورة الزخرف، حيث أن التفسير يكون للآية التي تليها.

**Comment by ahmedre** [comment]
There seems to be mistake in the tafseer of as-Sa'diyy rahimahullaah for aayah 3 of Sooratul Faatihah. It seems to have been replaced by the tafseer for the first few aayahs of Aale Imraan. I hope this will be fixed soon,

**Comment by ahmedre** [comment]
هناك خطا طباعي في تفسير السعدي حيث تكرر تفسير الآية في ثلاث آيات مختلفة
سورة البقرة آية 121 و مابعدها

**Comment by ahmedre** [comment]
وأرجو أن تراجعوا تفسير السعدي لصفحة 167 حيث أنه غير مكتوب (الأعراف 138 : 143) ولكم من الله خير الجزاء.

**Comment by ahmedre** [comment]
surah hajj ayah 52

**Comment by ahmedre** [comment]
لفت انتباهي ان تفسير السعدي لصفحة ٣٣ به خطأ ألا وهو تكرار نفس التفسير لكل الآيات الكريمات في هذه الصفحة.
لذا وجب علي التنبيه وجزاك الله كل خير.

**Comment by ahmedre** [comment]
هناك ملاحظة في تفسير السعدي سورة ابراهيم الآية 8 ،9 يظهر تفسير الاية 8 ، 9 من سورة الحجر
وعندما ذهبت إلى سورة الحجر وجدت تفسير الآيتين فارغ

**Comment by ahmedre** [comment]
كان عندى ملحوظه بسيطه فى تطبيق القرءان الكريم فى التفسير للسعدى ... فى سورة الزخرف من ءاية 26 حتى ءاية 84 يتقدم التفسير الآيه بحيث سبقته ,ففى ءاية 26 جمعت تفسير ءايتين مما أدى إلى التأثير بالتأخير عن باقى آيات السورة حتى ءاية 86 ... و بارك الله فيكم

**Comment by Somaiagabr** [comment]
في تفسير السعدي آيه 23 من سورة الزمر هذا الجزء غير موجود بهذه الآيه قال تعالى في هذا الموضع { يَهْدِي بِهِ مَنْ يَشَاء ُ }. لا يوجد { مِنْ عِبَادِهِ } في هذه الآيه

**Comment by ahmedre** [comment]
```
العلامة عبد الرحمن بن سعدي:
📝 تنبيه على خطإ مطبعي :

🔹الحمد لله والصلاة والسلام على رسول الله وعلى آله وصحبه ومن والاه. أما بعد:

🔸فقد وقفت على كلمة في تفسير العلامة عبدالرحمن السعدي رحمه الله والمعروف بـ: ((تيسير الكريم الرحمن في تفسير كلام المنان)) في شرح سورة (يس) دفعتني للشك أن الشيخ العلامة عبدالرحمن السعدي رحمه الله يمكن أن يقولها وهذه الكلمة جآءت في تفسير قول الله تعالى : ((يَا حَسْرَةً عَلَى الْعِبَادِ )) حيث ورد في بعض الطبعات مانصه:
قال اللّه متوجعاً للعباد: { يَا حَسْرَةً عَلَى الْعِبَادِ مَا يَأْتِيهِمْ مِنْ رَسُولٍ إِلَّا كَانُوا بِهِ يَسْتَهْزِئُونَ } أي: ما أعظم شقاءهم، وأطول عناءهم، وأشد جهلهم، حيث كانوا بهذه الصفة القبيحة، التي هي سبب لكل شقاء وعذاب ونكال" إنتهى

🔹فاستغربت لفظة متوجعاً حيث أنني بفهمي القاصر أعلم أنها صفة نقص ولم يصف الله بها نفسه ولم يصفه بها رسوله عليه الصلاة والسلام فما بالك بالعلامة الإمام إبن سعدي رحمه الله؟!!

🔸وعند الرجوع لطبعة أخرى للكتاب وهي طبعة مكتبة الصفا المصرية وجدت بدل كلمة (متوجعاً) كلمة (مترحماً) فاطمأننت بأن هذا هو الصواب،وزادني طمأنينة ماوجدته في بعض أقراص الحاسوب.

🔹والنسخ التي ورد بها لفظ متوجعاً والتي وقفت عليها هي:

1-طبعة مكتبة الرشد بالرياض الطبعة الرابعة 1424هـ /2003م(تحقيق:عبدالرحمن بن معلا اللويحق)

2-طبعة مكتبة الرسالة.

👈 والمؤسف بأن هاتين الطبعتين أكثر طبعتين تداولاً وذلك لجودة طباعتهما، ولعله يوجد غيرهما يحتوي على هذا الخطأ، هذا إن لم أكن أنا المخطئ.

📣 فأرجوا التنبيه على هذا الخطأ والذي يوجد أيضاً حتى في بعض المواقع الإسلامية على شبكة الإنترنيت، أو أرجوا تنبيهي إن كنت أخطأت.
منقول 
```

**Comment by ahmedre** [comment]
> أود التنبيه على خطأ في تفسير السعدي اﻵية 9 من سور إبراهيم 14
> وذلك عند فتح تفسير السعدي لهذه الآية يعطيني تفسير ﻵية مختلفه

**Comment by ahmedre** [comment]
> لاحظت في نسخة الأندرويد أن الآيات 211 إلى 215 من سورة البقرة قد تم تكرار التفسير لها بتفسير الآية 210.. من تفسير ابن سعدي
page 33

**Comment by ahmedre** [comment]
> يوجد خطأ في تشكيل كلمة "كل" في تفسير السعدي في الآية رقم 6 من سورة هود.

**Comment by ahmedre** [comment]
>  هناك خطأ في تفسير السعدي لآية 9 - سورة إبراهيم

**Comment by ahmedre** [comment]
> تفسير ابن سعدي الصفحة 167 غير موجودة

**Comment by ahmedre** [comment]
> الخطأ في وضع تفسير آية ٢:٢٥٨ لآية ٢:٢٥٩ من تفسير الشيخ ناصر السعدي رحمه الله.

**Comment by ahmedre** [comment]
> تفسير السعدي للآية خمسة من سورة القمر
> أرجو التأكد من صحة الآية المذكورة في التفسير. قوله تعالى (ولو جاءتهم كل آية....)

**Comment by ahmedre** [comment]
```
اود ان اشير الى ان في تفسير السعدي في سورة الطور
في تفسير قوله تعالى:

(أَفَسِحْرٌ هَٰذَا أَمْ أَنْتُمْ لَا تُبْصِرُونَ)
[سورة الطور 15]

اظن- و الله اعلم - ان هنالك خطأ في السطر الثالث من تفسير الاية الكريمة حيث ان الناقلين جعلوا curly brackets بدلا من double quotation

  في قول الشيخ رحمه الله :

  أهذا سحر لا حقيقة له، فقد رأيتموه، أم أنتم في الدنيا لا تبصرون.
 
و استعمال curly brackets ممكن ان يشكل على القارئ فيظن انها اية لان الايات تكون مكتوبة بين curly brackets. و قد اشكل علي شخصياً.

فأود ان تراجعوا النقل

الصورة  في الاسفل توضح كلامي عن موضع الخطأ الذي اظنه .
و الصورة الثانية من موقع اخر مستعملين double qutation في كلام الشيخ.

```

**Comment by hmaher** [comment]
fixed, and bumped up to version 5

**Comment by ahmedre** [comment]
jazakAllah khairan @hmaher - pushed this to the server - barak Allah feek!

**Comment by ahmedre** [comment]
replaced this tafseer with a new version from furqan.co.
