### ISSUE TITLE
[FEATURE] have GitHub workflow to generate a build

### ISSUE THREAD

**Issue by MahmoudMabrok** [quran/quran_android#3002]
we need a way to generate a build from a commit, branch,tag instead of build locally or waiting a build to be uploaded to google play, like nightly build.

**Comment by MahmoudMabrok** [comment]
I found it existing [here](https://github.com/quran/quran_android/actions/runs/12189131304), we would add this hint at docs.

**Comment by ahmedre** [comment]
JazakumAllah khairan - we use this more to compare apks for apk size difference etc. I'd love to start using the alphas though as you suggested for people who want to follow it, maybe per commit or per day with commits or something.
