### ISSUE TITLE
شريط معلومات الصفحة وشريط الصوت لا يختفوا في وضع النافذة العائمة

### ISSUE THREAD

**Issue by KhaledKhaled0909** [quran/quran_android#3011]
لا أستطيع اخفاء الشريطين في وضع النافذة العائمة أبدا مهما حاولت ولا أستطيع القراءة لأنهم أصبحوا رماديين![Screenshot_20241209-235154_Quran.jpg](https://github.com/user-attachments/assets/63e8eeb8-ca21-4a62-92d5-f73310ffb1eb)

**Comment by ahmedre** [comment]
جزاكم الله خيراً
ما عندي وضع النافذة العائمة، لكن يحدث عندي في "سبليت سكرين" - إن شاء الله أنظر في الأمر
