### ISSUE TITLE
Tamil translation

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#304]
In soorath As Shu'araa, the mismatch of Tamil translation to the aayaath starts from aayath 126 up to aayath 206.

The translation for aayath 126 is missing. Instead it points to the translation of aayath 127. And thereafter all the aayaath upto 205 points to the translation of the next aayath.

It gets corrected at aayath 206, wherein the translation of 205 and 206 are the same.

**Comment by Somaiagabr** [comment]
Surat Ali-Emran verse16 and 26 in tamil  translation  some words missing

**Comment by ahmedre** [comment]
someone wants P. Jain ul-Abdeen - don't know if he's sunni or not, we'd have to find out.

**Comment by ahmedre** [comment]
28:77 has a typo

**Comment by ahmedre** [comment]
replaced with the quranenc.com version on 3/21/2020.
