### ISSUE TITLE
خطأ في تفسير ابن كثير / Ibn Katheer

### ISSUE THREAD

**Issue by hmaher** [quran/quran_android#306]
في سورة الأنبياء الآية ٩٧

**Comment by Somaiagabr** [comment]
ال عمران ايه ١٦٣
الخطا: علموا
الصواب : عملوا

**Comment by Somaiagabr** [comment]
للآية 19 في سورة الملك انه تم الاشارة الى الآية في سورة النحل ( أو لم يروا الطير... ) والصحيح هو (ألم يروا الى الطير....)

**Comment by ahmedre** [comment]
While I'm reading in surat 'Al-Ahzab' ayat '40' with its tafseer "Ibn Katheer" :

وكان له صلى الله عليه وسلم من خديجة أربع بنات: "ينب ورقية وأم كلثوم وفاطمة رضي الله عنهم أجمعين فمات في حياته ثلاث وتأخرت فاطمة رضي الله عنها حتى أصيبت به صلى الله عليه وسلم ثم ماتت بعده لستة أشهر

I noticed a letter "ز" is missing in front of the prophet's daughter, peace be upon them, "زينب".

**Comment by ahmedre** [comment]
https://twitter.com/zsamerz/status/707343714918785024

2 mistakes - surah jathiya verse 28 - "jul ummah" <-- ummah misspelled, and "mimma qad abraz" (maybe it's in either surah jatihya or kahf).

**Comment by ahmedre** [comment]
Tafseer Ibn Katheer for Surat Sad, Ayah 17.
It's written
ﻗﻮﻟﻪ ﺗﻌﺎﻟﻰ "ﺇﻧﺎ ﺳﺨﺮﻙ ﺍﻟﺠﺒﺎﻝ ﻣﻌﻪ ﻳﺴﺒﺤﻦ ﺑﺎﻟﻌﺸﻲ ﻭﺍﻹﺷﺮﺍﻕ"
and the correct Ayah is 
ﻗﻮﻟﻪ ﺗﻌﺎﻟﻰ "ﺇﻧﺎ ﺳﺨﺮنا اﻟﺠﺒﺎﻝ ﻣﻌﻪ ﻳﺴﺒﺤﻦ ﺑﺎﻟﻌﺸﻲ ﻭﺍﻹﺷﺮﺍﻕ"

**Comment by ahmedre** [comment]
Surah Al-Aaraaf verse 143 page 167.
Prophet Musa pbuh name had been written 'Mumis' which is a very bad word in Arabic. I've contacted you before but found no reply & the mistake is still present.

**Comment by ahmedre** [comment]
from an email:

50:38
"أو لم يروا أن الله الذي خلق السموات والأرض ولم يعي بخلقهن قادر على أن يحيى الموتى بلى إنه على كل شيء دير " قدير و ليس دير

**Comment by ahmedre** [comment]
70:38
أيطمع

**Comment by ahmedre** [comment]
> I noticed the following in the tafsir ib Karhir of ayah 7 in surat al mumtahina
> الأنصار "واذكروا نعمة الله عليكم إذ كنتم أعداء فألف بين قلوبكم فأصبحتم بنعمته إخوانا وكنتم على شقا حفرة من النار فأنقذكم منها" الآية
> It should have been شفا not شقا

**Comment by ahmedre** [comment]
في سورة النور اية 58 في تفسير ابن كثير اخر جملة كتبت 'حكيم عليم' بدل 'عليم حكيم' ارجو التصحيح

**Comment by ahmedre** [comment]
sura a7qaf verse 21 -
(نكالا لما بين يديها وما خلفها) هي الصحيحة، بينما ذكرت في التفسير (وما خلفهما)

**Comment by ahmedre** [comment]
4:174 - wa anzalna ilaykum nooran mubeena - nooran is written with a 'f'

**Comment by ahmedre** [comment]
this makes no sense...

![screenshot_2016-08-19-08-10-56](https://cloud.githubusercontent.com/assets/47771/22402952/cf0cebac-e5bd-11e6-9a6f-5dcd7e473bc2.jpg)

**Comment by ahmedre** [comment]
7:202

**Comment by ahmedre** [comment]
```
There are 3 verses that are missing in Arabic Tafseer Ibn kathir.

"فإن عثر على أنهما استحقا إثما فآخران يقومان مقامهما من الذين استحق عليهم الأوليان فيقسمان بالله لشهادتنا أحق من شهادتهما وما اعتدينا إنا إذا لمن الظالمين" Al-Maaida (5:107)

"وجعلنا الليل والنهار آيتين فمحونا آية الليل وجعلنا آية النهار مبصرة لتبتغوا فضلا من ربكم ولتعلموا عدد السنين والحساب وكل شيء فصلناه تفصيلا" Al-Israa (17:12)

"إن هذا لفي الصحف الأولى" Al-A'laa (87:18)
```

**Comment by ahmedre** [comment]
> يرجى العلم أن الهمزة ناقصة في تفسير آية 268 في سورة البقرة كمايلي : ( الشيطان يعدكم الفقر ويأمركم بالفحشا)
> يرجى إضافة الهمزة لتصبح بالفحشاء.

**Comment by ahmedre** [comment]
> خطا مطبعي عند قوله (ثم ملوا ملة أخرى ) والخطأ كتابة ياء بدل الالف المقصورة
> عند النقطة الحمراء في السطر رقم 17 من أعلى

![- -](https://cloud.githubusercontent.com/assets/47771/22457909/f0724b38-e74e-11e6-8163-ca7d0c7b2917.png)

sura yusuf verse 2

**Comment by ahmedre** [comment]
sura maryam verse 28
![screenshot_20161231-064340](https://cloud.githubusercontent.com/assets/47771/22502201/cccedb24-e820-11e6-829d-679c5c437055.jpg)

**Comment by ahmedre** [comment]
يوجد خطأ في ربط تفسير الآيات 97 حتى 100 من سورة المائدة ...

basically the tafseer doesn't match the verses

**Comment by ahmedre** [comment]
في برنامج القرآن تفسير ابن كثير الآية١٤٣ في سورة الأعراف يجب تغيير كلمة مومس بموسى

**Comment by ahmedre** [comment]
> Assalam alaykum warahmatuLlahi wabarakaatuh.there is a missing translated verse i wish you could rectify because it will lead to misunderstanding. Tafsir Al haafidh ibn Kathyr in Surah Ar Rum verse 16.there is also a repetition of translation on two different verses on the same Surah verse number 25 which is to be on verse number 26.

**Comment by ahmedre** [comment]
check sura mumtahana ayah 10 - something seems very wrong according to the email i got

**Comment by ahmedre** [comment]
ayah 122 and 123 of sura baqarah share their translation - check that this is intended.

**Comment by ahmedre** [comment]
> لاحظت خطأ مطبعي صغير في تفسير بن كثير كالتالي:

> "يا مريم اقنتي لربك واسجدي واركعي مع الراكعين" أما القنوت فهو الطاعة في خشوع كما قال تعالى "وله من ** السموات والأرض كل له قانتون" وقد قال ابن أبي حاتم: حدثنا يونس بن عبدالأعلى أخبرنا ابن وهب أخبرني عمرو بن الحارث أن دراجا أبا السمح حدثه عن أبي الهيثم عن أبي .. 

> ولعل الآية المقصودة هي :
> (وَلَهُ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ ۖ كُلٌّ لَهُ قَانِتُونَ)
> [سورة الروم 26]

**Comment by ahmedre** [comment]
4:174 - typo

**Comment by ahmedre** [comment]
page 250 -
> As it should be (البرق) not (الرق)

**Comment by ahmedre** [comment]
sura mu'minoon 33 and 34 use the same tafseer

**Comment by ahmedre** [comment]
replaced this tafseer with a new version from furqan.co. closing.
