### ISSUE TITLE
 اخطاء في تفسير الميسر / Muyassar

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#319]
صفحة ٣٨٩
كلمة "العالين" بدلا من " العالمين"

**Comment by Somaiagabr** [comment]
- لم يتم ادراج التفسير الميسر للآية الأولى من سورة الرعد 13:1.

- في التفسير الميسر لسورة الأنعام الآية 6:115 مكتوب الحليم* بظواهر الأمور و بواطنها بدلا من العليم* بظواهر الأمور و بواطنها.

**Comment by Somaiagabr** [comment]
في سورة الأنعام آية 115(وتمت كلمة ربك صدقا وعدلا لامبدل  لكلماته وهو السميع العليم)  ،مكتوب وهو الحليم بظواهر أمورهم وبواطنها.

**Comment by Somaiagabr** [comment]
للآية ١ و ٢ من سورة ابراهيم غير مدرج

**Comment by ahmedre** [comment]
يوجد خطاء املائي في التفسير الميسر سورة ال عمران

الاية الثالثة
في التفسير مكتوب ((موسى علبه السلام))
والصحيح ((عليه)) كما تعلموا

**Comment by ahmedre** [comment]
> Concerning the Tafsir (Arabic Muyassar Tafseer) of some verses on the Quran, with Surah Al-Jathiya, in [45:5] & [45:9], it's written on my: Quran for Android application as shown on the pictures: " النار instead of النهار " and " آياتا instead of آياتنا ", hopefully Allah clarify us all our mistakes and Thanks again for the efforts you put in this project, May Allah help you and accept this work from you.

**Comment by ahmedre** [comment]
> Ad-Dukhan:[44:56] ,it's written on my: Quran for Android application as shown on the pictures: " التقين instead of المتقين "

**Comment by ahmedre** [comment]
> هناك خطأ بتفسير الاية يضاهئون قول الذين كفرو من قبل بتفسير الميسر حيث ورد : لا يشابهون والصحيح يشابهون

**Comment by ahmedre** [comment]
> ادت ان انبهكم لخطئ في التفسير الميسر لكلمة
> " يستعجلونه" في الآية 58 من سورة الأنعام كتبت :
> "يستحجلونه "

**Comment by ahmedre** [comment]
check sura tawbah ayah 30

**Comment by ahmedre** [comment]
typo ayah 8 sura 60

**Comment by ahmedre** [comment]
completely replaced the muyassar database in February of 2019.
