### ISSUE TITLE
suggested reciters 

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#320]
عبد الخالق عبد الفتاح عطية " مسجد الحصري بـ ٦ اكتوبر
احمد حداد " الحصري بـ ٦ اكتوبر
محمد عبد الله المعداوي

Muhammad al Luhaidan

**Comment by ahmedre** [comment]
closing, because `lim requested_reciters(t)` as `t` approaches the day of judgement is `Qaris.GLOBAL_REGISTRY.size()` - insha'Allah we'll add whomsoever we can.
