### ISSUE TITLE
malaysian translation issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#321]
In surah [Al-Araf 7:169]
terjemahannya
"Dan kampung akhirat itu lebih (BAIK) bagi...."
BAIK dlm kurungan tersebut tidak ditulis dlm terjemahannya, harap dpt tuliskannya dlm update masa hadapan. Jazakallah :)

**Comment by asyazwan** [comment]
Another I received via email from Br. Ismail.

```
Dan jangan sekali-kali orang-orang yang bakhil dengan harta benda yang telah dikurniakan Allah kepada mereka dari kemurahanNya - menyangka bahawa keadaan bakhilnya itu baik bagi mereka. Bahkan ia adalah buruk bagi mereka. Mereka akan dikalongkan (diseksa) dengan apa yang mereka bakhilkan itu pada hari kiamat kelak. Dan bagi Allah jualah hak milik segala warisan (isi) langit dan bumi. Dan (ingatlah), Allah Maha Mengetahui dengan mendalam akan segala yang kamu kerjakan. (mukjizat) yang nyata dan dengan (korban) yang katakan, maka membunuh mereka, jika kamu orang-orang yang benar (dalam apa yang kamu dakwakan itu)?"
```
3:180

Starting from `(mukjizat) yang nyata` on the last line until the end should be removed. I don't know how it came about, but it's in other Malay translations as well such as from quran.com. It doesn't make sense and does not align with other languages such as the English or Indonesia counterparts.

**Comment by asyazwan** [comment]
I edited my previous post with more details but it didn't bump. So... bump.

**Comment by ahmedre** [comment]
another one - 

```
وَجَاءَتْ سَكْرَةُ الْمَوْتِ بِالْحَقِّ ۖ ذَٰلِكَ مَا كُنْتَ مِنْهُ تَحِيدُ

"Dan datanglah "Sakaratulmuat" membawa kebenaran. Inilah perkara yang engkau selalu mengelak diri daripadanya!"

Correct word is "Sakaratulmaut"

Thanks a lot for your attention.
```

in 50:20

**Comment by ahmedre** [comment]
@asyazwan sorry i completely dropped off on this - what do i need to do - just apply the fixes from your 6/28 post? can you also give me one for this - if so i will insha'Allah release a fixed database within a day of when you give me this insha'Allah.

**Comment by ahmedre** [comment]
another one:

> Recently i found some word missing in the Malay translation such as in [3:173]
> I also found some words that might be misplaced in the translation such as at [3:180]

**Comment by ahmedre** [comment]
> Al Baqoroh 2 : 254

> ولا خلة
> "tidak ada persahabatan"

> "Hai orang-orang yang beriman, belanjakanlah (di jalan Allah) sebagian dari rezeki yang telah Kami berikan kepadamu sebelum datang hari yang pada hari itu tidak ada lagi jual beli "......" dan tidak ada lagi syafa'at. Dan orang-orang kafir itulah orang-orang yang zalim."

**Comment by ahmedre** [comment]
![screenshot_20170130-125302](https://cloud.githubusercontent.com/assets/47771/22412950/4a180520-e668-11e6-911e-087da9fe6389.png)

Typo:
1 menyebut-nyebut
2 mengawasi

**Comment by asyazwan** [comment]
Yes you can use my 6/28 fixes. I will take a look at the rest and update.

**Comment by ahmedre** [comment]
awesome, jazakAllah khairan - just keep in mind there might be a few more (i am going through our remaining backlog of emails and recording anything that i find) - i'll keep adding them here insha'Allah.

**Comment by ahmedre** [comment]
> Sepertinya Ada Penulisan yang keliru diterjemahan
> Malaikat-mmalaikat ?

![screenshot_2016-11-23-12-21-23-328_com quran labs androidquran](https://cloud.githubusercontent.com/assets/47771/22415904/d24bfdcc-e67f-11e6-9430-a9ebdfca539c.png)

**Comment by ahmedre** [comment]
> Please check translation on: Annisa, 92 using bahasa Indonesia.

> There is a missing for 1 sentence.

> "Maka jika ia [yang terbunuh] dari kaum yang merupakan musuh kalian dan ia seorang mukmin, maka hendaklah ia [yg membunuh] membebaskan budak mukmin".

> Please insert it!

> Please check the legalised translation, from Depag RI

**Comment by ahmedre** [comment]
> Pada saat ditampilkan terjemahan, penulisan ayat tidak lengkap, contoh qs 60:1
> Mohon untuk dicek kembali dan dilakukan perbaikan

**Comment by ahmedre** [comment]
> Didalam surah al furqan ayat 30 tercantum "sesuatu yang tidak diacuhkan", seharusnya kata mahjuro artinya "  sesuatu yang diacuhkan"

**Comment by ahmedre** [comment]
@asyazwan done with all the emails - can you help me out with these? also, where are you getting the corrections from for these? jazakAllah khairan

**Comment by ahmedre** [comment]
> In suratul Isra' first ayah. You said the meaning of البصير was "mengetahui" in Malay. But البصير mean  "Melihat" .

**Comment by ahmedre** [comment]
> "...dan (sejenis lagi) bintang-bintang ternak..." - binatang

sura An'am 138

**Comment by ahmedre** [comment]
cc @khalid-hussain can you help me out with this? i wanted to get these fixes into Quran and i think @asyazwan is busy - jazakAllah khairan

**Comment by asyazwan** [comment]
For some reason I stopped getting emails about this, sorry for being a year late.

## [Report #1](https://github.com/quran/quran_android/issues/321#issuecomment-275828925)

It's not 50:20, it's 50:19 but the error is correct.

### Problem:

> "Dan datanglah **"Sakaratulmuat"** membawa kebenaran. Inilah perkara yang engkau selalu mengelak diri daripadanya!"

### Should be:

> "Dan datanglah **"Sakaratulmaut"** membawa kebenaran. Inilah perkara yang engkau selalu mengelak diri daripadanya!"

### Reason:

Typo.

### Fix (`quran.ms.db`):

```sql
UPDATE `verses`
SET `text` = 'Dan (apabila sampai ajal seseorang) datanglah "Sakaratulmaut" membawa kebenaran (yang telah dijanjikan, serta dikatakan kepada yang mengingkarinya sebelum itu): "Inilah perkara yang engkau selalu mengelak diri daripadanya!"'
WHERE `sura` = 50 AND `ayah` = 19;
```

## [Report #2](https://github.com/quran/quran_android/issues/321#issuecomment-275834352)

I did not find anything weird for 3:173. Not enough info to go on. As for 3:180 [should already be fixed](https://github.com/quran/quran_android/issues/321#issuecomment-229051416), right @ahmedre ? I just checked my copy and the error is still there. Did you apply my patch? This would be pretty important to fix as the meaning changed a lot.

## [Report #3](https://github.com/quran/quran_android/issues/321#issuecomment-275835477)

I'm not well-informed to change this from "friends" to "friendship". Other sources like [Malaysia's government](http://ii.islam.gov.my/quran/terjemahan_ayat_new.php?page=26&surahrumi=Al%20Baqarah) also does not use what the reporter suggested. So I'm leaving this.

## [Report #4](https://github.com/quran/quran_android/issues/321#issuecomment-275981959)

### Problem:

> Wahai sekalian manusia! Bertaqwalah kepada Tuhan kamu yang telah menjadikan kamu (bermula) dari diri yang satu (Adam), dan yang menjadikan daripada (Adam) itu pasangannya (isterinya - Hawa), dan juga yang membiakkan dari keduanya - zuriat keturunan - lelaki dan perempuan yang ramai. Dan bertaqwalah kepada Allah yang kamu selalu meminta dengan **menyebut-yebut** namaNya, serta peliharalah hubungan (silaturrahim) kaum kerabat; kerana sesungguhnya Allah sentiasa memerhati (**mengawas**) kamu.

### Should be:

> Wahai sekalian manusia! Bertaqwalah kepada Tuhan kamu yang telah menjadikan kamu (bermula) dari diri yang satu (Adam), dan yang menjadikan daripada (Adam) itu pasangannya (isterinya - Hawa), dan juga yang membiakkan dari keduanya - zuriat keturunan - lelaki dan perempuan yang ramai. Dan bertaqwalah kepada Allah yang kamu selalu meminta dengan **menyebut-nyebut** namaNya, serta peliharalah hubungan (silaturrahim) kaum kerabat; kerana sesungguhnya Allah sentiasa memerhati (**mengawasi**) kamu.

### Reason:

Simple typos.

### Fix: (`quran.ms.db`):

```sql
UPDATE `verses`
SET `text` = "Wahai sekalian manusia! Bertaqwalah kepada Tuhan kamu yang telah menjadikan kamu (bermula) dari diri yang satu (Adam), dan yang menjadikan daripada (Adam) itu pasangannya (isterinya - Hawa), dan juga yang membiakkan dari keduanya - zuriat keturunan - lelaki dan perempuan yang ramai. Dan bertaqwalah kepada Allah yang kamu selalu meminta dengan menyebut-nyebut namaNya, serta peliharalah hubungan (silaturrahim) kaum kerabat; kerana sesungguhnya Allah sentiasa memerhati (mengawasi) kamu."
WHERE `sura` = 4 AND `ayah` = 1;
```

## [Report #5](https://github.com/quran/quran_android/issues/321#issuecomment-276000305)

This is not Malaysia but Indonesia. Regardless, I checked and somebody already fixed it.

## [Report #6](https://github.com/quran/quran_android/issues/321#issuecomment-276004061)

Also Indonesia, also seems to be fixed.

## [Report #7](https://github.com/quran/quran_android/issues/321#issuecomment-276244731)

Seems to be UI glitch/bug report, not translation per se.

## [Report #8](https://github.com/quran/quran_android/issues/321#issuecomment-276621986)

I think this one is also Indonesia. Regardless, the error is not anywhere, so it's probably fixed.

## [Report #9](https://github.com/quran/quran_android/issues/321#issuecomment-280247510)

### Problem:

> Maha Suci Allah yang telah menjalankan hambaNya (Muhammad) pada malam hari dari Masjid Al-Haraam (di Makkah) ke Masjid Al-Aqsa (di Palestin), yang Kami berkati sekelilingnya, untuk memperlihatkan kepadanya tanda-tanda (kekuasaan dan kebesaran) Kami. Sesungguhnya Allah jualah yang Maha Mendengar, lagi **Maha Mengetahui**.

### Should be:

> Maha Suci Allah yang telah menjalankan hambaNya (Muhammad) pada malam hari dari Masjid Al-Haraam (di Makkah) ke Masjid Al-Aqsa (di Palestin), yang Kami berkati sekelilingnya, untuk memperlihatkan kepadanya tanda-tanda (kekuasaan dan kebesaran) Kami. Sesungguhnya Allah jualah yang Maha Mendengar, lagi **Maha Melihat**.

### Reason:

Wrong translation of `البصير `, using the meaning of "All-Knowing" instead of the correct one: "All-Seeing".

### Fix (`quran.ms.db`):

```sql
UPDATE `verses`
SET `text` = "Maha Suci Allah yang telah menjalankan hambaNya (Muhammad) pada malam hari dari Masjid Al-Haraam (di Makkah) ke Masjid Al-Aqsa (di Palestin), yang Kami berkati sekelilingnya, untuk memperlihatkan kepadanya tanda-tanda (kekuasaan dan kebesaran) Kami. Sesungguhnya Allah jualah yang Maha Mendengar, lagi Maha Melihat."
WHERE `sura` = 17 AND `ayah` = 1;
```

## [Report #10](https://github.com/quran/quran_android/issues/321#issuecomment-285984625)

### Problem:

> Dan mereka berkata lagi: "Ini adalah binatang-binatang ternak dan tanaman-tanaman yang dilarang, yang tidak boleh seorang pun memakannya kecuali sesiapa yang kami kehendaki", - menurut anggapan mereka; dan (sejenis lagi) binatang-binatang ternak yang dilarang menunggangnya; dan (sejenis lagi) **bintang-bintang** ternak yang tidak mereka sebutkan nama Allah ketika menyembelihnya; (semuanya itu mereka lakukan dengan) berdusta terhadap Allah. Allah akan membalas mereka disebabkan apa yang mereka telah ada-adakan itu.

### Should be:

> Dan mereka berkata lagi: "Ini adalah binatang-binatang ternak dan tanaman-tanaman yang dilarang, yang tidak boleh seorang pun memakannya kecuali sesiapa yang kami kehendaki", - menurut anggapan mereka; dan (sejenis lagi) **binatang-binatang** ternak yang dilarang menunggangnya; dan (sejenis lagi) binatang-binatang ternak yang tidak mereka sebutkan nama Allah ketika menyembelihnya; (semuanya itu mereka lakukan dengan) berdusta terhadap Allah. Allah akan membalas mereka disebabkan apa yang mereka telah ada-adakan itu.

### Reason:

Typo. "Bintang" means star, while "binatang" means animal.

### Fix (`quran.ms.db`):

```sql
UPDATE `verses`
SET `text` = 'Dan mereka berkata lagi: "Ini adalah binatang-binatang ternak dan tanaman-tanaman yang dilarang, yang tidak boleh seorang pun memakannya kecuali sesiapa yang kami kehendaki", - menurut anggapan mereka; dan (sejenis lagi) binatang-binatang ternak yang dilarang menunggangnya; dan (sejenis lagi) binatang-binatang ternak yang tidak mereka sebutkan nama Allah ketika menyembelihnya; (semuanya itu mereka lakukan dengan) berdusta terhadap Allah. Allah akan membalas mereka disebabkan apa yang mereka telah ada-adakan itu.'
WHERE `sura` = 6 AND `ayah` = 138;
```

cc. @ahmedre

**Comment by asyazwan** [comment]
@ahmedre any updates?

**Comment by ahmedre** [comment]
76:30 or 31 might have an error according to an email

**Comment by ahmedre** [comment]
@asyazwan really sorry - in sha' Allah will do this soon

**Comment by ahmedre** [comment]
check sura mursalat ayah 77

> Tertulis :  malaikat-malaikan yg diutus
> Mestinya :  malaikat-malaikat yang diutus

**Comment by ahmedre** [comment]
> (Abdullah Muhammad Basmeih)
> (Setelah membaca surat itu), berkatalah raja perempuan negeri Saba': "Wahai ketua-ketua kamu! Sesungguhnya telah disampaikan kepadaku sepucuk surat yang mulia.

> -Sura An-Naml, Ayah 29

says the correct word should be kaum

**Comment by ahmedre** [comment]
16:120
takat => takut?

**Comment by ahmedre** [comment]
5:81 first word

**Comment by ahmedre** [comment]
review anfal 67

**Comment by ahmedre** [comment]
check sura kahf 13 and 14

**Comment by ahmedre** [comment]
check 89:9

**Comment by ahmedre** [comment]
> (Abdullah Muhammad Basmeih)
> Benda-benda yang kamu sembah itu tidak lain hanyalah nama-nama yang kamu dan datuk nenek kamu menamakannya. **Allah sekali-kali menurunkan sebarang bukti** yang membenarkannya. Mereka yang berbuat demikian, tidak menurut melainkan sangkaan-sangkaan dan apa yang diingini oleh hawa nafsunya. Padahal demi sesungguhnya telah datang kepada mereka petunjuk dari Tuhan mereka.

> -Sura An-Najm, Ayah 23

> The bold should have the word "tidak" in the sentence

> It should be

> Allah sekali-kali "tidak" menurunkan sebarang bukti

**Comment by ahmedre** [comment]
> Actually, I want to highlight an error in translation in Malay language 3:180. I will attach the screenshot. The errors is on last 4 lines translation.

**Comment by asyazwan** [comment]
> @asyazwan can you check quran.com and see if web version has any of these issues?

@naveed-ahmad 
Sorry for the delay. I have checked for Malaysian issues addressed in [this post](https://github.com/quran/quran_android/issues/321#issuecomment-396816543) and it has all the same issues.

>  also, where are you getting the corrections from for these?

@ahmedre normally they're no-brainer typos. Anything more I would cross-check with tanzil.net (like I said [here](https://github.com/quran/quran_android/issues/321#issuecomment-47629914)) and quran.com but AFAIR they also have the same issues (probably db from common source?). Anything more than that I would cross-check English translations (Shahih International).

**Comment by asyazwan** [comment]
@ahmedre as for the newer reports you posted:

> 76:30 or 31 might have an error according to an email

Need more info. Seem correct to me, unless it's a really subtle typo I'm missing.

---

> check 53:23

and

> > (Abdullah Muhammad Basmeih)
> > Benda-benda yang kamu sembah itu tidak lain hanyalah nama-nama yang kamu dan datuk nenek kamu menamakannya. **Allah sekali-kali menurunkan sebarang bukti** yang membenarkannya. Mereka yang berbuat demikian, tidak menurut melainkan sangkaan-sangkaan dan apa yang diingini oleh hawa nafsunya. Padahal demi sesungguhnya telah datang kepada mereka petunjuk dari Tuhan mereka.
> 
> > -Sura An-Najm, Ayah 23
> 
> > The bold should have the word "tidak" in the sentence
> 
> > It should be
> 
> > Allah sekali-kali "tidak" menurunkan sebarang bukti

Correct. `sekali-kali` should be `tidak sekali-kali`.

---

> check sura mursalat ayah 77
> 
> > Tertulis :  malaikat-malaikan yg diutus
> > Mestinya :  malaikat-malaikat yang diutus

This is referring to Indonesian I'm sure. And it's already fixed there.

---

> > (Abdullah Muhammad Basmeih)
> > (Setelah membaca surat itu), berkatalah raja perempuan negeri Saba': "Wahai ketua-ketua kamu! Sesungguhnya telah disampaikan kepadaku sepucuk surat yang mulia.
> 
> > -Sura An-Naml, Ayah 29
> 
> says the correct word should be kaum

Correct. `kamu!` should be `kaum!`.

---


> typo 41:43
> 
> > The true spelling is TERDAHULU.

Correct. `terdahuhu` should be `terdahulu`.

---

> 16:120
> takat => takut?

Nope, that would be changing the meaning. It's just an uncommon word to be used in this context.

---

> 5:81 first word

Correct. `Sekirany` should be `Sekiranya`.

---

> review anfal 67

Can't review; not a scholar.

---

> sura nahl ayah 112

Need more info.

---

> check 51:49
> 
> ![20170722_072824_resized](https://user-images.githubusercontent.com/47771/49332085-20f12280-f5c0-11e8-89b7-f83857ba7853.jpg)

This is Indonesian.

---

> check sura kahf 13 and 14

Need more info.

---

> check 89:9

Correct *but* for Indonesian, `¤amud` should be `Tsamud`. [Tanzil](http://tanzil.net/#trans/id.indonesian/89:9) got it right. [Quran.com](https://quran.com/89/9-19) is also wrong.

---

> > Actually, I want to highlight an error in translation in Malay language 3:180. I will attach the screenshot. The errors is on last 4 lines translation.

Already addressed in my earlier [fixes](https://github.com/quran/quran_android/issues/321#issuecomment-229051416).

**Comment by ahmedre** [comment]
jazakAllah khairan @asyazwan - in sha' Allah i'll get to these before Ramadan. do you think the tanzil version is better than ours (if it's the same translator and theirs is more accurate, we can just replace with Tanzil - what do you think?)

> I wish to report mistyped Malay Translation in 3:180. I think the part of the translation from 3:181 accidentally mix up into the translation of 3:180.

**Comment by ahmedre** [comment]
one more:
> I wish to report mistyped Malay Translation in 3:180. I think the part of the translation from 3:181 accidentally mix up into the translation of 3:180.

**Comment by ahmedre** [comment]
btw @asyazwan - is this right? if so, can you PR it?

> Assalamu'alaikum warahmatullahi wabarakaatuhu, ingin koreksi Kesalahan penulisan huruf, surah Al Ahqaf, (bukit-bukir pasir), yang benar (bukit-bukit pasir), Jazaakumullahu Khairan, Wassalamu'alaikum warahmatullahi wabarakaatuhu

**Comment by asyazwan** [comment]
> jazakAllah khairan @asyazwan - in sha' Allah i'll get to these before Ramadan. do you think the tanzil version is better than ours (if it's the same translator and theirs is more accurate, we can just replace with Tanzil - what do you think?)

For Indonesia, it seems Tanzil fixed a lot of the mistakes. So it's probably worth it for Indonesia.

For Malaysia, no, as they contain the same mistakes. Chances are, our DB is more correct at this point.

**Comment by asyazwan** [comment]
> one more:
> 
> > I wish to report mistyped Malay Translation in 3:180. I think the part of the translation from 3:181 accidentally mix up into the translation of 3:180.

This has been reported at least 4 times I think and I've addressed the fix above.


> btw @asyazwan - is this right? if so, can you PR it?
> 
> > Assalamu'alaikum warahmatullahi wabarakaatuhu, ingin koreksi Kesalahan penulisan huruf, surah Al Ahqaf, (bukit-bukir pasir), yang benar (bukit-bukit pasir), Jazaakumullahu Khairan, Wassalamu'alaikum warahmatullahi wabarakaatuhu

This is Indonesia, but sure, I will PR it and add Malaysia translations as well insyaAllah.

**Comment by ahmedre** [comment]
jazakAllah khairan @asyazwan and really sorry this took forever :( updated now with all your sqlite fixes from long ago, plus all the other answers you gave me for the more recent questions. may Allah reward you greatly and my apologies for letting this sit all this time :(

**Comment by asyazwan** [comment]
There's another report I got via email. Malay tafseer of Surah Yusuf 12:10, `pergi` (go) should be `perigi` (well).
