### ISSUE TITLE
indonesian translation issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#322]
Salaam alayk.. just to inform that there is a mistake in surah 45:23 indonesian translation. Pls double check them..

45:23

أَفَرَأَيْتَ مَنِ اتَّخَذَ إِلَٰهَهُ هَوَاهُ وَأَضَلَّهُ اللَّهُ عَلَىٰ عِلْمٍ وَخَتَمَ عَلَىٰ سَمْعِهِ وَقَلْبِهِ وَجَعَلَ عَلَىٰ بَصَرِهِ غِشَاوَةً فَمَنْ يَهْدِيهِ مِنْ بَعْدِ اللَّهِ ۚ أَفَلَا تَذَكَّرُونَ

Maka pernahkah kamu melihat orang yang menjadikan hawa nafsunya sebagai tuhannya dan Allah membiarkannya ............ berdasarkan ilmu-Nya dan Allah telah mengunci mati pendengaran dan hatinya dan meletakkan tutupan atas penglihatannya? Maka siapakah yang akan memberinya petunjuk sesudah Allah (membiarkannya sesat). Maka mengapa kamu tidak mengambil pelajaran?

**Comment by Somaiagabr** [comment]
Surah 25 ayah 24.
Expected:
Penghuni-penghuni surga pada hari itu paling...
Current state:
Penghuni-penghuni surga pada hari itu palig...

**Comment by Somaiagabr** [comment]
An-Nisa 108. 

On your translations said " mereka bersembunyi dari manusia, tetapi mereka tidak bersembunyi dari Allah, padahal Allah beserta mereka, ketika pada suatu malam mereka menetapkan keputusan rahasia yang Allah tidak redlai...." its suppose to be " Mereka dapat bersembunyi dari manusia, tetapi mereka tidak dapat bersembunyi dari Allah, karena Allah beserta mereka, ketika pada suatu malam mereka menetapkan keputusan rahasia yang tidak diridai-Nya..."


On your translations said "they hide from humans, but they can not hide from Allah, and Allah is with them when on one night they hold a secret that Allah does not redlai .... "its suppose to be" they can hide from humans, but they can not hide from God, because God is with them when by night they hold secret no pleasing his ... "

**Comment by Somaiagabr** [comment]
Al-Baqara 2:73 on indonesian translation. "dam" memperlihatkan padamu tanda-tanda kekuasaan-Nya agar kamu mengerti. That is not "dam" but dan.

**Comment by Somaiagabr** [comment]
Al-Baqara 2:122 on indonesian translation. Hai Bani Israil, ingatlah akan nikmat-Ku yang telah Ku-anugerahkan kepadamu dan Aku telah "melabihkan" kamu atas segala umat. That is not "melabihkan" but melebihkan.

**Comment by Somaiagabr** [comment]
urah ash-shaffat, ayah 28.

Pengikut-pengikut mereka berkata (kepada pemimpin-pemimpin mereka): "Sesungguhnya kamulah yang datang kepada kami dan kanan.

The correct one should be :

Pengikut-pengikut mereka berkata (kepada pemimpin-pemimpin mereka): "Sesungguhnya kamulah yang datang kepada kami dari kanan.

**Comment by Somaiagabr** [comment]
In surah Al - WAQI'AH verse 75, :

(فَلَا أُقْسِمُ بِمَوَاقِعِ النُّجُومِ)
your translation is:

"Maka Aku bersumpah dengan masa turunnya bagian-bagian Al-Quran."

The correct is:

"maka Aku bersumpah dengan tempat beredarnya bintang-bintang".

**Comment by ahmedre** [comment]
Dalam terjemah bahasa Indonesia, qs Allah Maidah ayat 119 dalam aplikasi A quran tertulis :
Allah berfirman: "Ini adalah suatu hari yang bermanfaat bagi orang-orang yang benar kebenaran mereka. Bagi mereka surga yang dibawahnya mengalir sungai-sungai; mereka kekal di dalamnya selama-lamanya; Allah ridha terhadap-Nya. Itulah keberuntungan yang paling besar".

Seharusnya :
Allah berfirman: "Ini adalah suatu hari yang bermanfaat bagi orang-orang yang benar kebenaran mereka. Bagi mereka surga yang dibawahnya mengalir sungai-sungai; mereka kekal di dalamnya selama-lamanya; Allah ridha kepada mereka dan mereka pun ridha kepada-Nya. Itulah keberuntungan yang paling besar".

**Comment by ahmedre** [comment]
@habibr this has been sitting here for a while, i'd love to fix these - can you get a copy of the mushaf for the same translator and let's fix our copy to match a correct book copy and update? would love if you can help with this (especially since i don't speak Indonesian).

**Comment by ahmedre** [comment]
another one -
> Brother, I found that Indonesian translation for Surah Baqarah (2) ayah 59 is missing a word that should be there. I also checked http://quran.com/2/59 and see its Indonesian translation, it also misses a word. Do you know where should I report this matter?

**Comment by ahmedre** [comment]
> Mohon di koreksi surat al mu'minuun ayat 51

Google Translate:
> We are in a correction letter al mu'minuun paragraph 51 

not sure what he means, but can we check this?

**Comment by ahmedre** [comment]
> Uncomplete translate,
> please check QS 18:80

**Comment by habibr** [comment]
Insha-allah I will re-check these with printed mushhaf.

**Comment by habibr** [comment]
@ahmedre Are all these, the reported issues, have not been corrected?

It is just in time that we now have the "official" indonesian translation of the Qur'an. The Indonesia Ministry of Religious Affair just published an online (and android) versions of the Qur'an. I can check against that.

Where should I correct these translation mistakes?

**Comment by ahmedre** [comment]
@habibr none of these have been corrected yet as far as i remember - it's a sqlite database, so if you can update that directly, would be awesome - if not, if you tell me the full ayah i can update them.

the translation we're using says "Bahasa Indonesia" - i am not sure what that is. if the official one is online, we can actually replace ours with that one if you can find it somewhere?

**Comment by ahmedre** [comment]
> I like to inform you that there's a mistake in translation to Bahasa. In surah Arrahman ayah 6, it written "Dan tumbuh tumbuhan", in English it means "and plants" it supposed to be "Dan bintang-bintang", which in English "and stars"

**Comment by habibr** [comment]
It seems that the current translation has quite a number of errors, some are serious like the last one you quoted. I agree in replacing ours with the "official" version. I will find out how to get the whole translation from the ministry.

Okay, I have downloaded the sqlite database. Do you have suggestions for a database editing program in Ubuntu?

**Comment by ozbek** [comment]
> Do you have suggestions for a database editing program in Ubuntu?

Maybe [SQLite Manage](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/) for Firefox?

**Comment by habibr** [comment]
Thanks, I will try it.

**Comment by habibr** [comment]
I have finished checking the problematic translations mentioned in this issue. I put the database record [here](https://github.com/habibr/quran_database/tree/master/db).

**Comment by ahmedre** [comment]
jazakAllah khairan - I suspect there will be a few more (am going through the backlog of emails, still some left). After that's done can push this insha'Allah (in the meanwhile will add any new ones we receive to this ticket).

**Comment by ahmedre** [comment]
> There's a typo in translation to Bahasa Indonesia, surah 16 ayah 67
> minimuman => minuman
![screenshot_2016-09-15-05-12-16-682_com quran labs androidquran](https://cloud.githubusercontent.com/assets/47771/22413246/1f679a54-e66b-11e6-9d10-ed3246287546.png)

**Comment by ahmedre** [comment]
I found this translation for Ar-Rum 41:
ظَهَرَ الْفَسَادُ فِي الْبَرِّ وَالْبَحْرِ بِمَا كَسَبَتْ أَيْدِي النَّاسِ لِيُذِيقَهُمْ بَعْضَ الَّذِي عَمِلُوا لَعَلَّهُمْ يَرْجِعُونَ

Telah nampak kerusakan di darat dan di laut disebabkan karena perbuatan tangan manusi, supay Allah merasakan kepada mereka sebahagian dari (akibat) perbuatan mereka, agar mereka kembali (ke jalan yang benar).

The correct one should be :
Telah nampak kerusakan di darat dan di laut disebabkan karena perbuatan tangan manusia, supaya Allah merasakan kepada mereka sebahagian dari (akibat) perbuatan mereka, agar mereka kembali (ke jalan yang benar).

**Comment by ahmedre** [comment]
not sure what this means:
> Surat 42 - 43 eror muhon bantuannya

**Comment by ahmedre** [comment]
> There must be "kemudian dia termasuk orang-orang yang beriman, dan saling berpesan untuk bersabar dan saling berpesan untuk berkasih sayang" 

![screenshot_2016-11-23-07-47-37](https://cloud.githubusercontent.com/assets/47771/22415940/2c21ac8e-e680-11e6-9329-a84ec134f65e.png)

**Comment by habibr** [comment]
Done, corrected.

**Comment by ahmedre** [comment]
> I see in the surah Al-Maidah Ayah 51 has unrevisied version for the Indonesian translation. The translation use revision before year 2002 for the section 'pemimpin-pemimpin(mu)'. Could you please change to the latest revision 'teman dekat(mu)'? Because the revision after year 2002 use that words. Which it has the meaning of 'allies'.

> Please see the source:
> https://seword.com/politik/ahok-dan-ayat-al-maidah-51-hasil-revisi-kementrian-agama/

**Comment by ahmedre** [comment]
jazakAllah khairan - almost done with the email backlogs, so hopefully in the next few days insha'Allah will take all your changes and push them - may Allah reward you greatly! btw, are you correcting from the equivalent book version of this translation?

**Comment by habibr** [comment]
The suratul Maidah verse 51 was receiving a great attention lately in indonesia because some political and religious cases in our country. The commenter talked about the word "_awliya_" in arabic. The current translation is **leaders** or **guardians** whereas in the latest official translation it is "**close friends**" or "**allies**". There were some arguments about the word choosing.

Regarding the indonesian translation, I have compared the contents of a few other online or android based Qur'an apps and found out that they use the same version as ours. So, they contain the same mistakes presumably because they use the same source of indonesian translation.

The Indonesian Ministry of Religious Affair has produced different versions of indonesian translation. I assume that the online version is the latest one. I am correcting against that version.

I think we should be using the official translation. That way, we have some stronger ground and responsibility for our Quran app.

**Comment by habibr** [comment]
Btw, what does the word أَوْلِيَاءُ means?

**Comment by ahmedre** [comment]
i always understood the English as allies - most of the English translations say this too, though some say "friends" and some say "patrons."

i think we should use theirs if we can - can you link the website, do you think we can just scrape it and use it?

**Comment by habibr** [comment]
I am contacting the contact email provided there, but have not got answers yet. It is live [here](http://quran.kemenag.go.id).

In the mean time I am collecting the translation data from the website. They actually encourage indonesian muslim to use the "official" quran version from the government. They even provided the fonts for those who want to print the whole quran. But, I have not found the direct link to the indonesian translation data.

I think it is okay to scrape it and then credit and acknowledge the source. When they replied, I can talk more about our intention to use their 'official' translation.

**Comment by ahmedre** [comment]
awesome, sounds like a great plan masha'Allah! i am almost done with the email backlog - i'll update anything else i see and can start working to replace the current sqlite with the document you prepared insha'Allah.

**Comment by ahmedre** [comment]
> I found the mistake in Q.S. 6:115 on Tarjamah Bahasa Indonesia (only one letter in one word).

**Comment by ahmedre** [comment]
@habibr i am done - let's figure out if we can scrape the government's translation and replace this one if it's indeed the official government one? do you need help?

**Comment by habibr** [comment]
@ahmedre ok, I have just corrected that and updated the db.

I have also finished getting the official translations. I spotted one mistake in the official one and now am figuring out how to compare the new with the old translations. I will identify those translations that are far in differences and make sure they are still within the correct meaning. I will not read all the translations one by one though. I think the government has done that job.

I think we can keep the old translation in place as an option but later change the default for indonesian translation to the official one. Or we can indicate the version/year of the two indonesian translations available. That way, people can cross reference and compare if they found some differences in translations.

I will update you when I am done.

**Comment by ahmedre** [comment]
sounds good - are the translations different (i.e. are both "the official translations," but one was old and one is new?) - if so, let's just keep one entry - if they're different translations altogether, it makes sense as two translations and people can choose which to download.

**Comment by habibr** [comment]
I do not know about the old one. By "the old one" I refer to the current indonesian translation used in our app. Some other apps refer that as also the "official" translation from the Ministry of Religious Affair but from some years ago. Maybe you know better the year.

Reading from the official indonesian quran website, the new translations have got major revisions in 2002 and again in 2016 just before the launch of the website and the app.

So, I think they are from the same official translation.

**Comment by ahmedre** [comment]
ok then in that case, let's go with the current official one as a replacement for the previous one then.

**Comment by habibr** [comment]
Agree...

**Comment by habibr** [comment]
@ahmedre the new indonesian translation is ready [here](https://github.com/habibr/quran_database/tree/master/db). Please re-check it. I have checked the number of ayahs in each surah and some string similarity checks against the old.

**Comment by ahmedre** [comment]
@habibr jazakAllah khairan - a few minor questions before i upload this:

1. how did you generate the database (so i can spot check against it)
2. are the spelling changes you made reflective of how things are spelled in Indonesian? if not, i'd leave them (ex rida, salat, saleh, zalim, zikir, Talut are very close to their Arabic counterparts - Samud is similar but we'd probably spell it as Thamud.
3. for the notes - just want to make sure it's clear to people that these are "notes we added" as opposed to part of the translation - the Android app for the official Indonesian translation has 1 star ratings because of sura Maida' and the "awliya'" tafseer, so i think adding a footnote in this case is good - not sure about the other one though since i don't have any context on it.

**Comment by habibr** [comment]
1. I used the search facility of the "Qur'an Kemenag" to generate the database. It allows you to directly search for a specific ayah by entering the surah number and ayah in the search input, such as 5:51. This  in turn can be queried using GET method to this [URL](http://devquran.majorbee.com/index.php/result/5/51). As you can see, you can just replace the corresponding surah and ayah numbers to get the ayah.
2. Yes. The changes that I made basically to differentiate different arabic consonants that have no corresponding latin letter. For example, the letters ص, س, and ش could be represented as only S but it is better to differentiate them by: S for the 'sin', Sh for the 'sad' and Sy for the 'shin'. That kind of differentiation or _transliteration_ is common and widely used in our indonesian language. Most of them were also used in the old version of the translation.
Just like your example in english, we usually represent Th in Thamud as Ts and not S.
I do not know why the official version chooses to use the simplified transliteration for such common words that have been assimilated into our language for long time and are still used by many.
With my suggested changes, indonesian readers would not mistakenly take those words as different words with different meanings.
3. I think a footnote would be good. For the second note, you can also compare several english translations available in quran.com for that particular ayah. While most of them translate 'wan najmu' as 'and herbs/shrubs', there is one that make note of other meaning as "stars". It also [address this comment ](https://github.com/quran/quran_android/issues/322#issuecomment-218296080) about the ayah.

**Comment by ahmedre** [comment]
jazakAllah khairan - i wrote a script to verify myself, and did a really really quick glance through differences between what i scraped off their website (well, what i could scrape, since now, the site seems to be suffering with 501 errors) and your db - verified that the first 28 suras (a little over 20 juzs) look fine.

question - (take it with a grain of salt, i don't speak Indonesian) - are these among some of the other replacements you did?

- "menzalimi" with "menzhalimi"
- "salatlah" with "shalatlah"
- "dizalimi" with "dizhalimi"
- "keridaan" with "keridhaan"
- "kezaliman" with "kezhaliman"
- "ridai" with "ridhai"
- "berzikir" with "berdzikir"
- "Lut" with "Luth"
- "diridai" with "diridhai"

jazakAllah khairan - will let you know when it's uploaded insha'Allah

**Comment by habibr** [comment]
I think my replacements should cover the example you presented. In our language, we have a "base word" that can be turned into "derivative words" when we want to form verbs, adverbs, adjective or nouns. For example, **zhalim** is the base word for men**zhalim**i. We call the _**men**_ in front of _zhalim_ as prefix and **_i_** behind it as suffix. So, I searched for those "base words" to be replaced that should also cover the derivatives.

But, thank you for rising up this issue. I should re-check again, making sure there are no other base words that shared the words that I replaced (although as far as I know, there are none).

**Comment by habibr** [comment]
@ahmedre I have re-checked the changes and there should be no "over-correction" to other words with different meanings.

I also found several more inconsistencies and mistakes and corrected the database.

**Comment by ahmedre** [comment]
sorry for the delay - updated  - please update within the app and let me know - you'll have to remove, restart the app, then re-download

**Comment by habibr** [comment]
Jazakallahu khairan katsir to you too. :)
