### ISSUE TITLE
farsi translation issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#323]
Dears. In farsi translation of sura Al-
Qaria (101:5) it reads (...گوها) where it should be (   ..کو ها).This is a seriuos change in meaning snd needs to be fixed. 
Thanks

**Comment by amirhakh** [comment]
سلام

can add translation & audio from below links?
http://tanzil.net/trans/
http://zekr.org/resources.html

**Comment by Somaiagabr** [comment]
ترجمه فارسی 64:17   غلط. شکور :  بردبار   لا بدبار.

**Comment by ahmedre** [comment]
there are a bunch of &quot; that need to be fixed

**Comment by ahmedre** [comment]
another report (though not sure what's wrong with it)

![screenshot_2017-02-28-01-02-47](https://cloud.githubusercontent.com/assets/47771/23392579/8f13e5f6-fd31-11e6-82b9-13917fb8aaa5.png)

**Comment by amirhakh** [comment]
Salam
I told that multiple translator, translate Quran in Farsi (Persian) and other language. I find that resource in simple zip and text value format that have multiple translation for all language.
Every one like some translation and read translated Quran from interested translator.
I Think that you can add this translation source or format support for people.

فی امان ال...

**Comment by ahmedre** [comment]
> This quran is very good but same words not correct in Persian language  if possible please do it correctly جزاک الله خیر
> For exempel this aia
> بَلَىٰ مَنْ أَوْفَىٰ بِعَهْدِهِ وَاتَّقَىٰ فَإِنَّ اللَّهَ يُحِبُّ الْمُتَّقِينَ

> (Hussein Taji Kal Dari)
> آری (گناه هست) هر که به پیمان خود وفا کند و پرهیزگاری نماید، پس بی گمان خداوند پرهیزگاران را دوست دارد.

> -Sura Aal-E-Imran, Ayah 76
> This aia shod be translate like this

> بَلَىٰ مَنْ أَوْفَىٰ بِعَهْدِهِ وَاتَّقَىٰ فَإِنَّ اللَّهَ يُحِبُّ الْمُتَّقِينَ
> . آری، هر کس به عهد خود وفا کند و خدا ترس و پرهیزکار شود همانا خداوند پرهیزکاران را دوست می‌دارد.

**Comment by ahmedre** [comment]
> رَسُولٌ مِنَ اللَّهِ يَتْلُو صُحُفًا مُطَهَّرَةً

> (Sahih International)
> A Messenger from Allah, reciting purified scriptures

> (Hussein Taji Kal Dari)
> پیامبری از سوی خداوند (بیاید) که صحیفه های پاک را **نخواند**.

> -Soera Al-Bayyinah, Ayah 2

> The highlighted word above means not to read/recite terwijl the real meaning to read/recite.

**Comment by ahmedre** [comment]
> وَلَوْ دُخِلَتْ عَلَيْهِمْ مِنْ أَقْطَارِهَا ثُمَّ سُئِلُوا الْفِتْنَةَ لَآتَوْهَا وَمَا تَلَبَّثُوا بِهَا إِلَّا يَسِيرًا
> -سوره اﻷحزاب، آیه ۱۴

> با عرض سلام
> در آیه بالا کلمه لآتوها مد آن اشتباه تایپ شده و فقط باید همزه باشد  و همچنین مد در کلمه بهآإلا یسیرا نیز اشتباها تایپ نشده است لطفا اصلاح بفرمایید باتشکر از برنامه خیلی خیلی خوبتون اجرکم عند الله

**Comment by ahmedre** [comment]
الخطأ في الترجمه فارسية ( گله داری).
الخطأ = روز ( يعني اليوم)
صح = روزه ( يعني الصيام)

**Comment by ahmedre** [comment]
replaced with Quranenc.com on 4/4/2020
