### ISSUE TITLE
اخطاء في التسجيلات الصوتية (Recitation related problems)

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#330]
محمد جبريل
- الشيخ محمد جبريل في سورة يونس الصوت غير واضح و فيه تشويش كبير
- ٧٣ النحل

**Comment by Somaiagabr** [comment]
عبدالله بصفر

*نقص كلمة بصورة هود  آية 82  وهي كلمة(  منضود )

**Comment by Somaiagabr** [comment]
القارئ سهل ياسين
* ملفات الصوت لاتعمل من اول سورة النور الى سورة الناس

**Comment by Somaiagabr** [comment]
القارئ االحصري مجود
 فى سورة هود ايه رقم 23  يتلو (صدق العظيم )  مما جعل باقي الملفات الاخري غير مرتبة

**Comment by Somaiagabr** [comment]
ابو بكر الشاطري
* error timing

**Comment by Somaiagabr** [comment]
الحصري (متصل

* لقمان الايه ٣١ لم يلفظ كلمه اياته

**Comment by ahmedre** [comment]
ghamdi - surah hashr verse 24 - missing "al7akeem"

**Comment by ahmedre** [comment]
sheikh Mahir - 9:52 is wrong (64kbps, 128kbps is deleted)

**Comment by ahmedre** [comment]
sahl Yaseen - sura Nisa' - timing files issue - verse 26 timings are somehow verse 15 timings and this continues for a while until it catches up :(

**Comment by ahmedre** [comment]
minshawi mujawwad - 57:24 missing "huwa" in "huwa alghaniy al7ameed

**Comment by ahmedre** [comment]
sura baqarah - husary mujawwad - recitation changes partway through (around 242 or 243) to be abdulbasit

**Comment by ahmedre** [comment]
sura hashr verse 24 - last word is cut off

**Comment by ahmedre** [comment]
sudais 2:205 - word "al-nasl" pronounced a bit oddly

**Comment by ahmedre** [comment]
merging into #204
