### ISSUE TITLE
Images not the same size

### ISSUE THREAD

**Issue by farajn** [quran/quran_android#334]
In page 214, in tablet mode, the right image is shorter than the left image:

![2013-09-16 17 38 35](https://f.cloud.github.com/assets/2012321/1153033/ad82c912-1f18-11e3-93fe-de34e7eda1a9.png)

**Comment by ahmedre** [comment]
these are actually fixed for the new 1260 images (which is what tablets and most new devices these days should get). can delete your existing images and uninstall/reinstall the app to let it download the new ones.
