### ISSUE TITLE
malayalam issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#338]
from an email:
there are errors in malayalam translation (shaik muhammed &vanidas) in sura alankabooth 8 to 12 ayaths.

**Comment by Somaiagabr** [comment]
Surat Al-Anaam 
Aaya 6:157-160
Translation: Malayalam translation by Muhammad karakunnu and Vanidas elayavoor

The above aayaths meaning is totally different from other translations

**Comment by Somaiagabr** [comment]
verse 22:43 by mohammed karakkunnu and abdul hameed as it is showing mistake in mohammed karakkunnu's translation.

**Comment by Somaiagabr** [comment]
Ankabut (29) I saw the meaning of verse 12 is missing and instead the meaning of verse 8 repeated against the verse 12. This is in Malayalam translation of Mohamed Karakkunnu and Vanidas.

**Comment by ahmedre** [comment]
> there is some error i found in  malayalam transilation of muhammed karakkunn and vanidas .kindly rectify and update the same. Error found in  surah 22 hajj ayah 22.41 ,22.42,22.43.

**Comment by ahmedre** [comment]
request for Amanu moulavi

**Comment by ahmedre** [comment]
Malayalam meaning of Muhammed karakkunnu and vanidas elayavoor. 20:41 to 20:44

**Comment by ahmedre** [comment]
check sura an'am 160

**Comment by ahmedre** [comment]
sura 6:160 for mohammed karakkun

**Comment by ahmedre** [comment]
>  i found some mistakes in malayalam translation( muhammed karakunnu and vanidas elayavur) of surah AL - HAJJ ayah 41 to 44... they repeats the same 37 to 40's.

**Comment by ahmedre** [comment]
> In Malayalam meaning of 15:34, 
> Allah says to iblees,  but in transalation some people have mistake

> So please edit or change അവൻ  to അല്ലാഹ്

**Comment by ahmedre** [comment]
2:133 has a typo
> അക്ഷരപിശക് വന്നിട്ടുണ്ട്... മാറ്റി എഴുതണം
<img width="374" alt="screen shot 2019-01-27 at 12 08 03 am" src="https://user-images.githubusercontent.com/47771/51792225-a4498180-21c7-11e9-8014-8b23e82bc094.png">

**Comment by ahmedre** [comment]
disabling this translation due to a large number of errors and difficulty in fixing them. we'll support the Abdul Hameed Madani and Kunhi Mohammed's translation moving forward since the quranenc team maintains it on their site and have a team who can look into typos if they are reported.
