### ISSUE TITLE
Support for Indo-Pak script

### ISSUE THREAD

**Issue by ofa1** [quran/quran_android#341]
May Allah bless you all for the great work you're doing. This is my favourite Qur'an app. It would be more helpful if you guys added the Indo-Pak/Urdu script of Qur'an also for people living in the subcontinent. JazakAllahu Khairan

**Comment by ahmedre** [comment]
already done - check it out here - https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh
