### ISSUE TITLE
Issue with Tafsir Font?

### ISSUE THREAD

**Issue by afarra** [quran/quran_android#402]
From emails there seems to be issue with Tafsir font after the change:

> لا يمكن لي في التفسير أحسن الخط. وقد يتصل بعض كلمة ببعض

> السلام عليكم //الاخوة المحترمين ..الرجاء ثم الرجاء ..رجاء خاص جدا جدا… ارجو من سيادتكم ان تعيدوا خط التفسير الي الخط العريض كما كان في السابق حيث ان التحديث الاخير اصبح الخط رفيع جداا ويصعب قرأته وكذلك نوعية الخط ارجوكم ارجوكم ان تعيدوا النظر في نوع الخط في التفسير… شكرا لكم على تعاونكم وجزاكم الله خير

I wonder if it could be related to the Night Mode changes I made? I made some fixes to night mode that touched tafsir, though hardly touched font. I'll review it again to make sure I didn't break anything. Did we make any other tafsir related changes this release?

**Comment by ahmedre** [comment]
old issue, closing.
