### ISSUE TITLE
Ability to speed up/slow down audio playback

### ISSUE THREAD

**Issue by ismusidhu** [quran/quran_android#408]
Speeding up/Slowing down audio playback based on reader's ability will be a useful feature. This feature will be particularly useful when a reader is trying to read _Quraan e Majeed_ as much as possible while wanting to avoid even any single mistake. This feature will also be helpful to a _hifz_ student for quickly reviewing what he has already memorized. At the same time slowing down feature will help slow readers or beginners in arabic and _Quraan_ reading.

**Comment by omarmeky** [comment]
+1
