### ISSUE TITLE
Is there any specific reason for using 2 spaces for indentation?

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#429]
Assalamu alaikum

From Readme:
> [Code Style](https://github.com/quran/quran_android#code-style)
> ------------------------
> - tab size: 2
> - indent : 2
> - continuous indent: 4
>
>you can set these under code style and code style java in android studio or intellij.

I see this guideline is not followed in lots of places in the code: some indentations are 3 spaces, some are 4 spaces, some are even tabs (`\t`).

Is there any particular reason for choosing 2 while Android's formal indentation policy is [**4 spaces**](https://source.android.com/source/code-style.html#use-spaces-for-indentation)?
Of course, there is no such requirement as everyone needs to follow Android's coding style, but that's what most devs are used to and most IDEs are configured to by default. 
And we programmers are a lazy nation, we do not always go about changing IDE settings :)

**Comment by ahmedre** [comment]
i am thinking:
a. stick to 2 spaces
b. increase the 80 character limit (but still keep reasonable, to intellij's default 100 character limit per line

we should probably:
a. pull in the codestyles as @hakimrie suggested
b. enforce checkstyle on checkin to avoid being able to check in code where spacing is off

**Comment by ozbek** [comment]
JazakAllah khairan, let's see to it...

> b. increase the 80 character limit (but still keep reasonable, to intellij's default 100 character limit per line
Android Studio's default is also 100.

**Comment by ozbek** [comment]
Resolved as of dd8c059c21d173601fad95c16c44da8702043724.

**Comment by ahmedre** [comment]
@ozbek quick question - curious as to what you changed from the original `AndroidStyles.xml` - i see some import orders changed, etc - do you know what all you changed? jazakAllah khairan.

**Comment by ozbek** [comment]
Sorry for the delayed response.

The only change I made was to set indentation and continuous indentation to 2 and 4 spaces, respectively, in every possible place.
