### ISSUE TITLE
redo about page (and credit everyayah)

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#43]
everyayah.com should be in the credits list for the audio insha'Allah.
we also should redo the about page and make it nicer (and include the version number).

**Comment by matalbab** [comment]
kuliahshamsuri.bloger.id

**Comment by matalbab** [comment]
Ambo oyak doh wahai tuhe ku

**Comment by matalbab** [comment]
﷽Bismillah.blog

Verily He Who ordained the Qur'an for thee, will bring thee back to the Place of Return. Say: "My Lord knows best who it is that brings true guidance, and who is in manifest error."

And thou hadst not expected that the Book would be sent to thee except as a Mercy from thy Lord: Therefore lend not thou support in any way to those who reject ((Allah)'s Message).
(28. Al-Qasas 85,86) 

https://ayatbyayat.blogspot.com/2020/01/free-quran-fail-perayat.html?
_everyayah.com
