### ISSUE TITLE
اخطاء في تفسير التحرير والتنوير

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#440]
تفسير اية 102 من البقرة محذوف من تفسير التحرير و التنوير لابن عاشور

**Comment by echiheb** [comment]
من الآية 50 الى الآية 88 لايوجد تفسير التحرير والتنوير

**Comment by ahmedre** [comment]
تفسير التحرير و التنوير لابن عاشور غير موجود للايات من 62 ال88 من سورة البقرة

**Comment by ahmedre** [comment]
> حيث وضعت همزة تحت الالف في حرف "الا" 
> وهذا خطأ و تغيير للمعنى 
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/47771/22416451/8817fb26-e683-11e6-9317-634f14fa0aec.png)

**Comment by ahmedre** [comment]
> من الآية 50 الى الآية 88 لايوجد تفسير التحرير والتنوير

**Comment by ahmedre** [comment]
> السلام عليكم ورحمة الله وبركاته 
> خطأ مطبعي واضح تلاصق أحرف
> في تفسير قول الله (أيود أحدكم أن تكون له جنة من نخيل ...)

![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/47771/22451718/a4d9e6a0-e725-11e6-9f3f-a98875cae9a0.png)

**Comment by ahmedre** [comment]
> لاحظت خطأ في كتابة الآية الكريمة "يسألونك عن الساعة أيان مرساها ".  وذلك في تفسير Arabic Tanweer Tafseer كما يلي:

> ( كَأَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوا إِلَّا عَشِيَّةً أَوْ ضُحَاهَا (46)جواب عما تضمنه قوله : { يسئلونك على الساعة أيان مرساها } [ النازعات : 42 ] باعتبار ظاهر حال السؤال من طلب المعرفة بوقت حلول الساعة واستبطاء وقوعها الذي يرمون به إلى تكذيب وقوعها ، فأجيبوا على طريقة الأسلوب .... )

**Comment by ahmedre** [comment]
>  يوجد خطأ بتفسير التنوير آية 210 البقرة
> والخطأ هو بكتابة آية 44 الطور، كلمة مركوم وهي مكتوبة مركرم

**Comment by ahmedre** [comment]
replaced this tafseer with a new version from furqan.co. closing.
