### ISSUE TITLE
التفسير في اللغه الالبانية

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#443]
هل تستطيعون ان تضاعو في لغة اﻷلبانية ترجمة حسان ناهي .ترجمته افضال و اقراب للفهم من ترجمت افندي ناهي.

**Comment by Somaiagabr** [comment]
mistake in surah Rrahman ayah 70-72

**Comment by Somaiagabr** [comment]
Murselat Aya 16, at the Albanian traslation there is an error at the aya writin

**Comment by ahmedre** [comment]
closing and merging into #324.
