### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#458]
from an email we got (and i think we should definitely think about this, these are some good ideas masha'Allah):

Assalamu Alaikum and jazakumumullahu katheeran

I would like to urge the team to not miss a great opportunity for much reward. Two features _in a widget_ form will do wonders for the ppl of Quran, the family of Allah, the best Muslims:
1. Direct Surah/Ayah jump: People learning islam and daa'ees especially find references to Aayaat on the move and need to cross check or quote it or bookmark for tafsir study. Readers of physical mushaf at home might want to continue at the mosque for short reading. A widget that takes input like (23:21) and then jumps or book marks or shares immediately will be super.
2. Arabic search jump: for same read on move or quote on move  as above - on the move you want to look up ayat...opening app takes time. Widget launches straight to translate/bookmark/share

So while typing this email i could quote ayaat very quickly, especially if you can design a keyboard add-on (that's third feature actually?)

Jkkk

Salam.

**Comment by yFotouh** [comment]
salam 3alaikum,
i was wondering if my pull request reached you for the widget feature?
Wa jazakum allah khayran

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i just tried it today, i am really sorry, i forgot. i like the idea behind this and the fact that it provides quick access, but the ui needs to improve. i especially love the one touch to get to the last page you were reading, i think that's great!

how do you feel about us actually having a list of bookmarks in the widget? i can try to see if i can get us some designs (will take at least 2 weeks though insha'Allah) so we can iterate on this and get it shipped out?

walsalam 3alaikum.

**Comment by yFotouh** [comment]
السلام عليكم,
Well glad you liked it , and as you said the designs needs to improve ,and in fact i have not spent time at all in modifying it since i'm not very good at designing  , and thought that anyone could just plug these icons with the suitable images for each of the 3 widget options or of coarse if someone would like to change completely how it looks.
I could work also on a fourth widget option to get bookmarks in the weekend , but still will actually not spend so much time on how it looks , but can do something basic design though like a custom list view with a quran icon somewhere in the list view plus of coarse the text reference of bookmark and again someone could just come out and plug the suitable image or maybe change it's position so it would look nice.
Regarding shipping, do you mean merging my branch with the master?
وجزاكم الله خيرا
@ahmedre

**Comment by yFotouh** [comment]
@Hello :)
@ahmedre

**Comment by ahmedre** [comment]
sorry for the delay - insha'Allah let me get back to you this weekend.

**Comment by ahmedre** [comment]
![widget-1_2x](https://cloud.githubusercontent.com/assets/47771/7449069/1d8f0f44-f1e1-11e4-8937-8ce8dd0ec8cb.jpg)
![widget-eng_2x](https://cloud.githubusercontent.com/assets/47771/7449071/1d91c838-f1e1-11e4-9777-d8c786638ea8.jpg)
![widget-2_2x](https://cloud.githubusercontent.com/assets/47771/7449070/1d90562e-f1e1-11e4-8d40-930702d0837d.jpg)

**Comment by yFotouh** [comment]
salam 3alaikum,
Great ,should i start working with these images and cut out the icons as separate files ?
i think most of these icons already exist in the project except for the jump icon.

**Comment by ahmedre** [comment]
wa3laikum alsalam - for jump, use the "reply" icon from https://github.com/google/material-design-icons. will insha'Allah get the arabic Quran logo. the rest should already be in the app.

**Comment by lessmore618** [comment]
السلام عليكم 
Any updates on this widget issue? Why isn't it yet implemented?
وجزاكم الله خيرا

**Comment by ozbek** [comment]
Wa alaikum assalam @lessmore618.

As can be seen from the linked PRs, proposed changes are not quite production ready.

**Comment by mnayef95** [comment]
@ahmedre Are you still need implement this widget?

**Comment by ismail-s** [comment]
FYI I've done some work on #845 and got it to work with the latest code in this repo. But:

- the code isn't ideal yet eg `BookmarksDBAdapter` is still tightly coupled to the bookmarks widget
- The widgets don't look that nice currently, I haven't spent time on that yet.

Inshallah I'll get there soon (if I keep reminding myself to do it as well..). My code hasn't yet been pushed to Github yet either, Inshallah I'll do that soon as well..

**Comment by ahmedre** [comment]
jazakAllah khairan, looking forward to it!

**Comment by ismail-s** [comment]
I've created #1378 and put some comments on for people to feedback on (cc @ahmedre). There is still various stuff for me to do on the PR.

**Comment by ahmedre** [comment]
@ismail-s - jazakumAllah khairan - sorry i know i've been slow about this :( will get to it soon in sha' Allah and do really appreciate your help and may Allah reward you greatly
