### ISSUE TITLE
Merge Bookmarks and Tags into a single UI

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#469]
Assalamu alaikum.

As it stands, separate screen for bookmarks and tags cause confusion (please see #377 and #378 for examples). It took me half an hour, and dozen tests with bookmarking/tagging and going through issues list before I could understand that tagging really is only for orginizing bookmarks into categories.

That's, for achieving a better user experience, I suggest merging those two screens into one.
Final UI can essentially be called 'Bookmarks' with 'Current Page' at the top. 
The menu will include 'Alphabetical', 'Date Added', 'Location in Quran' and 'Show tags' options. When 'Show tags' is enabled (default) the first three options will sort bookmarks within tags, otherwise sorting will be for all bookmarks.

What do you think?

**Comment by afarra** [comment]
**My use case:**
* Bookmark to track progress (e.g. daily reading) *(have to keep deleting old bookmarks)*
* Tags to save/categorize favorites that I would like to come back to in the future (e.g. duas)

I think the confusion stems from the fact that the current "bookmarks" implementation we have is more like favorites actually. The only true bookmark we have is the "Current Page" bookmark.

**My Suggestion:**
* Merge tags and bookmarks together into same page like you suggested, and call it Favorites. Essentially, it's starred ayahs, that you can tag if you want or leave without tags. 
* Favorites page would look the same as the bookmarks page looks now, but with the tags as little tokens below the sura name.
* In the "Sort By" button of the Favorites page, add a "Categorize by Tags" option. If selected, it'll show the same view we have for Tags page now.
* Introduce *actual* Bookmarks like the "Current Page" bookmark. Bookmarking a page would replace the previous page. That way people don't have to keep deleting old bookmarks every time they finish reading their daily reading

**Favorites**
![tags](https://cloud.githubusercontent.com/assets/965594/5593153/2add836c-91c7-11e4-9915-71f672cd5537.png)

**Favorites with "Categorize by Tags" selected**
![favorites](https://cloud.githubusercontent.com/assets/965594/5593152/2ad5241a-91c7-11e4-9449-7bdaf8032a8c.png)

**Bookmarks**
![bookmarks](https://cloud.githubusercontent.com/assets/965594/5593151/2acca1a0-91c7-11e4-8777-0c7412972d96.png)

What do you guys think?

**Comment by ahmedre** [comment]
jazakAllah kharian Ahmed.
i agree with the whole thing about favorites (and your first screenshot) and think we should do that (along with the group by tags option).

as for the idea of bookmarks, i think it's confusing - reasons:
1. in the real world, a bookmark is physically moved by a person from page x to page y.

2. in quran android, we already have one "automatically moving bookmark" which is "current page" - having multiple named "automatically moving bookmarks" would pose several problems, including:
a. which bookmark do you move if multiple bookmarks are on the same page?
b. confusing the user by adding yet another concept to the mix

based on this, i'd like to go with your favorites idea as a replacement for the current bookmarks + tags (and keep "current page" as our only "automatically moving bookmark" for now).

**Comment by afarra** [comment]
I agree current page is sufficient, but the issue with it is sometimes I
open the app to quickly look up a verse and that ends up overriding the
bookmark and I lose track of where I was.

Maybe there's another way? The main UX problem here is to not to have to
keep deleting old "favorites" when keeping track of progress.

**Comment by ahmedre** [comment]
speaking of moving bookmarks, we do something similar in [Ayah](https://play.google.com/store/apps/details?id=com.ayah) - basically, "Favorites" in Ayah are Quran for Android's bookmarks, and Ayah also has a concept of a single bookmark that, when you assign it, replaces the previous one automatically. Ayah doesn't have tags though.

thinking about it, my use case is similar to Ahmed's first use case - whenever i read, i manually make a new bookmark and delete the old one. i think i recall Ahmed saying that the thing he didn't like about Ayah's method is that there is only one bookmark (for me personally, i usually only want one, except maybe in Ramadan where i may track more, for example, one for my personal reading, and one for the taraweeh reading).

thinking to go ahead with merging the screens insha'Allah.

**Comment by ozbek** [comment]
:+1: Finally!
