### ISSUE TITLE
Issue in the Audio Mode (Listening mode )

### ISSUE THREAD

**Issue by lakani** [quran/quran_android#471]
Description:
While listing to Quran and after the system reaches the last verse in the Page , the system stops playing audio !!!, I’m expecting that the system continues to the next page and keeps playing Quran

Steps
1-	I started the application 
2-	Tab one of the verse “ex.  El Baqraa”
3-	Selected “abd Al-Basit” and tabbed the Play button
4-	Application started to download the Verses 
5-	Application started playing the Audio 
6-	Once the application reaches the last Ayah in this Page, the Application Stops 

The expected Behavior 
The application should
 
1- Download the next page Ayah Audio
2- Continues playing the next Ayah
3- Flip to the next page

**Comment by ahmedre** [comment]
this isn't a bug - there's a setting that controls the default download amount - it's set to "page" by default. you can switch it to "sura" in settings if you'd like. shuyookh with gapless don't have this issue since we download the full sura anyway.
