### ISSUE TITLE
Wrong audio download

### ISSUE THREAD

**Issue by afarra** [quran/quran_android#475]
From a friend: Mumtahana or mujadila, husary mujawwad selected but downloads abdulbaasit instead

**Comment by ozbek** [comment]
Not reproducible (at least, as of commit 9e5cecfc9639e950a5241d665e8b14d53c0d26a1). 

In fact, files downloaded through the app UI match with that of http://4quran.com/files/readers/Mahmood%20Khaleel%20Al-Husaree-%5BMujawwad%5D/058.mp3 and http://4quran.com/files/readers/Mahmood%20Khaleel%20Al-Husaree-%5BMujawwad%5D/060.mp3

**Comment by ahmedre** [comment]
closing unless someone else complains.
