### ISSUE TITLE
imlaei text for 4:6

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#477]
the imlaei text (in translation view) for 4:6 has the tashkeel as ﺍﻟﻨِّﻜَﺎﺡَ instead of the correct tashkeel. the strange thing is, the data source is the same as we use for http://quran.com/4/6, which renders it correctly - however, if you try to copy/paste the word from there into here, for instance, the same problem will happen with the text.

looks like a possible font rendering bug, in which case i am not sure what (if anything) we can do about this. this maybe more reason to prioritize using uthmani text in translation view as well.

**Comment by aessam** [comment]
Does it happen while generating using the Perl scripts or happen on the phone?

Also is it possible to use fonts instead of images for devices that can run it?
I will gladly handle that.

**Comment by ahmedre** [comment]
it happens when generating the images (it's a bug in the font itself if you will), so using the fonts won't help in this case.

**Comment by ahmedre** [comment]
2:4 is another example. we should try with a custom font and see if this problem still exists.

**Comment by ahmedre** [comment]
more examples - 2:125 (tahira) and 2:136 (nufariqu). this is still broken on Android M.

**Comment by ahmedre** [comment]
plan of action:
1. try with a custom (non-roboto) font to see if the problem exists. if this solves the problem, this is the quickest solution for the time being and we should push this fix out.

2. if the above doesn't work, we have to think about the quickest way to push images into the translation view instead of using the normal arabic text. even though we are clear that the way to read the Quran is the uthmani text (i.e. the images), the number of people emailing us about this suggests that people actually use the translation view for reading the arabic.

3. we should report whatever findings we have to the android bug tracker so this bug can be fixed in future android versions.

this is pretty important to fix since it is showing people incorrect things (even though the underlying data is correct, as can be seen on quran.com itself when viewing those same verses with the text with tashkeel option).

**Comment by ahmedre** [comment]
110:3 "rabbika" is another example.

**Comment by ahmedre** [comment]
tried many other fonts, none worked, but al7amdulillah, the qurancomplex hafs font (http://fonts.qurancomplex.gov.sa/?page_id=42) did work - patch incoming.

**Comment by ahmedre** [comment]
today, i learned, that this is actually *not* a bug - because the line is underneath the shadda, it's equivalent to a kasra. in either case, will keep the patch using the uthmani hafs font since it's probably better to use a specified font than to count on the various fonts used on people's devices.
