### ISSUE TITLE
translation restricted to a verse

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#487]
someone sent a screencast where they couldn't move forward or backwards in the verses - while looking at the code, i saw something that suggests that this could indeed happen. should probably fix this.

**Comment by ahmedre** [comment]
to be clear, here's how to repro:
- start playing audio (anything).
- long tap an ayah and choose translation.
- try to move to the previous or next ayah - no go.

likewise, you'd expect the translation would update as the qari continues reading, but it doesn't. we should fix this. my thought is to add a checkbox "follow audio" (only if audio is playing). if that's checked, we will explicitly update the translation when the verse changes. if the user explicitly hits previous/next, we'll uncheck it and show them previous/next.

one thing i am not sure of - in that case, should we stop jumping to the previous/next arabic page as well?

**Comment by malzantot** [comment]
Salam Alikum,

I wonder what you mean by "try to move to the previous or next Ayah"..
 Does this mean moving forward and backward in translation (or tafsir) is not possible while audio is playing ?? I can't reproduce it.

**Comment by ahmedre** [comment]
wa3laikum alsalam -
yes - strangely enough, i can't repro it now either, but i definitely was able to a few minutes ago :(
walsalam 3alaikum.

**Comment by Ahmed9914** [comment]
@ahmedre Can we close this for now if the bug isn't reproducible?

**Comment by ahmedre** [comment]
closing
