### ISSUE TITLE
What's the purpose of preference classes?

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#491]
At the moment there are 4 preference files under [`app/src/main/java/com/quran/labs/androidquran/ui/preference`](https://github.com/quran/quran_android/tree/master/app/src/main/java/com/quran/labs/androidquran/ui/preference). Except for `SeekBarPreference.java`, the other 3 are doing only one thing: **change the color of the dialog title**.

However, it appears to me that such change was required sometime earlier but is not required anymore. For instance, I compared runtime results for `QuranListPreference` and `ListPreference` and they look identical on a device.

Maybe those classes are not needed anymore?

**Comment by ahmedre** [comment]
i don't remember on the top of my head, but you maybe right, we may not need this anymore. i will test it and get back to you insha'Allah.

**Comment by ozbek** [comment]
Please see the discussion in PR https://github.com/quran/quran_android/pull/492 for details.
