### ISSUE TITLE
Network error notification should be cancelled once download resumes

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#493]
I just had this "network error" notification while downloading sura images. The download quickly resumed after showing "retrying..." message for couple seconds. However, "network error" notification was not cleared. It is a very minor UI issue, but I think, the error notification must be cancelled once download progress is back to normal.

Please see the below screenshot.

![screenshot_2015-03-11-10-55-15](https://cloud.githubusercontent.com/assets/452620/6589202/a09a5df2-c7df-11e4-8a84-1905ac155d42.png)

**Comment by ahmedre** [comment]
looks like this happens during the "auto retry" phase (since manually restarting the download or hitting retry if there's a dialog does actually dismiss the error dialog).

**Comment by ozbek** [comment]
That's right, it happened after an auto-retry. 
Jazak Allah khairan for the fix.
