### ISSUE TITLE
SearchView Widget Material Design inconsistency

### ISSUE THREAD

**Issue by khalid-hussain** [quran/quran_android#497]
When the searchView widget is activated, it shows the app icon. This is against [Material Guidelines](http://www.google.co.uk/design/spec/patterns/search.html). It should not show the app icon.

Screenshot:
![](http://s24.postimg.org/6hnm2d0ed/Screenshot_2015_03_11_10_26_49.png)

**Comment by ahmedre** [comment]
jazakAllah khairan - yep, that's because i unfortunately haven't had time to materialize the search yet. insha'Allah will fix it in the near future.
