### ISSUE TITLE
Repeat Verse Plays 1 more time [BUG]

### ISSUE THREAD

**Issue by guneysus** [quran/quran_android#499]
Repeat mode plays verses 1 more time. The main reason should be star counter starts from 0.

![screenshot_2015-03-18-12-16-08](https://cloud.githubusercontent.com/assets/949232/6706717/dd525220-cd68-11e4-985c-8f0cb2f3885e.png)

**Comment by ahmedre** [comment]
this isn't a bug, it's intentional. repeat "1 time" means you repeat the verse 1 time. repeat "never" means "never repeat this verse" (so only say it once).

**Comment by guneysus** [comment]
It is a little bit confusing. Because `never repeat` is never used. But there is an option. 
I want to listen a verse 3 times, but have to select 2? 
![screenshot_2015-03-23-17-52-08](https://cloud.githubusercontent.com/assets/949232/6784018/dd36962c-d185-11e4-8fd3-0ed02e335c51.png)

**Comment by ahmedre** [comment]
jazakAllah khairan, agreed, you have a good point. We should change it to "play set of verses x times" and "play each verse x times"
