### ISSUE TITLE
Localization Support for Surah Names [Feature Request]

### ISSUE THREAD

**Issue by guneysus** [quran/quran_android#500]
Is it possible to define surah names in localized form? I am willing to support of localization of surah names to Turkish.

[sura_names.xml](https://github.com/quran/quran_android/blob/master/app/src/main/res/values/sura_names.xml)

**From:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="sura_names">
        <item>Al-Fatiha</item>
        <item>Al-Baqara</item>
...
```

**To:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="sura_names">
        <item>Fatiha</item>
        <item>Bakara</item>
...
```

**Comment by ozbek** [comment]
Yes, possible.

Just need to create a new `sura_names.xml` file with correct translations under `values-tr/`.
