### ISSUE TITLE
New Feature Suggestion : Playing Sura

### ISSUE THREAD

**Issue by malzantot** [quran/quran_android#508]
Salam Alikum,

I have a simple idea for a new feature that I can work on, so I hope to hear your feedback and I hope you approve it.

The new feature is adding a "Play button" in the Sura row.

Currently,  if the user wants to listen to Sura, he has to do so :
1. Click on Sura row, to open the Mushaf page of the Sura.
2. Long tap the first Ayah, and click play.
3. Select range from the beginning of Surah to its End.

which are 3 steps, so I would like to suggest adding Play button to the sura row like here:
![screen shot 2015-03-23 at 8 23 35 pm](https://cloud.githubusercontent.com/assets/1429452/6795247/c6a794b4-d19a-11e4-91e9-c658ffa9cc21.png)

So, that If the user clicks the Play icon, it will open the Mushahf page of the Sura beginning and automatically start playing audio from the start of Sura till its end.

If the user touches elsewhere on the Sura row, it will open  the page normally without playing audio.

Salam Alikum,

**Comment by ozbek** [comment]
Wa alaikum assalam. 

Sounds like a handy feature, there might be a need to add default reciter option to Settings though.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan - i think this is a good idea for an audio specific app (i have actually wanted to build one using the quranicaudio data set, just haven't gotten around to it) - in Quran, however, i think we should keep the focus more on the reading aspect of things (and audio as a means of revising or what not as opposed to the app being used as a general Quran player).
walsalam 3alaikum.
