### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by nassimjd** [quran/quran_android#510]
Assalamo alaicom brothers, I've done the pt-br (values-pt   folder)translation for both the reader and strings xml files. I tried to merge but I'm not sure if it went through.
I still have some issue that I don't get pretty well on github

**Comment by ozbek** [comment]
Wa alaikum assalam 

You have merged the changes from your own repository to your own repository, i.e, to the same repository. The only thing is that they are of different branches. 

You need to send the pull request here, to this repository/project.

**Comment by nassimjd** [comment]
ok let me try it again to 
/project

**Comment by ahmedre** [comment]
you can just go to your repository and there should be a button for "make a pull request" or something.

**Comment by nassimjd** [comment]
first time I sent it to my own repo and then I sent it to the
quran/quran_android   repository, but don't know if it went

the gui interface is a bit difficult to understand

what is the path to send it throught Git shell?
بارك الله فيكم


Nassim Dhaher


2015-03-31 23:22 GMT-04:00 ahmedre <notifications@github.com>:

**Comment by ahmedre** [comment]
closing in favor of #560
