### ISSUE TITLE
Ayah number isn't highlighted when ayah is highlighted

### ISSUE THREAD

**Issue by abdarraafi** [quran/quran_android#511]
Aswrwb my dearest @ahmedre,

When an ayah is searched for and highlighted, in the translation view, the ayah number is not highlighted.

![screenshot_2015-04-05-15-49-33](https://cloud.githubusercontent.com/assets/3399326/6999027/da092de0-dbab-11e4-99fc-44ac39667d14.png)

Wishing you the bestest,

Shatil

**Comment by ahmedre** [comment]
done, jazakAllah khairan!
