### ISSUE TITLE
Translation view's ayah number isn't highlighted

### ISSUE THREAD

**Issue by abdarraafi** [quran/quran_android#512]
Aswrwb again, my dearest @ahmedre!

When searching for an aayah, the ayah number is highlighted on the mus'haf view page. When the world icon is tapped and translation view appears, the ayah that was highlighted on mus'haf view isn't highlighted anymore....

Unless you go into landscape mode! That triggers the highlighting, and then if you return to portrait mode, the highlighting sticks. Below are before and after screenshots:

Before rotating:

![screenshot_2015-04-05-15-55-51](https://cloud.githubusercontent.com/assets/3399326/6999039/b4acab3e-dbac-11e4-8009-90d57d66c736.png)

After rotating:

![screenshot_2015-04-05-15-56-06](https://cloud.githubusercontent.com/assets/3399326/6999040/bbfbe59e-dbac-11e4-84d6-aa53fa140d76.png)

Shatil

**Comment by ahmedre** [comment]
jazakAllah khair bro, fixed.
