### ISSUE TITLE
Misaligned auto-scroll in portrait recitation mode

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#523]
Observed on Nexus 5 with Android 5.1 using the latest code from master branch.
The app directory structure is as follows:

    .
    └── sdcard
        └── quran_android
            ├── audio
            │   ├── husary
            │   │   ├── 006.mp3
            │   │   └── husary.db
            │   └── .nomedia
            ├── databases
            │   ├── ayahinfo_1260.db
            │   └── quran.ar.db
            └── width_1260
                ├── page001.png
                ├── page002.png
                ├── page003.png
                └── ....png

Please see [the screen recording](https://video.googleusercontent.com/zreTtOIMHCvGUPcHoSpdxoQWvMuN0xJde8h7SqcYUM23-UMB_Y7jLddkgxk9kn6GVc1kXiiOdpBU_Q) for details.

**Comment by ahmedre** [comment]
interesting - so i am curious, did you touch the screen at all during that time, or is it trying to figure out where the top of the ayah is and keeps scrolling around that area on its own?

**Comment by ozbek** [comment]
That's me trying to see the whole ayah, but the app is _pulling_ the screen down automatically.

**Comment by ATouhou** [comment]
I might be. It sounds like the same error.
It happened in sura tawbah, I did not touch the screen, but let it play ayah for ayah. in some of the pages, when reaching the middle/end part of a page, it does no align vertically correct and show the last part ofthe ayah.

**Comment by ahmedre** [comment]
Fixed this earlier today al7amdulillah.
