### ISSUE TITLE
Russian translation issues

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#525]
cc @ozbek @Valey

salam 3alaikum -
hope you are both well. can one of you help with this?

lint shows:

> For locale "ru" (Russian) the following quantities should also be defined: few, many.

the items in question are:

```xml
    <plurals name="verses">
        <item quantity="one">%s аят</item>
        <item quantity="other">%s аят (-а/-ов)</item>
    </plurals>

    <plurals name="search_results">
        <item quantity="one">Результат для \"%1$s\": </item>
        <item quantity="other">%2$d Результаты для \"%1$s\": </item>
    </plurals>
```

so aside from few and many missing for both, `other` for `verses` looks strange to me (i don't speak Russian, but it doesn't look correct?).

according to the documentation for `other`:

> When the language does not require special treatment of the given quantity (as with all numbers in Chinese, or 42 in English).

so in English, for example, we have `one` for one and `other` for everything else. Arabic has `zero` for zero, `one` for one, `two` for two, `few` for 3-10, `many` for 11 and more.

can one of you fix these?
jazakumAllah khairan!
walsalam 3alaikum.

**Comment by ahmedre** [comment]
this is the plurals documentation for Android which may help:
http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by ozbek** [comment]
Wa alaikum assalam, jazak Allah khair. 

I was aware of this issue, but never had chance to look into. I will try to fix it, but would prefer @Valey 's solution as Russian is not my native language (assuming his is).
