### ISSUE TITLE
update open source projects in about

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#527]
as part of the planned cleanup for about and how the strings are handled and whatnot, we should also cleanup the open source projects list - things like ActionBarSherlock are no longer in use, whereas things like RxJava and RxAndroid are now in use (and are not yet referenced).

**Comment by ozbek** [comment]
I was referring to this very issue of out of sync [elsewhere](https://github.com/quran/quran_android/issues/522). I think, these are technical information that can be kept in one single language, i.e., English and end-users who are into such things would still have no problem comprehending it.

**Comment by ahmedre** [comment]
agreed.

**Comment by ahmedre** [comment]
closing since i think this is now resolved.
