### ISSUE TITLE
broken basmala in surat al-teen

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#529]
هناك خطأ مطبعي في سورة التين صفحة 597، إضافة شدة على (بسم الله الرحمن الرحيم).

**Comment by malzantot** [comment]
نفس الخطأ في سورة القدر (صفحة ٥٩٨)

-- Moustafa

**Comment by ozbek** [comment]
Mind to provide more details, like the device your are using and the app data folder structure (normally, `/sdcard/quran_android/`)?

I don't see any apparent issues on page 597 in Nexus 5:

![screenshot_2015-05-20-14-14-16](https://cloud.githubusercontent.com/assets/452620/7719349/0fa33dca-fefb-11e4-8a08-d116c0fddfcd.png)

**Comment by ozbek** [comment]
@malzantot, same with page 598: no issues on my end:

![screenshot_2015-05-20-14-21-42](https://cloud.githubusercontent.com/assets/452620/7719396/bb323998-fefb-11e4-9349-d192ebcc7546.png)

**Comment by ahmedre** [comment]
both have the bug - look at the b in bismillah - compare the one at the top of 597/598 with the one at the bottom of 597/598 - the one at the top is wrong.

**Comment by ahmedre** [comment]
we'll have to patch this (and might as well in the process fix the 3 pages with different font size and the spacing for pages 1 and 2 on non-1260 image sets).

**Comment by malzantot** [comment]
You can notice in your screenshot  there is a "shadda" on بسم الله الرحمن
الرحيم

In sourat al-tin but not in Surat al-alq .

-- Moustafa

**Comment by ozbek** [comment]
Right, now I see. Jazak Allah khair.

**Comment by ahmedre** [comment]
turns out this wasn't broken - it was actually correct :( checked the mushaf and it indeed has a shadda for only these 2 suras.
