### ISSUE TITLE
remember selection to see translations

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#530]
when a user goes into translations, we should probably default them to translations by default.

**Comment by ozbek** [comment]
Do you mean the case when there are no downloaded translations?

**Comment by ahmedre** [comment]
no - as in when you choose a sura and tap the globe to open translation mode, when you hit back, we take you to the index. so next time you tap a page (or the "last page" button), let's go back to translation by default instead of to the arabic page.

**Comment by ozbek** [comment]
I see. I have never used the back button at the top. Now that I tried, I see an inconsistency with the system back button:

 - Pressing the back button at the top opens the index page.
 - Pressing the system back button opens the Arabic page.

So, then pressing the system back button should also open the index page.

**Comment by ahmedre** [comment]
anyone should feel free to work on this and send a PR
