### ISSUE TITLE
Scroll on versebyverse playback, not showing entire ayah.

### ISSUE THREAD

**Issue by ATouhou** [quran/quran_android#535]
Salam.
In some pages, when it scrolls, it does not show the entire ayah, but shows instead more of the "above" part , than the actual ayah being recited.
Hope you understand. It should scroll so it shows the next ayah completely :-) Using Sony Xperia Z3

**Comment by ozbek** [comment]
Wa alaikum assalam. 

Is this related? https://github.com/quran/quran_android/issues/523

**Comment by ATouhou** [comment]
It might be, I will comment in it
