### ISSUE TITLE
"Calculating App Size"

### ISSUE THREAD

**Issue by ATouhou** [quran/quran_android#536]
Salam.
I have approx 40gb of reciters audio. This causes every time I enter "settings" page, it takes maybe 30 seconds to "calculate app size", is it not possible to have the app size inside another place, like "move files" or something, so whenever entering "settings" page, I don't have to wait the 30 seconds for app calculation...?
BarakAllahoufeekum

**Comment by khalid-hussain** [comment]
Waʻalaikum Assalam,

I'm having a similar 'issue' but I've only downloaded 2 complete reciters and 1/2 for another one. It takes about 5 seconds every time I enter the Settings page.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
jazakAllah khairan - that is, indeed, a bug.
will fix it insha'Allah (by not bothering to show the dialog in the first place).
walsalam 3alaikum.

**Comment by ahmedre** [comment]
jazakAllah khairan - that was a pretty bad bug :(

i've temporarily fixed it by removing the dialog and just updating the messaging on the last item to say "calculating app size" (until it's done, when it will enable the item and switch the summary text back the way it was).

the better fix is to give some thought to this - as to whether it's even needed in the first place or not, for example. another problem is that if you go into prefs and back really quickly, it will keep the task running (which is a big issue, especially if it's taking ~30 seconds). will file another ticket for cleaning this stuff up, but at least this way we have a fix for the next version insha'Allah, even if it's not the ideal fix.

**Comment by ahmedre** [comment]
see also #537
