### ISSUE TITLE
Highlight glitch Surah As-Saff (page 552: last ayah)

### ISSUE THREAD

**Issue by khalid-hussain** [quran/quran_android#538]
Assalamuʻalaikum,

I've tried editing the page image to remove that thin line on the bottom left but the highlight still comes up wrong. I don't think it has to do with the page image but with the database. This is not to say the page image should not be improved.

Screenshot:
![](http://s25.postimg.org/mf5zzfnkf/Screenshot_2015_06_09_07_47_30.png)

**Comment by ATouhou** [comment]
Bug confirmed on My Phone using the  1260 width.
It need to be fixed from ayah_1260.db i think mohammed :D
Den 09/06/2015 16.51 skrev "Mohammad Khalid Hussain" <
notifications@github.com>:

**Comment by khalid-hussain** [comment]
The same issue occurs on the first page of Surah Al-Munafiqoon.

Screenshot:
![](http://s25.postimg.org/kllmuw6q7/Screenshot_2015_06_13_15_54_16.png)

**Comment by ahmedre** [comment]
this is a bug with the font - we should fix this insha'Allah in the next version along with #663

**Comment by ahmedre** [comment]
depends on:
 https://github.com/quran/quran.com-images/issues/7
https://github.com/quran/quran.com-images/issues/8

**Comment by ahmedre** [comment]
fixed in ce6b40d4da96bc5313dcbd35fc1e18a2045f962b
