### ISSUE TITLE
QuranScreenInfo getHeight is often wrong

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#539]
while refactoring some code, i noticed that the `getHeight` method of `QuranScreenInfo` is often wrong - the reason is that it caches the height from `QuranScreenInfo` (which will depend on the orientation). while the effects are not catastrophic (they only effect scrolling to the highlighted ayah in landscape and the toolbar position), it is definitely wrong, and its effects can be seen.

for example, start the app in landscape on a galaxy s2 (480x800 resolution device). in portrait, open up 2:187. long press it, and notice that the toolbar is below the first line instead of below the ayah. the correct behavior (as observed if you start the app in portrait instead) is that the toolbar be underneath the ayah.

this is minor, but likely should be fixed anyway for correctness (either by removing the need for `getHeight` or by properly getting the height instead of using a cached version).

**Comment by ATouhou** [comment]
Actually it is a big problem if wanting to reading with recitation without touching Phone :-( May Allah reward you for All your hard work brother,ameen

**Comment by ahmedre** [comment]
it doesn't break scrolling in and of itself, it makes a small difference in how much it scrolls by - either way insha'Allah will fix it.

**Comment by ahmedre** [comment]
this code changed a lot in the past few years so likely is fixed now, closing.
