### ISSUE TITLE
Weird display on minimize and change orientation

### ISSUE THREAD

**Issue by ATouhou** [quran/quran_android#540]
Salam
I think This problem Comes from minimizing (with playing sound maybe?) then changed orientation opening the App again
https://www.dropbox.com/s/4ihi5pmpyo9anqg/Screenshot_2015-06-10-09-47-15.png?dl=0

**Comment by ahmedre** [comment]
wa3laikum alsalam,
that's very strange - can you find out more exact steps for how to reproduce this problem? also, what phone is this? normally, the page stretches to fill the width, right?
jazakAllah khairan.
walsalam 3alaikum.

**Comment by ATouhou** [comment]
I Will try in Sha Allah :-) yes i get the normal display usually and got it
in locked orientation.

I'm using a Sony xperia z3 on OS 5.0.2

I think it is When it is minimized and playing quran to the next page
Den 11/06/2015 05.56 skrev "ahmedre" <notifications@github.com>:

**Comment by ahmedre** [comment]
i think i fixed this when i fixed lots of fragments related issues - please re-open if you still see this
