### ISSUE TITLE
Landscape mode: Autoscrolling not working correctly (tested on Samsung Galaxy S4)

### ISSUE THREAD

**Issue by epandzo** [quran/quran_android#545]
__Summary:__ When using Quran Android in Landscape mode and playing recitation, auto scrolling is not allways positioning correctly (part that is reciting it often not visible on the screen)

__Tested on:__ Samsung Galaxy S4

__Possible resolutions:__
- Fix autoscroll algorithm in Landscape mode
- Add option to turn off autoscroll

__Severity:__ Low

May Allah reward you for your good deeds.

**Comment by ahmedre** [comment]
fixed this al7amdulillah. insha'Allah next version will have it.
