### ISSUE TITLE
[Bug] Wrong search redirection

### ISSUE THREAD

**Issue by Akmal02** [quran/quran_android#546]
Assalamialaikum.
I'm using Android 4.4.2
When I want to search something in the Quran, it brings me to the wrong ayah, fr example, searching a text that are supposed to be in Sura Al-Baqarah brings to Sura An-Nisa.
I don't know what happens, if it is just phone,

**Comment by ahmedre** [comment]
yes, there is a bug here - i am closing this ticket and tracking it in #554 since it has details on how to repro and see this behavior.
