### ISSUE TITLE
"Network error, trying to resume" when downloading data

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [quran/quran_android#548]
I just received what described itself as a small but important update. I kept trying to download it to no avail.

I was seeing this error:
"Network error, trying to resume..."

It never starts downloading. It's always 0% until it throws an error in the notification bar "could not download due to network error". Then it asks me again if I want to download Quran data. Still repeats same cycle.

I cleared data and uninstalled it trying to fix it, now after reinstalling, it's doing the same thing for the whole Quran data, not just the "small but important update".

How do I fix this?

**Comment by BoringUserWhoCantCode** [comment]
I would also appreciate a quick confirmation if someone faces the same problem. I've been facing more than my typical share of problems with apps lately. I'm thinking of reinstalling the system.

**Comment by ahmedre** [comment]
1. which version are you using (is it the latest quran android?)
2. what device are you on?
3. are there any files at all in `/sdcard/quran_android`?

**Comment by BoringUserWhoCantCode** [comment]
Yes it's the latest in Play Store.

Phone is Nexus 5, Android 4.4.4

There were files before I reinstalled it. I think 281MB or 261MB before I
deleted them all to reinstall the app.

Now there an empty folder called "width_1260", that it. Size is 0MB.

**Comment by ahmedre** [comment]
i can't see anything strange with the servers - the fact that width_1260 is empty makes sense, since it didn't download the files, and therefore, there is nothing extracted there.

so some things to try:
1. don't download files when it asks you, and open any page - wait a second or two and see if the page shows up (if it does, that means it's successfully able to download from the internet) - my guess is, it won't show you anything.

2. open a browser on your phone and try to go to http://android.quran.com and see if it opens or not

**Comment by BoringUserWhoCantCode** [comment]
It didn't show anything in the page.

Yet, http://android.quran.com/ is readily accessible.

**Comment by BoringUserWhoCantCode** [comment]
Oh God, sorry about that. It's totally my fault. Sorry about that.

Consider this solved. The solution is not really worth posting, it's way to limited for my use case.

May Allah accept you and reward you for your great efforts.
Sorry about the unnecessary annoyance.

**Comment by samiqureshi** [comment]
Posting your solution might help others. I have the same issue and this seems to be the only post on Google about it. Can you explain what you did?

**Comment by michele-musa** [comment]
I had the same issue. The storing space was finished: eliminated few images and all was ok.
Jazaka Allahu Khairan. Assalamu 3aleikum

**Comment by ozbek** [comment]
Wa alaikum assalam. 

Do you mean that you had "Network error" notification when there was not sufficient space left on the device storage?

**Comment by michele-musa** [comment]
Yes. "Network error, trying to resume"

**Comment by michele-musa** [comment]
I freed some space on the device and the error is gone (update successfull)

**Comment by ozbek** [comment]
Interesting... I can not reproduce it, I am seeing "Not enough disk space to download" message.

Please file a separate bug report if you see "Network error, trying to resume" error for not enough disk space case again. Thanks.

**Comment by michele-musa** [comment]
Ok, if it happens again i'll file a separate bug report.
I had 0 kB available on the SD (and few kB on the internal memory), and the app set to save the data on the external SD memory card. I searched the error message on Google and found this thread.
Jazaka Allahu khairan, wa assalamu `aleikum

**Comment by adliabdoh** [comment]
I have more than enough space to download the audio on the app. Yet it always goes to downloading 41 surahs and then it goes "network error, trying to resume". someone please help

**Comment by ozbek** [comment]
Can you open Surah 42 and see if page loads?

**Comment by adliabdoh** [comment]
The page definitely loads, I found that the audio for Abu bakr Shatri
(gapless) cant be downloaded for this surah but it does for other reciters
(i'm assuming they're non-gapless if that helps)

**Comment by ozbek** [comment]
Ah, so you were actually facing issue with the audio? Can you post a separate question for that, please? This one is about Qur'an pages.

**Comment by adliabdoh** [comment]
Who do I refer to for the audio section?

**Comment by ozbek** [comment]
Please use this link: https://github.com/quran/quran_android/issues/new

In title, please define the issue with a short, brief sentence. And then explain the problem in detail in the comment/body section.

Thanks.

**Comment by adliabdoh** [comment]
JazakAllahu Khair
