### ISSUE TITLE
[!]Offline resource-pack >>>

### ISSUE THREAD

**Issue by MuSamDu** [quran/quran_android#553]
Asalom alicon, hello developers:
After i install your quran_android app, i would like to install some resources like translations and audio, and downloading them really costs a lot of time, so would you please release resource packs as offline-installable apks so that i can download them in a faster internet and install them everywhere, thanks for paying attension! :smile:

**Comment by ahmedre** [comment]
wa3laikum alsalam,
most of our files (audio, etc) are easily transferrable from one device to another. some files (ex pages) may not be relevant to another device, depending on the screen size, so you may have to download them again. unfortunately, there is no supported way right now, so just download the files via the app and then manually back them up.
waslalam 3alaikum.
