### ISSUE TITLE
stream setting may not check if the file is downloaded

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#557]
i got an email bug report which seems to imply that when the "prefer streaming" setting is checked, that we aren't checking to see if we have the file locally first. we should do this if we aren't already.

**Comment by mhussien86** [comment]
Need to be tested ? anyone worked on this ? are we still have this issue ?

**Comment by ahmedre** [comment]
i haven't verified it myself yet, but i wouldn't be surprised if it were true.

**Comment by ozbek** [comment]
@ahmedre, do you want to keep this open until the proper "rewrite" of AudioService?

**Comment by ahmedre** [comment]
no that's ok - we'll close this given your fix
