### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by nassimjd** [quran/quran_android#560]
Assalamoalaicom brothers

please copy the portuguese translation from this location as I really can't get the push request to work.

I've made a link to my values-pt folder which has the readers.xml and readers.xml files translated to Portuguese.
http://1drv.ms/1SKQPvS

Baraka Allaho fikom

**Comment by nassimjd** [comment]
actually pull request and push request using Sourcetree for github..

**Comment by ahmedre** [comment]
this is already merged so closing, jazakAllah khairan
