### ISSUE TITLE
yusuf ali 11:18 typo - life should be lie

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#562]
correct on quran.com so we must have already corrected it there.

**Comment by Somaiagabr** [comment]
51:47 it should say 'space', not 'pace'

**Comment by Somaiagabr** [comment]
in surah 3, verse 131:
Shouldn't it say "prepared" instead of "repaired".

**Comment by alireza-ahmadi** [comment]
All of these typos still exists, is there any way to fix them?

**Comment by ahmedre** [comment]
copied and merging into #329 - planning on fixing these soon insha'Allah.
