### ISSUE TITLE
add .nomedia file to audio

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#565]
i am on the fence about this one, but saw several complaints recently about it. i personally don't use my quran android audio as the audio on my device.

we should probably do this anyway for gapped audio.

any thoughts on whether or not we should also do this for gapless?

**Comment by asimmohiuddin** [comment]
Yeah, I personally don't use my media player to play quran but prefer to go through the quran app. I would imagine if someone had a lot of the quran downloaded and also other things like lectures, etc, it would make it difficult finding their other audio.

I think both ways is fine but I am leaning towards adding that .nomedia.

**Comment by ozbek** [comment]
Yes, please. 

As @asimmohiuddin stated, absence of `.nomedia` makes things a little messy at times. On the other hand, users can always add Qur'an audio files manually by browsing the folders with `.nomedia`.

**Comment by ahmedre** [comment]
sounds good - PR? :)
