### ISSUE TITLE
better compression for existing images

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#569]
per the suggestion of @ens4dz, if we run `pngcrush` on our quran images, we can likely decrease the size (and thus save bandwidth for everyone).

**Comment by boussouira** [comment]
> [PNG is lossless](http://superuser.com/questions/845394/how-is-png-lossless-given-that-it-has-a-compression-parameter). GIMP is most likely just not using the best word in this case. Think of it as "quality of compression", or in other words, "level of compression". With lower compression, you get a bigger file, but it takes less time to produce, whereas with higher compression, you get a smaller file that takes longer to produce. Typically you get diminishing returns (i.e., not as much decrease in size compared to the increase in time it takes) when going up to the highest compression levels, but it's up to you.

It's true the size will be a smaller, but that will add more CPU usage to decode the image

**Comment by ahmedre** [comment]
this is now fixed (see #699)
