### ISSUE TITLE
sura naba' ayah 40 for shuraim cut off

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#571]

**Comment by asimmohiuddin** [comment]
Asalaamualaikum, this is only for the gapped version and below is the missing file alhamdulillah.
https://www.dropbox.com/s/7aihc7ynak1s8tp/078041.mp3?dl=0

**Comment by ahmedre** [comment]
jazakAllah khairan - the file you sent is the other half (there is no verse 41, just 40 verses) - i found that the 64kbps version was complete, so i just replaced the 128kbps version with it (http://www.everyayah.com/data/Saood_ash-Shuraym_64kbps/078040.mp3).
