### ISSUE TITLE
Issue in downloading surat An-nur (24) for sahl yaseen (gaples)

### ISSUE THREAD

**Issue by MoeHus** [quran/quran_android#578]
This is booking download the whole Quran for Sahl Yaseen and blocking Surat An Nu recitation.

**Comment by ahmedre** [comment]
unfortunately, that one is missing. we had to decide whether to push sheikh Sahl when this sura was missing or leave him out completely, so we pushed it anyway so that people who requested him could listen to his recitation.

if you find any recitation for him for sura noor, please send it our way and we'll be happy to add it insha'Allah.

**Comment by MoeHus** [comment]
Thanks for looking into this.
I'll look for recitation for him.  but in the mean while as this is breaking full Quran download and surah streaming, just as a suggestion why don't you add Surat noor for any other sheikh in its place just so at least people will be able download?

**Comment by MoeHus** [comment]
There you go

http://server6.mp3quran.net/shl/024.mp3

**Comment by ahmedre** [comment]
ran across this one before, it won't do it because it's not complete :(

**Comment by MoeHus** [comment]
Found it, but it needs some work, I'll post it tomorrow inshallah.
Its in an excellent quality too.

**Comment by MoeHus** [comment]
I found it as Warsh so here it is. (I'll keep looking for it as Hafs)
https://onedrive.live.com/redir?resid=9A394C8C3A13873D!12359&authkey=!AOUEp4_l8BGTlQc&ithint=file%2cMP3

I found the whole Quran for this Sheikh in the same quality as Sura Nur but Warsh reading, will you be interested? if so I do need to work on splitting it into multiple sura as it is big chunks of audio files?

**Comment by ahmedre** [comment]
the warsh version won't work unfortunately since the recitation is different and would confuse people :( please let me know if you do find a hafs version!

**Comment by ahmedre** [comment]
merging into #204

**Comment by ahmedre** [comment]
fixed - found a correct version and uploaded. you'll have to delete and redownload the database to get the updated timings though.
