### ISSUE TITLE
Text cut off in translation mode

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#581]
i've seen a few emails saying roughly this:
"If you chose translation Sith Aya visible and enlarge text size, sometimes the top most Ayat line's zabar or pesh gets cut off. E.g. 4:27(checked today). 3:254(yesterday). There are more such instances."

**Comment by ahmedre** [comment]
another email shows this happening in Arabic with the new font. i am guessing it's related to the LineHeight changes recently pushed.

**Comment by ofa1** [comment]
Here's a screenshot of it happening in the Naksh Indo-pak script version : http://imgur.com/kFLYp7o

**Comment by ahmedre** [comment]
jazakAllah khairan - ouch, that's pretty bad. i think i know the change i made to cause this :S will try to fix it insha'Allah.

**Comment by ofa1** [comment]
Insha'Allah Khair. May Allah reward you guys in keeping with His Grace and
Generosity. Absolutely stupendous job that you guys are doing.
Alhamdulillah.

Another point, it gets this bad when I rotate the screen from portrait to
landscape. Just in portrait mode it's readable, though text is extremely
close.

On Wed, Oct 28, 2015 at 10:25 AM, Ahmed El-Helw <notifications@github.com>
wrote:

> jazakAllah khairan - ouch, that's pretty bad. i think i know the change i
> made to cause this :S will try to fix it insha'Allah.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quran/quran_android/issues/581#issuecomment-151725619>
> .
>



-- 

Omair Fareed Ahmed

**Comment by ahmedre** [comment]
insha'Allah this is fixed now.
