### ISSUE TITLE
Malaysian app translation should be values-ms?

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#584]
salam 3alaikum -
@asyazwan, our translation for Malay is in `values-ms`, but it seems like this should be `values-my` - can you confirm one way or the other so i can move it? `values-ms` seems to be Burmese.
jazakAllah khairan,
walsalam 3alaikum.

**Comment by asyazwan** [comment]
@ahmedre sorry I missed the notification. Yes, `my` is the rightful code.

**Comment by ahmedre** [comment]
seems like it's already `values-my` - i have no idea what i was thinking when i filed this bug :S closing, jazakAllah khairan.
