### ISSUE TITLE
improve translation downloading screen

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#589]
pull to refresh would be nice here since some people get empty cache files and can't get any data for ~1 week or without removing the cache file.

**Comment by ahmedre** [comment]
adding pull to request should be pretty straight forward

**Comment by ahmedre** [comment]
cc @hosainnet since you're pretty familiar with this code - just need to wrap the `RecyclerView` with a `SwipeRefreshLayout` and force an update

**Comment by hosainnet** [comment]
Sure I'll have a look inshallah
