### ISSUE TITLE
Bring back this project to "Open Source" state

### ISSUE THREAD

**Issue by Korayem** [quran/quran_android#591]
Stopping people wanting to do good because some are misusing the openness of this project is nonsense. It is like stopping the printing of new Quran books because some are misusing it. This is the very definition of burying a head in sand.

First of all, let's size the problem. How many abuse the project? And, more importantly, how many downloads do they get on their fake apps? Google ranks search results taking into account number of downloads. It's no wonder the Quran Android (this project) is always topping the list. If a muslim leaves all the good apps on the top and decides to install scum app, then it's his fault.

Then there's a strong action that can be taken. Quran Android has millions of users world wide. You can use this army to shutdown ANY app that misuses this project's code. Just send a Push Notification (not to all users, but may be a subset to avoid any annoyances) asking them to report scum Quran app on the store. In a matter of hours they will vanish. Most, if not all, will take action simply put because emotionally, this is the QURAN!! they won't tolerate any misuse.

Muslims needs more open-mindness. This project was a beacon for such openness until it was shut down.

Muslims need to confront problems smartly and firmly. No more burying heads in sand.

**Comment by ozbek** [comment]
Uh huh! Sounds like a solid plan :)

**Comment by ahmedre** [comment]
just to be clear, the project was not shut down - the last release was 12 days ago, and today, for example, 8 commits were made. the source was closed to avoid more of these issues occurring.

that having been said, i typically give people who ask access (provided they want the access to contribute, not so that they can "write their own Quran app").

so all that having been said, what difference does it make if the app is open source or not as long as it's being actively developed?

**Comment by Korayem** [comment]
Thanks for clarifying this @ahmedre. The wording is important.

If it's still closed though, you'll miss on all those beautiful pull requests from people wanting to make this a better product as well as those who want to learn from it.

**Comment by asyazwan** [comment]
:+1: 

> so all that having been said, what difference does it make if the app is open source or not as long as it's being actively developed?

Being Open Source by default is the better spirit to show for such a project. There are probably better ways to handle the abuse than to "take the toys home" so to speak...

Regardless, alhamdulillah. Jazakumullahu khairan katsira.

**Comment by boussouira** [comment]
This project closed again? i must say it suck to have your app stolen, but Quran android source can be found easily from the forks, so if someone want to publish version to make money nothing can stop them. also you don't need the source code to bundle a malware to an apk.
Asking permission to read source code and making a pull requests is really not how github/FOSS work.  
[Jarir Reader](https://www.jarirreader.com/) is built on top off my GPL-app [Arabic Reader](https://github.com/boussouira/android-arabic-reader), they didn't publish the source code, when i contacted them, they denied the use of my app, they said they used the original FBreader (which doesn't support RTL), but my app icon was included in their app, with the renamed class names too.  

It's clear that Arab people don't care about EULA or source license, you have a lot of valid reasons to close the source, but it would make sense if this app's source code was never published, once something is on the Internet, you can't get it back, this move only make contribution from new developers harder, even if there aren't many.

**Comment by ahmedre** [comment]
jazakumAllah khairan. fixed.

**Comment by Korayem** [comment]
YAAYY! you did the right thing bro. May Allah reward you.

Now don't forget to add the feature I described above to easily ask massive user base to report this app copycats :)
