### ISSUE TITLE
Display Juz in Surah Overview List

### ISSUE THREAD

**Issue by av2k** [quran/quran_android#592]
السلام عليكم و رحمة الله

Is it possible to display the Juz number next to the Surah Names in the Overview List?

It would be neccessary to display multiple Juz numbers for some Suwar, for example al Baqarah which spans over three Juz.

Since the application is solely for the Qur'an, I think it would be possible to hardcode the Surah-to-Juz matching (or vice versa) within the application.

Here is a link to a list with the Juz:

https://en.wikipedia.org/wiki/Juz%27

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
we already have the juz' number as a header on top of the items, like this:

![screenshot-2015-11-29_13 28 40 307](https://cloud.githubusercontent.com/assets/47771/11460180/1fa5db6c-969d-11e5-8e70-c16173c2df2b.png)

did you have something else in mind?
walsalam 3alaikum.

**Comment by ahmedre** [comment]
maybe, however, we can pin the headers (which we currently aren't doing).

**Comment by av2k** [comment]
السلام عليكم ورحمة الله وبركاته

excuse me brother, I just noticed that Quran for Android is not open source anymore, but I'm still using the open source version.

I think the ticket can be rejected since the function is already integrated  ما شاء الله

Not related to this ticket, I am a little bit sad that the program is closed-source. I do not use the Google Play store, rely on open-source software and consequently will not be able to profit from the apparently much enhanced recent versions. I hope that the decision to close the source of the application might be reversed إن شاء الله

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
more discussion on open source, etc in #591 - note that Quran for Android is not on F-Droid, we never pushed it there. as for getting apks from outside of google play, i plan on re-publishing these apks somewhere so you can download them without using google play if you choose not to use it.
walsalam 3alaikum.
