### ISSUE TITLE
Replace "infinitely" with "loop", "indefinitely" or "continuously"

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#595]
Although I can not say that's incorrect, option name "infinitely" (the last item in `repeatValues`) is not a common word used for playback repetition. Normally, the words "loop", "indefinitely" or "continuously" are used in regards to playback.

What do you think?

**Comment by ahmedre** [comment]
sure - i like both "loop" and "indefinitely," but i think "loop" is probably better.

**Comment by ahmedre** [comment]
jazakAllah khairan for fixing this.
