### ISSUE TITLE
Discussion: Merging Bookmarks and Tags

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#596]
There's a lot of confusion about bookmarks and tags. I've always told people that a bookmark is like a sticker you add to a page or an ayah, and that tags are things you write on that sticker (or remove).

Part of what might make that easier to understand is merging tags and bookmarks into one tab (bookmarks). It would default to showing each bookmark with underlying tags underneath it (if any) within the list. we'd add a sort option for sorting by tags so that no functionality is lost.

Thoughts?

cc @ozbek @afarra @hmaher

**Comment by ozbek** [comment]
You mean https://github.com/quran/quran_android/issues/469?

**Comment by ahmedre** [comment]
jazakAllah khairan - closing in favor of #469 :)
