### ISSUE TITLE
Option to show tags in Bookmarks

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#599]
In #469, tags and bookmarks were merged into one screen.

There is an option to group by tags, and this is (currently) the default. It may make sense before release to make the default depend on whether or not the person has any tags or not (if not, then don't group by tags).

Enabling "group by tags" shows the tags and allows interaction with them. It may also make sense to have a second option, "show tags" (unrelated to group by), which, irrespective of the group by option, would show the tags underneath each bookmark.

I think this makes sense, but open to any ideas on this - Thoughts?

cc @ozbek

**Comment by ozbek** [comment]
JazakAllah khair, nicely done.

Regarding the "show tags", I would not add it as an option. Having to many unnecessary options confuses the users. Rather, I think, it's better to simply _show the tags underneath each bookmark_ _**when "Group by tags" is disabled**_.

**Comment by ahmedre** [comment]
waiyyakum.
that's a good point - let's go with that for now insha'Allah.

**Comment by ahmedre** [comment]
this is done as of f77231a89e5b12d9b7f56e3533e9fcdeeef6c941.
