### ISSUE TITLE
build error - 1-3-2016

### ISSUE THREAD

**Issue by aakhws** [quran/quran_android#603]
ASA, 

I am new to Android development and trying to get the environment setup. I have installed Andriod Studio 1.5.1 and other supporting tools (I think).

When I build the app i get the following error

"
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
:app:fabricGenerateResourcesMadaniBeta FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.
"

Any help would be great.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
try building debug instead of beta - you can change the flavor that's built by clicking "Build Variants" (on the bottom left side of the IDE usually) and make sure "madaniDebug" is selected.
walsalam 3alaikum.

**Comment by aakhws** [comment]
Thanks, that seems to work. Is there a wiki or a doc to get someone like me going with this project especially getting familiar with Android Studio to checkout the changes. OT should I just read up on Android Studio website for it.

Sorry for asking for this kind of help, it has been 10+ yrs since I last setup a build environment for Java project. Any help is well appreciated. I will keep digging into it in the mean time.

**Comment by ahmedre** [comment]
unfortunately we don't have much documentation right now :( also, the codebase is not all in great shape - some of this code has been around for a long time and needs to be rewritten, and there are always improvements that can be made.

i'd say if you don't know much about Android to start by looking at developer.android.com, where there are good starting points, tutorials, and introduction to the Android concepts that should help make some of the stuff happening in the app make more sense. you can always post questions you have as well and insha'Allah i or someone else can help.

**Comment by aakhws** [comment]
Thanks, I will start from developer.android.com and will post if have any questions.
