### ISSUE TITLE
Upload to FDroid

### ISSUE THREAD

**Issue by shawnl** [quran/quran_android#617]
F-Droid[1] is a repository of free and open source android apps, that can be installed without Google Play or a google account.

[1] https://f-droid.org/

**Comment by ozbek** [comment]
I think, there were similar discussions elsewhere here.

**Comment by ozbek** [comment]
Found it: #434.
Probably, need to re-open #434 and merge this one with it.

**Comment by ahmedre** [comment]
closing to merge with #434.
