### ISSUE TITLE
Please add Husary Muallim recitation

### ISSUE THREAD

**Issue by riasatislam** [quran/quran_android#620]
Assalamu alaikum brs

It would be very nice if you could add Sh. Husary's Muallim recitation. This will help people learning to recite the Quran since many of the Ustadhs suggest Sh. Husary's muallim recitation.

Having this within Android Quran will be beneficial since other apps that have Sh. Husary's muallim recitation needs to be updated or doesn't support background playback.

And ofcourse, having it within Android Quran means, users can have a 1-app solution.

Hope to see this added.

Jazakallah khair for all your efforts.

**Comment by ozbek** [comment]
Wa alaikum assalam

Did you try **Husary Mujawwad** from reciters drop-down? It appears to be the same as what you are asking about.

**Comment by riasatislam** [comment]
jazakallah khair for your reply brother I am aware of that one.

But, I was asking about this,
http://www.versebyversequran.com/site/husary-muallim-teacher-style/

*Riasat Islam*
MSc ICT Innovation
UCL & KTH
Phone: +46 (0) 76 779 1428
Website: https://se.linkedin.com/in/riasatislam

**Comment by ahmedre** [comment]
already added, so closing.
