### ISSUE TITLE
Figure out a good logging strategy

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#621]
- send logs functionality (implemented in e5c3d945942d4e7cb45d1f7d7a62e22199132c69) - am worried that too many people will use this. should this only be available in beta builds, for example, and if someone complains about something, just send them a beta build? or leave it in prod and hide it somehow, similar to how Android hides developer options. thoughts? (cc @ozbek)

note that the main use case here is that we get a bunch of emails where people are complaining about always being prompted to download images, even when they've already downloaded them. the vast majority of people don't have this problem, but for the few who do, 

- `Crashlytics.log` - we should likely replace this with a `Timber.w` or higher, and add a crash reporting tree to Timber which logs said messages to Crashlytics.

**Comment by ozbek** [comment]
What exactly is that you are worried about regarding _"am worried that too many people will use this"_? Is that you are worried about to receive too many emails? Or suspecting that would cause some sort of negative effect on over all app performance?

**Comment by ahmedre** [comment]
too many emails - i don't think it should make any considerable difference on performance.

**Comment by ozbek** [comment]
> too many emails

OK. Then, probably, it's better to hide the functionality from stable builds and see if there is going to be enough beta testers experiencing the issue and willing to send the logs. If the situation proves the opposite (i.e., you don't get enough feedback from beta users), then you can enable the feature for everyone later...

**Comment by ahmedre** [comment]
a81b1be81f8ae34bab82ad602c2c6cd586f6f74f makes it only visible for beta or debug.
