### ISSUE TITLE
sahl yaseen sura noor missing

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#637]
we can get a replacement from mp3quran.net http://server6.mp3quran.net/shl/024.mp3 but the timing files are all off, so we'll also need to update the gapless database.

**Comment by asimmohiuddin** [comment]
@ahmedre The above file only has the recitation from the first 5 minutes. I believe the timings in the timings file for this particular surah was for a warsh recitation.

**Comment by ahmedre** [comment]
merging into #204

**Comment by mamdouhbreika** [comment]
Assalamu alaikum wa rahmatullahi wa barakatuh
I wonder if you could add Sheikh Rajab Zaki as one of the reciters in Quran for Android. Several websites have excellent downloadable mp3 recordings of his recitation which can be easily found on Google.
Jazakum Allahu khairan
Mamdouh Breika

**Comment by ozbek** [comment]
Wa alaikum assalam wa rahmatullahi wa barakatuh.

@mamdouhbreika, you may want to open a new ticket for that as this issue is about another reciter.

**Comment by mamdouhbreika** [comment]
I wonder if it is possible to add reciter Rajab Zaki to Quran for Android.  An excellent MP3 recording of his recitation of the entire Quran is available on Google.

**Comment by ozbek** [comment]
Yes, please open a new issue.
