### ISSUE TITLE
البسملة

### ISSUE THREAD

**Issue by EarthMan123** [quran/quran_android#640]
السلام عليكم ورحمة الله وبركاتة وبعد
فقد لاحظت عدم وجود الشدة في جميع سور القرآن وهي موجودة في المصاحف التي لدي.

**Comment by EarthMan123** [comment]
السلام عليكم ورحمة الله وبركاتة وبعد
فقد لاحظت عدم وجود الشدة في جميع سور القرآن وهي موجودة في المصاحف التي لدي.

**Comment by ahmedre** [comment]
وعليكم السلام ورحمة الله وبركاته
جزاكم الله خيراً 
الباء المشددة فقط في موضعين، وإن شاء الله نصلح ذلك
https://github.com/quran/quran.com-images/issues/30
والسلام عليكم

**Comment by ahmedre** [comment]
am almost done with this - soon in sha' Allah.
