### ISSUE TITLE
New Feature of quran android / quran naskh

### ISSUE THREAD

**Issue by tahabashir1991** [quran/quran_android#642]
vote for the new feature you like
options are
1. colour option
2. reading mode
3. juz list improment
4. juz divisions

http://goo.gl/forms/Pebtnx7OQA

to see them in action in images 
here is the sway 
https://sway.com/iiCfHUpuDfEs1VXK

**Comment by ozbek** [comment]
The form should have been a multiple choice form. As far as I can see, these features are not mutually exclusive :)

You could actually open a separate issue for each feature and upload the sway images right here to GitHub. Not many people would willing to click and go through yet another webpage to see what you are trying to see.

Overall, good suggestions. Well done! :+1:
