### ISSUE TITLE
Crash with NoClassDefFoundError on Samsung devices

### ISSUE THREAD

**Issue by llweifall** [quran/quran_android#643]
Dear developers,

I have found that the method setSupportActionBar of android support library v7 is used in many activities. However, this method crashed the app on Samsung devices.
I found the discussions in the bug tracking system of Android: [here](https://code.google.com/p/android/issues/detail?id=78377). 

I have found similar fixes in other apps like [AnkiDroid](https://github.com/ankidroid/Anki-Android/pull/3942)

Thanks a lot.

**Comment by ozbek** [comment]
Can you mention the device name/model? I don't see any issues on S7...

**Comment by llweifall** [comment]
It affects older samsung devices running 4.2.2 systems. I found some developers pasted a rather full list in the discussion in that Android issue page.
Samsung Garda (Galaxy Light)
Samsung Galaxy Mega 6.3
Samsung Galaxy Tab3 7.0
wiko
Samsung Galaxy S4 Zoom
Samsung Galaxy S3 Mini
Samsung Galaxy S4 Mini
Samsung Galaxy Ace 3

Thanks a lot for your quick reply

**Comment by ahmedre** [comment]
i worked around this issue a while back with:
`-repackageclasses 'android.support.v7'` in proguard.cfg and haven't seen crashes from it since - can you give me a stack trace?
jazakAllah khairan.

**Comment by llweifall** [comment]
Thank you very much for this information. I checked my proguard.cfg and added the code you provided and did not see the crash. I am sorry maybe I mistakenly changed proguard.cfg.

**Comment by ozbek** [comment]
:+1:  Please consider closing the ticket. Thanks.

**Comment by llweifall** [comment]
Thanks a lot and please close this issue.
