### ISSUE TITLE
اخطاء في تفسير الطبري Tabari translation

### ISSUE THREAD

**Issue by Somaiagabr** [quran/quran_android#644]
the tafsir is off, underneath every ayah they have the tafsir for the preceding ayah,

**Comment by Somaiagabr** [comment]
Surah Al-Insaan, misplaced between verses. Eg. tafseer for verse 25 supposed to be for verse 26, etc.

**Comment by ahmedre** [comment]
> خطا مطبعي في تفسير الطبري
> حيث لا يوجد فاصل  بين قول الله (وهو كره لكم )والكلام بعده حسب ما هو موجود في الصورة

![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/47771/22416190/bbee7b34-e681-11e6-9060-fa7db7bf358a.png)

**Comment by ahmedre** [comment]
replaced this tafseer with a new version from furqan.co. closing.
