### ISSUE TITLE
Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'. > Crashlytics Developer Tools error.

### ISSUE THREAD

**Issue by EgyptianM** [quran/quran_android#662]
Assakamu Alykom,
I got this error when I imported the project into Android Studio, my Android Studio version is 2.2 preview 3 and I have Fabric plugin installed already.
How to solve this?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
build the debug flavor, not beta (since it doesn't require Fabric keys) - i.e. in Android Studio, click "Build Variants" on the left and make sure it's set to debug (instead of beta).

or, from the command line, you can just run `./gradlew assembleMadaniDebug`
walsalam 3alaikum.

**Comment by nur2318** [comment]
salam,

i get this error even when following your instruction

Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.

**Comment by ozbek** [comment]
Wa alaikum assalam. As stated above _build the debug flavor, not beta_.

**Comment by nur2318** [comment]
salam bro,

my build type is debug
Flavours is madani

this is the result:

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.**

NO IDEA WHY?

**Comment by ahmedre** [comment]
salam 3alaikum,
your build type is beta, not debug, as evidenced by:
`Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.`

make sure you run `./gradlew assembleMadaniDebug` - if you're building from Android Studio, in the release types, make sure to select madani and debug.

**Comment by nur2318** [comment]
my bad but even I run it with "gradlew assembleMadaniDebug" I get it wrong

* What went wrong:
Execution failed for task ':app:processMadaniDebugResources'.
←[33m> ←[39mcom.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by ahmedre** [comment]
make sure you have android build tools properly installed and configured - seems to me it doesn't know where aapt is - usually you do this by form of setting `ANDROID_HOME` environment variable

**Comment by AhmedAmmarNegoudi** [comment]
what is fabric keys and what is its benifit ?
can i build a release or only debug ?

**Comment by sollyez** [comment]
salam,

i get this error even when following your instruction


Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.


![screenshot 81](https://user-images.githubusercontent.com/530451/37871718-9313d6b2-301f-11e8-9cab-eee1d0de3c00.jpg)

**Comment by sollyez** [comment]
@ahmedre 

alhamdulillah .. case closed thank you
