### ISSUE TITLE
Shemerly Quran pages

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#665]
we have the pages for Shemerly as contributed by our brother Waleed Ibrahim, jazahuAllah khairan. we should have a Shemerly version of the app.

**Comment by ahmedre** [comment]
so 5ba6c51 contains an initial implementation of supporting the Shemerly pages. i figured i'd open this with a list of outstanding problems (and also to get any feedback/ideas from the community about what we should do - push it or not, etc).

a few problems with this version:

#### general problems
- the images are massive (268mb) despite running them through some image optimization apps (compare this to the madani images of a similar size, which are 101mb).
- currently, only images for width 1200 are generated
- the images are not of uniform size (the widths of one image to another may change by a few pixels - while this doesn't really matter, ideally, they should all be the same size)
- some of the images have lines at the top or bottom of the page that are out of place

#### bugs
- since there are 521 pages, i am expecting misbehavior on tablets with dual screen mode
- since verses can span ayahs in Shemerly (unlike all our other types), there are bugs with highlighting verses that are split across pages.
- also due to the above, when playing audio on an ayah at the bottom of page x which continues on page x + 1, the app automatically puts you on page x + 1. this isn't ideal, but the only way to handle this is to know which part of the ayah (and audio file) are part of page x vs which are parts of x + 1.

#### not yet implemented

- highlighting for pages 1 and 2 isn't present. it's there for all the remaining pages, however.


my main concerns with respect to releasing this are the image download size issue (major problem, since device storage is little and bandwidth is precious in many countries), followed by the bugs (though only 2 of them can be (reasonably) fixed, the third one will take a lot of work - either manual, or figuring out an automated way to figure out the timestamps where the pages are switched).

on the flip side, a search for Shemerly in Google Play (both in Arabic and English) shows no results, and in the iOS App Store, only 1 result, last updated in 2014.

**Comment by ozbek** [comment]
Please excuse my ignorance, but what/who is "Shemerly"? Google search is yielding only some personal Facebook and twitter pages.

**Comment by ahmedre** [comment]
it is exactly like the normal mus7af (madani mus7af, hafs 3an assem) - the difference is that ayat can span multiple pages (unlike the standard Madani mus7af where ayahs never span pages), and, consequently, it's a total of 521 pages instead of 604. it's pretty popular among people in Egypt (not sure about other countries).

**Comment by ahmedre** [comment]
update - re-compressed the images with less colors (using `convert -colors 64 +dither source destination`), and re-optimized them - now the zip is at 112mb.

**Comment by ahmedre** [comment]
closing for now since there are no action items at the moment - an apk is buildable and works, and we can re-visit when we figure out if we will support multiple page types in the same apk or not.

**Comment by ducaale** [comment]
would a list of each page first word index help? this is [the first 5 juz'](https://github.com/quran/quran_android/files/2860721/shemerly_page_first_word_index.txt). I can add more if it helps

**Comment by ahmedre** [comment]
re-opening - in sha' Allah will see what's left to release this and i'll update here if i need any help

**Comment by ahmedre** [comment]
oh and jazakAllah khairan by the way.

**Comment by ducaale** [comment]
The web version of quran has audio that is indexed by word, is it the same for quran android? If it is the same then it can be combined with shemerly_page_first_word_index.txt the fix the third bug.

**Comment by ducaale** [comment]
Hi @ahmedre, how I can build shemerly variant

**Comment by ahmedre** [comment]
you can't right now - if there's interest i can make the page type accessible in the normal Quran for Android app under page types though since everything is pretty much working.

**Comment by ducaale** [comment]
I wanted to see if i can fix bug number 3

> also due to the above, when playing audio on an ayah at the bottom of page x which continues on page x + 1, the app automatically puts you on page x + 1. this isn't ideal, but the only way to handle this is to know which part of the ayah (and audio file) are part of page x vs which are parts of x + 1.

**Comment by ahmedre** [comment]
what was your plan to fix it? really the only fix is if we know where the audio for each ayah begins and ends so we can transition to the next page at the right time.

**Comment by ducaale** [comment]
the audio for quran_frontend is indexed by word, is it the same for quran_android?

**Comment by ahmedre** [comment]
not for all the qaris though unfortunately :(

**Comment by ducaale** [comment]
qaris that are indexed by word together with [shemerly_page_first_word_index.txt](https://github.com/quran/quran_android/files/3159206/shemerly_page_first_word_index.txt) can be used change page automatically when ayah continues on the next page

**Comment by ahmedre** [comment]
excellent masha'Allah - the remaining issue is just which qaris overlap - the answer sadly might be none, because of all the qaris supported on quran.com, they're all gapped qaris and not gapless. there's a plan to fix this but it may take some time

**Comment by ducaale** [comment]
do you mean when qaris repeats the same word?
> the remaining issue is just which qaris overlap

**Comment by ducaale** [comment]
I think it can be released as public beta until all bugs are sorted out. shemerly mushafs are becoming rarer these days that it would a benefit a lot of people if this was to be released.

**Comment by benomaire** [comment]
King Fahd Glorious Quran Printing Complex prepared a Mushaf (written by Uthman Taha) matching Shemerly print. For details look at pages 80-86 of https://qurancomplex.gov.sa/kfgqpc-books-booklets-complextechguide/

This version is available in 

1. https://play.google.com/store/apps/details?id=com.kfgqpc.mmn
2. https://apps.apple.com/app/id1462577431
3. http://iswy.co/e2ar0e
4. https://www.almeshkat.net/book/14787

I know that using this version might require repeating some of the work done on the original Shemerly version, but it is an option. May be both can be included!

**Comment by ahmedre** [comment]
closing this now that the app ships with Shermerly.
