### ISSUE TITLE
remember scroll position on orientation change in translation

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#667]
if you scroll in portrait mode to an ayah and switch to landscape, it returns to the top. we should at least return to the top of the ayah that was last being read.

**Comment by ahmedre** [comment]
this is much easier to do now that we're using `RecyclerView` - marking this as up for grabs, @hakimrie, feel free if you get a chance.

**Comment by selmanon** [comment]
@ahmedre The fragment `TranslationFragment` creation (`onCreateView`) is triggered 3 times due to page number calculation, which mean that `onViewStateRestored`is called 3 times, at the first time the position is valid but the second and the third it isn't (and the value is equal to 0).
Did I need to ignore the second and third call to `onViewStateRestored` by checking if the position is equal to 0 ? Because in my opinion there isn't an other way.

**Comment by ozbek** [comment]
> `TranslationFragment` creation (`onCreateView`) is triggered 3 times

Uh huh! Don't you think that that's the problem? Is there a way to _fix_ it and trigger `onCreateView` only once?

**Comment by ahmedre** [comment]
`ViewPager` generates no less than 3 pages - the current page, the page before, and the page after. so these "extra 2" are for the left and right page. there's no way to decrease this (nor do we want to, because otherwise, switching pages would be very slow, because you'd have to generate the page only once dragging started).

**Comment by ahmedre** [comment]
@selmanon you'd want to compare the page number to the page number known by `PagerActivity`.

**Comment by selmanon** [comment]
@ahmedre my bad .. got it .. I believed that it's due to some calculation stuff to get the right page index.

**Comment by selmanon** [comment]
@ahmedre just to share the behavior that actually I found, RV normally persist the state of the position without any additional coding (Ref : https://github.com/googlesamples/android-RecyclerView) the ref code example of RV did use additional code to persist the position state but I deleted them and it still persist the RV scroll position.

Actually, the `TranslationView` use a custom view `TranslationView` with a RV as field member and with this design android do not play well.

**Comment by Ahmed9914** [comment]
@ahmedre I think we can close this issue now.

**Comment by ahmedre** [comment]
jazakAllah khairan @Ahmed9914
