### ISSUE TITLE
Translation to surah names

### ISSUE THREAD

**Issue by habibr** [quran/quran_android#673]
Is there a way to translate the surah names? I do not see them in the strings.xml.

**Comment by ahmedre** [comment]
yes, they are [here](https://github.com/quran/quran_android/blob/master/app/src/main/res/values/sura_names.xml) - i don't think we're showing them in the app right now though

**Comment by ozbek** [comment]
Please see `surah_names.xml`

https://github.com/quran/quran_android/blob/master/app/src/main/res/values/sura_names.xml

**Comment by habibr** [comment]
Although the surah names in english and in Indonesian (or other languages) might be similar, the readers could see the names a bit strange and some questions could arise within themselves. I just showed the qur'an to my daughter and she directly pointed out the strange names of the surahs... :)

I think it would be a nice addition to the app if the `surah_names.xml` could be translated. I would be happy to translate them...

**Comment by ahmedre** [comment]
the `sura_names_translation` array is currently translated only in English and Russian - nothing stops other apps from translating it, we're just not showing it yet afaik, but we could/should.

**Comment by ozbek** [comment]
Russian locale shows both names: Arabic transliteration and Russian translation. In fact, that was first requested by Russian users.

**Comment by habibr** [comment]
ok, i will copy the strings to values-in to prepare for the indonesian version of the surah names.

**Comment by ahmedre** [comment]
@ozbek ah i forgot about this - should we enable this for all languages?

**Comment by ozbek** [comment]
Check out `show_sura_names_translation`: 

https://github.com/quran/quran_android/blob/master/app/src/main/res/values/booleans.xml

**Comment by habibr** [comment]
So, @ozbek, I should also copy this `booleans.xml` and set the translation there?

**Comment by ozbek** [comment]
Yes, but there is no need to copy everything. Just set `show_sura_names_translation` to true.

**Comment by ozbek** [comment]
> should we enable this for all languages?
Somehow, I have missed this part. Previously, we have agreed to enable/disable that feature based on `show_sura_names_translation` value per locale.

**Comment by ahmedre** [comment]
closing for now, please re-open if anything is needed.
