### ISSUE TITLE
non standard word in Indonesian app localization 

### ISSUE THREAD

**Issue by hakimrie** [quran/quran_android#676]
word `izin` is better than `ijin` in [localization for Indonesian (Bahasa Indonesia)](https://github.com/quran/quran_android/blob/master/app/src/main/res/values-in/strings.xml), since `ijin` is non standard in Bahasa Indonesia.

What do you think @habibr ?

reference: [Great dictionary of The Indonesian Language](http://kbbi.web.id/izin)

**Comment by habibr** [comment]
Well, if it is in KBBI then it is okay. Even though, sometimes I do not agree with their choices especially for words that have been assimilated into indonesian. The letter Z is a bit difficult to be pronunciated by most indonesian tongues. Many would say Z as J, that's why I prefer ijin than izin.

**Comment by ahmedre** [comment]
closing this, please feel free to reopen if needed
