### ISSUE TITLE
Uzbek translator's name is out of sync

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#692]
Translations drop down:
![screenshot_20161010-112759](https://cloud.githubusercontent.com/assets/452620/19225835/dd220c18-8edd-11e6-9ebd-d796a9deea39.png)

Translations settings:
![screenshot_20161010-112821](https://cloud.githubusercontent.com/assets/452620/19225840/ed9343dc-8edd-11e6-97f9-9d8380959f42.png)

**Comment by ahmedre** [comment]
@ozbek PR? :)

**Comment by ozbek** [comment]
The one from the drop-down seems to come from the server. So, perhaps, the answer is no :)

**Comment by ahmedre** [comment]
i think the way it works (it's been a while so i could be wrong) - translation manager saves the records of downloaded translations into a database and the dropdown is read from the database (`TranslationsDBHelper`). in that case, we just need to prefer the `translator` field to the `name` field when it exists i think?

**Comment by ozbek** [comment]
OK. Apparently, both `"translator"` and `"translator_foreign"` (translator's localized name) comes from the server. We save the `"translator"` to the database and use it elsewhere in the app. However, `"translator_foreign"` is not saved in the database and is not accessible (Translation manager uses JSON file for that). So, this requires an upgrade to translations.db.

**Comment by ozbek** [comment]
@ahmedre, what do you think? Am I on the right track?

**Comment by ahmedre** [comment]
yes looks like you're right - in `writeTranslationUpdates`, you'll want to save it (`item.translation.translatorNameLocalized`). but as you said, you'll want to add an upgrade to the database to add a column for this first (maybe just leaving that field null for now, and it updates the next time the person goes into the translation manager).
