### ISSUE TITLE
Whats the keystore file pls? for signing config release

### ISSUE THREAD

**Issue by sadraNOORME** [quran/quran_android#693]
I have gotten the following error when running the app:
Error:Execution failed for task ':app:validateReleaseSigning'.

> Keystore file C:\xampp\htdocs\quran_android-2.7.2\app\path\to\key not found for signing config 'release'.

Kindly help what the key is,,

Much appreciate

**Comment by ahmedre** [comment]
please build the debug flavor - `./gradlew assembleMadaniDebug` from the command line, or in Android Studio, change the build target to debug, this way you won't need the keystore.

**Comment by sadraNOORME** [comment]
@ahmedre thanks, i did run it through the cmd and gotten successfully built 
![image](https://cloud.githubusercontent.com/assets/20816487/19427609/a9bf101a-9477-11e6-9201-4063a1c424bd.png) but stil when running like the SearchActivity i get the keystore issue again 
![image](https://cloud.githubusercontent.com/assets/20816487/19427634/d0ffa248-9477-11e6-8a43-c089e1ad3a1e.png)

any idea pls?!

Thankss ahead

**Comment by ahmedre** [comment]
on the very right side of the Android Studio window is a button called "build variants" - make sure all of them are set to debug and not release - the signing one seems to be building beta, not debug, so please change to debug and it will work.

**Comment by sadraNOORME** [comment]
you are a life saver man! i was stuck for a day! 1000 thumbs ups (y)

**Comment by ozbek** [comment]
Please consider closing the ticket if your problem has been resolved.
