### ISSUE TITLE
  Addition of new reciter

### ISSUE THREAD

**Issue by MalikSaabSays** [quran/quran_android#694]
السلام عليكم 
 Take a listen of Ahmed Khadr at-trablesi. Heard recitation on makkah live tv.
Check it out:
http://youtu.be/pzu5IN7cRCU

If files are available, could we add to the reciters list?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
i think we have him, but only for Qaloon.
jazakAllah khairan, but closing for now since we're focusing on making things better and improving before adding new qaris for now insha'Allah.
walsalam 3alaikum.

**Comment by kb-programmer** [comment]
That's a great idea. Lets make existing features better first.
