### ISSUE TITLE
No Class Found (crashlytics)

### ISSUE THREAD

**Issue by sadraNOORME** [quran/quran_android#695]
Hi
I have saved the quran as a library and wish to use it as part of my another app, but i get some classnotfound while the library is imported already and added to the dependencies:

![image](https://cloud.githubusercontent.com/assets/20816487/19673759/5dbb0950-9ab5-11e6-9f4b-1a6537a9632c.png)

I have already managed to run it but it creates a new app and run it there,not in the main i have added it
another question i have is, this library( if i saved as library) can be running in another app view correct?

**Comment by ozbek** [comment]
Looks like something related to Crashlytics. Feed your own Crashlytics keys or remove it from the lib.

**Comment by sadraNOORME** [comment]
well wouldnt removing coz some part of the app to fail? 
and for that, is that enough removing this:
 compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }

**Comment by sadraNOORME** [comment]
But is that possible to run the library (quran app) in a view of another app?

**Comment by ozbek** [comment]
> well wouldnt removing coz some part of the app to fail? 

No.

> But is that possible to run the library (quran app) in a view of another app?

That depends on your implementation. Quran is not designed as a library, it's a stand-alone app.

**Comment by sadraNOORME** [comment]
Well, i am using it as a library, all is good except for:
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/crashlytics/android/answers/Answers;
 at com.quran.labs.androidquran.QuranDataActivity.checkPermissions(QuranDataActivity.java:119) and many more views..
should i do anyth in my main app pls?

**Comment by ozbek** [comment]
Sorry, as I mentioned earlier, Quran Android is a stand-alone application. I am not sure about the original authors, but I think _support for using it as a library is beyond its scope_.

**Comment by rhonyabdullah** [comment]
Sorry, but have you try to update your crashlytics version ?

**Comment by ahmedre** [comment]
compile the app using the debug flavor instead of beta or release flavors. closing this, please reopen if you're still having issues.
