### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by rhonyabdullah** [quran/quran_android#696]
Assalamu'alaykum.
 How can i contribute to this development process ? Is there any standarizations about how to contribute in this project ?

Salam.

**Comment by Gujarats** [comment]
Wa'alaykumsalam. 
You can contribute to this project by learning the structure and the style code in the Readme.md. And clone this project and find some issue that you can solve and make pull request.

 I think that's how you contribute on opensource project. But before go to code, you must try and find the bugs and create the issue that would help too. 

more about this [here](https://quran.zendesk.com/hc/en-us/articles/211545523-How-do-I-contribute-)
