### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by shahrukhmlk** [quran/quran_android#697]
Please document the code so that we can contribute to the code.
جزاك الله على ذلك العمل الجميل

**Comment by ozbek** [comment]
That's a very good suggestion. However, that's easier said than done. After all, writing docs is one of the most hated part of any programmer's job :)

To help with the cause, may I suggest you to ask about the parts that are not clear for you? At least, that way, the maintainers will know from where to start documenting the code.

**Comment by hulk9914** [comment]
I suggest to start documenting by putting a brief description at the beginning of each class to help other developers understand what is the role of each class.

**Comment by ahmedre** [comment]
i am closing this issue for now, but i definitely agree and will start adding more comments insha'Allah
