### ISSUE TITLE
Memorization mistakes markers

### ISSUE THREAD

**Issue by mgalaleldin** [quran/quran_android#702]
Assalamu Alaykom,

I have a suggestion for a feature that I believe would be very useful.

For someone memorising Quran, it would be nice to have a way to mark the Aya where he/she made mistake. The marking would not just be on/off like the tag/bookmark, but rather incrementing marker. Each time a mistake is made/remade then the marker for that is incremented, and a visual feedback is given to the user by - for example - darkening the marker colour. Similarly, every time the Aya is recited correctly the marker is decremented.

It's the user responsibility to increment/decrement the marker.

Additionally, the user should be able to see a summary of all memorisation mistake markers in one view, ideally sorted descendingly by number of occurrence. This help the user focus on the Aya's that needs the most attention.

One more add on is to annonymously share the summary of the mistakes across all the program user to some website. People memorizing a new page for example can go on that site for that page and see in advance what is the most Aya with mistake to focus on it from the get go.

This also provide a chance for people to discuss this mistake. For example, someone might comment on how he connects two Ayas together when memorizing so others can benefit. 

Couple more enhancements

1. Categorization of the mistake and color coding it (Tajweed, Tashkeel, wrong word, etc...).
1. Using the "word" as a unit and not just the Aya. As a peson can have two different types of mistakes in a single Aya.

**Comment by kb-programmer** [comment]
Salaam Alaikum. This is a wonderful recommendation. I just clone this project and I am interested in contributing to in the future In Sha Allah. May Allah reward everyone of you for your contributions, Ameen.

**Comment by murtraja** [comment]
Is this still open?

**Comment by ahmedre** [comment]
jazakAllah khairan - closing for now since we do have the ability to tag ayahs
