### ISSUE TITLE
Reorganize Settings Menu

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#704]

**Comment by ahmedre** [comment]
The settings menu is getting a bit unwieldy.

Thoughts:
1. maybe move "Advanced Options" into a separate screen
2. maybe move "Display Options" into a separate screen
3. move "Volume Key Navigation" under Reading preferences

"maybe" because I could be convinced either way - open to feedback.

**Comment by ahmedre** [comment]
anyone should feel free to work on this and send a PR

**Comment by ozbek** [comment]
> move "Volume Key Navigation" under Reading preferences

+1... OK, no "maybe" there, but still I voted :)

**Comment by ahmedre** [comment]
lol, everything should be considered a maybe :)

**Comment by ozbek** [comment]
> maybe move "Display Options" into a separate screen

Regarding "Display Options", this seems to overlap with "Reading Preferences". For example, "New background" or "Lock screen orientation" could have been in "Reading Preferences", or "Show page info" or "Highlight bookmarks" could be put to "Display Options". 

Only "Arabic mode" does not seem to fit to "Reading Preferences" as that's purely about the UI. Is it not time to remove that option altogether? Android supports Arabic natively now.

**Comment by ahmedre** [comment]
i am good with your PR - but just wanted to comment on the Arabic setting - i personally use this (despite my phone being in English as the default locale) - i think it probably gets a lot of use from:

1. people who speak Arabic fluently but usually converse in English - so they leave their phones in English and just enable Arabic for Islamic apps when the option is there
2. people who are learning Arabic

so i personally would be sad if this went away :(
