### ISSUE TITLE
Improve "translation text size" and "text brightness" settings

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#708]
the easiest thing to do would be to fade the value of text brightness depending on the brightness (and change the text size of the font depending on text size, though that could get unwieldy). alternatively, put a dialog up.

**Comment by MahmoudMabrok** [comment]
how could I start to do this feature?

**Comment by ahmedre** [comment]
i think the main problem with these settings is that adjusting it doesn't give a good idea of what it is adjusted to. it would be nice if the text brightness one changed the text brightness of the setting itself or something, and the text size one changed the size of the text itself (maybe just of the number of the size on the left of the seek bar or something)

**Comment by ahmedre** [comment]
this was already done by @amynbe, jazakumAllah khairan.
