### ISSUE TITLE
Switch Translations to use a RecyclerView

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#710]
`TranslationView` currently uses lots of custom logic to assemble a view on the fly. We should just use a `RecyclerView` here.

**Comment by ahmedre** [comment]
@hakimrie were you still planning to do this or should I?

**Comment by hakimrie** [comment]
@ahmedre I am sorry, I have been quite busy lately. please do so if you have time.
jazakallah khayran.

**Comment by ahmedre** [comment]
fixed in 819b3f5d97036aaecd42d9ae7cd7b800a32eec80
