### ISSUE TITLE
Localization issue in setting screen 

### ISSUE THREAD

**Issue by mhussien86** [quran/quran_android#712]
When changing the app language to Arabic there is missing translation in advanced setting screen.

![15204127_10153852295672024_1093815246_o](https://cloud.githubusercontent.com/assets/5372852/20664812/83a849f0-b565-11e6-80f6-fae9c6d82119.png)

**Comment by ozbek** [comment]
Also, on Android 7, turning Arabic mode on/off is messing up the UI:

![screenshot_20161130-084500](https://cloud.githubusercontent.com/assets/452620/20733964/b0353e90-b6d9-11e6-92d2-117a88cd6977.png)

**Comment by ahmedre** [comment]
for the first one, @mhussien86, can you add the translations to values-ar/strings.xml corresponding to those strings?

for the second one @ozbek i think it it's probably related to over-eager data caching, i'll take a look insha'Allah.

**Comment by mhussien86** [comment]
@ahmedre  Okay i will do it in the coming PR iSA.

**Comment by hosainnet** [comment]
Is this resolved by #718? If so can we close it please?

**Comment by ahmedre** [comment]
yep - closing
