### ISSUE TITLE
BookmarkPresenter always uses cached data if locale layout direction is RTL

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#717]
See [BookmarkPresenter.java line 421](https://github.com/quran/quran_android/blob/7a2b5c3edba4010860cf67a9fd992a821e101dbc/app/src/main/java/com/quran/labs/androidquran/presenter/bookmark/BookmarkPresenter.java#L421).

That's somewhat wrong as we support more than one RTL locale (Arabic, Kurdish, Persian).

**Comment by ahmedre** [comment]
do you think we should actually bother fixing this? it only matters for someone who had their phone as Persian, for example, and then switched to Arabic or Kurdish (then we would maintain the cache), which seems unlikely?

**Comment by ozbek** [comment]
Right. Actually, I never have seen the the problem. I was doing something else, saw the code and thought the logic was weird, and reported here. What you say sounds reasonable. Closing.
