### ISSUE TITLE
Organize toolbar & start Fragment code in activities 

### ISSUE THREAD

**Issue by mhussien86** [quran/quran_android#719]
Move the initialization code of the toolbar from onCreate to a method with name initToolBar() and call the method.

    final Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    toolbar.setTitle(R.string.menu_about);
    setSupportActionBar(toolbar);
    final ActionBar ab = getSupportActionBar();
    if (ab != null) {
      ab.setDisplayHomeAsUpEnabled(true);
    }

And the code for starting fragments to startFragment() method just to clean up onCreate method in activities

    final FragmentManager fm = getFragmentManager();
    final Fragment fragment = fm.findFragmentById(R.id.content);
    if (fragment == null) {
      fm.beginTransaction()
          .replace(R.id.content, new QuranAdvancedSettingsFragment())
          .commit();
    }

**Comment by ozbek** [comment]
Why? In general, method calls are more expensive.

**Comment by mhussien86** [comment]
Yes i know, we need to measure it first and see if it's worth optimization. How much actual time will we save? 
regarding the maintenance and code look it is better.

**Comment by ahmedre** [comment]
closing for now, but feel free to do this @mhussien86  - anyway, planning on getting rid of all fragments at some point in the not-so-distant future insha'Allah
