### ISSUE TITLE
Feature: Add some reciters that read with Warsh an nafi

### ISSUE THREAD

**Issue by ticmaroc** [quran/quran_android#735]
Assalamo 3alaykom warahmato Allahi wabarakatoh,
First, i wanna thank you for this wonderfull project. Jazakaom Allaho khayran
Could you add some reciters that read with Warsh an Nafi.
Regards

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
insha'Allah we'll do this when we publish a Warsh version. until then, we won't because it will confuse the Hafs readers.
walsalam 3alaikum.
