### ISSUE TITLE
Regression in Audio manager

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#738]
Not sure what caused it (yet), but the Audio manager keeps showing progress dialog without any result.

**Comment by ahmedre** [comment]
`getGaplessSheikhObservable` and `getGappedSheikhObservable` were returning null, and in RxJava 2, returning null from functions isn't allowed. cleaned this up to filter out non existent files and not propagating them instead of returning null.

**Comment by ahmedre** [comment]
jazakAllah khairan for pointing this out
