### ISSUE TITLE
Language change buggy on Android 7

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#746]
as reported by @ozbek in #712:

![b0353e90-b6d9-11e6-92d2-117a88cd6977](https://cloud.githubusercontent.com/assets/47771/21538099/306336a0-cd4e-11e6-8c6c-3e22f311c325.png)

**Comment by hosainnet** [comment]
I'll pick this up if not one is working on it

**Comment by ahmedre** [comment]
please go ahead - i imagine it's a static number formatter instance that needs to be cleared and/or reset.

**Comment by zmoustafa** [comment]
Ahmed, have you managed to reset the instance?

**Comment by ahmedre** [comment]
@zmoustafa yes - the problem was that `Locale.getDefault()` was still returning Arabic when switching away from the Arabic setting. the patch merged will invalidate the cache whenever the `Locale` changes as well.
