### ISSUE TITLE
Touching long press at any where gives a highlight

### ISSUE THREAD

**Issue by engamr88** [quran/quran_android#753]
Alsalam Alikom,
When i touch a long press outside the screen anywhere it gives a highlight anywhere in the Sura.

**Comment by ozbek** [comment]
Wa alaikum assalam.

Can you elaborate on "long press outside the screen"?

**Comment by engamr88** [comment]
Can you give me an email or what's app number to send you a video of it

**Comment by ahmedre** [comment]
if you long press not too far from the screen bounds, we usually try to figure out "what's the closest ayah?" and highlight that - you can send an email to quranandroid@gmail.

**Comment by ozbek** [comment]
Yeap, please use the above gmail.com address. Alternatively, you can upload the video to Youtube and post the link here. Thank you.

**Comment by ahmedre** [comment]
brother, did you send the email, i didn't see it? i'll close for now.

**Comment by engamr88** [comment]
Yes I've sent an email thanking you for your clarification ... i didn't
notice that you are detecting the closest Ayah ... Thanks for your good
work
