### ISSUE TITLE
Can't clear aya's selection in phones and tablets with no back button

### ISSUE THREAD

**Issue by hulk9914** [quran/quran_android#754]
Asalamu 3laikum,
While using the app on a tablet with no back button, I selected an ayah with long press but clearing the selection was not possible as I couldn't show the virtual on-screen back button without pulling the drawer from the top of the screen.
I suggest to clear the selection by pressing outside the page boundary (related to #753 )

**Comment by ozbek** [comment]
Wa alaikum assalam.
How is that possible for a device not to have a back button?

**Comment by ahmedre** [comment]
wa3laikum alsalam,
you can always double tap the screen to unselect.
walsalam 3alaikum.

**Comment by hulk9914** [comment]
@ozbek Here's an example of such a device
![](http://tabletmonkeys.com/images/2015/11/Lenovo-Tab-2-A10-30-660x461.jpg)
@ahmedre wa3laikum alsalam, I didn't know that before, Jazakallahu Khairan.

**Comment by ozbek** [comment]
I also just got to know about it :) 
I suggest to add it to Help screen as that is not an obvious _trick_.
