### ISSUE TITLE
Add "More translations..." to drop down spinners

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#760]
an easy way to get to "more translations" would be helpful.

**Comment by uzairmad** [comment]
would this be linking the TranslationManagerActivity to be launched by a spinner item?

**Comment by ahmedre** [comment]
yep!

**Comment by ozbek** [comment]
This one also did not get closed automagically...:\

**Comment by ahmedre** [comment]
yeah need to do fix #... in order for it to automatically close
