### ISSUE TITLE
English Translation typo 

### ISSUE THREAD

**Issue by tahakidwai** [quran/quran_android#781]
English translation of Muhsin Khan & Taqiuddin Hilali in 11:18 there is a typo.

18. "And who does more wrong than he who invents a lie against Allah. Such wi, l be ..."

It should be corrected to

18. "And who does more wrong than he who invents a lie against Allah. Such will be..."

Barak Allah feekum. May Allah accept your efforts.

**Comment by ahmedre** [comment]
another one - sura 27 (Naml) ayah 62 -
"... Or the One who responds to a helpless person when **He** prays to Him and removes distress"

the **He** shouldn't have a capital H.

**Comment by ahmedre** [comment]
sura 30 ayah 24 -
"And it is among His signs that He shows you the **lightening** which causes fear and hope, and that He sends down water from the sky, then He revives the earth with it after its death. Surely in this there are signs for a people who understand"

lightening is misspelled.

**Comment by ahmedre** [comment]
sura 30 ayah 48 -
"Allah is the One who sends the winds, so they stir up a cloud, then He spreads it in the sky however **he** wills, and makes it (split) into pieces. Then you see the rain coming out from its midst. So, once He makes it reach those whom He wills from His slaves, they start rejoicing"

h should be capital here

**Comment by ahmedre** [comment]
Mufti Taqi Uthmani -
sura 56:72 has a "5" in it that shouldn't be there.

**Comment by ahmedre** [comment]
Mufti Taqi Uthmani - 39;44 is not complete.

**Comment by ahmedre** [comment]
Yusuf Ali translation of 11:18. Lie is replaced with life.

**Comment by ahmedre** [comment]
check Abdul Haleem 2:93

**Comment by ahmedre** [comment]
check Abdul Haleem 2:20

**Comment by ahmedre** [comment]
> Another notification concerning the: "Saheeh International translation", in Surah Al-Waqi'ah:[56:85] it's written on my: Quran for Android Application: "And Our Angels" while It seems that "Saheeh International translation" actually says: "And We [i.e., Our angels]", which seems more logical if we translate from Arabic, but the meaning effectively may be the Angels, from the Tafsirs. Can you confirm this please ?

**Comment by ahmedre** [comment]
Yusuf Ali - 10:85 - "our" instead of "out"

**Comment by ahmedre** [comment]
Abdul Haleem - 88:17 - translates ibl as rain clouds - all other English translations use camel

**Comment by ahmedre** [comment]
Sahih Intl - 42:9 - "him" should be "Him"

**Comment by ahmedre** [comment]
copied and merging into #329.
