### ISSUE TITLE
Sharing Qaloon verses uses Hafs text

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#783]
@youssefmehdi @g360230 
was wondering if one of you can help with this - quran.ar.db is what we use when we share Arabic text, but right now, on Qaloon, this is the Hafs database, which is probably not what people are expecting. any suggestions on how to handle this, or should i just disable sharing on Qaloon?

**Comment by g360230** [comment]
salamo aleikom,
First, we suggest to not disable this option now.
For information, this issue will appeared also on warsh version.
we plan to start this task just after finishing our in progress task :
- qualoun: 
  1- audio hodheifi
- warsh:
  1- uploading all image and data base
  2- audio
 If another one want to take this task, it's OK for us.  
Fee amen allah

**Comment by ahmedre** [comment]
ok insha'Allah - i'll fix this one, and please continue the progress for warsh in #629
