### ISSUE TITLE
bengali

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#786]
got this email:

> Dear brothers Jazakumullah for your great app.... While reading 2:70 I noticed a rendering problem in Bengali translation. " মূসা (আঃ) বললেন, তিনি বলেন যে, এ গাভী ভূকর্ষণ ও জল সেচনের শ্রমে অভ্যস্ত নয়-হবে নিষ্কলঙ্ক, নিখুঁত।" The mentioned Bengali part will actually go to 2:71 but its showing on 2:70

**Comment by ahmedre** [comment]
another email:

> 2:72 translation in Bengali language is wrong, plz fixed it.
> I mean in sura baqarah.

![screenshot_2017-01-12-07-51-20](https://cloud.githubusercontent.com/assets/47771/22454993/843139b2-e73e-11e6-9681-d33a3a56088a.jpeg)

**Comment by Sadmansamee** [comment]
I have updated database with additional 2 more database, would you like to upload them?

**Comment by Sadmansamee** [comment]
https://drive.google.com/open?id=0BxbCLALrxOOaR1Zib1h5NXREdUk
This is files for Quran Bangla translation, formatted for Tanzil.

**Comment by ahmedre** [comment]
> Dear I found some error in Bengali translations, sura all imran ayah 28, 

> 3:28- মুমিনগন যেন অন্য মুমিনকে ছেড়ে *কেন* কাফেরকে বন্ধুরূপে গ্রহণ না করে। যারা এরূপ করবে আল্লাহর সাথে তাদের কেন সম্পর্ক থাকবে না। তবে যদি তোমরা তাদের পক্ষ থেকে কোন অনিষ্টের আশঙ্কা কর, তবে তাদের সাথে সাবধানতার সাথে থাকবে আল্লাহ তা’আলা তাঁর সম্পর্কে তোমাদের সতর্ক করেছেন। এবং সবাই কে তাঁর কাছে ফিরে যেতে হবে।

> It will be *কোন*

> Also I found many words like this if you need I may help you to find the error.

**Comment by ahmedre** [comment]
got an email about a mistake in 3:81

**Comment by ahmedre** [comment]
missing sura Yusuf ayah 50?

**Comment by ahmedre** [comment]
closing because replaced Bengali translation with the quranenc one on 4/10/2020.
