### ISSUE TITLE
Uzbek translation issue

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#788]
> Сод сурасининг (38-сура) 54- ояти бундай ёзилган *Албатта, бу Бизнинг (берадиган) ризқимиздир. Унинг ъеч тугаши йщқдир.*... Бу оятда (хеч-ъеч) (йщқдир-йўқдир) шундай қилиб тузатилсин! 

cc @ozbek

**Comment by ozbek** [comment]
Fixed (please remove the `.zip` extension).

[quran.uz.db.zip](https://github.com/quran/quran_android/files/738449/quran.uz.db.zip)

**Comment by ozbek** [comment]
@ahmedre, is there any additional info/change required for this?

**Comment by ahmedre** [comment]
nope, i'll take care of it this weekend insha'Allah

**Comment by ahmedre** [comment]
sorry for the delay, this is done - jazakAllah khairan
