### ISSUE TITLE
removing headphones doesn't pause audio

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#790]
this is bad, we should pause audio if the headphones are disconnected. we actually have code for this, so there's some bug causing it to not be triggered (the whole "becoming noisy" bits).

**Comment by ozbek** [comment]
The last time I checked, this was working. 
Any info on the device details, Android version?

**Comment by ahmedre** [comment]
i got an email about it and just tried and was able to repro on my pixel running the latest Nougat.

**Comment by hosainnet** [comment]
Just reproduced on a 5X, 7.1.1
I can have a look at this
