### ISSUE TITLE
Hizb inconsistency on page

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#793]
the mus7af shows the juz'/page at the top of the page, not the one at the bottom. a good example is page 121, where juz' 7 starts at the last ayah - the mus7af shows "juz' 6" at the top - we also show juz' 6.

the tricky part is the hizb - juz' 7 is hizb 13 - juz' 6's last hizb is 12. we show "juz' 6, hizb 12" which is confusing to people.

not sure what the right approach is here... options:
1. ignore it
2. hide the hizb when juz' is changing (my preferred option if there's no better solution)
3. show juz' 6 / hizb 12 (maybe... but i prefer option 2)
4. show juz' 7 / hizb 13 (against this though because juz' 7 is different than what the mus7af shows)

thoughts?
walsalam 3alaikum

**Comment by Ahmed9914** [comment]
و عليكم السلام

This case happened just twice along all the 30 juz's, So I think it's better to ignore it.
Just an opinion.

و جزاكم الله خيرا.

**Comment by ahmedre** [comment]
sounds good, let's just ignore it for now then. if a lot of people complain, we can just remove "hizb" from only those 2 cases (basically any case where the juz' doesn't start at the top of the page - sura ma2ida has one and tawbah has the other).
