### ISSUE TITLE
Tag re-appears after deletion

### ISSUE THREAD

**Issue by fikr4n** [quran/quran_android#803]
How to reproduce:

1. Create a named tag of an ayah
2. Delete the named tag in Bookmarks tab
3. Go to any Quran page before the snackbar disappears
4. Approximately 5 seconds later, back to Bookmarks tab

Expected: the deleted tag has disappeared

Actual: the deleted tag re-appears, but as unnamed tag

Version: 2.7.4 (madani)

**Comment by ahmedre** [comment]
jazakAllah khairan for this - i am trying to repro but can't.

if you are referring to the "Not Tagged" section, that's only there when a bookmark exists without a tag. since deleting a tag doesn't delete the bookmarks underneath (and only de-associates the tag from all its bookmarks and then delete the tags), that bookmark moves to the "Not Tagged" section (which may be hidden if you have everything with a tag before removing it).

does that make sense or am i missing a bug somewhere? jazakAllah khairan.

**Comment by fikr4n** [comment]
![join_1000](https://cloud.githubusercontent.com/assets/5564999/22736087/2dd0045c-ee2f-11e6-8410-2a3dec124627.png)

I thought it was a bug, because usually it is gone after I delete it instead of become unnamed bookmark ("Not Tagged"). So it is a feature :D. Why is not it deleted directly?

**Comment by ozbek** [comment]
You are deleting a bookmark, but not a tag (as was assumed by @ahmedre). Appears to be a bug.

**Comment by fikr4n** [comment]
Hmm... it's okay, it's my mistake, I misunderstood the feature 😄.

Is there any reason that deleting a tag causes it become "Not Tagged" instead of really deleting it (deleting the bookmark as well)?

**Comment by ozbek** [comment]
As far as I can see, there are 2 things:
 - Tag: deleting it will simply remove it, but bookmarks will be kept
 - Bookmark: deleting it will/should remove it all together.

OP is about the second one. So, that's a bug.

**Comment by ahmedre** [comment]
i think removing a bookmark only deletes it when not "grouped by tag" - if "grouped by tag," i take it to mean "untag" instead of "remove the bookmark" - but am willing to change this if you think this makes more sense.

**Comment by ozbek** [comment]
Hmm... there is a tag button to clear or re-tag tags. Users can use that button to _untag_. I think, deleting a bookmark should remove it.

**Comment by haroonrasheedjava** [comment]
Dear brother

Assalaamu 'Alaykum,  My kinds have created vague tags and they look awkward when I try to tag an Ayah. How do I delete unwanted tags?

**Comment by Ahmed9914** [comment]
@haroonrasheedjava 

و عليكم السلام و رحمة الله و بركاته

You can long press on the aya you want to untag, then choose tag, then uncheck the unwanted tag, now you made the aya bookmarked but un-tagged.

**Comment by haroonrasheedjava** [comment]
That feature is working as expected. I want to delete the tags which are
untagged, they're still available as tag options if I try to tag another
aayah.

How do I delete them?

جزاك الله خيرا

**Comment by shaikq** [comment]
https://github.com/quran/quran_android/issues/961 please refer this issue, it shows how to delete tags.

**Comment by haroonrasheedjava** [comment]
Doesn't work, deleted bookmarked tags re appear when I tag another aayah

**Comment by ahmedre** [comment]
this is easy to fix, but may have unintended consequences. consider for example a bookmark with two tags, "one" and "two" - also, let's say that "group by tags" is enabled.

you'll see something that looks like:

![screenshot_1529754835](https://user-images.githubusercontent.com/47771/41809377-a574f7d0-76fd-11e8-8028-a656f0076977.png)

today, if i long press the ayah under "one" and choose to delete, it will leave it under "two." with this change, if i long press the ayah under "one" and choose to delete, it will delete it from both (which could be confusing?)

thoughts? cc @ozbek

**Comment by ahmedre** [comment]
closing for now, please feel free to re-open for discussion if you think this behavior should change.
