### ISSUE TITLE
Write a unit test for AudioUtils

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#804]
i introduced a crash a8f2b2d742026a542b8751a622252e584e6e72b6 that i fixed in 02c953d91b3dcae6a2bf6a808854d2d5921986be. a unit test would have easily caught this.

i think the steps here are:
1. change the class to a Singleton class
2. inject the context so we don't have to pass it along everywhere
3. add tests for some of these methods and document them

**Comment by hosainnet** [comment]
Happy to pick this up

**Comment by hosainnet** [comment]
@ahmedre when you say turn it into a Singleton, you mean via Dagger or just by plain Java?

Also I presume this involves turning static methods to instance methods?

**Comment by ahmedre** [comment]
either one - preferably dagger though.

so it'd look like:

```
@Singleton
public class AudioUtils {
    @Inject
    public AudioUtils(Context appContext) {
    }
}
```

and then when you want to use it (i.e. in `PagerActivity` for example), you'd just do

`@Inject AudioUtils audioUtils;`

since `PagerActivity` already deals with injection for you, you should be able to use it easily whenever you need it.

**Comment by MahmoudMabrok** [comment]
is still this open to work on it? @ahmedre

**Comment by ahmedre** [comment]
I guess it's already done some time ago here: https://github.com/quran/quran_android/blob/master/app/src/test/java/com/quran/labs/androidquran/util/AudioUtilsTest.kt

will close this but am happy to accept PRs with more tests added to this or anywhere else.
jazakumAllah khairan.
