### ISSUE TITLE
Spelling mistake in Russian translation (Kuliev)

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#807]
The fix is very minor.

from
> 18:7. Воистину, все, что есть на земле, Мы сделали украшением для нее, чтобы испытать людей ивыявить, чьи деяния окажутся лучше.

to
>18:7. Воистину, все, что есть на земле, Мы сделали украшением для нее, чтобы испытать людей и выявить, чьи деяния окажутся лучше.

Attached is the fixed db (please remove the .zip extension).
[quran.ru.kuliev.db.zip](https://github.com/quran/quran_android/files/787208/quran.ru.kuliev.db.zip)

**Comment by ahmedre** [comment]
jazakAllah khairan, updated.

also, please note i also ran:
`update properties set value=3 where property='text_version';`
