### ISSUE TITLE
translation names cut off in spinner

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#809]
this is via an email report i got in

![screenshot_2017-02-21-10-44-46](https://cloud.githubusercontent.com/assets/47771/23199691/cfb3bc64-f884-11e6-9adf-f2d2e053f07c.png)

**Comment by ozbek** [comment]
Why the spinner is not using localized name?

**Comment by ahmedre** [comment]
good question, i am not sure - maybe it has to do with when he downloaded the one that is showing in Arabic versus the others

**Comment by ozbek** [comment]
This did not get closed automatically...

**Comment by ahmedre** [comment]
jazakAllah khairan
