### ISSUE TITLE
File name is shown instead of translation's (or translator's) name

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#810]
Occasionally, instead of translation's or translator's name, database file name is used. It's OK most of the time, but happens fairly frequently.

![screenshot_20170224-211200](https://cloud.githubusercontent.com/assets/452620/23303363/068fcaa8-fad7-11e6-9162-4154c0f59d9f.png)

**Comment by ahmedre** [comment]
is this still happening @ozbek? usually this is the fallback case though when the other information isn't there still.

**Comment by ozbek** [comment]
I don't see the translators' name at all now :-\\

![Ikhlas](https://user-images.githubusercontent.com/452620/78418179-c1ec6380-7674-11ea-84a0-29774be54f32.jpg)


(debug build from master HEAD is OK)

**Comment by ahmedre** [comment]
yes i broke it recently and fixed in #1295 - still need to push to production at some point though

**Comment by ozbek** [comment]
JazakAllah, it's fixed then.
