### ISSUE TITLE
downloading when screen is off

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#812]
i got this via an email but haven't confirmed it yet - if i have to guess, this maybe a valid bug and we should look into it.

on a Pixel on Android 7.1.1:

> I've noticed that download keeps going as long as you watch it. It gives network error and tried to resume. If you're on that screen, keeping it awake, it will resume. Otherwise it gives error and cancels download. I also remember that it was like this for my last device as well. Note that I set my wifi to stay on even when phone sleeps.

we should check this - this might be something related to all the doze mode optimizations.

**Comment by ozbek** [comment]
Not reproducible on Nexus 5X with Android 7.1.2.

**Comment by ahmedre** [comment]
will have to play with it some more - doze mode will kick in at some point - first in partial doze mode (in which we may still have network access - i am not sure though), and then in full doze mode (when we'll lose access). i guess the question is whether or not we currently gracefully handle and resume from these situations.

i think for our testing purposes, we'll either have to test with the command line adb commands to trigger doze mode and app standby:

`adb shell dumpsys deviceidle force-idle`
`adb shell am set-inactive <packageName> true`

as an aside, it's worth noting that the download service is not a foreground service (unlike the audio service), and as thus, we can actually enter app standby mode while a download is underway.

**Comment by ahmedre** [comment]
a lot of how this code works changed in the past 3 years, so closing for now.
