### ISSUE TITLE
Translation view: jumping disables action bar spinner

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#834]
1. Open the app in translation mode
2. Select 'Jump' menu and go to any page
3. Observe that action bar is no more a spinner and one can not (de-)select translations.

**Comment by Ahmed9914** [comment]
@ozbek This is fixed now. Please close.

**Comment by ozbek** [comment]
Uh huh? Why is this not auto-magically get closed? Probably, should have used the magic word (`Closes #834` or `Fixes #834`) in the PR :)
