### ISSUE TITLE
am i allowed to upload this project to my playstore account ?

### ISSUE THREAD

**Issue by muafakul** [quran/quran_android#839]
am i allowed

**Comment by ozbek** [comment]
Why would you want to do that?

**Comment by muafakul** [comment]
i want to join all feature include as sunnah and al qur an

**Comment by nyitgroup** [comment]
People ask for that but I think it is better to work together and improve one app.

**Comment by ozbek** [comment]
> i want to join all feature include as sunnah and al qur an

Yes, you can make modifications, build a new app and publish in Play Store. However,

 - you will need to open source your modified app (as per the license)
 - the network resource end points are hard-coded in the app which means, unless you redirect the traffic to your own network, your app will still depend on this project's maintainers servers (for whom maintaining the servers does not come for "free")

**Comment by muafakul** [comment]
but , am i allowed to monetize the modificated source then the earning i will donate to suriah , idlib and other country that need help

**Comment by nyitgroup** [comment]
According to the License [https://github.com/quran/quran_android/blob/master/LICENSE](License)
You can use the code for commercial gain. The question is how are you going to do it. Some people just put ads everywhere which would not be nice.

**Comment by Abdullah076** [comment]
ads are annoying & disturbing for islamic apps.
many times a improper picture of non-mahram woman may appear in ad; which is not at all expected by islamic app users specially in Quran app.
so I am strongly agianst ads.
if someone want to monetize, he can make the app paid. or make option to donate if any one wants to. but not by ads!

**Comment by nyitgroup** [comment]
That is interesting. Why isn't there a donation button on the current app? 
We can call it buy coffee for the developers? 5$
You guys work hard. I would not mind donating.

**Comment by muafakul** [comment]
maybe i will block the porn ads sources ,but let me add the ads outside the main quran ,

**Comment by ahmedre** [comment]
@muafakul:

please don't do this -
1. this is disrespectful to the book of Allah
2. you are profiting off the efforts and work of many people who put hard work and effort to provide this app to people for free. this is not right morally or otherwise. we open sourced this app so people can contribute code or learn how to do things in their own apps, not so they can profit off of our work.
3. there is an ongoing cost to maintaining this app (servers cost money every month, and pages and audio download from our servers).
4. the materials we use (pages, audio, translations, etc) have licenses - most people don't mind using their data in a free app, but would be unhappy about profiting from their efforts and work.

if you want to use ads, please write your own app without using any of our code or content.

**Comment by Abdullah076** [comment]
even if you block porn ads; there is chance that images of non-mahram may appear. cause for muslims we have to lower our gaze. 
it includes women who may not be in improper dress; but her hair/face is open. 
i dont think there will be any way to block all woman (i dont mean porn; i mean every improper/proper woman without hijab). 
that is unexpected by islamic app users. they dont use islamic apps to do zina of eyes, right?

**Comment by Abdullah076** [comment]
brother, ahmed i recently wanted to donate on your Quran project. but the donation is showing that you dont accept donations.
can you tell me how can i donate in your app?

**Comment by ahmedre** [comment]
jazakAllah khairan @Abdullah076 - we don't have a donation option right now, most importantly, please keep us in your du3a insha'Allah :)

**Comment by ahmedre** [comment]
closing, please re-open if necessary

**Comment by thawri1** [comment]
excuse me for reopening. @ahmedre 
I am hired to develop a Quran app in a specific language. I am working on it from scratch and different UI. this app will be free and without ads inshallah.
can I use some portion of the codes or some classes (for example QuranInfo, QuranDataSource, MadaniDataSource, etc)?
can I use databases and other data?
if I use them, must open source all codes?
I don't know much about licenses and my boss does not like to open source the project.
