### ISSUE TITLE
audio download manager

### ISSUE THREAD

**Issue by nyitgroup** [quran/quran_android#843]
I think that is one of the most important and confusing parts of the app. People should have the option to download the entire Quran for one reciter in an easy way. Why is it hidden in the settings from the average user? 
 Also it would be nice to have better control in that screen. For example click on a reciter and delete a sura or more. 
Another option is to list the sura and which ones are downloaded and when clicked which reciter to keep or delete. 
Even in the Quran reading page. You don't have any indication of reciters that are already available and ones that need to be downloaded. Maybe the spinner can have the downloaded reciters at the top with a green background color.

**Comment by ozbek** [comment]
> Why is it hidden in the settings from the average user?

Where would you have it?

**Comment by nyitgroup** [comment]
In the menu of the first activity of the App would be a good place to put a menu item to point to Audio Download.

**Comment by murtraja** [comment]
@ahmedre Shoudn't this issue be closed?

**Comment by ahmedre** [comment]
jazakAllah khair - closing, will consider making it visible from the reciters screen at some point
