### ISSUE TITLE
Farsi translations are incorrect & incomplete

### ISSUE THREAD

**Issue by bateni** [quran/quran_android#848]
I noticed that many strings are not translated to Farsi, and among those translated many are not correct.

- There are things that are plain wrong: horizontal vs vertical, before vs after, etc.
- There are sentences that do not make sense in the context.
- There are many spelling errors (use of Arabic Ya with two dots under it instead of the Farsi Yeh, e.g.).
- ZWNJ is missing in a lot of words.
- Sometimes the substitution arguments like %1$s, %2$d are placed in the wrong part of the sentence.

**Comment by bateni** [comment]
I have fixed most of these and sent the pull request #847.

**Comment by ahmedre** [comment]
merged, jazakAllah khairan
