### ISSUE TITLE
Add option for Auto-updating translations and tafaseer

### ISSUE THREAD

**Issue by Ahmed9914** [quran/quran_android#855]
السلام عليكم
If a translation (or tafseer) database is updated, existing users are not notified about this update until they open the translations list manually and find that their is an available update.
So, can we add an option to automatically check for translations updates and notify the users about them.
و جزاكم الله خيرا.

**Comment by ozbek** [comment]
Wa alaikum assalam.

Why? [`QuranActivity.updateTranslationsListAsNeeded()`](https://github.com/quran/quran_android/blob/master/app/src/main/java/com/quran/labs/androidquran/ui/QuranActivity.java#L274) does. Are you testing against the master branch HEAD?

**Comment by Ahmed9914** [comment]
This issue occurred on the last pushed version into play store, I was searching for an aya tafseer through Al-Sa3di tafseer and it wasn't available, later I found that it was added in another issue ticket. Then I opened the list of translations and tafseers and found there is an update available for this tafseer however it wasn't updated automatically.

Thats why I opened this issue. 
Can you reproduce this on any recently updated translation which was already downloaded before?

**Comment by ahmedre** [comment]
the check occurs once every 10 days. it shows a dialog box that you might have missed if there's an update.

to be safe, we can write a unit test to make sure this works as expected

**Comment by Abdullah076** [comment]
else a manual "check for updates" option can be added in settings. some apps used this feature.
Using this users can check for updates after some times in sha Allah. Also a option can be added that, if update checking isnt done manually for 10/15 days, it will show a notification for checking updates.

**Comment by ozbek** [comment]
To manually check for new updates, hold and swipe down the list while at the top of the Translation Manager screen.

**Comment by Abdullah076** [comment]
yes, got that. but that would update only translations databases right? it wont update the audio databases i think.
what i saw in a app that it checks for update for audio and trans dbs.
also if it this option is present in setttings; then the checking for updates will be more user-friendly i guess.
