### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by drisschobix** [quran/quran_android#858]
Hello I face this issue when I want to build the  application.
Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.

![capture](https://cloud.githubusercontent.com/assets/24933959/25305613/843cea5a-2776-11e7-8b37-500ccfc9bb1c.JPG)

**Comment by Ahmed9914** [comment]
please check this https://github.com/quran/quran_android/issues/693
