### ISSUE TITLE
[Qaloon][Warsh] Some juz' don't point to the right places

### ISSUE THREAD

**Issue by g360230** [quran/quran_android#859]
Some juz' don't point to the right places
@ahmedre : The correction will be made in data base or in the source code ?
The table below lists the error list

| hezb | current soura number | current Aya number | current page | new Sourat number | new Aya number | new page |
| --- | --- | --- | --- | --- | --- | --- |
| 7 | 3 | 93 | 62 | 3 | 92 | 62 |
| 10 | 4 | 88 | 92 | 4 | 87 | 92 |
| 10,25 | 4 | 100 | 94 | 4 | 97 | 94 |
| 10,75 | 4 | 135 | 100 | 4 | 140 | 100 |
| 12,5 | 5 | 51 | 117 | 5 | 49 | 116 |
| 13,5 | 5 | 109 | 126 | 5 | 111 | 126 |
| 19,25 | 8 | 61 | 184 | 8 | 60 | 184 |
| 20,5 | 9 | 60 | 196 | 9 | 61 | 196 |
| 22,25 | 10 | 53 | 214 | 10 | 49 | 214 |
| 23 | 11 | 6 | 222 | 11 | 1 | 221 |
| 24,75 | 12 | 30 | 238 | 12 | 23 | 238 |
| 25,75 | 13 | 5 | 249 | 13 | 1 | 249 |
| 28,25 | 16 | 75 | 275 | 16 | 79 | 275 |
| 30,5 | 18 | 32 | 297 | 18 | 30 | 297 |
| 33,25 | 21 | 29 | 324 | 21 | 30 | 324 |
| 35,25 | 23 | 36 | 344 | 23 | 39 | 344 |
| 37,25 | 25 | 53 | 364 | 25 | 45 | 364 |
| 37,25 | 26 | 181 | 374 | 26 | 160 | 374 |
| 40,25 | 28 | 76 | 394 | 28 | 71 | 394 |
| 41,5 | 30 | 31 | 407 | 30 | 30 | 407 |
| 42,5 | 33 | 6 | 418 | 33 | 1 | 418 |
| 43,25 | 33 | 51 | 425 | 33 | 49 | 424 |
| 48,5 | 41 | 9 | 477 | 41 | 1 | 477 |
| 50,5 | 44 | 17 | 496 | 44 | 25 | 497 |
| 56,25 | 63 | 4 | 554 | 63 | 9 | 555 |
| 57,75 | 70 | 19 | 569 | 71 | 1 | 570 |
| 60,75 | 100 | 9 | 599 | 101 | 1 | 600 |

**Comment by ahmedre** [comment]
this change has to be made in the code - we'd change `QuranData` in a similar way to how we did it for naskh and override these.

**Comment by g360230** [comment]
Can you tell me which function iplemented exactly?

**Comment by ahmedre** [comment]
you don't need to implement any functions - you just need to do something similar to what we did here in naskh:

https://github.com/quran/quran_android/blob/master/app/src/naskh/java/com/quran/labs/androidquran/data/QuranData.java

override the arrays that you need, populate them with all the data just exactly like the naskh one did (all the suras are on different pages on naskh, and naskh is not 604 pages).
