### ISSUE TITLE
How can i Change its package name and Run For Release

### ISSUE THREAD

**Issue by Adnan-addi** [quran/quran_android#862]
I download the source and try to change its package name , but after doing that the app is running in debug mode , i want to run it for release mode and want to build my own signed apk , How can i do that in this particular project as there are a lot packages in its src folder , and how to update gradle so that it does not run in developer mode and does not generate lint app for debug , i want to rebrand it for my people here . ?

**Comment by ozbek** [comment]
First of all, thanks for your interest on the project.

The main purpose of open sourcing the project is to get as many developers as possible to support it and make the app useful to wider audience. From what you have wrote, I assume there is something that you don't like about the app. What is that? Maybe we can fix that "problem" faster/better here and make the app acceptable for your people there? I mean, what is the reason you want a re-branded app and not the one this project is providing?

**Comment by Adnan-addi** [comment]
Salam , there is no issue with the app . I want to rebrand it and make it
colourful for the children youngers one as colors will attract more
children.  i run a school here in my town . i searched this as open source
and want to re engineer and build for my young ones . I appreciate your
efforts in this project. you have done a lot more for this humanity . and
muslims all over the Globe. May Allah bless you .

**Comment by Abdullah076** [comment]
wa'alaykumus salaam.
though i am not part of the Quran for Android team.
however, i have a request.

if you ever re-brand it & make a new one based on it; kindly dont include any ads. as ads are very disturbing for islamic apps. also dont make it a paid app. make it a free app with no ads.
however, you may add option for optional donation in the app, if anyone wants to donate.

**Comment by ahmedre** [comment]
+1 on @Abdullah076's request, and please add links back to the various sources.
jazakAllah khairan.

**Comment by tetouanweb** [comment]
hello
if i need to buy the code source to make release app, how much ??

**Comment by ozbek** [comment]
@tetouanweb: maybe this verse answers your question: https://quran.com/26/109? In other words, the source code is not on sale :)

**Comment by tetouanweb** [comment]
Sorry, but do not take the words as if I speak to you as a salesman of religion, my question and just because I want to participate in the publication of the Qoran from my website with your project.

And even if I pay what I can pay, I can never pay such a book as the Qoran.
I am a Muslim from Morocco, a country in the north of Africa if you do not know it, and I have seen the edition available on your project which prompted me to even ask what I said and because That I find a copy of your project sell on a website.

جازكم الله خيرا و أدخل عليكم هدا الشهر بالمغفرة و الأجر العظيم

**Comment by ozbek** [comment]
Where did you see it being sold?

**Comment by tetouanweb** [comment]
can i send you private msg ?

**Comment by tetouanweb** [comment]
i send u the link in mail !! ok it's possible ?

**Comment by ozbek** [comment]
Yes, please mail to quranandroid@gmail.com

**Comment by tetouanweb** [comment]
i have send u a mail

**Comment by tetouanweb** [comment]
i hope that i have give u a good information

**Comment by tetouanweb** [comment]
what new on my link, it's true or not ?
