### ISSUE TITLE
Immersive mode not needed in some cases Naskh app

### ISSUE THREAD

**Issue by asimmohiuddin** [quran/quran_android#863]
Currently at least on the Naskh version immersive mode is enabled to allow for pages to fit the whole screen. The "longest" pages currently used have an aspect ratio of 16 by 9. Considering new devices like Galaxy S8 and LG G6 have an aspect ratio greater than 18 by 9, they don't need the screen space created when immersive mode is enabled. For such devices it would be best to turn off immersive mode.

**Comment by ahmedre** [comment]
i think @ozbek wanted to add an option for always being able to enable (or disable) immersive mode from settings - if we do that, we don't have to bother here then (except maybe as a "best option for a default?")

**Comment by asimmohiuddin** [comment]
@ahmedre @ozbek I think a default option for all apps should be no immersive mode except for Naskh on devices that use 16:9 aspect ratio or less

**Comment by ahmedre** [comment]
i made this a setting for now (but i don't do any special defaulting to off for devices with x on naskh - it basically defaults to off, except for naskh).
