### ISSUE TITLE
[ALL] Update audio and database files

### ISSUE THREAD

**Issue by g360230** [quran/quran_android#866]
Actual vesion of quran android doesn't support update for both audio files and database.

**Comment by g360230** [comment]
Is it better to update file in application startup as for page update or when playing file?
It is obvious that some file download is to be done on startup to identify audio file to be updated.
Is it correct?

**Comment by ahmedre** [comment]
yes, what i was thinking to do was to build a web service to keep the versions - then we'd just version via the filename. we'll do this for both the iOS and Android apps insha'Allah.

most likely, it'll be easier to just update when we play the audio.

**Comment by ahmedre** [comment]
we've had this for pages and translations from a long while back.
as for audio, it was just done in #1318. should be in the next release in sha' Allah.
