### ISSUE TITLE
Ayah Verification

### ISSUE THREAD

**Issue by OmarShoaib** [quran/quran_android#868]
Assalam O Alaikum,

First of all,  I really appreciate your efforts on this app. 

Can you please verify the highlighted part in the below screen shot (taken from you app). Also Kindly re-verify the app's content as this is very sensitive app.

![screenshot_2017-05-14-19-35-58](https://cloud.githubusercontent.com/assets/28688176/26034969/9ed89e80-38de-11e7-827b-f7f573478f9e.png)

Thanks

**Comment by Abdullah076** [comment]
wa'alaykumus salaam.
can you mention what is wrong here brother?

**Comment by OmarShoaib** [comment]
There is a "tashdeed" over "vaao"  of "vanahar" when I heard the audio and tele this with QUR'AN MAJEED as well... 

Apology if I misspelled the words... It's just for the hint..

**Comment by ahmedre** [comment]
wa3laikum alsalam,
we are using the madani mus7af script from quran complex, which prints the mus7af for many parts of the muslim world. as far as we know, there are no mistakes in the images that we're using. i am guessing, however, that you're used to reading the naskh script. both the madani script and the naskh script are completely valid and are both found in masa7if in masjid al 7aram and masjid al nabawi.

if you are more used to reading the naskh mus7af, please check out our naskh app here:
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran.naskh

it's the exact same app, but uses the 15 line naskh style writing, which you maybe more used to.
here's a photo taken from a madani mus7af that is exactly the same as what's used in this app:

![2017-05-14 10 34 35](https://cloud.githubusercontent.com/assets/47771/26036371/3b45c3ea-3891-11e7-8130-82cf0366339c.jpg)

here's the same verse from the naskh mus7af (and [this](http://android.quran.com/data/naskh/width_1280/page532.png) is the full page:
<img width="319" alt="screen shot 2017-05-14 at 10 37 13 am" src="https://cloud.githubusercontent.com/assets/47771/26036375/57d8598c-3891-11e7-8f56-0aba712f4006.png">


walsalam 3alaikum.

**Comment by ahmedre** [comment]
closing, please re-open if you have any additional questions about this.
