### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by tetouanweb** [quran/quran_android#872]
Asalamo 3alaykom

i love ur app very much, and i have download it to get AJJR for you and for me by publishing it.

but when i have lunch android studio, i got this error : 

Error:Execution failed for task ':app:fabricGenerateResourcesMadaniBeta'.
> Crashlytics Developer Tools error.

**Comment by ozbek** [comment]
Wa alaikum assalam.

Possible duplicate of #693.
