### ISSUE TITLE
How can i make a release !!

### ISSUE THREAD

**Issue by tetouanweb** [quran/quran_android#873]
Hello

I am very happy to see like this product on the net, what drives me to ask a question may be that it is stupid, but I will pose it as same.
How can I make a release for this application to be able to publish it for free on the play store has to have AJR in God, which makes you also you will have more AJR.

sorry for my bad english ;-)

**Comment by tetouanweb** [comment]
if there is a way to buy it, how much that will cost and thx for ur jobs

**Comment by MamdouhRElNakeeb** [comment]
It's already published for free on the play store
https://play.google.com/store/apps/details?id=com.quran.labs.androidquran

**Comment by tetouanweb** [comment]
i know that, why u get not chance to us to get AJR with God ???

**Comment by MamdouhRElNakeeb** [comment]
I'm just telling you, I thought you don't know.
You can contact the developer directly and ask him for more details.

**Comment by tetouanweb** [comment]
thx for replaying to my post, i will wait the reply of the developper :)

**Comment by ozbek** [comment]
> How can i make a release !!

Is that a technical question?

**Comment by tetouanweb** [comment]
no, my question is how to get release apk with name package personnel if it's possible

**Comment by ozbek** [comment]
Yes, I read your question. What do you mean «how»? Just change it :)

**Comment by tetouanweb** [comment]
i don't have a good english, my question mean how can i got solution to make a release apk signed

**Comment by ozbek** [comment]
This indeed looks like a technical question.... If you don't know how to change the package name, I think, it'd be better if you seek help around yourself. This place is for issues and enhancements about Quran Android application (https://play.google.com/store/apps/details?id=com.quran.labs.androidquran). Anything else is beyond the scope of this project.

**Comment by tetouanweb** [comment]
ok thx for replying to my question :) see you !!! 

u can close this sujet :)

**Comment by ozbek** [comment]
> u can close this sujet :)

You can close it yourself. Simply press the "Close issue" button at the bottom of the comment input form.

![github-close-own-issue](https://cloud.githubusercontent.com/assets/452620/26181391/aed8758e-3baa-11e7-8a87-5b1d5a13ac35.png)

**Comment by naveed-ahmad** [comment]
@tetouanweb app this already available, and FREE. Why not contribute if you really looking for AJAR ?
 
## Few more ways to earn ajar could be:
- Install the app, and learn/listen the Quran
- Promote the app within your circle, family/friends etc.

**Comment by tetouanweb** [comment]
i'm with you on ur saying, just when i have find it on a website in sold, that why i have ask for it.

big regards to team for this great job
