### ISSUE TITLE
✓ •New audio translation that I'm eager to do!

### ISSUE THREAD

**Issue by enisbc** [quran/quran_android#875]
Following text is an email from enisbc@gmail.com (me):
"I have been working on the audio translation of Bosnian's great scholar Besim Korkut (p.a. Baseem Corecoot). Throughout my project, the following idea came across my mind: Could I separate that translation on ayahs and submit it to You for further process and, eventually, publish. I have seen option on qariah menu for an English translation, and my "why not" momentum emerged. So 10 minutes ago I have successfully separated Suratul-Fatihah to ayahs, renamed them properly, and overwrote them over Saad al-Ghamdi's audio. It worked perfectly fine. So, insha-Allah, one of my high- priority​ plans for Ramadan is to separate the whole Qur'an to ayahs and make Besim's audio translation widely accessible. So my question stands: if I start separating the Qur'an, and when it's finished, will You, my brothers, publish that translation?
I will attach seven ayahs of translation to check out. They are with lower qualities, but for the sake of storage (and I couldn't find any better)."
And I had sent 7 audio attachments for every ayah.

**Comment by enisbc** [comment]
Forgot to say: email was sent to quran.android@gmail.com.

**Comment by Abdullah076** [comment]
though i am not a member Quran android team, but i want to mention that the audio translation is already available in verse by verse format here. 
http://www.everyayah.com/data/translations/besim_korkut_ajet_po_ajet/
so i dont think you should put your energy to the already done task. instead you may do other things if you want in sha Allah.
may Allah accept your intention brother

**Comment by ozbek** [comment]
> Forgot to say: email was sent to quran.android@gmail.com.

This projects official email address is quranandroid@gmail.com (no period between the two words).

**Comment by enisbc** [comment]
Thanks #Abdullah 076, sure you saved me enormous amount of time. Now all I have to do is to rearrange ayahs by folders. Thanks again and السلام عليكم

**Comment by enisbc** [comment]
Did it! Copies as Saood Ash-Shuraym (17). If I could only change his name

**Comment by enisbc** [comment]
Thanks #Abdullah 076, sure you saved me enormous amount of time. Now all I have to do is to rearrange ayahs by folders. Thanks again and السلام عليكم
