### ISSUE TITLE
خطأ في التلاوة من قبل الشيخ ماهر المعيقلي

### ISSUE THREAD

**Issue by technomacx** [quran/quran_android#878]
أتمنى أن يكون هذا المكان المناسب للتنبيه على مثل هذه الأخطاء

(فَأَقْبَلَتِ امْرَأَتُهُ فِي صَرَّةٍ فَصَكَّتْ وَجْهَهَا وَقَالَتْ عَجُوزٌ عَقِيمٌ)
[سورة الذاريات 29]
خطأ في لفظ كلمة (صَرَّةٍ)

(مَثَلُ الْجَنَّةِ الَّتِي وُعِدَ الْمُتَّقُونَ ۖ تَجْرِي مِنْ تَحْتِهَا الْأَنْهَارُ ۖ أُكُلُهَا دَائِمٌ وَظِلُّهَا ۚ تِلْكَ عُقْبَى الَّذِينَ اتَّقَوْا ۖ وَعُقْبَى الْكَافِرِينَ النَّارُ)
[سورة الرعد 35]
خطأ في لفظ كلمة (الْجَنَّةِ)

**Comment by ahmedre** [comment]
merging into #204
