### ISSUE TITLE
Importing the project in Eclipse

### ISSUE THREAD

**Issue by WailB** [quran/quran_android#884]
كل عام وانتم بخير جعلنا الله واياكم من صوام هذا الشهر الفضيل وقوامه ومن العتقاء من النار.

I have a problem with importing the project to eclipse. I have all required android SDK files and downloaded the latest gradle plug-in. I ran the gradlew.bat file that came with the files since I am working in windows. But when I import the project I get the following error:

`Synchronize Gradle projects with workspace failed due to an error in the referenced Gradle build. Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-all.zip'.  A problem occurred configuring project ':app'. SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

Also this:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED
```

I would appreciate any help on this issue.

**Comment by fikr4n** [comment]
First of all, I am not using Eclipse anymore.

> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

> Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Based on the message, just set the Android SDK location to where you place your Android SDK.

**Comment by WailB** [comment]
Thank you for your response. Where should set the android SDK location for gradle in eclipse? In general its already set in eclipse since I am already compiling other android projects currently.

**Comment by fikr4n** [comment]
> Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by WailB** [comment]
Thank you. I needed to add a new file called local.properties with the following line in order for it to import correctly in eclipse:

sdk.dir=H\:\\Android\\android-sdk
