### ISSUE TITLE
Question about how a verse gets highlighted

### ISSUE THREAD

**Issue by sohaeb** [quran/quran_android#888]
So sorry if this has been already asked before. I tried searching but no avail.

1- I know that the pages are basically pictures downloaded. Then, how does the app detect the verses when clicking on an ayah.

2- How does the app make the highlight move with the audio ? Would someone be kind to briefly explain this ? i.e: Do you trim the audio and manually set the verses to each trimmed part ?

bonus if you can link me to the implementation of this feature.

**Comment by ahmedre** [comment]
the high level is that we have a database that says where each ayah is in the image (x,y coordinates for each ayah). when the person clicks, we know the x and y that the person clicked at, and so we can map this back to the ayah clicked accordingly.

in more detail, the database that says where each ayah is stores, for each page and ayah, a set of bounding boxes that contain the ayah (there could be several for one ayah - one per line). then, to highlight the ayah, we just draw a shaded rectangle above the page at those coordinates. to handle different screen sizes, we have to know how much the image is scaled by when it's displayed and adjust the coordinates we have accordingly to get the right position.

for the audio, we have two types - gapped and gapless - gapped is one mp3 per ayah, so it's easy to know when the ayah changed. gapless is one mp3 per sura, and we have a timing file that says the milliseconds at which each ayah starts and ends. when the verse changes, we update the highlight accordingly.

**Comment by fatmian** [comment]
Assalam-o_alykum!
I am new to android programming and currently working on the Quraan application.I have trouble in adjusting ayah coordinates according to different screen sizes to get right ayah bounds from database.Please explain this concept in detail.
Jazakallah.

**Comment by AcerTech** [comment]
Here is a Quran app uses the coordinates (check the github link), check json folder in the project files or see attached file
[json.zip](https://github.com/quran/quran_android/files/4570254/json.zip)


[https://github.com/rayed/Quran](url)

**Comment by mohammedsalem97** [comment]
@ahmedre  would you mind if you point to the particular file that contains the ayat boundaries because i spent alot of time searching for this file 😢

**Comment by adelpro** [comment]
> @ahmedre would you mind if you point to the particular file that contains the ayat boundaries because i spent alot of time searching for this file 😢
ayas are grouped by pages: 
for example, page number 10:
[https://github.com/rayed/Quran/blob/2995a7567d8e79f61853812f44a3444424732dfe/json/page_10.json](https://github.com/rayed/Quran/blob/2995a7567d8e79f61853812f44a3444424732dfe/json/page_10.json)

page 11:
[https://github.com/rayed/Quran/blob/2995a7567d8e79f61853812f44a3444424732dfe/json/page_11.json](https://github.com/rayed/Quran/blob/2995a7567d8e79f61853812f44a3444424732dfe/json/page_11.json)

**Comment by bllfoad** [comment]
Please check my repo AyahAi for this: [AYAHAI-WEB](https://github.com/bllfoad/ayahai-web)
