### ISSUE TITLE
Zooming in pages of Quran

### ISSUE THREAD

**Issue by ssaaiidd** [quran/quran_android#889]
It would be nice to have a tool that we can adjust the size of the verses, or to use two fingers.

**Comment by ozbek** [comment]
Did you try the landscape mode? What's the use case for zooming?

**Comment by ssaaiidd** [comment]
Yes I tried. Zooming is enough but too small when using the device upright.

**Comment by ozbek** [comment]
You mean in portrait mode? If zoom is enabled, you will have to scroll left and right to read the lines. I think, that will add very little benefit. Please use landscape mode if you prefer larger text.

**Comment by ssaaiidd** [comment]
Okay. Thanks
