### ISSUE TITLE
Support tablets / larger screen devices

### ISSUE THREAD

**Issue by ezzadeen** [quran/quran_android#89]
Assalam alaikum

By chance I noticed today that the app on the honecomb tablet doesn't work properly. When I looked at the source code I realized why. You need to add res/layout-xlarge directory and copy all the files in the res/layout to this one + ensure the sizes are scaled to fill the tablets' larger screens. You can test the changes in the emulator. I couldn't add a new directory to fix this problem but I gave you the hint to fix it.

**Comment by ahmedre** [comment]
we did this long ago - closing.
