### ISSUE TITLE
Can't de-select ayah in Translation mode

### ISSUE THREAD

**Issue by Ahmed9914** [quran/quran_android#890]
السلام عليكم

I think we have to refactor the work done [here](https://github.com/quran/quran_android/commit/2bbfa7c81f7f63808e41396a09b0ff31c8527445) by implementing something like `isInAyahTranslationMode, startAyahTranslationMode, endAyahTranslationMode` to handle the selection and de-selection of ayah in translation mode.
Currently pressing back button after selecting ayah will fall back to the quran page. I think we have to handle `onBackPressed` in translation mode.

جزاكم الله خيرا
وتقبل الله منا و منكم

**Comment by ahmedre** [comment]
this is mostly fixed now except for bookmarking which should be done at some point in the future in sha’ Allah. closing for now.
