### ISSUE TITLE
Database error :

### ISSUE THREAD

**Issue by hakeempp** [quran/quran_android#891]
Barakallahu lakum fee amalikum...
There is an error in MALAYALAM translation @ aya: 6:157, 158, 159, and 160.  It is a data base error. Kindly fix it for beginners to holy kithab...

Thank you again.

**Comment by hakeempp** [comment]
Translation of pre coming ayah repeated....

Location: 
Aya: 6:157, 158 , 159 , 160 
Translation: Malayalam - കാരകുന്ന് & എളയാവൂര്

http://tanzil.net/#trans/ml.karakunnu/6:157

**Comment by ahmedre** [comment]
closing since this translation was replaced on 4/10/2020.
