### ISSUE TITLE
unable to view translation even after downloading translations

### ISSUE THREAD

**Issue by shaikq** [quran/quran_android#910]
app says "you don't have any translations/tafaseer downloaded yet." though i have downloaded. Not sure whether issue with app or my device.

**Comment by ozbek** [comment]
Please provide your device details, Android version, and app version. Also, which location are you using for data?

**Comment by shaikq** [comment]
I think, i found the problem, after downloading the translation, the dropdown menu to select the translation does appear, but it is partially hidden by 'GET TRANSLATIONS' button. so, this is the reason i couldn’t view translation.
![screenshot_20171004-020542](https://user-images.githubusercontent.com/23194259/31148415-2e053278-a87c-11e7-9a9f-e9c956578d7c.png)
![screenshot_20171004-020600](https://user-images.githubusercontent.com/23194259/31148428-38a9757c-a87c-11e7-92d9-c6c50ecbcef7.png)
![screenshot_20171004-020609](https://user-images.githubusercontent.com/23194259/31148435-3bbc8574-a87c-11e7-97c5-4ead8e0765ea.png)
![screenshot_20171004-020642](https://user-images.githubusercontent.com/23194259/31148438-3ee010ae-a87c-11e7-96ea-54ad1ac75eb4.png)
![screenshot_20171004-020650](https://user-images.githubusercontent.com/23194259/31148444-41b68db2-a87c-11e7-9416-1611d3677f9c.png)
![screenshot_20171004-020655](https://user-images.githubusercontent.com/23194259/31148449-44899d18-a87c-11e7-8d2b-ca7051593f5a.png)
