### ISSUE TITLE
Can I use this app for creating my own free source app ?

### ISSUE THREAD

**Issue by waleedkaramat** [quran/quran_android#914]
I want to create an android Quran memorization app can I use this project for this purpose?
P.S: The app will be available for free download no user will be charged and no ads would be placed.

**Comment by Gujarats** [comment]
nope. But you can contribute to fix some bugs instead. many people has install this application so you can contribute to achieve your purpose.

**Comment by OmarEinea** [comment]
Why not @Gujarats ? it's licensed under GPLv3, which should mean that he can modify the source as he wants as long as he keeps the modified source open. Isn't that how it works?

**Comment by Ahmed9914** [comment]
Please, read [this](https://github.com/quran/quran_android/issues/839) to get the answer.

**Comment by OmarEinea** [comment]
> Please, read this to get the answer.

Jazaka Allahu Khairan, this is very helpful.

**Comment by ahmahm12** [comment]
Assalamualaikum all How can i remove leaks testing app from source code

**Comment by ahmedre** [comment]
wa3laikum alsalam,
you can remove leakcanary and its associated dependencies.
closing for now.
walsalam 3alaikum.
