### ISSUE TITLE
translations not showing up

### ISSUE THREAD

**Issue by ahmedre** [quran/quran_android#915]
finally started catching up on emails, and got lots of reports about translations not showing up. they show as downloaded but neither show up in the internal panel nor in the translation panel. given the sheer number of complaints received, there's definitely a bug and this should be investigated asap.

**Comment by ahmedre** [comment]
did a fresh install today and noticed the following:

1. long press and go to translations - download a translation
2. go back - still shows nothing downloaded
3. go back again and come back in - again nothing downloaded shown, but if you press the drop down and hit the checkmark, things work as expected.

**Comment by ahmedre** [comment]
pushed a fix to a branch - may just release off of this branch since master is in a slightly less stable state (due to requiring fixes for Android O).

**Comment by ozbek** [comment]
Possible duplicate of #910.

**Comment by ahmedre** [comment]
ಠ╭╮ಠ
duplicate of #910

**Comment by jon-hasen** [comment]
This issue was resolved for a time but has returned. All translations dont show up despite being downloaded. Is there a repo for a stable version with the fix? @ahmedre

**Comment by ahmedre** [comment]
The latest version in the store should have this fix iirc

**Comment by jon-hasen** [comment]
Sadly just downloaded this on the Google Play store on my Z Flip 6 and  its
not fixed.

**Comment by ahmedre** [comment]
I am not sure I'll have to take another look to see if anything is obvious
