### ISSUE TITLE
Warn to Secde ayah

### ISSUE THREAD

**Issue by mahirekici** [quran/quran_android#919]
Selamün Aleyküm Brother
He does not warn you in the Secde ayah .

**Comment by ozbek** [comment]
Wa alaikum assalam. "He" who? :)

**Comment by mahirekici** [comment]
SAJDAH VERSES

**Comment by mahirekici** [comment]
need to notification, popup message

**Comment by ozbek** [comment]
Do you mean while playing audio recitation?

**Comment by mahirekici** [comment]
we would like to give a warning message at places where sajdah verses during no page transitions

.Sayfa geçişleri sırasında secde ayeti  olan yerlerde uyarı mesajını vermesini istiyoruz :)

**Comment by ozbek** [comment]
How would you like the warning messages to appear? 
_Uyarı mesajlarını nasıl verilmesini istiyorsunuz?_

**Comment by mahirekici** [comment]
maybe  alert message

**Comment by ozbek** [comment]
At the time of recitation a person will be in either of these two states:
1. Looking at the Qur'an page on the screen.
2. Not looking at the Qur'an page on the screen

If you are in state (1), you will notice this symbol ![sajdah-ayah-symbol](https://user-images.githubusercontent.com/452620/32008079-49ac4c66-b9e6-11e7-87e9-74d71bd9fd9d.png) next to a sajdah ayah and know that that's a sajdah ayah. If you are in state (2), then you won't see the sajdah ayah notification.

So, I think, there is really no need for an additional alert.
