### ISSUE TITLE
Adjusting ayah coordinates according to different screen sizes

### ISSUE THREAD

**Issue by fatmian** [quran/quran_android#920]
Assalam-o_alykum!
I am new to android programming and currently working on the Quraan application.I have trouble in adjusting ayah coordinates according to different screen sizes to get right ayah bounds from database.I have done some scaling by getting coordinates and screen size percentage and multiply with target screen size,but it didn't work properly.Please explain this concept in detail.
Jazakallah.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
the sizes are there assuming the image is the same size as the screen. when it's not, you calculate a ratio and apply it to the actual screen size.
walsalam 3alaikum.
