### ISSUE TITLE
The latest debug build is showing only 2 reciters

### ISSUE THREAD

**Issue by ozbek** [quran/quran_android#923]
Please see the below screenshots:

![device-2017-12-05-124357](https://user-images.githubusercontent.com/452620/33589125-1a87dfd8-d9ba-11e7-9c1b-185c2e35188c.png)

![device-2017-12-05-124150](https://user-images.githubusercontent.com/452620/33589124-18008aa8-d9ba-11e7-820b-2d57d997b2ca.png)

Or is that intentional?

**Comment by ahmedre** [comment]
intentional - like iOS, split out the data to avoid people who take and relaunch the app from killing our servers as well.
