### ISSUE TITLE
Reward for reading Quran

### ISSUE THREAD

**Issue by ibnharoon** [quran/quran_android#929]
I was thinking of tracking the reading of Quran by audio and video and reward the reader with cryptocurrency or digital currency. Anyone would be interested in seeing this feature implemented? The algorithms would be a little complex but it's doable. What do you guys think?

**Comment by ozbek** [comment]
Cryptocurrency? )) Simply give them some points, that'd do the job.

**Comment by ibnharoon** [comment]
They need to be able to 'use' the points/coins. Maybe company can partner to provide products or services that can be purchased with the coins.

**Comment by ozbek** [comment]
No, they don't necessarily need to be able to use the points. See, for example, how stack exchange network sites work.

**Comment by ibnharoon** [comment]
Usable points will give more incentive to read like this walking app https://sweatco.in/hi/bustamamharun

**Comment by Riz-waan** [comment]
Although I see what you are saying, the problem would come with people trying to abuse it.

**Comment by ahmedre** [comment]
closing for now

**Comment by Riz-waan** [comment]
@ibnharoon sweatcoin points are basically unusable.
