### ISSUE TITLE
Surat Quraysh not Downloading

### ISSUE THREAD

**Issue by mwaqas84** [quran/quran_android#935]
Dears,
Stay blessed. Ameen,

I have installed the app from google play store, all working fine, Audios are downoading fine. But just some Surahs such that "Surat Quraysh" , "Surat l-Kafirun", "Surat Al-Qariah" and there are few more, won't download. Even though I click on play icon it does not start downloading. Please have a look on the screenshot and in this screenshot if I click on play icon it does not start downloading the audios. 

![surat quraysh screenshot](https://user-images.githubusercontent.com/8478644/37149683-c0c1ffda-22f0-11e8-81bb-131cd5eeac4d.png)

I installed it in another android mobile and same issue.

Thanks in advance.

**Comment by mwaqas84** [comment]
Dear @ozbek 
May Allah reward you with goodness.
This alternative option worked fine once I downloaded whole Quran audios from settings "**Audio Manager (experimental)**" for **Minshwai Murattal (gapless)**.

Just wondering that if its a minor issue in the app if someone don't want to download whole audios at once? for example if someone tries to download only Surahs that are mentioned in the very first comment above? Do you think this minor issue will be solved in near future?

Thanks

**Comment by ozbek** [comment]
Yes, of course. We will look into it. Thanks for reporting :+1:

**Comment by AhmedKamal** [comment]
Hey @ozbek 
I did some investigation and I believe I found and fixed the bug, will open a pull request if you don't mind :)

**Comment by ozbek** [comment]
@ahmedre is of authority here, but I believe you don't need to ask him either to open a PR :)
