### ISSUE TITLE
bug in translation quot problem

### ISSUE THREAD

**Issue by spamershouse** [quran/quran_android#941]
in some  translations that have quots in Turkish Diyanet Isleri. ' " ' is not shown but writen as 'quot;'

**Comment by spamershouse** [comment]
i inspected the database in quran.tr.diyanet.db
we need to execute a replace &QUOT;  TO  '" '

**Comment by ahmedre** [comment]
also Russian.

**Comment by ahmedre** [comment]
replaced the diyanet database today please try again - closing.
