### ISSUE TITLE
Download Manager

### ISSUE THREAD

**Issue by afarra** [quran/quran_android#95]
Next version should include a download manager. A separate page from which you can:
a) Navigate and see what is downloaded
b) Select and delete specific items that are on the file system to free up space
c) Navigate and see everything that is downloadable from the servers
d) Select and download items before hand, so you wouldn't be interrupted while listening and asked whether to download

This should include all items, i.e: Pages, Tafsirs, Reciters, as well as other masa7if when it is supported. It would be good if for each of these you can either download all OR navigate into it and select a subset of suras/juz2s to download.

Some sort of functionality to download to the computer (as a lot of users ask for this) and then use the Download Manager to get them from it would only quadruple the awesomeness, but that may be a bit far fetched.

**Comment by ahmedre** [comment]
closing for now.
