### ISSUE TITLE
"و" is not part of the arabic verb

### ISSUE THREAD

**Issue by ahadel** [quran/quran_android#953]
In arabic "و" is speacial char like and in english 
You can see this issue by searching for this verb 
يقطعون 
The result will be 1 occurance and it should be 3 occurance ,

The missing 2 results is starting with "و" 
Wich is not part of the verb .

I think the seaech algorithm should not search for the whole word , part of the word is correct , i see the same problem with starting "ال"  for each word in search term , "ال"  example "الجنة" and "جنة"

جزاكم الله خيرا 
أحمد

**Comment by ahmedre** [comment]
closing because fixed.
