### ISSUE TITLE
[Qaloon/Warsh] New update

### ISSUE THREAD

**Issue by g360230** [quran/quran_android#956]
Sallem, 
Happy Ramadhan for all the team.
We noticed new update for Quran Android Application (30/05/2018) that is not ported on Qaloon and Warsh application. Could you please port it.
Is there any limitation for Qaloon/Warsh or extra work that we can help to resolve it.
بارك الله فيكم.
.لا تنسونا من صالح دعائكم

**Comment by ahmedre** [comment]
Wa3laikum alsalam,
Ramadan Mubarak to you too!
Most of the changes are not applicable (new qaris, new madani script
option), so the release would mostly be bug fixes for Android O and P. I am
intending to merge the two apps into the main app in the near future in
sha' Allah and remove the current extra apps from the store afterwards. I
can try to push an update with said bugfixes later this week though in sha'
Allah.
Walsalam 3alaikum.

**Comment by g360230** [comment]
Thank you for these informations.
Juste on question : why removing extra apps when merging all apps in a single one.
Actually Qaloon application is download +100 000 and Warsh +10 000.
We prefer to preserve Qaloon and Warsh.

**Comment by ahmedre** [comment]
there are a few reasons for this:
1. it's a bit of a hassle to push 4 apks for every release - this number would only grow with time as more types were added.
2. the majority of bad reviews on warsh/qaloon suggest that the people downloading it don't know what they are and think they're just different fonts or something - so they turn around leaving bad reviews due to "errors," when in fact they don't realize that they're probably looking for Hafs.

why do you think having it as a separate app is better? the only strong argument i can see is that it's better advertised (where as it's not as obvious that an app just named "Quran" supports Warsh/Qaloon).

**Comment by g360230** [comment]
Sallem, 
The reason is that Qaloon/Warsh users are not "geek", they don't know how to manipulate android phones and applications. They simply click on the icon to have Quran : no search option, no hizb naviogation, ... 
So we propose to keep Warsh/Qaloon application and there is no need to maintain them. You can maintain only the new application (all Riwaya).
Eid Mubarak for all the staff.

**Comment by ahmedre** [comment]
wa3laikum alsalam,
will think about it some more in sha' Allah - let's see.

i have another question - i have a copy of Warsh from QuranComplex - do you know if their copy is Warsh 3an Nafe3 (since the one we have is the Ashbani one?) - also, if so, does it make sense to bundle those as types within the warsh app?

**Comment by ahmedre** [comment]
@g360230, got this email:

> لكن من باب المناصحة في مصحف القرآن شعبة في سورة "يس" الآية الرابعة عشر كلمة فعززنا كتبت على روياة شعبة بدون تشديد للزاي وهذا صحيح لكنها لم تلون بالون الأحمر فلو تكرمتم وعدلتموها في التحديث القادم بارك الله بكم

**Comment by ahmedre** [comment]
@g360230 

> وفي الآية ربم ١٠٩ من سورة الأنعام في قراءة حفص عن عاصم ".... أنها إذا جاءت " بفتح الألف.
وفي قراءة شعبة بكسرها " إنها إذا جاءت" 

> والمثبت عندكم هو الهمزة المفتوحة وليس المكسورة فنرجو التعديل.

**Comment by ahmedre** [comment]
@g360230 

> سورة الانعام اية ١٠٩‎
> هناك خطأ في الاية برواية شعبة. في روابة شعبة "أنها" تقرأ " إنها" بالكسر.

**Comment by ahmedre** [comment]
@g360230 

> احظت في سورة النحل الاية 37 ان تشكيل كلمة "يهدى" غريب و انني أظنه خطأ فأرجو منكم التثبب و تصحيحها او تصحيحي.

**Comment by ahmedre** [comment]
@g360230 

> جزاكم الله خيرا علي ما تقومون به برجاء كتابة كلمة فعززنا باللون الاحمر في قوله تعالي (إِذْ أَرْسَلْنَا إِلَيْهِمُ اثْنَيْنِ فَكَذَّبُوهُمَا فَعَزَزْنَا بِثَالِثٍ فَقَالُوا إِنَّا إِلَيْكُمْ مُرْسَلُونَ)
[سورة يس 14]

>  كما هوا الحال في الكلمات التي خالف فيها شعبة حفص

**Comment by ahmedre** [comment]
> السلام عليكم ورحمة الله وبركاته هناك خطأ في الاية 14 من الاحقاف ...و الخطأ كلمة أصحاب كتبت أصخاب 

this isn't really true, but there's a dot of tashkeel that makes it look kinda like a خ though it's not.

**Comment by ahmedre** [comment]
> أما بعد فهناك بعض التنبيهات على الرواية (ورش):
> -الإمالة أو التقليل غير موجودة في رسم المصحف وكذا المد المنفصل ليست هناك إشارة لأنه مد مشبع هذا في مد الصلة الكبرى
> -والترقيم الأيات حسب الرواية.

**Comment by ahmedre** [comment]
ادعوكم الى تصحيح تلاوة الاية 37 من سورة التوبة للقارئ احمد خضر

@g360230

**Comment by ducaale** [comment]
I think bad reviews can be mitigated by:
1. displaying a warning that says this is not the standard hafs qiraa'ah.
2. Replaying to negative reviews (can be a tedious work)

**Comment by ducaale** [comment]
If you go the one apk route, one way support for different qiraa'ah can be advertized is by screenshots in the app store / play store

**Comment by ahmedre** [comment]
@g360230 still around brother? someone is complaining about ayah 103 of sura Yunus having a hamza - i checked another copy of warsh with asbahani and it doesn't have. please advise.

**Comment by benomaire** [comment]
> البرنامج ممتاز واسأل الله أن يزيد مطور البرنامج علما ونفعا للمسلمين وجعله الله في ميزان حسناته اخوتي القائمين على البرنامج عندي ملاحظة في سورة الأعراف الآية رقم 195 التنوين الذي على كلمة ءاذان غير واضح او غير موجود بل عليها ضمة فقط بالله عليكم تصحيح هذه الكلمة وبارك الله فيكم

This is for Qaloon. I think we need to rescan the page, or add the faint tanween.

**Comment by ahmedre** [comment]
closing this now since we've fixed both sets of imags on Qaloon and Warsh.
also, worth noting that updates for one app happen for all of them (except for things like audio which shouldn't).
