### ISSUE TITLE
Playing

### ISSUE THREAD

**Issue by aluckin3** [quran/quran_android#958]
When you play a verse from start of page, it starts and then when you want to play from specific verse to it doesn't play, rather it's playing from play before

**Comment by ozbek** [comment]
If you want to start the playback from a certain ayah, please long click on that ayah and then choose the play button from the pop-up menu.

**Comment by aluckin3** [comment]
If you start the playback from some page, by clicking play button next to name of recitator, and then you long click on certain ayah then your playback will not work, because of first playback. You should stop playback that first time is started, and start new playback.

**Comment by ozbek** [comment]
OK, one should probably stop the current playback before starting a new one. 

What is your issue/question? :)

**Comment by aluckin3** [comment]
I think you should create to stop old thread, and start new one, if you can add that feature.
May Allah give you best of dunya and akhirah

**Comment by ahmedre** [comment]
closing for now, please reopen if necessary
