### ISSUE TITLE
App allows empty tags, duplicate tags and no delete option

### ISSUE THREAD

**Issue by shaikq** [quran/quran_android#961]
App does not have option to delete / remove tags and it also accepts empty / duplicate tags.
![screenshot_quran_20180618-010647](https://user-images.githubusercontent.com/23194259/41511561-db0410ea-7296-11e8-86ad-e22a8577d772.png)
![screenshot_quran_20180618-010658](https://user-images.githubusercontent.com/23194259/41511562-df85837e-7296-11e8-80f2-72fa67452068.png)
![screenshot_quran_20180618-010712](https://user-images.githubusercontent.com/23194259/41511563-e2bae548-7296-11e8-8568-a54060185d97.png)
![screenshot_quran_20180618-010718](https://user-images.githubusercontent.com/23194259/41511566-e5f5c14c-7296-11e8-8fb1-6afed5ece6aa.png)
![screenshot_quran_20180618-011300](https://user-images.githubusercontent.com/23194259/41511567-e8437dfe-7296-11e8-894c-20b76d43c2e1.png)

**Comment by ahmedre** [comment]
hmm, we shouldn't allow empty and/or blank spaces as tags. deletion works though, it's just a bit hidden. in the bookmarks list (on the main screen of the app) tap the three line graph-like/sorting icon and click on "group by tags" - then long press the tags and hit the x button to remove them.

**Comment by shaikq** [comment]
Ok found the tag delete feature, i guess handling empty / duplicate tag is relatively easy. Jazak Allahu Khayran.
