### ISSUE TITLE
Wrong Juz in some specific case

### ISSUE THREAD

**Issue by Naheel-Azawy** [quran/quran_android#970]
Alsalamu alykum,
Good news! an issue that is easy to fix! I just didn't have time to fix it on my own :(
This problem can be seen in sura Al-Maeda page 121. The 7th Juz indeed starts at that page at Aya 82 but most of this page is in the 6th Juz. In fact, if you check any printed Quran it can be seen that page 121 is marked under Juz 6.
I'm not sure if this problem occurs somewhere else and I'm not sure if this is a rule but I think that the right way of selecting the Juz for a page is selecting the Juz of the first Aya in the page.
Again I'm not sure but the problem can be probably fixed from com.quran.labs.androidquran.data.QuranInfo.getJuzFromPage()

And I almost forgot to thank you for your great work!

**Comment by ahmedre** [comment]
wa3laikum alsalam -
yes, but the madani mus7af does show as @Naheel-Azawy said the previous juz' - so we should fix this in sha' Allah just to be consistent (also, other people have complained to me about this in the past as well so might as well fix it for consistency reasons).
walsalam 3alaikum.

**Comment by ahmedre** [comment]
in addition to these 2, one complaint about -

- check also juz' 23 and juz' 26 to make sure they're correct
- 3/4 hezb 60 is one page late?

so let's double check these are correct also.
