### ISSUE TITLE
Wrongly numbered ayaats in Abdul Haleems translation

### ISSUE THREAD

**Issue by hamzapeer** [quran/quran_android#975]
In the English translation of Sir Abdul Haleem there is a mistake in the numbering. Check surah 69 verses 9,10 and 11.

**Comment by khalid-hussain** [comment]
Can you describe the mistake and its correction? Has the translator, i.e. Sir Abdul Haleem, acknowledged this mistake (i.e. Do you have proof)?

**Comment by hamzapeer** [comment]
yes he has , i personally messaged him , he said he is going fix it in the coming edition. the nature of the mistake is that the verse number and the translations dont match. i already quoted the verse above.

**Comment by ahmedre** [comment]
today, it was:

```
69:9 - Pharaoh, too, and those before him, and the ruined cities: these people committed grave sins and disobeyed the messenger of their Lord, so He seized them with an ever-tightening grip.
69:10 - But when the Flood rose high,
69:11 - We saved you in the floating ship,
```

@hamzapeer i agree this is a mistake - if you have access to Sir Abdul Haleem, can you ask him about ayah 9 specifically - i can change it to the below without changing any words and it's *almost* fine - but 69:9 would be missing the translation of the last word (translated as "with sin." by Sahih International). if he can give me a suggestion on this i would love to fix it.

```
69:9 - Pharaoh, too, and those before him, and the ruined cities:
69:10 - these people committed grave sins and disobeyed the messenger of their Lord, so He seized them with an ever-tightening grip.
69:11 - But when the Flood rose high, We saved you in the floating ship,

**Comment by hamzapeer** [comment]
Alsalam alaikum,
Thank you for looking into the concern, I will contact sir haleem and will
let you know his response on your mentioned changes as soon as possible.

**Comment by ahmedre** [comment]
jazakAllah khairan, really appreciate it and waiting for his reply in sha' Allah

**Comment by ahmedre** [comment]
until you hear back, replacing this with:

```
69:9 - And there came Pharaoh and those before him and the overturned cities with sin. [via Sahih International]
69:10 - these people committed grave sins and disobeyed the messenger of their Lord, so He seized them with an ever-tightening grip.
69:11 - But when the Flood rose high, We saved you in the floating ship,
```

**Comment by ahmedre** [comment]
please re-open when you hear back from the sheikh, closing for now. jazakumAllah khairan.
