### ISSUE TITLE
Wrong Bengali Translation

### ISSUE THREAD

**Issue by mfaisalpasha** [quran/quran_android#980]
There's a sentence missing in Bengali translation of Ayah 50 of Surah Yusuf.

**Comment by ahmedre** [comment]
merged this into #786

**Comment by emrhossain** [comment]
![Screenshot_20200508-045943~2](https://user-images.githubusercontent.com/13637300/81353455-f11a4880-90ea-11ea-8e85-b8e7eb765aaa.png)
This translation is wrong

**Comment by ahmedre** [comment]
which translator?

**Comment by emrhossain** [comment]
Bengali translate

- Emran

**Comment by mfaisalpasha** [comment]
Brother Emran,
Which Translator? Because there are two translations now. Muhiuddin Khan and Abu Bakar Zakaria.Though Muhiuddin Khan is not available in the app for time being  because of typos.

**Comment by emrhossain** [comment]
Abu bakar zakaria translate

- Emran

**Comment by ahmedre** [comment]
jazakAllah khairan - i've reported this to the quranenc.com team since that's where we got the translation.
