### ISSUE TITLE
Can't download the application from Sudan

### ISSUE THREAD

**Issue by obayit** [quran/quran_android#983]
Google Play says that the app is not available in my country!

**Comment by obayit** [comment]
For now I can download apk file from [releases](https://github.com/quran/quran_android/releases). Thanks for ignoring this issue XD

**Comment by ahmedre** [comment]
This is strange, because we enabled it for all countries, we never disabled it for any country :(

**Comment by ozbek** [comment]
Google Play might have added Sudan to available countries list later. It is worth to check the Store listing section from time to time @ahmedre, because they don't make the app auto-available for countries added after the app has been released.

**Comment by ozbek** [comment]
In-app purchase or any other kind of donation was never added. Are you sure you are looking at https://play.google.com/store/apps/details?id=com.quran.labs.androidquran app? Being open source, there are many clones of the app and some even contain ads (unfortunately).

**Comment by obayit** [comment]
@ozbek Yes.

Someone from the team needs too look at this!

**Comment by ahmedre** [comment]
salam 3alaikum,
JazakAllah khairan for the heads up - I checked and, indeed, 2 countries were disabled - Sudan and the Solomon Islands - I know for a fact I didn't disable for any country, so apparently, as one brother messaged and told me, they sometimes add new countries and set them as disabled unless the app developer opts in to them manually.

Within a few hours, you should see it on the store again. jazakAllah khairan for reporting this!
walsalam 3alaikum.
